# English language version of the Coccinella message catalog.
#
#       The English catalog is the master of all other catalogs
#
#       Translators:
#         cs  David Stancl (david.stancl at seznam.cz), 2007-2008
#         da  Mogens Pedersen  (Mogens.Pedersen at skolekom.dk), 2006
#         de  Hermann J. Beckers (hj dot beckers at onlinehome dot de), 2004-2008
#         es  Néstor Díaz (n3storm at grupoikusnet.com), 2004
#             Antonio F. Cano (antonio at grupoikusnet.com), 2006
#             Agustin Vericat (agustin at grupoikusnet.com), 2006
#             César Alcalde (lambda512 at gmail.com), 2008
#         fr  Guillaume Ayoub (xovni at wanadoo.fr), 2004-2005
#             Nicolas Vérité (xmpp:nyco@jabber.fr, nicolas.verite at gmail.com), 2008
#         it  Mirko Graziani (contatto at imatica.it), 2006-2008
#         ko  Dylan Park, Korea NVC Center (hanmaum AT krnvc.org), 2006
#         nl  Sander Devrieze (s.devrieze at pandora.be), 2004-2008
#             Bart Van Hove (bartvanhove at skynet.be), 2004
#         pl  Zbigniew Baniewski (zb at ispid.com.pl), 2005-2008
#         ru  Alexander Balezin (xmpp:gescheit@jabber.ttn.ru, gescheit at list.ru), 2005-2007
#         sv  Mats Bengtsson, 2002-2008
#
# General type of text, such as "OK", "Cancel", and the like. 
# We use the source string as the message.
# Defined in global namespace and may therefore be used in any namespace.
# 
#   $Id: en.msg,v 1.258 2008-09-24 18:37:59 sdevrieze Exp $

::msgcat::mcset en Abort
::msgcat::mcset en Action
::msgcat::mcset en Add
::msgcat::mcset en Address
::msgcat::mcset en Admin
::msgcat::mcset en admin
::msgcat::mcset en Affiliation
::msgcat::mcset en Always
::msgcat::mcset en Any
::msgcat::mcset en Appearance
::msgcat::mcset en Author
::msgcat::mcset en Avatar
::msgcat::mcset en Binary
::msgcat::mcset en Birthday
::msgcat::mcset en Bookmarks
::msgcat::mcset en Browser
::msgcat::mcset en Cancel
::msgcat::mcset en Chatroom
::msgcat::mcset en City
::msgcat::mcset en Clear
::msgcat::mcset en Client
::msgcat::mcset en Close
::msgcat::mcset en Color
::msgcat::mcset en Company
::msgcat::mcset en Configure
::msgcat::mcset en Connection
::msgcat::mcset en Contact
::msgcat::mcset en Contacts
::msgcat::mcset en Coordinates
::msgcat::mcset en Country
::msgcat::mcset en Create
::msgcat::mcset en Customization
::msgcat::mcset en Date
::msgcat::mcset en Default
::msgcat::mcset en Delete
::msgcat::mcset en Department
::msgcat::mcset en Description
::msgcat::mcset en Detect
::msgcat::mcset en Discover
::msgcat::mcset en Downloading
::msgcat::mcset en Edit
::msgcat::mcset en Email
::msgcat::mcset en Emoticons
::msgcat::mcset en Encoding
::msgcat::mcset en Enter
::msgcat::mcset en Error
::msgcat::mcset en Export
::msgcat::mcset en Extensions
::msgcat::mcset en File
::msgcat::mcset en Filter
::msgcat::mcset en Finish
::msgcat::mcset en Finished
::msgcat::mcset en First
::msgcat::mcset en Fonts
::msgcat::mcset en Forward
::msgcat::mcset en From
::msgcat::mcset en General
::msgcat::mcset en Grant
::msgcat::mcset en Group
::msgcat::mcset en Groups
::msgcat::mcset en Height
::msgcat::mcset en History
::msgcat::mcset en Home
::msgcat::mcset en Host
::msgcat::mcset en Icon
::msgcat::mcset en Image
::msgcat::mcset en Import
::msgcat::mcset en Inbox
::msgcat::mcset en Info
::msgcat::mcset en Invite
::msgcat::mcset en Invitation
::msgcat::mcset en Key
::msgcat::mcset en Language
::msgcat::mcset en Last
::msgcat::mcset en Less
::msgcat::mcset en Login
::msgcat::mcset en Logout
::msgcat::mcset en Member
::msgcat::mcset en member
::msgcat::mcset en Message
::msgcat::mcset en Middle
::msgcat::mcset en Minutes
::msgcat::mcset en Moderator
::msgcat::mcset en moderator
::msgcat::mcset en Moderators
::msgcat::mcset en More
::msgcat::mcset en Name
::msgcat::mcset en Network
::msgcat::mcset en Never
::msgcat::mcset en Next
::msgcat::mcset en Nickname
::msgcat::mcset en No
::msgcat::mcset en no
::msgcat::mcset en None
::msgcat::mcset en Notes
::msgcat::mcset en Occupation
::msgcat::mcset en Offline
::msgcat::mcset en OK
::msgcat::mcset en Online
::msgcat::mcset en Open
::msgcat::mcset en Owner
::msgcat::mcset en owner
::msgcat::mcset en Participants
::msgcat::mcset en Password
::msgcat::mcset en Personal
::msgcat::mcset en Phone
::msgcat::mcset en Play
::msgcat::mcset en Plugins
::msgcat::mcset en Port
::msgcat::mcset en Ports
::msgcat::mcset en Preferences
::msgcat::mcset en Previous
::msgcat::mcset en Print
::msgcat::mcset en Priority
::msgcat::mcset en Profile
::msgcat::mcset en Progress
::msgcat::mcset en Proxy
::msgcat::mcset en Quit
::msgcat::mcset en Quote
::msgcat::mcset en Rate
::msgcat::mcset en Region
::msgcat::mcset en Register
::msgcat::mcset en Remaining
::msgcat::mcset en Remove
::msgcat::mcset en Reply
::msgcat::mcset en Resource
::msgcat::mcset en Revoke
::msgcat::mcset en Role
::msgcat::mcset en Save
::msgcat::mcset en Search
::msgcat::mcset en Secured
::msgcat::mcset en Send
::msgcat::mcset en Server
::msgcat::mcset en Service
::msgcat::mcset en Services
::msgcat::mcset en Settings
::msgcat::mcset en Shortcut
::msgcat::mcset en Size
::msgcat::mcset en Skin
::msgcat::mcset en Sleep
::msgcat::mcset en Sounds
::msgcat::mcset en Specific
::msgcat::mcset en Status
::msgcat::mcset en Stop
::msgcat::mcset en Subject
::msgcat::mcset en System
::msgcat::mcset en Text
::msgcat::mcset en Theme
::msgcat::mcset en Timeout
::msgcat::mcset en Title
::msgcat::mcset en Topic
::msgcat::mcset en Transports
::msgcat::mcset en Type
::msgcat::mcset en Unregister
::msgcat::mcset en Username
::msgcat::mcset en Version
::msgcat::mcset en Visitors
::msgcat::mcset en Voice
::msgcat::mcset en voice
::msgcat::mcset en Volume
::msgcat::mcset en Warning
::msgcat::mcset en Website
::msgcat::mcset en Whiteboard
::msgcat::mcset en Width
::msgcat::mcset en Work
::msgcat::mcset en Yes
::msgcat::mcset en yes

# Try to move next strings to normal strings
# Canvas item options, names and values.
# Names:
::msgcat::mcset en Anchor
::msgcat::mcset en Arrow
::msgcat::mcset en {Arrow shape}
::msgcat::mcset en {Cap style}
::msgcat::mcset en Dash
::msgcat::mcset en Fill
::msgcat::mcset en {Font familiy}
::msgcat::mcset en {Join style}
::msgcat::mcset en Justify
::msgcat::mcset en Outline
::msgcat::mcset en {Outline stipple}
::msgcat::mcset en Smooth
::msgcat::mcset en Stipple
::msgcat::mcset en Tags

# Values (see item inspector to see what they mean):
# anchor
::msgcat::mcset en N
::msgcat::mcset en NE
::msgcat::mcset en E
::msgcat::mcset en SE
::msgcat::mcset en S
::msgcat::mcset en SW
::msgcat::mcset en W
::msgcat::mcset en NW
::msgcat::mcset en Center

# arrow
::msgcat::mcset en Both

::msgcat::mcset en Transparent
::msgcat::mcset en {Gray 75%}
::msgcat::mcset en {Gray 50%}
::msgcat::mcset en {Gray 25%}
::msgcat::mcset en {Gray 12%}

::msgcat::mcset en Round
::msgcat::mcset en Miter
::msgcat::mcset en Bevel
::msgcat::mcset en Butt
::msgcat::mcset en Projecting

::msgcat::mcset en Normal
::msgcat::mcset en Bold
::msgcat::mcset en Italic

::msgcat::mcset en Left
::msgcat::mcset en Right
::msgcat::mcset en False
::msgcat::mcset en True

# dashes
::msgcat::mcset en Dotted
::msgcat::mcset en Dash-dotted
::msgcat::mcset en Dashed


# Status messages.
::msgcat::mcset en available
::msgcat::mcset en away
::msgcat::mcset en {do not disturb}
::msgcat::mcset en {not available}
::msgcat::mcset en {extended away}
::msgcat::mcset en invisible
::msgcat::mcset en chat

# TODO
# All menu labels; concateneted and prepended with 'm' for the database key.
::msgcat::mcset en mAboutCoccinella      {&About Coccinella}
::msgcat::mcset en mAction               {&Action}
::msgcat::mcset en {Add to Dictionary}
::msgcat::mcset en mAdHocCommands        {C&ommands}
::msgcat::mcset en mAddContact...        {&Add Contact...}
::msgcat::mcset en mAddSpeechBubble      {Add Speech Bubble}
::msgcat::mcset en mAll                  {All}
::msgcat::mcset en mArc                  {Arc}
::msgcat::mcset en mArcs                 {Arcs}
::msgcat::mcset en mAttachMessage        {Attach Message...}
::msgcat::mcset en {Available}
::msgcat::mcset en {Away}
::msgcat::mcset en mBackgroundColor...   {Background Color...}
::msgcat::mcset en {Background Image}
::msgcat::mcset en mBackgroundImage...   {&Background Image...}
::msgcat::mcset en mBold                 {Bold}
::msgcat::mcset en mBrushThickness       {Brush Thickness}
::msgcat::mcset en mBugReport...         {&Report Bug...}
::msgcat::mcset en mBusinessCard...      {View &Business Card...}
::msgcat::mcset en {&Business Card...}
::msgcat::mcset en mCall                 {&Call...}
::msgcat::mcset en {Chat}
::msgcat::mcset en mChat...              {Cha&t...}
::msgcat::mcset en mChord                {Chord}
::msgcat::mcset en {Clear Menu}
::msgcat::mcset en {&Close Window}
::msgcat::mcset en mCoccinellaHome...    {&Home Page...}
::msgcat::mcset en mColor...             {Color...}
::msgcat::mcset en mContacts...          {&Contacts...}
::msgcat::mcset en mControlPanel         {Control Panel}
::msgcat::mcset en {&Copy}
::msgcat::mcset en {&Create Chatroom...}
::msgcat::mcset en {Cu&t}
::msgcat::mcset en mDebug                {&Debug}
::msgcat::mcset en mDecreasing           {&Decreasing}
::msgcat::mcset en mDictionaries         {Dictionaries}
::msgcat::mcset en {&Discover Server...}
::msgcat::mcset en {Do Not Disturb}
::msgcat::mcset en {&Edit}
::msgcat::mcset en {Edit &Bookmarks...}
::msgcat::mcset en {Edit &Business Card...}
::msgcat::mcset en mEditContact...       {&Edit Contact...}
::msgcat::mcset en {&Edit Item...}
::msgcat::mcset en mEditNick             {&Edit Nickname}
::msgcat::mcset en {&Edit Profiles...}
::msgcat::mcset en {Enter Chat&room...}
::msgcat::mcset en mErrorLog             {&Error Log...}
::msgcat::mcset en mExport               {Export}
::msgcat::mcset en mExportImage...       {Export Image...}
::msgcat::mcset en mExportMovie...       {Export Movie...}
::msgcat::mcset en {Extended Away}
::msgcat::mcset en mFile                 {&File}
::msgcat::mcset en mFill                 {Fill}
::msgcat::mcset en mFillColor...         {Fill Color...}
::msgcat::mcset en {Find}
::msgcat::mcset en {Find Next}
::msgcat::mcset en {Find Previous}
::msgcat::mcset en {Flip}
::msgcat::mcset en mFont                 {Font}
::msgcat::mcset en mFontSize             {Font Size}
::msgcat::mcset en mGrid                 {Grid}
::msgcat::mcset en {Hide Control Panel}
::msgcat::mcset en mHistory...           {&History...}
::msgcat::mcset en mHorizontal           {Horizontal}
::msgcat::mcset en mHugeFont             {Huge}
::msgcat::mcset en mIconSet...           {Icon &Set...}
::msgcat::mcset en mIgnore               {&Ignore}
::msgcat::mcset en {Image Larger}
::msgcat::mcset en {Image Smaller}
::msgcat::mcset en mImport               {Import}
::msgcat::mcset en mImportImage/Movie... {&Import Image/Movie...}
::msgcat::mcset en mInbox...             {&Inbox...}
::msgcat::mcset en mIncreasing           {&Increasing}
::msgcat::mcset en mInfo                 {&Info}
::msgcat::mcset en {Invisible}
::msgcat::mcset en mItalic               {Italic}
::msgcat::mcset en mJiveCall             {Call}
::msgcat::mcset en mJiveForward          {Forward Call}
::msgcat::mcset en mLargeFont            {Large}
::msgcat::mcset en {Larger}
::msgcat::mcset en mLargerFont           {Larger}
::msgcat::mcset en mLastLogin/Activity   {Last Login/Activity}
::msgcat::mcset en mLibrary              {&Library}
::msgcat::mcset en mLineSmoothness       {Line Smoothness}
::msgcat::mcset en mLocalTime            {Local Time...}
::msgcat::mcset en {Login to %s}
::msgcat::mcset en mLoginTrpt            {Login to Transport}
::msgcat::mcset en {Logout from %s}
::msgcat::mcset en mLogoutTrpt           {Logout from Transport}
::msgcat::mcset en {&Lower}
::msgcat::mcset en {&Message}
::msgcat::mcset en {Mi&nimize}
::msgcat::mcset en {&New Account}
::msgcat::mcset en mNewWindow            {New &Window}
::msgcat::mcset en mNormal               {Normal}
::msgcat::mcset en {Not Available}
::msgcat::mcset en mOffline              {&Offline}
::msgcat::mcset en mOpenFile...          {&Open File...}
::msgcat::mcset en mOpenFolder...        {&Open Folder...}
::msgcat::mcset en {Open St&ream}
::msgcat::mcset en mOutlineColor         {Outline Color}
::msgcat::mcset en mPageSetup            {Page Set&up...}
::msgcat::mcset en {New P&assword}
::msgcat::mcset en {&Paste}
::msgcat::mcset en mPieslice             {Pieslice}
::msgcat::mcset en mPlugins              {Plu&gins}
::msgcat::mcset en mPreferences          {&Preferences}
::msgcat::mcset en mPreferences...       {&Preferences...}
::msgcat::mcset en mPrint...             {&Print...}
::msgcat::mcset en mQuit                 {&Quit}
::msgcat::mcset en {&Raise}
::msgcat::mcset en {Re&do}
::msgcat::mcset en {Refresh}
::msgcat::mcset en {Re&gister}
::msgcat::mcset en {&Remove Account}
::msgcat::mcset en mRemoveContact        {&Remove Contact...}
::msgcat::mcset en mRemoveListing        {Remove &Listing}
::msgcat::mcset en {&Restore}
::msgcat::mcset en mSave		 {&Save...}
::msgcat::mcset en mSaveAs               {Save &As...}
::msgcat::mcset en mSaveAsItem           {Save As Item...}
::msgcat::mcset en mSaveCanvas           {&Save...}
::msgcat::mcset en mSaveImageAs          {Save Image As...}
::msgcat::mcset en {&Search}
::msgcat::mcset en {Select &All}
::msgcat::mcset en mSendFile...          {Send &File...}
::msgcat::mcset en mServer               {&Server}
::msgcat::mcset en {&Setup Assistant}
::msgcat::mcset en mShiftConstrain       {Shift Constrain}
::msgcat::mcset en {Show}
::msgcat::mcset en {Show Control Panel}
::msgcat::mcset en mSize                 {Size}
::msgcat::mcset en {Slide Show}
::msgcat::mcset en {Smaller}
::msgcat::mcset en mSort                 {Sort}
::msgcat::mcset en mCheckSpell           {Check Spelling}
::msgcat::mcset en mStopTrans            {Stop &Transactions}
::msgcat::mcset en mStraighten           {Straighten}
::msgcat::mcset en mStyle                {Style}
::msgcat::mcset en mSyncPlayback         {Sync Playback}
::msgcat::mcset en mTabs                 {&Tabs}
::msgcat::mcset en mTakeSnapShot         {Take &Snapshot}
::msgcat::mcset en mThickness            {Thickness}
::msgcat::mcset en mTimeCode             {Timecode}
::msgcat::mcset en mTo45degrees          {To 45 degrees}
::msgcat::mcset en mTo90degrees          {To 90 degrees}
::msgcat::mcset en mToolbar              {Tool&bar}
::msgcat::mcset en mTransports           {&Transports}
::msgcat::mcset en {&Undo}
::msgcat::mcset en mUnregister           {&Unregister}
::msgcat::mcset en mUpdateCheck          {&Update Check}
::msgcat::mcset en mVersion              {Version}
::msgcat::mcset en mVertical             {Vertical}
::msgcat::mcset en mWeight               {Weight}
::msgcat::mcset en mWhiteboard           {&Whiteboard...}


# Short texts only. Use english text as database key.
::msgcat::mcset en {About %s}
::msgcat::mcset en {About QuickTimeTcl}
::msgcat::mcset en {Add Contact}
::msgcat::mcset en {Add File Type}
::msgcat::mcset en {Add/Edit File Type}
::msgcat::mcset en {Add Profile}
::msgcat::mcset en {Alert sounds}
::msgcat::mcset en {Alternative chatroom}
::msgcat::mcset en {Always ask}
::msgcat::mcset en {Application Status}
::msgcat::mcset en {Auto Away}
::msgcat::mcset en {Auto Join}
::msgcat::mcset en {Auto Reply}
::msgcat::mcset en {Auto-accept}
::msgcat::mcset en {Auto-reject}
::msgcat::mcset en {Blocking support}
::msgcat::mcset en {Bookmark this chatroom}
::msgcat::mcset en {Broken Image}
::msgcat::mcset en {Buffering support}
::msgcat::mcset en {Built in server}
::msgcat::mcset en {Business Card: %s}
::msgcat::mcset en {Cache folder}
::msgcat::mcset en {Changes since previous release}
::msgcat::mcset en {Chat system}
::msgcat::mcset en {Chat window}
::msgcat::mcset en {Chat With %s}
::msgcat::mcset en {Chatroom presence change}
::msgcat::mcset en {Clear Cache}
::msgcat::mcset en {Close Slot}
::msgcat::mcset en {Close tab}
::msgcat::mcset en {Configure Chatroom}
::msgcat::mcset en {Contact Actions}
::msgcat::mcset en {Contact Icons}
::msgcat::mcset en {Contact ID}
::msgcat::mcset en {Contact Name}
::msgcat::mcset en {Create Chatroom}
::msgcat::mcset en {Create new item for each line of text}
::msgcat::mcset en {Custom Status}
::msgcat::mcset en {Default Applications}
::msgcat::mcset en {Default group}
::msgcat::mcset en {Default nickname}
::msgcat::mcset en {Delete Profile}
::msgcat::mcset en {Disable All}
::msgcat::mcset en {Discover permanently}
::msgcat::mcset en {Discover Server}
::msgcat::mcset en {Disk cache size}
::msgcat::mcset en {Edit Bookmarks}
::msgcat::mcset en {Do you want to hang up?}
::msgcat::mcset en {Edit Business Card}
::msgcat::mcset en {Edit Contact}
::msgcat::mcset en {Edit File Type}
::msgcat::mcset en {Edit Item}
::msgcat::mcset en {Edit Profiles}
::msgcat::mcset en {Email addresses}
::msgcat::mcset en {Email client}
::msgcat::mcset en {Enable nickname coloring}
::msgcat::mcset en {Enter Chatroom}
::msgcat::mcset en {Enter/Create Chatroom}
::msgcat::mcset en {Exit chatroom}
::msgcat::mcset en {Error code}
::msgcat::mcset en {External Midi Player}
::msgcat::mcset en {Factory Settings}
::msgcat::mcset en {File Cache}
::msgcat::mcset en {File Transfer}
::msgcat::mcset en {File Transfer Error}
::msgcat::mcset en {File transfer}
::msgcat::mcset en {File Type}
::msgcat::mcset en {File Types}
::msgcat::mcset en {First name}
::msgcat::mcset en {Font size}
::msgcat::mcset en {Font weight}
::msgcat::mcset en {Format: mm/dd/yyyy}
::msgcat::mcset en {Forwarded message}
::msgcat::mcset en {Full Name}
::msgcat::mcset en {Hide all on system tray click}
::msgcat::mcset en {History length}
::msgcat::mcset en {Import Iconset}
::msgcat::mcset en {Incoming Message}
::msgcat::mcset en {Insert emoticon}
::msgcat::mcset en {Invite Contact}
::msgcat::mcset en {Logged in}
::msgcat::mcset en {Iconset Archive}
::msgcat::mcset en {Last Activity}
::msgcat::mcset en {Last name}
::msgcat::mcset en {Loading available chatrooms}
::msgcat::mcset en {Local nickname}
::msgcat::mcset en {Local Time}
::msgcat::mcset en {Logged out}
::msgcat::mcset en {Login as invisible}
::msgcat::mcset en {Logout on sleep}
::msgcat::mcset en {Logout With Message}
::msgcat::mcset en {MIDI command}
::msgcat::mcset en {MIDI Player}
::msgcat::mcset en {MIME type}
::msgcat::mcset en {My Status}
::msgcat::mcset en {NAT Address}
::msgcat::mcset en {New Account}
::msgcat::mcset en {New Bookmark}
::msgcat::mcset en {New Form}
::msgcat::mcset en {New password}
::msgcat::mcset en {New Password}
::msgcat::mcset en {New Version}
::msgcat::mcset en {Incoming chat}
::msgcat::mcset en {New chat thread}
::msgcat::mcset en {Incoming message}
::msgcat::mcset en {New shortcut}
::msgcat::mcset en {No restriction}
::msgcat::mcset en {No registered history for}
::msgcat::mcset en {More recent than}
::msgcat::mcset en {Once per session}
::msgcat::mcset en {Open Business Card}
::msgcat::mcset en {Open Failed}
::msgcat::mcset en {Open File}
::msgcat::mcset en {Open Folder}
::msgcat::mcset en {Open Stream}
::msgcat::mcset en {Open with}
::msgcat::mcset en {Own Contact ID}
::msgcat::mcset en {Own Full Contact ID}
::msgcat::mcset en {Plain text password}
::msgcat::mcset en {Play sound}
::msgcat::mcset en {Postal code}
::msgcat::mcset en {Presence Control}
::msgcat::mcset en {Presence Error}
::msgcat::mcset en {Presence Subscription}
::msgcat::mcset en {Profile Name}
::msgcat::mcset en {Receive File}
::msgcat::mcset en {Recent Avatars}
::msgcat::mcset en {Reject file}
::msgcat::mcset en {Relogin on activity}
::msgcat::mcset en {Relogin on wakeup}
::msgcat::mcset en {Remove Account}
::msgcat::mcset en {Remove Avatar}
::msgcat::mcset en {Remove Contact}
::msgcat::mcset en {Requires a restart of %s}
::msgcat::mcset en {Retype password}
::msgcat::mcset en {Right click to open menu}
::msgcat::mcset en {Save As}
::msgcat::mcset en {Save As GIF}
::msgcat::mcset en {Save Canvas Item}
::msgcat::mcset en {Save File}
::msgcat::mcset en {Save Message}
::msgcat::mcset en {Save password}
::msgcat::mcset en {Save to disk}
::msgcat::mcset en {Search People}
::msgcat::mcset en {Search results}
::msgcat::mcset en {Select Avatar}
::msgcat::mcset en {Select File}
::msgcat::mcset en {Select Font}
::msgcat::mcset en {Select Server}
::msgcat::mcset en {Send File}
::msgcat::mcset en {Send Live}
::msgcat::mcset en {Set Status}
::msgcat::mcset en {Setup Assistant}
::msgcat::mcset en {Show Icon}
::msgcat::mcset en {Show navigation buttons}
::msgcat::mcset en {Show notifier window}
::msgcat::mcset en {Show popup}
::msgcat::mcset en {Show offline users}
::msgcat::mcset en {Show Text}
::msgcat::mcset en {Show Text and Icon}
::msgcat::mcset en {Show transports}
::msgcat::mcset en {Smooth freehand strokes}
::msgcat::mcset en {Sound set}
::msgcat::mcset en {Start chat}
::msgcat::mcset en {Start minimized in system tray}
::msgcat::mcset en {Start minimized in taskbar}
::msgcat::mcset en {Status Info}
::msgcat::mcset en {Status message}
::msgcat::mcset en {Subscription Failed}
::msgcat::mcset en {Subscription Pending}
::msgcat::mcset en {Synchronise cache}
::msgcat::mcset en {Take Snapshot}
::msgcat::mcset en {Tel (fax)}
::msgcat::mcset en {Tel (voice)}
::msgcat::mcset en {Text-to-Speech}
::msgcat::mcset en {Thread started}
::msgcat::mcset en {Update Check}
::msgcat::mcset en {Use HTTP transport}
::msgcat::mcset en {Use SASL authentication}
::msgcat::mcset en {Use TLS and SASL}
::msgcat::mcset en {Use TLS on separate port (old)}
::msgcat::mcset en {Use proxy}
::msgcat::mcset en {Use secure connection}
::msgcat::mcset en {Use compression}
::msgcat::mcset en {User Activity}
::msgcat::mcset en {Contact is offline}
::msgcat::mcset en {Contact is online}
::msgcat::mcset en {Contact presence change}
::msgcat::mcset en {Username & Password}
::msgcat::mcset en {View business card}

::msgcat::mcset en {Windows opacity}
::msgcat::mcset en {Writing file}

::msgcat::mcset en {Please join me for video chat on}

# Chatrooms.
::msgcat::mcset en {Kick Participant}
::msgcat::mcset en {Ban Participant}
::msgcat::mcset en {Destroy Chatroom}
::msgcat::mcset en {Edit Lists}
::msgcat::mcset en {Edit the voice list}
::msgcat::mcset en {Edit the ban list}
::msgcat::mcset en {Edit the member list}
::msgcat::mcset en {Edit the moderator list}
::msgcat::mcset en {Edit the admin list}
::msgcat::mcset en {Edit the owner list}

# Naming of protocol systems and their identifiers.
# Low priority.
::msgcat::mcset en {Screen Name}
::msgcat::mcset en {Gadu-Gadu Number}
::msgcat::mcset en {ICQ Number}
::msgcat::mcset en {IRC}
::msgcat::mcset en {MSN Address}
::msgcat::mcset en {Email Address}
::msgcat::mcset en {QQ Number}
::msgcat::mcset en {Tlen Address}
::msgcat::mcset en {Jabber ID}
::msgcat::mcset en {Yahoo ID}

# Time intervals.
::msgcat::mcset en {Ten seconds}
::msgcat::mcset en {One minute}
::msgcat::mcset en {Ten minutes}
::msgcat::mcset en {One hour}  

# Splash screen:
::msgcat::mcset en {Sourcing Tcl code}
::msgcat::mcset en {Loading Tcl packages}
::msgcat::mcset en {Sourcing Jabber code}
::msgcat::mcset en {Searching for our hostname}
::msgcat::mcset en {Initializing}
::msgcat::mcset en {Setting preferences}
::msgcat::mcset en {Looking for %s}

# Subscriptions:
::msgcat::mcset en {Both you and your contact can see eachother's presence.}
::msgcat::mcset en {You cannot see your contact's presence, but your contact can see yours.}
::msgcat::mcset en {Both you and your contact cannot see eachother's presence.}
::msgcat::mcset en {You can see your contact's presence, but your contact can't see yours.}


# Messages for tk_messageBox:
::msgcat::mcset en {We are about to receive the file %s. Do you want to receive it?}
::msgcat::mcset en {You already have the latest version available (%s).}
::msgcat::mcset en {Opening a whiteboard file clears the current whiteboard!}
::msgcat::mcset en {Do you actually want to quit?}
::msgcat::mcset en {Cannot open file %s.}
::msgcat::mcset en {Do you really want to reset your customization to factory defaults?}
::msgcat::mcset en {Cannot start the internal HTTP server: %s}
::msgcat::mcset en {Cannot find importer for the MIME type %s}
::msgcat::mcset en {Cannot read %s: %s}
::msgcat::mcset en {Cannot write to %s: %s}
::msgcat::mcset en {Cannot start server socket. Perhaps you are not connected.}
::msgcat::mcset en {One or more fields are missing. Try again or cancel.}
::msgcat::mcset en {You need to fill in at least the server name and user name.}
::msgcat::mcset en {There are no plugins or helper applications identified on this system.}
::msgcat::mcset en {Passwords do not match. Please try again.}
::msgcat::mcset en {The preferences have been changed. Do you want to cancel anyway?}
::msgcat::mcset en {At least one setting requires a restart of %s.}
::msgcat::mcset en {Cannot find necessary Tcl extension.}
::msgcat::mcset en {The standard fonts, Times, Helvetica, and Courier, may not be removed.}
::msgcat::mcset en {Are you sure you want to close the setup assistant? You may start it any time later from the menu.}
::msgcat::mcset en {Be sure to fill in all entries before you continue.}
::msgcat::mcset en {This whiteboard document has been changed.}
::msgcat::mcset en {Do you want to save the changes?}

# Messages for tk_messageBox:
::msgcat::mcset en {To add a contact from a chat system without open federation, you need an account on this closed system, plus you need to register this account with the corresponding transport (%s). Do you want to do this now?}
::msgcat::mcset en {You need to fill in at least one valid address.}
::msgcat::mcset en {%s allows you to see his/her presence.}
::msgcat::mcset en {%s is already in your list. Do you want to continue anyway?}
::msgcat::mcset en {Do you want to register a new account?}
::msgcat::mcset en {%s can see your presence.}
::msgcat::mcset en {%s cannot see your presence.}
::msgcat::mcset en {The avatar must be square of size %s.}
::msgcat::mcset en {%s is invalid. Do you want to continue anyway?}
::msgcat::mcset en {Do you want to close this chat window and lose the complete conversation?}
::msgcat::mcset en {Do you want to invite this contact to a new chatroom?}
::msgcat::mcset en {This contact is not online anymore and the message is therefore not sent.}

::msgcat::mcset en {Cannot enter/create chatroom %s.}
::msgcat::mcset en {The connection was unexpectedly broken.}
::msgcat::mcset en {Iconset %s already exists.}
::msgcat::mcset en {Cannot load iconset %s.}
::msgcat::mcset en {Cannot enter chatroom %s: %s Do you want to retry?}
::msgcat::mcset en {Cannot connect to server %s to download update details: %s}
::msgcat::mcset en {Cannot download the configuration form of the chatroom.}
::msgcat::mcset en {Cannot open the inbox file %s when trying to save it.}
::msgcat::mcset en {Cannot read the inbox file %s: %s}
::msgcat::mcset en {Cannot query %s's last activity.}
::msgcat::mcset en {Cannot query %s's local time information.}
::msgcat::mcset en {Cannot register with service %s.}
::msgcat::mcset en {Cannot obtain search form.}
::msgcat::mcset en {Cannot send message to %s.}
::msgcat::mcset en {Cannot query %s's local time.}
::msgcat::mcset en {Cannot unregister from %s.}
::msgcat::mcset en {Cannot query %s's version.}
::msgcat::mcset en {Cannot subscribe to %s's presence. The contact does not allow you to see his/her presence.}
::msgcat::mcset en {Cannot set %s's nickname or group.}
::msgcat::mcset en {Received a fatal error: %s The connection is closed.}
::msgcat::mcset en {Cannot download file %s from %s.}
::msgcat::mcset en {The selected file does not exist. Select a new one.}
::msgcat::mcset en {The MD5 checksums did not match. The file may be corrupt.}
::msgcat::mcset en {Please fill in all fields before entering chatroom.}
::msgcat::mcset en {%s invited you to %s. Do you want to enter this chatroom?}
::msgcat::mcset en {You must provide a chatroom name.}
::msgcat::mcset en {You must provide a nickname.}
::msgcat::mcset en {You changed one or more values. Do you want to save them before closing?}
::msgcat::mcset en {Illegal character(s) in %s: %s!}
::msgcat::mcset en {Invalid Contact ID: %s. Please correct and resend.}
::msgcat::mcset en {Cannot create an image from %s.}
::msgcat::mcset en {Invalid Contact ID. You need to enter a valid one at the bottom (e.g. user@example.org).}
::msgcat::mcset en {Invalid Contact ID.}
::msgcat::mcset en {%s's local time is: %s}
::msgcat::mcset en {Cannot login because this username is already in use by someone else (%s).}
::msgcat::mcset en {The Contact ID differs from your profile. Do you want to save a new profile?}
::msgcat::mcset en {Your current login settings differ from your profile settings. Do you want to save them to your profile?}
::msgcat::mcset en {There are unsaved messages. Do you still want to quit?}
::msgcat::mcset en {The %s is missing or is too short!}
::msgcat::mcset en {%s does not support file transfer.}
::msgcat::mcset en {You must select a file to send.}
::msgcat::mcset en {Cannot find any chatroom service.}
::msgcat::mcset en {Cannot find any chatrooms at %s.}
::msgcat::mcset en {Cannot connect to %s. Either there are server or network issues, or you misspelled the server's name.}
::msgcat::mcset en {Cannot send when not logged in.}
::msgcat::mcset en {Registration with service %s was successful.}
::msgcat::mcset en {You are unregistered from %s.}
::msgcat::mcset en {%s wants to send you this file: %s Do you want to receive this file?}
::msgcat::mcset en {Cannot send the file %s to %s.}
::msgcat::mcset en {%s did not accepted the file %s.}
::msgcat::mcset en {Cannot open file %s}
::msgcat::mcset en {File transfer of %s to %s was successful.}
::msgcat::mcset en {Cannot download file over HTTP: timeout.}
::msgcat::mcset en {This is your own account at %s that acts as a service that transports messages to that IM system. It needs to be in your list. You have a subscription for %s: %s.}
::msgcat::mcset en {Cannot set new password.}
::msgcat::mcset en {Setting new password was successful.}
::msgcat::mcset en {The selected profile will be deleted. Do you also want to delete the account for this profile? This action cannot be undone. Press Cancel to abort deletion of account and profile.}
::msgcat::mcset en {The proxy server reported an error.}
::msgcat::mcset en {The registration failed.}
::msgcat::mcset en {The registration failed because this username is already in use by someone else.}
::msgcat::mcset en {The registration with %s was successful. Now you just need to Login using the same username and password.}
::msgcat::mcset en {You are now registered and automatically logged in as %s}
::msgcat::mcset en {Please enter or select first a server.}
::msgcat::mcset en {Do you really want to remove your account? This process cannot be undone.}
::msgcat::mcset en {Do you want to save this message before closing?}
::msgcat::mcset en {Cannot search.}
::msgcat::mcset en {There was an invalid field. Please correct it.}
::msgcat::mcset en {Contact ID %s is invalid. Do you want to skip it and send to the rest?}
::msgcat::mcset en {Select a presence state and optionally enter a message.}
::msgcat::mcset en {The most frequent combinations are easily reachable as menu entries.}
::msgcat::mcset en {Subscription request will be accepted in: %s secs.}
::msgcat::mcset en {Subscription request will be rejected in: %s secs.}
::msgcat::mcset en {%s additional contacts can see your presence.}
::msgcat::mcset en {Time since %s was last connected}
::msgcat::mcset en {Server %s did not respond: timeout.}
::msgcat::mcset en {Time since server %s was started}
::msgcat::mcset en {Time since client %s was last active}
::msgcat::mcset en {Your registered account with the %s service will be put in your roster to work as a transport with this service.}
::msgcat::mcset en {Because %s does not allow you to see his/her presence anymore, he/she is removed.}
::msgcat::mcset en {%s does not allow you to see his/her presence anymore. Do you want to remove %s?}
::msgcat::mcset en {%s does not allow you to see his/her presence anymore.}
::msgcat::mcset en {You cannot see %s's presence anymore.}
::msgcat::mcset en {The uptime/last activity is}
::msgcat::mcset en {Do you want to exit the chatroom %s?}
::msgcat::mcset en {Do you really want to remove this contact? This action cannot be undone.}
::msgcat::mcset en {%s is not online. If your message contains any images or other multimedia, your contact will not see them unless you are online while he/she reads your message. Do you want to send it anyway?}
::msgcat::mcset en {Do you want to close this whiteboard and lose the complete session?}

::msgcat::mcset en {The login process was aborted.}
::msgcat::mcset en {Protocol error during the login process.}
::msgcat::mcset en {Login failed because of unknown account or wrong password.}

# Related error conditions detected by the client.
::msgcat::mcset en {The server %s has no support for TLS.}
::msgcat::mcset en {Cannot negotiate TLS with server %s.}
::msgcat::mcset en {The server has no support for SASL authentication.}
::msgcat::mcset en {Cannot authenticate due to internal protocol error.}

# A collective description of all stream errors.
::msgcat::mcset en {Stream error received from the server with code: %s}

# Account xform balloon help.
# From: JEP-0077: In-Band Registration (http://www.xmpp.org/extensions/xep-0077.html#registrar-formtypes)
# Note to translators: these are tooltips and has lower priority
::msgcat::mcset en {Street portion of a physical or mailing address}
::msgcat::mcset en {Locality portion of a physical or mailing address}
::msgcat::mcset en {Some date (e.g., birth date, hire date, sign-up date)}
::msgcat::mcset en {Email address}
::msgcat::mcset en {First name or given name}
::msgcat::mcset en {You are already registered with this service. These are your current login settings.}
::msgcat::mcset en {Last name, surname, or family name}
::msgcat::mcset en {Full name}
::msgcat::mcset en {Familiar name}              
::msgcat::mcset en {Password or secret}
::msgcat::mcset en {Telephone number}
::msgcat::mcset en {An administrative region of the nation, such as a state or province}
::msgcat::mcset en {URL to personal website}
::msgcat::mcset en {Account name associated with the user}
::msgcat::mcset en {Postal code portion of a physical or mailing address}

::msgcat::mcset en {Operating system}

::msgcat::mcset en {You are about to unregister a transport with a number of dependent contacts. Do you want to remove these contacts as well (Yes), keep them (No), or cancel everything (Cancel)?}

::msgcat::mcset en {On %s, %s %s wrote:}

::msgcat::mcset en {Shell print command, edit if desired}
::msgcat::mcset en {Enter the password for your account %s}
::msgcat::mcset en {Lock this item from being edited}

::msgcat::mcset en {Download of file %s finished.}
::msgcat::mcset en {File transport error: %s}
::msgcat::mcset en {The server closed the socket without replying.}
::msgcat::mcset en {Cannot download the file %s.}
::msgcat::mcset en {File transport of %s was reset.}

::msgcat::mcset en {Point tool, click to mark, double click to inspect, press to popup}
::msgcat::mcset en {Point tool, click to mark, double click to inspect, right click to popup}
::msgcat::mcset en {Move tool}
::msgcat::mcset en {Line tool}
::msgcat::mcset en {Arrow tool}
::msgcat::mcset en {Rectangle tool}
::msgcat::mcset en {Oval tool}
::msgcat::mcset en {Text tool}
::msgcat::mcset en {Click to delete}
::msgcat::mcset en {Pen tool}
::msgcat::mcset en {Brush tool}
::msgcat::mcset en {Paint tool, shift-click for transparency}
::msgcat::mcset en {Polygon tool, spacebar to cancel}
::msgcat::mcset en {Arc tool, click to set center, spacebar to cancel}
::msgcat::mcset en {Arc tool, click and drag}
::msgcat::mcset en {Rotate tool, select item first}

# Preferences:
::msgcat::mcset en {Apply auto-away on hidden chat tabs}
::msgcat::mcset en {Do Not Disturb when (active chat sessions)}
::msgcat::mcset en {By default use active <Return> to send messages}
::msgcat::mcset en {Treat normal messages as chat messages}
::msgcat::mcset en {Double click message in inbox}
::msgcat::mcset en {Login on %s startup}
::msgcat::mcset en {Open message in new window}
::msgcat::mcset en {Remember open windows between sessions}
::msgcat::mcset en {Reply to sender}
::msgcat::mcset en {Save message inbox between sessions}
::msgcat::mcset en {Show incoming messages in new window}
::msgcat::mcset en {Store preferences in same folder as program}
::msgcat::mcset en {Store preferences on same drive as program}
::msgcat::mcset en {You have chosen to store your preferences in the default location. If you remove or move your personal settings at %s, the preferences in the default location will be used the next time you start %s. Do you want to remove the old preferences?}
::msgcat::mcset en {You have chosen to store your preferences on the same drive as the application. If this drive is not a removable device your personal settings could be visible. Do you want to continue?}
::msgcat::mcset en {Amount of cache to store recent whiteboard files to increase speed.}
::msgcat::mcset en {Warning: by importing any other fonts than the standard three ones (Times, Helvetica or Courier), you must be confident that all remote clients also have this font installed on their system.}
::msgcat::mcset en {The selected iconset will become the default.}
::msgcat::mcset en {Set command to use for playing MIDI sounds. This option is only relevant if you use a sound set with MIDI files.}
::msgcat::mcset en {Away after}
::msgcat::mcset en {Extended Away after}
::msgcat::mcset en {Logout after}
::msgcat::mcset en {Use the following external address}
::msgcat::mcset en {Select the plugins you want to be loaded.}
::msgcat::mcset en {Only edit local whiteboard items}
::msgcat::mcset en {Items created by others cannot be edited when enabled}
::msgcat::mcset en {Edit, add or delete profiles. The selected profile will become the default.}
::msgcat::mcset en {Enter the name for the new profile.}
::msgcat::mcset en {Exclude addresses (* as wildcard).}
::msgcat::mcset en {Usage of this HTTP proxy settings is determined by each profile's settings. File transfers will not work if you use an HTTP proxy.}
::msgcat::mcset en {Chat on double-click instead of message}
::msgcat::mcset en {Clear list of contacts on logout}
::msgcat::mcset en {Remove contact without presence subscription}
::msgcat::mcset en {Show contacts without any subscription}
::msgcat::mcset en {Enable or disable sounds below}
::msgcat::mcset en {Text-to-speech for chat}
::msgcat::mcset en {Text-to-speech for messages}
::msgcat::mcset en {Text-to-speech for whiteboard text}
::msgcat::mcset en {Select voice for incoming text}
::msgcat::mcset en {Select voice for outgoing write}
::msgcat::mcset en {Resize window to fit slides}
::msgcat::mcset en {Use tabbed interface}
::msgcat::mcset en {The dialog is closed after (Seconds)}
::msgcat::mcset en {If auto-accept/reject show dialog with timer}
::msgcat::mcset en {Put contacts who add me to their list in}
::msgcat::mcset en {If someone wants to see my presence and}
::msgcat::mcset en {is in my list}
::msgcat::mcset en {is not in my list}

::msgcat::mcset en {Complete ip number or name}
::msgcat::mcset en {Warning: you have edited the shortcuts. Don't you want to save them?}

::msgcat::mcset en {If checked Return sends message, else use Ctrl/Cmd-Return}
::msgcat::mcset en {Authorization to server %s was successful. Downloading contacts...}
::msgcat::mcset en {Show or hide the chat history}
::msgcat::mcset en {Select a service, and enter a chatroom and nickname. Optionally, you can configure the chatroom.}
::msgcat::mcset en {Enter a server to discover and use its services.}
::msgcat::mcset en {Select a chatroom service, a chatroom, and a nickname.}
::msgcat::mcset en {You entered the chatroom}
::msgcat::mcset en {You logged out and exited the chatroom}
::msgcat::mcset en {Please enter your desired nickname for the chatroom %s}
::msgcat::mcset en {Synchronize chatroom presence with global presence}
::msgcat::mcset en {Show incoming messages in this window}
::msgcat::mcset en {Invite contact to chatroom %s.}
::msgcat::mcset en {Write Jabber server ip number or name, or choose from the popup menu. You should already have an account with this server.}
::msgcat::mcset en {Enter your account as user@example.org, or choose a profile. You should already have an account.}
::msgcat::mcset en {Enter your Contact ID as user@example.org. You should already have an account with this server.}
::msgcat::mcset en {Enter your username and password to login to %s.}
::msgcat::mcset en {Select a service, and enter a chatroom and nickname. You can discover the available chatrooms on the selected service. Some chatrooms may require a password.}
::msgcat::mcset en {Set a new password for}
::msgcat::mcset en {Select an image file for the background. To remove a background image press Remove and Save.}
::msgcat::mcset en {You are already registered with this service. These are your current registration settings.}
::msgcat::mcset en {Select a server from the list or manually enter one. Then press Next to retrieve the registration instructions. Follow the instructions and hit Register.}
::msgcat::mcset en {Register with the service %s. You may need to press the Next button to retrieve the registration instructions.}
::msgcat::mcset en {Select a service and press Next}
::msgcat::mcset en {Do you want to register a new account with %s.}
::msgcat::mcset en {Select the chat system and contact ID of the contact you would like to add.}
::msgcat::mcset en {Nickname and group are optional and can be set or changed later.}
::msgcat::mcset en {Edit nickname and group of %s. You also can request or remove presence subscription.}
::msgcat::mcset en {Request presence subscription}
::msgcat::mcset en {Remove presence subscription}
::msgcat::mcset en {The roster is up to date}
::msgcat::mcset en {Search contacts with the selected service. A new search form will empty the previous one.}
::msgcat::mcset en {Waiting for Get to be pressed}
::msgcat::mcset en {Select iconsets for each group. A deselected group will use the normal iconset.}
::msgcat::mcset en {%s contacts want to see your presence. Select those who may see your presence.}
::msgcat::mcset en {Entering a nickname and group is optional, and for your personal use only.}
::msgcat::mcset en {May %s see your presence?}
::msgcat::mcset en {The supported image formats are}
::msgcat::mcset en {Negotiating TLS security}
::msgcat::mcset en {Add your personal notes about this contact.}
::msgcat::mcset en {Version information for %s.}
::msgcat::mcset en {Waiting for disco result}
::msgcat::mcset en {Contacted %s. Waiting for response}
::msgcat::mcset en {Waiting for server response}
::msgcat::mcset en {Downloading configuration form}
::msgcat::mcset en {Connected to %s. Initializing the XML stream}
::msgcat::mcset en {Labels with (*) are required.}

# Setup assistant:
::msgcat::mcset en {This setup assistant will help you to configure the most important settings to get started with %s.}
::msgcat::mcset en {Any time you can press Previous to go back. Press Next to proceed.}
::msgcat::mcset en {Choose your language}
::msgcat::mcset en {Select or enter a server you wish to have your account on. If you already have an account, use the server of this account.}
::msgcat::mcset en {Enter your username and password. If the chosen username is already in use by someone else, you will not be able to register.}
::msgcat::mcset en {Click on the button below to create a new account. You must be connected to with the Internet. Pay attention to a possible firewall!}
::msgcat::mcset en {That's all. Also, be nice to the bug and his friends ;-)}

# Groupchat:
::msgcat::mcset en {Ban %s from the chatroom %s.}
::msgcat::mcset en {Converting Chat into Conference}
::msgcat::mcset en {Do you want to destroy the chatroom %s? Optionally, you can point present chatroom participants to an alternative chatroom and tell why the chatroom is destroyed.}
::msgcat::mcset en {Cannot enter chatroom %s.}
::msgcat::mcset en {Cannot invite %s to %s.}
::msgcat::mcset en {%s invites you to join chatroom %s.}
::msgcat::mcset en {The password %s is needed for entry.}
::msgcat::mcset en {Do you want to join right away?}
::msgcat::mcset en {Cannot interact with the chatroom %s.}
::msgcat::mcset en {Kick %s from the chatroom %s.}

::msgcat::mcset en {Downloading business card from %s}
::msgcat::mcset en {Cannot download business card.}
::msgcat::mcset en {Business card downloaded.}

::msgcat::mcset en {Automatically check for updates}
::msgcat::mcset en {Send a file to %s. A description is optional.}

# Composing events
::msgcat::mcset en {%s is composing a reply}
::msgcat::mcset en {%s is on the chat}
::msgcat::mcset en {%s is thinking what to write}
::msgcat::mcset en {%s has left the chat for a while}
::msgcat::mcset en {%s has closed the chat}

# TODO
# Get file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset en getcontacting   {Contacting %s. Waiting for response...}
::msgcat::mcset en geteoferr       {Connection to %s failed: received an eof.}
::msgcat::mcset en getconnerr	   {Connection to %s failed.}
::msgcat::mcset en getnegotiate    {Contacted %s. Negotiating...}
::msgcat::mcset en getreaderr      {Cannot read server response from %s.}
::msgcat::mcset en getunknownprot  {The server at %s did not respond with a well formed protocol.}
::msgcat::mcset en {Received response of the server %s.\n Error code %s\nMessage: %s}
::msgcat::mcset en getstarts	   {%s accepted file %s. Initiating file transfer...}
::msgcat::mcset en getended	   {Transfer from %s ended prematurely.}
::msgcat::mcset en getfinished	   {Finished downloading file %s from %s.}
::msgcat::mcset en getneterr	   {Cannot download from %s: network error.}

# TODO
# Put file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset en putcontacting   {Contacting %s. Waiting for response...}
::msgcat::mcset en puteoferr       {Connection to %s failed: received an eof.}
::msgcat::mcset en putconnerr	    {Connection to %s failed.}
::msgcat::mcset en putnegotiate    {Client contacted: %s; negotiating...}
::msgcat::mcset en putreaderr      {Error reading server response from %s.}
::msgcat::mcset en putunknownprot  {The server at %s did not respond with a well formed protocol.}
::msgcat::mcset en {The server at %s responded with a code %s: %s}
::msgcat::mcset en putstarts	    {Client at %s accepted file %s. Starts transfer...}
::msgcat::mcset en putended	    {Transfer to %s ended prematurely.}
::msgcat::mcset en putfinished	    {Finished putting file %s to %s.}
::msgcat::mcset en putneterr	    {Network error when putting to %s.}

# These are specific for phones (VoIP)
::msgcat::mcset en {Call}
::msgcat::mcset en {Forward current call to}
::msgcat::mcset en {Ring, ring}
::msgcat::mcset en {Phone is ringing from %s}
::msgcat::mcset en {Failed calling %s}
::msgcat::mcset en {Dial}
::msgcat::mcset en {Number}
::msgcat::mcset en {Call to}
::msgcat::mcset en {Forward to}

# Note to translators: these strings are not yet activated
::msgcat::mcset en {Address Book}
::msgcat::mcset en {New address book}
::msgcat::mcset en {Phone number}
::msgcat::mcset en {Modify address book}

# TODO
::msgcat::mcset en mNewAB		{New}
::msgcat::mcset en mModifyAB		{Modify}
::msgcat::mcset en mRemoveAB		{Remove}

::msgcat::mcset en {Make Call}
::msgcat::mcset en {Notify Call}
::msgcat::mcset en {Inbound Call}
::msgcat::mcset en {Outbound Call}
::msgcat::mcset en {Answer}
::msgcat::mcset en {Hung Up}
::msgcat::mcset en {Call VM?}

# IAX Phone
# Note to translators: these strings are not yet activated
if {0} {
    ::msgcat::mcset en Codecs
    ::msgcat::mcset en Devices
    ::msgcat::mcset en Filters
    ::msgcat::mcset en {IAX Phone}
    ::msgcat::mcset en {IAX Account}
    # translation help: http://en.wikipedia.org/wiki/Caller_id
    ::msgcat::mcset en {Caller ID number}
    ::msgcat::mcset en {Caller ID name}
    ::msgcat::mcset en Microphone
    ::msgcat::mcset en Speakers
    # translation help: http://en.wikipedia.org/wiki/Automatic_gain_control
    ::msgcat::mcset en {Automatic gain control (AGC)}
    ::msgcat::mcset en {Automatically adjust volume levels}
    # translation help: http://lists.xiph.org/pipermail/speex-dev/2007-May/005565.html
    ::msgcat::mcset en {Analog automatic gain control (AAGC)}
    ::msgcat::mcset en {Can prevent clipping}
    # translation help: http://en.wikipedia.org/wiki/Noise_reduction
    ::msgcat::mcset en {Noise reduction}
    # translation help: http://en.wikipedia.org/wiki/Comfort_noise
    ::msgcat::mcset en {Comfort noise} 
    ::msgcat::mcset en {Artificial background noise to fill silence}
    ::msgcat::mcset en Codec
    ::msgcat::mcset en {iLBC (internet Low Bitrate Codec) is a free speech codec suitable for robust voice communication over IP}
    ::msgcat::mcset en {Speex is an Open Source/Free Software patent-free audio compression format designed for speech}
    ::msgcat::mcset en {Standard used in European digital communication systems (ITU-T)}
    ::msgcat::mcset en {Standard used in digital communication systems in North America and Japan (ITU-T)}
    ::msgcat::mcset en {GSM 06.10 provisional standard for full-rate speech transcoding (ETSI)}
}

# Messages for Mood XEP: http://www.xmpp.org/extensions/xep-0107.html
# Note to translators: The upper case menu strings have lower case
# duplicates. If your language, like mine, always start with a lower case
# character you can run the following script in a wish shell (uncommented):
#
# set lines {paste in the desired text chunk here...}
# foreach line [split $lines "\n"] {
#     set str [string tolower [string trimleft [lindex $line 2] m]]
#     puts "::msgcat::mcset sv $str   [list [string tolower [lindex $line 3]]]"
# }
# bug: this should be M&ood..., but this does not work!
# TODO
::msgcat::mcset en mMood            Mood

::msgcat::mcset en Afraid
::msgcat::mcset en Amazed
::msgcat::mcset en Angry
::msgcat::mcset en Annoyed
::msgcat::mcset en Anxious
::msgcat::mcset en Aroused
::msgcat::mcset en Ashamed
::msgcat::mcset en Bored
::msgcat::mcset en Brave
::msgcat::mcset en Calm
::msgcat::mcset en Cold
::msgcat::mcset en Confused
::msgcat::mcset en Contented
::msgcat::mcset en Cranky
::msgcat::mcset en Curious
::msgcat::mcset en Depressed
::msgcat::mcset en Disappointed
::msgcat::mcset en Disgusted
::msgcat::mcset en Distracted
::msgcat::mcset en Embarrassed
::msgcat::mcset en Excited
::msgcat::mcset en Flirtatious
::msgcat::mcset en Frustrated
::msgcat::mcset en Grumpy
::msgcat::mcset en Guilty
::msgcat::mcset en Happy
::msgcat::mcset en Hot
::msgcat::mcset en Humbled
::msgcat::mcset en Humiliated
::msgcat::mcset en Hungry
::msgcat::mcset en Hurt
::msgcat::mcset en Impressed
::msgcat::mcset en {In awe}
::msgcat::mcset en {In love}
::msgcat::mcset en Indignant
::msgcat::mcset en Interested
::msgcat::mcset en Intoxicated
::msgcat::mcset en Invincible
::msgcat::mcset en Jealous
::msgcat::mcset en Lonely
::msgcat::mcset en Mean
::msgcat::mcset en Moody
::msgcat::mcset en Nervous
::msgcat::mcset en Neutral
::msgcat::mcset en Offended
::msgcat::mcset en Playful
::msgcat::mcset en Proud
::msgcat::mcset en Relieved
::msgcat::mcset en Remorseful
::msgcat::mcset en Restless
::msgcat::mcset en Sad
::msgcat::mcset en Sarcastic
::msgcat::mcset en Serious
::msgcat::mcset en Shocked
::msgcat::mcset en Shy
::msgcat::mcset en Sick
::msgcat::mcset en Sleepy
::msgcat::mcset en Stressed
::msgcat::mcset en Surprised
::msgcat::mcset en Thirsty
::msgcat::mcset en Worried

::msgcat::mcset en {Mood change}
::msgcat::mcset en {retracted mood}

::msgcat::mcset en is
::msgcat::mcset en because
::msgcat::mcset en afraid
::msgcat::mcset en amazed
::msgcat::mcset en angry
::msgcat::mcset en annoyed
::msgcat::mcset en anxious
::msgcat::mcset en aroused
::msgcat::mcset en ashamed
::msgcat::mcset en bored
::msgcat::mcset en brave
::msgcat::mcset en calm
::msgcat::mcset en cold
::msgcat::mcset en confused
::msgcat::mcset en contented
::msgcat::mcset en cranky
::msgcat::mcset en curious
::msgcat::mcset en depressed
::msgcat::mcset en disappointed
::msgcat::mcset en disgusted
::msgcat::mcset en distracted
::msgcat::mcset en embarrassed
::msgcat::mcset en excited
::msgcat::mcset en flirtatious
::msgcat::mcset en frustrated
::msgcat::mcset en grumpy
::msgcat::mcset en guilty
::msgcat::mcset en happy
::msgcat::mcset en hot
::msgcat::mcset en humbled
::msgcat::mcset en humiliated
::msgcat::mcset en hungry
::msgcat::mcset en hurt
::msgcat::mcset en impressed
::msgcat::mcset en {in awe}
::msgcat::mcset en {in love}
::msgcat::mcset en indignant
::msgcat::mcset en interested
::msgcat::mcset en intoxicated
::msgcat::mcset en invincible
::msgcat::mcset en jealous
::msgcat::mcset en lonely
::msgcat::mcset en mean
::msgcat::mcset en moody
::msgcat::mcset en nervous
::msgcat::mcset en neutral
::msgcat::mcset en offended
::msgcat::mcset en playful
::msgcat::mcset en proud
::msgcat::mcset en relieved
::msgcat::mcset en remorseful
::msgcat::mcset en restless
::msgcat::mcset en sad
::msgcat::mcset en sarcastic
::msgcat::mcset en serious
::msgcat::mcset en shocked
::msgcat::mcset en shy
::msgcat::mcset en sick
::msgcat::mcset en sleepy
::msgcat::mcset en stressed
::msgcat::mcset en surprised
::msgcat::mcset en thirsty
::msgcat::mcset en worried

::msgcat::mcset en {Custom Mood}

# TODO
::msgcat::mcset en mCustomMood...       {&Custom Mood...}

::msgcat::mcset en {Select your mood to show to your contacts.}
::msgcat::mcset en {Only contacts with compatible software will see your mood.}

# More balloonhelp stuff.
::msgcat::mcset en {Chat address}
::msgcat::mcset en {Group to which this contact should belong to}
::msgcat::mcset en {Your nickname for local display}
::msgcat::mcset en {Number of messages to display}
::msgcat::mcset en {Select or manually enter a chatroom service}
::msgcat::mcset en {Select or manually enter the name of a chatroom}

::msgcat::mcset en {Support for mp3, wav, and a few other audio formats}
::msgcat::mcset en {Support for common image formats}
::msgcat::mcset en {Support for PNG images}
::msgcat::mcset en {Support for several animation, video and audio formats}
::msgcat::mcset en {Support for several animation, image, video and audio formats}

::msgcat::mcset en {Enter the subject of the conversation, set by pressing Return}
::msgcat::mcset en {You need to be logged in to see the presence of this contact}
::msgcat::mcset en {Enter your message and press Return or Shift-Return}
::msgcat::mcset en {If activated then directed auto-away presence will be sent to users on hidden chat tabs}
::msgcat::mcset en {When you have <number> or more active chat sessions, presence state will be automatically changed to Do Not Disturb.}
::msgcat::mcset en {Show or hide status changes in chat}

::msgcat::mcset en {Not yet implemented.}

# Messages for User Activity XEP
::msgcat::mcset en Activity

# TODO
::msgcat::mcset en mActivity...       {Acti&vity...}
::msgcat::mcset en mCustomActivity... {Custom Activity...}

::msgcat::mcset en {Traveling}
::msgcat::mcset en {Commuting}
::msgcat::mcset en {Cycling}
::msgcat::mcset en {Driving}
::msgcat::mcset en {In a car}
::msgcat::mcset en {On a bus}
::msgcat::mcset en {On a plane}
::msgcat::mcset en {On a train}
::msgcat::mcset en {On a trip}
::msgcat::mcset en {Walking}

::msgcat::mcset en {Eating}
::msgcat::mcset en {Having a snack}
::msgcat::mcset en {Having breakfast}
::msgcat::mcset en {Having dinner}
::msgcat::mcset en {Having lunch}

::msgcat::mcset en {Doing chores}
::msgcat::mcset en {Buying groceries}
::msgcat::mcset en {Cleaning}
::msgcat::mcset en {Cooking}
::msgcat::mcset en {Doing maintenance}
::msgcat::mcset en {Doing the dishes}
::msgcat::mcset en {Doing the laundry}
::msgcat::mcset en {Gardening}
::msgcat::mcset en {Running an errand}
::msgcat::mcset en {Walking the dog}

::msgcat::mcset en {Working}
::msgcat::mcset en {Coding}
::msgcat::mcset en {In a meeting}
::msgcat::mcset en {Studying}
::msgcat::mcset en {Writing}

::msgcat::mcset en {Exercising}
::msgcat::mcset en {Hiking}
::msgcat::mcset en {Jogging}
::msgcat::mcset en {Playing sports}
::msgcat::mcset en {Running}
::msgcat::mcset en {Skiing}
::msgcat::mcset en {Swimming}
::msgcat::mcset en {Working out}

::msgcat::mcset en {Talking}
::msgcat::mcset en {In real life}
::msgcat::mcset en {On the phone}
::msgcat::mcset en {On video phone}

::msgcat::mcset en {Relaxing}
::msgcat::mcset en {Gaming}
::msgcat::mcset en {Going out}
::msgcat::mcset en {Partying}
::msgcat::mcset en {Reading}
::msgcat::mcset en {Rehearsing}
::msgcat::mcset en {Shopping}
::msgcat::mcset en {Socializing}
::msgcat::mcset en {Sunbathing}
::msgcat::mcset en {Watching tv}
::msgcat::mcset en {Watching a movie}

::msgcat::mcset en {Grooming}
::msgcat::mcset en {At the spa}
::msgcat::mcset en {Brushing teeth}
::msgcat::mcset en {Getting a haircut}
::msgcat::mcset en {Shaving}
::msgcat::mcset en {Taking a bath}
::msgcat::mcset en {Taking a shower}

::msgcat::mcset en {Drinking}
::msgcat::mcset en {Having a beer}
::msgcat::mcset en {Having coffee}
::msgcat::mcset en {Having tea}

::msgcat::mcset en {Inactive}
::msgcat::mcset en {Day off}
::msgcat::mcset en {Hanging out}
::msgcat::mcset en {On vacation}
::msgcat::mcset en {Scheduled holiday}
::msgcat::mcset en {Sleeping}

::msgcat::mcset en {Having appointment}

::msgcat::mcset en {Set your activity that will be shown to your contacts.}
::msgcat::mcset en {Select from the first button your general activity, and optionally, your specific actvity from the second button. You may also add a descriptive text.}

# XEP-0080: User Location
::msgcat::mcset en {Location}

# TODO
::msgcat::mcset en mLocation...		{Locat&ion...}

::msgcat::mcset en {Set your location that will be shown to your contacts.}
::msgcat::mcset en {Enter your location details below. At least you should set latitude and longitude.}

::msgcat::mcset en {Altitude}
::msgcat::mcset en {Named Area}
::msgcat::mcset en {GPS Bearing}
::msgcat::mcset en {Building}
::msgcat::mcset en {GPS Datum}
::msgcat::mcset en {GPS Error}
::msgcat::mcset en {Floor}
::msgcat::mcset en {Latitude}
::msgcat::mcset en {Locality}
::msgcat::mcset en {Longitude}
::msgcat::mcset en {Room}
::msgcat::mcset en {Street}
::msgcat::mcset en {Timestamp}

::msgcat::mcset en {Altitude in meters above or below sea level}
::msgcat::mcset en {Longitude in decimal degrees East}
::msgcat::mcset en {Latitude in decimal degrees North}
::msgcat::mcset en {The nation where the user is located}

::msgcat::mcset en {Synchronize with Google Earth}
::msgcat::mcset en {This is location data for}

# Buddy pouncing:
::msgcat::mcset en {Set a specific action for events related to %s. Select events using the tabs below.}
::msgcat::mcset en {Set a specific action for events related to any contact belonging to the group %s. Select events using the tabs below.}
::msgcat::mcset en {Set a specific action for events related to any contact in your contact list. Select events using the tabs below.}

::msgcat::mcset en {%s just went online!}
::msgcat::mcset en {%s just went offline!}
::msgcat::mcset en {%s just sent you a message!}
::msgcat::mcset en {%s just started a chat!}

::msgcat::mcset en {Send message with subject}
# TODO
::msgcat::mcset en mContactActions...   {&Contact Actions...}

# Image magic:
::msgcat::mcset en {Click on a window or drag a rectangular area to import a snapshot into the current whiteboard.}
::msgcat::mcset en {Dangerous in-box path name: %s}
::msgcat::mcset en {Click OK to remove files: %s}

# File Types
# translation help: http://en.wikipedia.org/wiki/List_of_file_formats
::msgcat::mcset en {World Application}
::msgcat::mcset en {QuickDraw 3D Metafile}
::msgcat::mcset en {Tcl File}
::msgcat::mcset en {Itcl File}
::msgcat::mcset en {Session Description Protocol}
::msgcat::mcset en {Adobe Flash Media}
::msgcat::mcset en {Mac Binary}
::msgcat::mcset en {VTK 3D}
::msgcat::mcset en {Generic File}
::msgcat::mcset en {PDF Document}
::msgcat::mcset en {PostScript Document}
::msgcat::mcset en {JavaScript File}
::msgcat::mcset en {TeX File}
::msgcat::mcset en {Archive Tar}
::msgcat::mcset en {Abi Word Document}
::msgcat::mcset en {Microsoft Excel Spreadsheet}
::msgcat::mcset en {Microsoft PowerPoint Presentation}
::msgcat::mcset en {Microsoft Word Document}
::msgcat::mcset en {MPEG Audio}
::msgcat::mcset en {AIFF/Amiga Audio}
::msgcat::mcset en {ULAW (Sun) Audio}
::msgcat::mcset en {Streaming Audio}
::msgcat::mcset en {WAV Audio}
::msgcat::mcset en {QCP Audio}
::msgcat::mcset en {MIDI Audio}
::msgcat::mcset en {BMP Image}
::msgcat::mcset en {FlashPix Image}
::msgcat::mcset en {GIF Image}
::msgcat::mcset en {JPEG Image}
::msgcat::mcset en {Macpaint Image}
::msgcat::mcset en {Adobe Photoshop Image}
::msgcat::mcset en {PNG Image}
::msgcat::mcset en {PICT Image}
::msgcat::mcset en {SGI Image}
::msgcat::mcset en {Truevision Targa Image}
::msgcat::mcset en {TIFF Image}
::msgcat::mcset en {X PixMap Image}
::msgcat::mcset en {Plain Text Document}
::msgcat::mcset en {XML Document}
::msgcat::mcset en {RTF Document}
::msgcat::mcset en {HTML Document}
::msgcat::mcset en {Cascading Style Sheet}
::msgcat::mcset en {QuickTime Video}
::msgcat::mcset en {MPEG-4 Video}
::msgcat::mcset en {DV Video}
::msgcat::mcset en {MPEG Video}
::msgcat::mcset en {Microsoft AVI Video}
::msgcat::mcset en {Autodesk's FLIC File}

# END --------------------------------------------------------------------------


