# Spanish language version of the Coccinella message catalog.
#
#       The English catalog is the master of all other catalogs
#
#       Translators:
#         cs  David Stancl (david.stancl at seznam.cz), 2007-2008
#         da  Mogens Pedersen  (Mogens.Pedersen at skolekom.dk), 2006
#         de  Hermann J. Beckers (hj dot beckers at onlinehome dot de), 2004-2008
#         es  Néstor Díaz (n3storm at grupoikusnet.com), 2004
#             Antonio F. Cano (antonio at grupoikusnet.com), 2006
#             Agustin Vericat (agustin at grupoikusnet.com), 2006
#             César Alcalde (lambda512 at gmail.com), 2008
#         fr  Guillaume Ayoub (xovni at wanadoo.fr), 2004-2005
#             Nicolas Vérité (xmpp:nyco@jabber.fr, nicolas.verite at gmail.com), 2008
#         it  Mirko Graziani (contatto at imatica.it), 2006-2008
#         ko  Dylan Park, Korea NVC Center (hanmaum AT krnvc.org), 2006
#         nl  Sander Devrieze (s.devrieze at pandora.be), 2004-2008
#             Bart Van Hove (bartvanhove at skynet.be), 2004
#         pl  Zbigniew Baniewski (zb at ispid.com.pl), 2005-2008
#         ru  Alexander Balezin (xmpp:gescheit@jabber.ttn.ru, gescheit at list.ru), 2005-2007
#         sv  Mats Bengtsson, 2002-2008
#
# General type of text, such as "OK", "Cancel", and the like. 
# We use the source string as the message.
# Defined in global namespace and may therefore be used in any namespace.
# 
#   $Id: es.msg,v 1.110 2008-09-24 18:37:59 sdevrieze Exp $

::msgcat::mcset es Abort                 {Cancelar}
::msgcat::mcset es Action                {Acción}
::msgcat::mcset es Add                   {Añadir}
::msgcat::mcset es Address               {Dirección}
::msgcat::mcset es Admin                 {Administrador}
::msgcat::mcset es admin                 {administrador}
::msgcat::mcset es Affiliation           {Afiliación}
::msgcat::mcset es Always                {Siempre}
::msgcat::mcset es Any                   {Cualquier}
::msgcat::mcset es Appearance            {Apariencia}
::msgcat::mcset es Author                {Autor}
::msgcat::mcset es Avatar                {Avatar}
::msgcat::mcset es Binary                {Binario}
::msgcat::mcset es Birthday              {Cumpleaños}
::msgcat::mcset es Bookmarks             {Favoritos}
::msgcat::mcset es Browser               {Navegador}
::msgcat::mcset es Cancel                {Cancelar}
::msgcat::mcset es Chatroom              {Sala}
::msgcat::mcset es City                  {Ciudad}
::msgcat::mcset es Clear                 {Limpiar}
::msgcat::mcset es Client                {Cliente}
::msgcat::mcset es Close                 {Cerrar}
::msgcat::mcset es Color                 {Color}
::msgcat::mcset es Company               {Compañía}
::msgcat::mcset es Configure             {Configurar}
::msgcat::mcset es Connection            {Conexión}
::msgcat::mcset es Contact               {Contacto}
::msgcat::mcset es Contacts              {Contactos}
::msgcat::mcset es Coordinates           {Coordenadas}
::msgcat::mcset es Country               {País}
::msgcat::mcset es Create                {Crear}
::msgcat::mcset es Customization         {Personalizar}
::msgcat::mcset es Date                  {Fecha}
::msgcat::mcset es Default               {Por defecto}
::msgcat::mcset es Delete                {Eliminar}
::msgcat::mcset es Deny                  {Denegar}
::msgcat::mcset es Department            {Departamento}
::msgcat::mcset es Description           {Descripción}
::msgcat::mcset es Detect                {Detectar}
::msgcat::mcset es Discover              {Descubrir}
::msgcat::mcset es Downloading           {Descargar}
::msgcat::mcset es Edit                  {Editar}
::msgcat::mcset es Email                 {Correo electronico}
::msgcat::mcset es Emoticons             {Emoticonos}
::msgcat::mcset es Encoding              {Codificar}
::msgcat::mcset es Enter                 {Entrar}
::msgcat::mcset es Error                 {Error}
::msgcat::mcset es Exit                  {Salir}
::msgcat::mcset es Export                {Exportar}
::msgcat::mcset es Extensions            {Extensiones}
::msgcat::mcset es File                  {Archivo}
::msgcat::mcset es Filter                {Filtro}
::msgcat::mcset es Finish                {Terminar}
::msgcat::mcset es Finished              {Terminado}
::msgcat::mcset es First                 {Primero}
::msgcat::mcset es Fonts                 {Tipografía}
::msgcat::mcset es Forward               {Avanzar}
::msgcat::mcset es From                  {De}
::msgcat::mcset es General               {General}
::msgcat::mcset es Get                   {Recibir}
::msgcat::mcset es Getting               {Recibiendo}
::msgcat::mcset es Grant                 {Dar permisos}
::msgcat::mcset es Group                 {Grupo}
::msgcat::mcset es Height                {Altura}
::msgcat::mcset es History               {Historial}
::msgcat::mcset es Home                  {Inicio}
::msgcat::mcset es Host                  {Host}
::msgcat::mcset es Icon                  {Icono}
::msgcat::mcset es Image                 {Imagen}
::msgcat::mcset es Import                {Importar}
::msgcat::mcset es Inbox                 {Mensajes}
::msgcat::mcset es Info                  {Información}
::msgcat::mcset es Invite                {Invitar}
::msgcat::mcset es Invitation            {Invitation}
::msgcat::mcset es Key                   {Clave}
::msgcat::mcset es Language              {Idioma}
::msgcat::mcset es Last                  {Último}
::msgcat::mcset es Less                  {Menos}
::msgcat::mcset es Login                 {Conectarse}
::msgcat::mcset es Logout                {Desconectarse}
::msgcat::mcset es Member                {Miembro}
::msgcat::mcset es member                {miembro}
::msgcat::mcset es Message               {Mensaje}
::msgcat::mcset es Middle                {Medio}
::msgcat::mcset es Minutes               {Minutos}
::msgcat::mcset es Moderator             {Moderador}
::msgcat::mcset es moderator             {moderador}
::msgcat::mcset es Moderators            {Moderadores}
::msgcat::mcset es More                  {Más}
::msgcat::mcset es Name                  {Nombre}
::msgcat::mcset es Network               {Red}
::msgcat::mcset es Never                 {Nunca}
::msgcat::mcset es New                   {Nuevo}
::msgcat::mcset es Next                  {Siguiente}
::msgcat::mcset es Nickname              {Apodo}
::msgcat::mcset es No                    {No}
::msgcat::mcset es no                    {no}
::msgcat::mcset es None                  {Ninguno}
::msgcat::mcset es Notes                 {Notas}
::msgcat::mcset es Occupation            {Profesión}
::msgcat::mcset es Offline               {Desconectado}
::msgcat::mcset es OK                    {OK}
::msgcat::mcset es Online                {Conectado}
::msgcat::mcset es Open                  {Abrir}
::msgcat::mcset es Owner                 {Propietario}
::msgcat::mcset es owner                 {propietario}
::msgcat::mcset es Participants          {Participantes}
::msgcat::mcset es Password              {Contraseña}
::msgcat::mcset es Personal              {Personal}
::msgcat::mcset es Phone                 {Teléfono}
::msgcat::mcset es Play                  {Escuchar}
::msgcat::mcset es Plugins               {Plugins}
::msgcat::mcset es Port                  {Puerto}
::msgcat::mcset es Ports                 {Puertos}
::msgcat::mcset es Preferences           {Preferences}
::msgcat::mcset es Previous              {Anterior}
::msgcat::mcset es Print                 {Imprimir}
::msgcat::mcset es Priority              {Prioridad}
::msgcat::mcset es Profile               {Perfil}
::msgcat::mcset es Profiles              {Perfiles}
::msgcat::mcset es Progress              {Progreso}
::msgcat::mcset es Proxy                 {Proxy}
::msgcat::mcset es Quit?                 {Salir}
::msgcat::mcset es Quote                 {Citar}
::msgcat::mcset es Rate                  {Valorar}
::msgcat::mcset es Region                {Región}
::msgcat::mcset es Register              {Registrarse}
::msgcat::mcset es Remaining             {Restante}
::msgcat::mcset es Remove                {Borrar}
::msgcat::mcset es Reply                 {Responder}
::msgcat::mcset es Resource              {Recursos}
::msgcat::mcset es Revoke                {Quitar permisos}
::msgcat::mcset es Role                  {Rol}
::msgcat::mcset es Running               {En funcionamiento}
::msgcat::mcset es Save                  {Guardar}
::msgcat::mcset es Search                {Buscar}
::msgcat::mcset es Secured               {Seguro}
::msgcat::mcset es Send                  {Enviar}
::msgcat::mcset es Server                {Servidor}
::msgcat::mcset es Service               {Servicio}
::msgcat::mcset es Services              {Servicios}
::msgcat::mcset es Settings              {Opciones}
::msgcat::mcset es Shortcut              {Atajo}
::msgcat::mcset es Shortcuts             {Atajos}
::msgcat::mcset es Size                  {Tamaño}
::msgcat::mcset es Skin                  {Skin}
::msgcat::mcset es Sleep                 {Sleep}
::msgcat::mcset es Sounds                {Sonidos}
::msgcat::mcset es Specific              {Especifico}
::msgcat::mcset es Status                {Estado}
::msgcat::mcset es Stop                  {Parar}
::msgcat::mcset es Subject               {Asunto}
::msgcat::mcset es System                {Sistema}
::msgcat::mcset es Text                  {Texto}
::msgcat::mcset es Theme                 {Tema}
::msgcat::mcset es Time                  {Hora}
::msgcat::mcset es Timeout               {Tiempo agotado}
::msgcat::mcset es Title                 {Título}
::msgcat::mcset es Topic                 {Tema}
::msgcat::mcset es Transports            {Pasarela}
::msgcat::mcset es Type                  {Tipo}
::msgcat::mcset es Unregister            {Desregistrarse}
::msgcat::mcset es Username              {Nombre de usuario}
::msgcat::mcset es Version               {Versión}
::msgcat::mcset es Visitors              {Visitantes}
::msgcat::mcset es Voice                 {Voz}
::msgcat::mcset es voice                 {voz}
::msgcat::mcset es Volume                {Volume}
::msgcat::mcset es Warning               {Atención}
::msgcat::mcset es Website               {Sitio Web}
::msgcat::mcset es Whiteboard            {Pizarra}
::msgcat::mcset es Width                 {Anchura}
::msgcat::mcset es Work                  {Trabajo}
::msgcat::mcset es Yes                   {Sí}
::msgcat::mcset es yes                   {sí}

# A few words that are not unambiguous and have therefore a prefix:
# Note to translators: this means "Application" as in computer program.
::msgcat::mcset es program-Application   {Programa}
::msgcat::mcset es machine-Sleep         {Sleep}

# Try to move next strings to normal strings
# Canvas item options, names and values.
# Names:
::msgcat::mcset es anchor                {Ancla}
::msgcat::mcset es arrow                 {Flecha}
::msgcat::mcset es arrowshape            {Forma de Flecha}
::msgcat::mcset es capstyle              {Estilo Mayúsculas}
::msgcat::mcset es dash                  {Estilo de línea}
::msgcat::mcset es fill                  {Rellenar}
::msgcat::mcset es fontfamily            {Familia de la fuente}
::msgcat::mcset es fontsize              {Tamaño de la fuente}
::msgcat::mcset es fontweight            {Grosor de la fuente}
::msgcat::mcset es image                 {Imagen}
::msgcat::mcset es joinstyle             {Estilo de la unión}
::msgcat::mcset es justify               {Justificar}
::msgcat::mcset es outline               {Linea exterior}
::msgcat::mcset es outlinestipple        {Punteado de la linea exterior}
::msgcat::mcset es smooth                {Suavizado}
::msgcat::mcset es stipple               {Punteado}
::msgcat::mcset es tags                  {Marcas}
::msgcat::mcset es text                  {Texto}
::msgcat::mcset es width                 {Anchura}

# Values (see item inspector to see what they mean):
# anchor
::msgcat::mcset es n                     {N}
::msgcat::mcset es ne                    {NE}
::msgcat::mcset es e                     {E}
::msgcat::mcset es se                    {SE}
::msgcat::mcset es s                     {S}
::msgcat::mcset es sw                    {SW}
::msgcat::mcset es w                     {W}
::msgcat::mcset es nw                    {NW}
::msgcat::mcset es center                {Centrado}
# arrow
::msgcat::mcset es last                  {Último}
::msgcat::mcset es first                 {Primero}
::msgcat::mcset es both                  {Ambos}

::msgcat::mcset es transparent           {Transparente}
::msgcat::mcset es gray75                {Gris 75%}
::msgcat::mcset es gray50                {Gris 50%}
::msgcat::mcset es gray25                {Gris 25%}
::msgcat::mcset es gray12                {Gris 12%}

::msgcat::mcset es round                 {Círculo}
::msgcat::mcset es miter                 {Mitra}
::msgcat::mcset es bevel                 {Bisel}
::msgcat::mcset es butt                  {Cabo}
::msgcat::mcset es projecting            {Projectando}

::msgcat::mcset es normal                {Normal}
::msgcat::mcset es bold                  {Negrita}
::msgcat::mcset es italic                {Italica}

::msgcat::mcset es left                  {Izquierda}
::msgcat::mcset es right                 {Derecha}
::msgcat::mcset es false                 {Falso}
::msgcat::mcset es true                  {Verdadero}

# dashes
::msgcat::mcset es none                  {Ninguno}
::msgcat::mcset es dotted                {Punteado}
::msgcat::mcset es dash-dotted           {Guiones-puntos}
::msgcat::mcset es dashed                {Guiones}


# Status messages.
::msgcat::mcset es available             {disponible}
::msgcat::mcset es away                  {ausente}
::msgcat::mcset es {do not disturb}      {no molestar}
::msgcat::mcset es {not available}       {desconectado}
::msgcat::mcset es {extended away}       {no disponible}
::msgcat::mcset es invisible             {invisible}
::msgcat::mcset es chat                  {libre para charlar}

# All menu labels; concateneted and prepended with 'm' for the database key.
::msgcat::mcset es mAboutCoccinella      {Acerca de Coccinella...}
::msgcat::mcset es mAboutQuickTimeTcl    {Acerca de QuickTimeTcl...}
::msgcat::mcset es mAction               {Acción}
::msgcat::mcset es mAddToDictionary      {Añadir al Diccionario}
::msgcat::mcset es mAdHocCommands        {Comandos Ad-Hoc}
::msgcat::mcset es mAddContact...        {&Añadir contacto...}
::msgcat::mcset es mAddSpeechBubble      {Añadir un bocadillo}
::msgcat::mcset es mAll                  {Todos}
::msgcat::mcset es mArc                  {Arco}
::msgcat::mcset es mArcs                 {Arcos}
::msgcat::mcset es mAttachMessage        {Adjuntar mensaje...}
::msgcat::mcset es mAvailable            {Disponible}
::msgcat::mcset es mAway                 {Ausente}
::msgcat::mcset es mBackgroundColor...   {Color de fondo...}
::msgcat::mcset es mBackgroundImage      {Imagen de fondo}
::msgcat::mcset es mBackgroundImage...   {Imagen de fondo...}
::msgcat::mcset es mBold                 {Negrita}
::msgcat::mcset es mBrushThickness       {Grosor de la brocha}
::msgcat::mcset es mBugReport...         {&Informar de un error...}
::msgcat::mcset es mBusinessCard...      {Ver &Tarjeta de visita...}
::msgcat::mcset es mBC...                {&Tarjeta de visita...}
::msgcat::mcset es mCall                 {Llamar a...}
::msgcat::mcset es mChat                 {Charla}
::msgcat::mcset es mChat...              {Charla...}
::msgcat::mcset es mChord                {Cuerda}
::msgcat::mcset es mClear                {Limpiar}
::msgcat::mcset es mClearMenu            {Limpiar Menu}
::msgcat::mcset es mCloseWindow          {&Cerrar la ventana}
::msgcat::mcset es mCoccinellaHome...    {&Página principal...}
::msgcat::mcset es mColor...             {Color...}
::msgcat::mcset es mContacts...          {&Contactos...}
::msgcat::mcset es mControlPanel         {Panel de Control}
::msgcat::mcset es mCopy                 {&Copiar}
::msgcat::mcset es mCreateRoom...        {&Crear una sala...}
::msgcat::mcset es mCustomStatus...      {Estado personalizado...}
::msgcat::mcset es mCut                  {Cortar}
::msgcat::mcset es mDash                 {Punteado}
::msgcat::mcset es mDebug                {Depurar}
::msgcat::mcset es mDecreasing           {Descendente}
::msgcat::mcset es mDictionaries         {Diccionarios}
::msgcat::mcset es mDiscoverServer...    {&Buscar servidores...}
::msgcat::mcset es mDoNotDisturb         {No molestar}
::msgcat::mcset es mEdit                 {Editar}
::msgcat::mcset es mEditBookmarks...     {Editar favoritos}
::msgcat::mcset es mEditBC...            {Editar &Tarjeta de visita...}
::msgcat::mcset es mEditContact...       {&Editar Contacto...}
::msgcat::mcset es mEditItem...          {&Editar Elemento...}
::msgcat::mcset es mEditNick             {Editar apodo}
::msgcat::mcset es mEditProfiles...      {&Editar Perfiles...}
::msgcat::mcset es mEnterRoom...         {Entrar sa&la...}
::msgcat::mcset es mErrorLog             {Mensajes de error...}
::msgcat::mcset es mExport               {Exportar}
::msgcat::mcset es mExportImage...       {Exportar Imagen...}
::msgcat::mcset es mExportMovie...       {Exportar video...}
::msgcat::mcset es mExtendedAway         {No disponible}
::msgcat::mcset es mFile                 {Archivo}
::msgcat::mcset es mFill                 {Rellenar}
::msgcat::mcset es mFillColor...         {Color de relleno...}
::msgcat::mcset es mFind                 {Buscar}
::msgcat::mcset es mFindNext             {Buscar siguiente}
::msgcat::mcset es mFindPrevious         {Buscar anterior}
::msgcat::mcset es mFlip                 {Reflejar}
::msgcat::mcset es mFont                 {Fuente}
::msgcat::mcset es mFontSize             {Tamaño de la fuente}
::msgcat::mcset es mGrid                 {Rejilla}
::msgcat::mcset es mHideControlPanel     {Ocultar el Panel de Control}
::msgcat::mcset es mHistory...           {&Historial...}
::msgcat::mcset es mHorizontal           {Horizontal}
::msgcat::mcset es mHugeFont             {Enorme}
::msgcat::mcset es mIconSet...           {&Conjunto de iconos...}
::msgcat::mcset es mIgnore               {Ignorar}
::msgcat::mcset es mImageLarger          {Agrandar la imagen}
::msgcat::mcset es mImageSmaller         {Reducir la imagen}
::msgcat::mcset es mImport               {Importar}
::msgcat::mcset es mImportImage/Movie... {&Importar una imagen o película...}
::msgcat::mcset es mInbox...             {&Buzón de entrada...}
::msgcat::mcset es mIncreasing           {Ascendente}
::msgcat::mcset es mInfo                 {Información}
::msgcat::mcset es mInvisible            {Invisible}
::msgcat::mcset es mItalic               {Cursiva}
::msgcat::mcset es mJiveCall             {Llamar a...}
::msgcat::mcset es mJiveForward          {Desviar la llamada actual a...}
::msgcat::mcset es mLargeFont            {Grande}
::msgcat::mcset es mLarger               {Agrandar}
::msgcat::mcset es mLargerFont           {Mas grande}
::msgcat::mcset es mLastLogin/Activity   {Última conexión/actividad}
::msgcat::mcset es mLibrary              {Biblioteca}
::msgcat::mcset es mLineSmoothness       {Suavizado de la línea}
::msgcat::mcset es mLocalTime            {Hora local...}
::msgcat::mcset es mLogin...             {Conectarse...}
::msgcat::mcset es mLoginTo              {Conectarse a %s}
::msgcat::mcset es mLoginTrpt            {Conectarse a un servidor de transporte}
::msgcat::mcset es mLogout               {Desconectarse}
::msgcat::mcset es mLogoutFrom           {Desconectarse de %s}
::msgcat::mcset es mLogoutTrpt           {Desconectarse de un servidor de transporte}
::msgcat::mcset es mLogoutWith...        {Desconectarse con el mensaje...}
::msgcat::mcset es mLower                {Bajar}
::msgcat::mcset es mMessage...           {&Mensaje...}
::msgcat::mcset es mMinimal              {Reducido}
::msgcat::mcset es mMinimize             {Mi&nimizar}
::msgcat::mcset es mNewAccount...        {Nueva cuenta...}
::msgcat::mcset es mNewWindow            {Nueva &Ventana}
::msgcat::mcset es mNormal               {Normal}
::msgcat::mcset es mNotAvailable         {No disponible}
::msgcat::mcset es mOffline              {Desconectado}
::msgcat::mcset es mOpenFile...          {&Abrir archivo...}
::msgcat::mcset es mOpenFolder...        {&Abrir carpeta...}
::msgcat::mcset es mOpenStream...        {Abrir &Flujo...}
::msgcat::mcset es mOutlineColor         {Color del borde}
::msgcat::mcset es mPageSetup            {&Propiedades de la página...}
::msgcat::mcset es mNewPassword...       {Nuevo P&assword...}
::msgcat::mcset es mPaste                {Pegar}
::msgcat::mcset es mPieslice             {Tartas}
::msgcat::mcset es mPlugins              {Plugins}
::msgcat::mcset es mPreferences          {Preferencias...}
::msgcat::mcset es mPreferences...       {&Preferencias...}
::msgcat::mcset es mPrint...             {Im&primir...}
::msgcat::mcset es mQuit                 {&Abandonar}
::msgcat::mcset es mRaise                {Elevar}
::msgcat::mcset es mRedo                 {Rehacer}
::msgcat::mcset es mRefresh              {Refrescar}
::msgcat::mcset es mRegister...          {Registrar...}
::msgcat::mcset es mRemoveAccount...     {&Eliminar cuenta...}
::msgcat::mcset es mRemoveContact        {Borrar el contacto...}
::msgcat::mcset es mRemoveListing        {Eliminar listado}
::msgcat::mcset es mRestore              {&Restaurar}
::msgcat::mcset es mSave                 {&Guardar...}
::msgcat::mcset es mSaveAs               {G&uardar como...}
::msgcat::mcset es mSaveAsItem           {Guardar como objeto...}
::msgcat::mcset es mSaveCanvas           {Guardar el dibujo}
::msgcat::mcset es mSaveImageAs          {Guardar la &imagen como...}
::msgcat::mcset es mSearch...            {Busca&r...}
::msgcat::mcset es mSelectAll            {Selecionar &todo}
::msgcat::mcset es mSendFile...          {Enviar un mensaje...}
::msgcat::mcset es mServer               {&Servidor}
::msgcat::mcset es mSetupAssistant...    {&Asistente de configuración}
::msgcat::mcset es mShiftConstrain       {Girar}
::msgcat::mcset es mShow                 {Visualizacion}
::msgcat::mcset es mShowControlPanel     {Show Control Panel}
::msgcat::mcset es mSize                 {Tamaño}
::msgcat::mcset es mSlideShow            {Pase de diapositivas}
::msgcat::mcset es mSmaller              {Reducir}
::msgcat::mcset es mSort                 {Ordenar}
::msgcat::mcset es mCheckSpell           {Revisar ortografía}
::msgcat::mcset es mStatus               {Estado}
::msgcat::mcset es mStopTrans            {Parar &Transaciones}
::msgcat::mcset es mStraighten           {Enderezar}
::msgcat::mcset es mStyle                {Estilo de vista}
::msgcat::mcset es mSyncPlayback         {Lectura sincronizada}
::msgcat::mcset es mTabs                 {&Pestañas}
::msgcat::mcset es mTakeSnapShot         {Coger captura}
::msgcat::mcset es mThickness            {Grosor de la línea}
::msgcat::mcset es mTimeCode             {Codificacion horaria}
::msgcat::mcset es mTo45degrees          {Girar 45 grados}
::msgcat::mcset es mTo90degrees          {Girar 90 grados}
::msgcat::mcset es mToolbar              {Barra de herramientas}
::msgcat::mcset es mTransports           {Transportes de otras redes}
::msgcat::mcset es mUndo                 {Deshacer}
::msgcat::mcset es mUnregister           {Desregistrarse}
::msgcat::mcset es mUpdateCheck          {Comprobar actualizaciones}
::msgcat::mcset es mVersion              {Versión}
::msgcat::mcset es mVertical             {Vertical}
::msgcat::mcset es mWeight               {Estilo del texto}
::msgcat::mcset es mWhiteboard           {Pizarra...}


# Short texts only. Use english text as database key.
::msgcat::mcset es {About %s}            {Acerca de %s}
::msgcat::mcset es {About QuickTimeTcl}  {Acerca de QuickTimeTcl}
::msgcat::mcset es {Add Contact}         {Añadir contacto}
::msgcat::mcset es {Add File Type}       {Añadir tipo de archivo}
::msgcat::mcset es {Add/Edit File Type}  {Añadir/Editar tipo de archivo}
::msgcat::mcset es {Add Profile}         {Añadir perfil}
::msgcat::mcset es {Alert sounds}        {Sonidos de alerta}
::msgcat::mcset es {All Supported Files} {Todos los archivos compatibles}
::msgcat::mcset es {Alternative chatroom} {Sala alternativa}
::msgcat::mcset es {Always ask}          {Pregunta siempre}
::msgcat::mcset es {Application Status}  {Estado de la Aplicación}
::msgcat::mcset es {Auto Away}           {Ausencia automática}
::msgcat::mcset es {Auto Join}           {Unirse de forma automática}
::msgcat::mcset es {Auto Reply}          {Autoresponder}
::msgcat::mcset es Auto-accept           {Aceptar automáticamente}
::msgcat::mcset es Auto-reject           {Rechazar automáticamente}
::msgcat::mcset es {Blocking support}    {Soporte de bloqueo}
::msgcat::mcset es {Bookmark this chatroom} {Recordar esta sala}
::msgcat::mcset es {Broken Image}        {Imagen rota}
::msgcat::mcset es {Buffering support}   {Buffering support}
::msgcat::mcset es {Built in server}     {Servidor embebido}
::msgcat::mcset es {Business Card}       {Tarjeta de visita}
::msgcat::mcset es {Cache folder}        {Directorio de caché}
::msgcat::mcset es {Changes since previous release} {Cambios desde la versión anterior}
::msgcat::mcset es {Chat system}         {Sistema de mensajería}
::msgcat::mcset es {Chat window}         {Ventana de chat}
::msgcat::mcset es {Chat With}           {Chatear con}
::msgcat::mcset es {Chatroom presence change} {Cambiar el estado en una sala}
::msgcat::mcset es {Clear Cache}         {Limpiar Cache}
::msgcat::mcset es {Close page}          {Cerrar página}
::msgcat::mcset es {Close Slot}          {Cerrar Slot}
::msgcat::mcset es {Close tab}           {Cerrar pestaña}
::msgcat::mcset es {Configure Chatroom}  {Configurar sala}
::msgcat::mcset es {Contact Actions}     {Acciones con los contactos}
::msgcat::mcset es {Contact Icons}       {Iconos de los contactos}
::msgcat::mcset es {Contact ID}          {Identificador Jabber}
::msgcat::mcset es {Contact Name}        {Nombre del Contacto}
::msgcat::mcset es {Create Chatroom}     {Crear Chatroom}
::msgcat::mcset es {Create new item for each line of text} {Crear un nuevo item por cada línea de texto}
::msgcat::mcset es {Custom Status}       {Estado personalizado}
::msgcat::mcset es {Default Applications} {Aplicaciones por defecto}
::msgcat::mcset es {Default group}       {Grupo por defecto}
::msgcat::mcset es {Default nickname}    {Apodo por defecto}
::msgcat::mcset es {Delete Profile}      {Eliminar perfil}
::msgcat::mcset es {Disable All}         {Desactivar Todos}
::msgcat::mcset es {Discover permanently} {Descubrir permanentemente}
::msgcat::mcset es {Discover Server}     {Descubrir Servidor}
::msgcat::mcset es {Disk cache size}     {Tamaño en disco del cache}
::msgcat::mcset es {Edit Bookmarks}      {Editar Marcadores}
::msgcat::mcset es {Do you want to hang up?} {Quieres colgar?}
::msgcat::mcset es {Edit Business Card}  {Editar Tarjeta de Visita}
::msgcat::mcset es {Edit Contact}        {Editar Contacto}
::msgcat::mcset es {Edit File Type}      {Editar Tipo de Fichero}
::msgcat::mcset es {Edit Item}           {Editar el objeto}
::msgcat::mcset es {Edit Profiles}       {Editar Perfiles}
::msgcat::mcset es {Email addresses}     {Direcciones de email}
::msgcat::mcset es {Email client}        {Cliente de email}
::msgcat::mcset es {Enable nickname coloring} {Activar coloreado de apodos}
::msgcat::mcset es {Enter Chatroom}      {Entrar en Chatroom}
::msgcat::mcset es {Enter/Create Chatroom} {Entrar/Crear Chatroom}
::msgcat::mcset es {Exit room}           {Salir de sala}
::msgcat::mcset es {Error code}          {Código de error}
::msgcat::mcset es {External Midi Player} {Programa para escuchar Midi}
::msgcat::mcset es {Factory Settings}    {Propiedades por defecto}
::msgcat::mcset es {File Cache}          {Caché}
::msgcat::mcset es {File Transfer}       {Transferencia de archivos}
::msgcat::mcset es {File Transfer Error} {Error en la transferencia}
::msgcat::mcset es {File transfer}       {Envío de archivo}
::msgcat::mcset es {File Type}           {Tipo de Fichero}
::msgcat::mcset es {File Types}          {Tipos de Fichero}
::msgcat::mcset es {First name}          {Nombre de pila}
::msgcat::mcset es {Font size}           {Tamaño de fuente}
::msgcat::mcset es {Font weight}         {Grosor de la fuente}
::msgcat::mcset es {Format: mm/dd/yyyy}  {Formato: mm/dd/yyyy}
::msgcat::mcset es {Forwarded message}   {Mensaje Reenviado}
::msgcat::mcset es {Full Name}           {Nombre completo}
::msgcat::mcset es {Hide all on system tray click}   {Ocultar todo al hacer click en la bandeja de sistema}
::msgcat::mcset es {History length}      {Tamaño del historial}
::msgcat::mcset es {Import Iconset}      {Importar Iconos}
::msgcat::mcset es {Incoming Message}    {Mensaje entrante}
::msgcat::mcset es {Insert emoticon}     {Insertar emoticono}
::msgcat::mcset es {Invite Contact}      {Invitar Contacto}
::msgcat::mcset es {Logged in}           {Conectado}
::msgcat::mcset es {Iconset Archive}     {Archivo de Iconos}
::msgcat::mcset es {Jabber ID}           {Identificador Jabber}
::msgcat::mcset es {Last Activity}       {Última actividad}
::msgcat::mcset es {Last name}           {Nombre}
::msgcat::mcset es {Loading available chatrooms} {Cargando las salas (chatroom) disponibles}
::msgcat::mcset es {Local nickname}      {Apodo Local}
::msgcat::mcset es {Local Time}          {Hora local}
::msgcat::mcset es {Logged out}          {Desconectado}
::msgcat::mcset es {Login as invisible}  {Conectarse con el estado "Invisible"}
::msgcat::mcset es {Logout on sleep}     {Desconectar al suspender}
::msgcat::mcset es {Logout With Message} {Desconectarse con el mensaje}
::msgcat::mcset es {MIDI command}        {Comando MIDI}
::msgcat::mcset es {MIDI Player}         {Reproductor MIDI}
::msgcat::mcset es {MIME type}           {Tipo MIME}
::msgcat::mcset es {My Status}           {Mi estado}
::msgcat::mcset es {NAT Address}         {Dirección NAT}
::msgcat::mcset es {New Account}         {Nuevo usuario}
::msgcat::mcset es {New Bookmark}        {Nuevo favorito}
::msgcat::mcset es {New Form}            {Nuevo Formulario}
::msgcat::mcset es {New Message}         {Nuevo mensaje}
::msgcat::mcset es {New password}        {Nueva contraseña}
::msgcat::mcset es {New Password}        {Nueva contraseña}
::msgcat::mcset es {New Profile}         {Nuevo perfil}
::msgcat::mcset es {New Topic}           {Nuevo tema}
::msgcat::mcset es {New Version}         {Nueva versión}
::msgcat::mcset es {Incoming chat}       {Chat entrante}
::msgcat::mcset es {New chat thread}     {Nuevo chat}
::msgcat::mcset es {Incoming message}    {Mensaje entrante}
::msgcat::mcset es {New shortcut}        {Nuevo atajo}
::msgcat::mcset es {No restriction}      {Sin restricciones}
::msgcat::mcset es {No registered history for} {No hay historia guardada de}
::msgcat::mcset es {More recent than}    {Más reciente que}
::msgcat::mcset es {Once per session}    {Una vez por sesión}
::msgcat::mcset es {Open Business Card}  {Abrir Tarjeta de Visita}
::msgcat::mcset es {Open Failed}         {Fallo al abrir}
::msgcat::mcset es {Open File}           {Abrir Archivo}
::msgcat::mcset es {Open Folder}         {Abrir carpeta}
::msgcat::mcset es {Open Helpfile}       {Abrir el archivo de ayuda}
::msgcat::mcset es {Open Image/Movie}    {Abrir imagen/vídeo}
::msgcat::mcset es {Open Stream}         {Abrir streaming}
::msgcat::mcset es {Open with}           {Abrir con}
::msgcat::mcset es {Own Contact ID}           {Identificador Jabber}
::msgcat::mcset es {Own Full Contact ID}           {Identificador Jabber completo}
::msgcat::mcset es {Plain text password} {Contraseña en texto plano}
::msgcat::mcset es {Play sound}          {Reproducir sonido}
::msgcat::mcset es {Postal code}         {Código Postal}
::msgcat::mcset es {Presence Control}    {Panel de Estado}
::msgcat::mcset es {Presence Error}      {Error de estado}
::msgcat::mcset es {Presence Subscription} {Subscripción al estado}
::msgcat::mcset es {Profile Name}        {Nombre del perfil}
::msgcat::mcset es {Receive File}        {Recibir archivo}
::msgcat::mcset es {Recent Avatars}      {Avatares recientes}
::msgcat::mcset es {Reject file}         {Rechazar archivo}
::msgcat::mcset es {Relogin on activity} {Reconectar si hay actividad}
::msgcat::mcset es {Relogin on wakeup}   {Reconectar al salir de suspension}
::msgcat::mcset es {Remove Account}      {Eliminar cuenta}
::msgcat::mcset es {Remove Avatar}       {Eliminar Avatar}
::msgcat::mcset es {Remove Contact}      {Eliminar Contacto}
::msgcat::mcset es {Remove Item}         {Borrar el objeto}
::msgcat::mcset es {Requires a restart of} {Requiere reiniciar %s}
::msgcat::mcset es {Retype password}     {Reescribir contraseña}
::msgcat::mcset es {Right click to open menu} {Haz click con el botón derecho para abrir el menú contextual}
::msgcat::mcset es {Save As}             {Guardar como}
::msgcat::mcset es {Save As GIF}         {Guardar como GIF}
::msgcat::mcset es {Save Canvas Item}    {Guardar Elemento Canvas}
::msgcat::mcset es {Save File}           {Guardar el archivo}
::msgcat::mcset es {Save Message}        {Guardar el mensaje}
::msgcat::mcset es {Save password}       {Guardar contraseña}
::msgcat::mcset es {Save to disk}        {Guardar en disco}
::msgcat::mcset es {Search People}       {Buscar Gente}
::msgcat::mcset es {Search results}      {Buscar resultados}
::msgcat::mcset es {Select Avatar}       {Seleccionar Avatar}
::msgcat::mcset es {Select File}         {Selecionar Archivo}
::msgcat::mcset es {Select Font}         {Elegir fuente}
::msgcat::mcset es {Select Server}       {Seleccionar Servidor}
::msgcat::mcset es {Send File}           {Enviar Archivo}
::msgcat::mcset es {Send Live}           {Enviar en directo}
::msgcat::mcset es {Set Status}          {Elegir estado}
::msgcat::mcset es {Setup Assistant}     {Asistente de configuración}
::msgcat::mcset es {Show Icon}           {Mostrar Icono}
::msgcat::mcset es {Show navigation buttons} {Mostrar los botones de navegación}
::msgcat::mcset es {Show notifier window} {Mostrar ventana de notificación}
::msgcat::mcset es {Show popup}          {Mostrar ventana emergente}
::msgcat::mcset es {Show offline users}  {Mostrar usuarios desconectados}
::msgcat::mcset es {Show Text}           {Mostrar texto}
::msgcat::mcset es {Show Text and Icon}  {Mostrar texto e iconos}
::msgcat::mcset es {Show transports}     {Mostrar transportes}
::msgcat::mcset es {Smooth freehand strokes} {Suavizar lineas dibujadas a mano alzada}
::msgcat::mcset es {Sound set}           {Conjunto de sonidos}
::msgcat::mcset es {Start chat}          {Comenzar chat}
::msgcat::mcset es {Start minimized in system tray} {Comenzar minimizado en la bandeja de sistema}
::msgcat::mcset es {Start minimized in taskbar} {Comenzar minimizado en la barra de tareas}
::msgcat::mcset es {Status Info} {Status Info}
::msgcat::mcset es {Status message}      {Mensaje de estado}
::msgcat::mcset es {Subscription Failed} {Fallo de registro}
::msgcat::mcset es {Subscription Pending} {Registro pendiente}
::msgcat::mcset es {Synchronise cache}   {Sincronizar cache}
::msgcat::mcset es {Take Snapshot}       {Capturar la pantalla}
::msgcat::mcset es {Tel (fax)}           {Fax}
::msgcat::mcset es {Tel (voice)}         {Teléfono}
::msgcat::mcset es Text-to-Speech        {Texto-a-Voz}
::msgcat::mcset es {Thread started}      {Hilo empezado}
::msgcat::mcset es {Update Check}        {Comprobar actualizaciones}
::msgcat::mcset es {Use HTTP transport}  {Usar transporte HTTP}
::msgcat::mcset es {Use SASL authentication} {Usar autenticación SASL}
::msgcat::mcset es {Use SSL for security} {Usar SSL para la seguridad}
::msgcat::mcset es {Use TLS and SASL}    {Usar TLS y SASL}
::msgcat::mcset es {Use TLS on separate port (old)} {Usar TLS en un puerto aparte (antigüo)}
::msgcat::mcset es {Use proxy}           {Usar proxy}
::msgcat::mcset es {Use secure connection} {Usar una conexión segura}
::msgcat::mcset es {Use compression}     {Usar compresión}
::msgcat::mcset es {User Activity}       {Actividad del usuario}
::msgcat::mcset es {Contact is offline}  {Contacto está desconectado}
::msgcat::mcset es {Contact is online}   {Contacto está conectado}
::msgcat::mcset es {Contact presence change} {El estado del Contacto ha cambiado}
::msgcat::mcset es {Username & Password} {Nombre y contraseña}
::msgcat::mcset es {View Business Card}  {Ver Tarjeta de Visita}
::msgcat::mcset es {View business card}  {Ver tarjeta de visita}

::msgcat::mcset es {Windows opacity}     {Opacidad de la ventana}
::msgcat::mcset es {Writing file}        {Guardar archivo}

# Chatrooms.
::msgcat::mcset es {Kick Participant}    {Echar al participante}
::msgcat::mcset es {Ban Participant}     {Prohibir la entrada al participante}
::msgcat::mcset es {Destroy Chatroom}    {Destruir Sala}
::msgcat::mcset es {Edit Lists}          {Editar Listas}
::msgcat::mcset es {Edit the voice list} {Editar la lista de miembros con voz}
::msgcat::mcset es {Edit the ban list}   {Editar la lista de miembros expulsados}
::msgcat::mcset es {Edit the member list} {Editar la lista de miembros}
::msgcat::mcset es {Edit the moderator list} {Editar la lista de moderadores}
::msgcat::mcset es {Edit the admin list} {Editar la lista de administradores}
::msgcat::mcset es {Edit the owner list} {Editar la lista de propietarios}

# Naming of protocol systems and their identifiers.
# Low priority.
::msgcat::mcset es Email                 {Correo electronico}
::msgcat::mcset es {Screen Name}         {Nombre en Pantalla}
::msgcat::mcset es {Gadu-Gadu Number}    {Número Gadu-Gadu}
::msgcat::mcset es {ICQ Number}          {Número ICQ}
::msgcat::mcset es IRC                   {IRC}
::msgcat::mcset es {MSN Address}         {Dirección MSN}
::msgcat::mcset es {Email Address}       {Dirección de correo electrónico}
::msgcat::mcset es {QQ Number}           {Número QQ}
::msgcat::mcset es {Tlen Address}        {Dirección Tlen}
::msgcat::mcset es {Jabber ID}           {Identificador Jabber}
::msgcat::mcset es {Yahoo ID}            {Yahoo ID}

# Time intervals.
::msgcat::mcset es {Ten seconds}         {Diez segundos}
::msgcat::mcset es {One minute}          {Un minuto}
::msgcat::mcset es {Ten minutes}         {Diez minutos}
::msgcat::mcset es {One hour}            {Una hora}

# Language names.
::msgcat::mcset es Czech                 {Checo}
::msgcat::mcset es Danish                {Danés}
::msgcat::mcset es Dutch                 {Holandés}
::msgcat::mcset es English               {Inglés}
::msgcat::mcset es French                {Francés}
::msgcat::mcset es German                {Alemán}
::msgcat::mcset es Italian               {Italiano}
::msgcat::mcset es Korean                {Coreano}
::msgcat::mcset es Polish                {Polaco}
::msgcat::mcset es Russian               {Ruso}
::msgcat::mcset es Spanish               {Español}
::msgcat::mcset es Swedish               {Sueco}

# Same languge names but with their native names.
# See the other catalogs to get these.
::msgcat::mcset es nativeCzech           {Čeština}
::msgcat::mcset es nativeDanish          {Dansk}
::msgcat::mcset es nativeDutch           {Nederlands}
::msgcat::mcset es nativeEnglish         {English}
::msgcat::mcset es nativeFrench          {Français}
::msgcat::mcset es nativeGerman          {Deutsch}
::msgcat::mcset es nativeItalian         {Italiano}
::msgcat::mcset es nativeKorean          {한국어}
::msgcat::mcset es nativePolish          {Polski}
::msgcat::mcset es nativeRussian         {русский}
::msgcat::mcset es nativeSpanish         {Castellano}
::msgcat::mcset es nativeSwedish         {Svenska}


# Splash screen:
::msgcat::mcset es splashsource          {Cargando el código fuente Tcl...}
::msgcat::mcset es splashload            {Cargando los paquetes Tcl...}
::msgcat::mcset es splashsourcejabb      {Cargando los recursos de Jabber...}
::msgcat::mcset es splashhost            {Buscando un dominio...}
::msgcat::mcset es splashinit            {Iniciando...}
::msgcat::mcset es splashprefs           {Cargando y aplicando las preferencias...}
::msgcat::mcset es splashlook            {Buscando}

# Subscriptions:
::msgcat::mcset es subscriptionBoth      {El contacto y usted pueden ver mutuamente su estado.}
::msgcat::mcset es subscriptionFrom      {No puede ver el estado de su contacto, pero él puede ver el suyo.}
::msgcat::mcset es subscriptionNone      {Ni su contacto ni usted pueden ver el estado del otro.}
::msgcat::mcset es subscriptionTo        {Puede ver el estado de su contacto, pero él no puede ver el suyo.}


# Messages for tk_messageBox:
::msgcat::mcset es messaskreceive        {A punto de recibir %s, acepta la recepción?}
::msgcat::mcset es messaupdatelatest     {Usted ya tiene la última versión(%s)}
::msgcat::mcset es messcanerasewarn2     {¡Abrir un fichero de pizarra borra la pizarra actual!}
::msgcat::mcset es messdoquit?           {¿Está seguro de que quiere salir?}
::msgcat::mcset es messerrpreffile2      {No se puede abrir el fichero %s.}
::msgcat::mcset es messfactorydefaults2  {¿Realmente desea reiniciar los valores a la configuración por defecto?}
::msgcat::mcset es messfailedhttp2       {No se pudo iniciar el servidor HTTP interno: %s}
::msgcat::mcset es messfailmimeimp2      {No se pudo encontrar un filtro de importación para el tipo MIME %s}
::msgcat::mcset es messfailopread2       {No se pudo leer %s: %s}
::msgcat::mcset es messfailopwrite2      {No se pudo escribir en %s: %s}
::msgcat::mcset es messfailserver2       {No se pudo iniciar el socket del servidor. Quizás no está conectado.}
::msgcat::mcset es messfieldsmissing     {Uno o más campos faltan, comenzar o cancelar}
::msgcat::mcset es messfillserveruser    {Debe al menos introducir el nombre de usuario y el servidor}
::msgcat::mcset es messnoplugs           {No se han detectado plugins o aplicaciones auxiliares en el sistema}
::msgcat::mcset es messpasswddifferent2  {Los passwords no coinciden. Por favor, inténtelo de nuevo.}
::msgcat::mcset es messprefschanged      {Las preferencias han cambiado, ¿desea cancelar de todas maneras?}
::msgcat::mcset es messprefsrestart2     {Al menos una opción requiere reiniciar %s.}
::msgcat::mcset es messprintnoextension2 {No se pudo encontrar la extensión Tcl necesaria.}
::msgcat::mcset es messrmstandardfonts   {Las fuentes standard Times, Helvetica y Courier no pueden ser eliminadas}
::msgcat::mcset es messsuassclose        {¿Está seguro de querer cerrar el asistente de configuración? Puede volverlo a ejecutar posteriormente desde el menú}
::msgcat::mcset es messsuassfillin       {Verifique que ha rellenado todos los campos antes de continuar}
::msgcat::mcset es messtimeout           {El tiempo para la conexión a caducado}
::msgcat::mcset es messunsavedmsgQ2      {El contenido de la pizarra ha cambiado.}
::msgcat::mcset es messunsaveddtl2       {¿Desea guardar los cambios?}

# Messages for tk_messageBox:
::msgcat::mcset es jamessaddforeign2     {Para añadir un contacto de un sistema de mensajería que no este federado necesita una cuenta en ese sistema, y registrarla en la correspondiente pasarela (%s) ¿Desea hacerlo ahora?}
::msgcat::mcset es jamessaddrmiss        {Debe rellenar al menos una dirección correcta.}
::msgcat::mcset es jamessallowsub2       {%s le autoriza a ver su estado.}
::msgcat::mcset es jamessalreadyinrost2  {%s ya está en su lista. ¿Desea continuar de todas formas?}
::msgcat::mcset es jamessaskregister     {¿Desea registrar una nueva cuenta?}
::msgcat::mcset es jamessautoaccepted2   {%s puede ver su estado.}
::msgcat::mcset es jamessautoreject2     {%s no puede ver su estado.}
::msgcat::mcset es jamessautosubs2       {Puede ver el estado de %s.}
::msgcat::mcset es jamessavaerrsize      {El avatar debe ser un cuadrado de tamaño %s.}
::msgcat::mcset es jamessbadjid2         {%s es inválido. ¿Desea continuar de todas formas?}
::msgcat::mcset es jamesschatclose2      {¿Desea cerrar esta ventana de chat y perder la conversación?}
::msgcat::mcset es jamesschatinvite      {¿Desea invitar a este contacto a una nueva chatroom?}
::msgcat::mcset es jamesschatoffline2    {Este contacto ya no está conectado, el mensaje no se envió.}

::msgcat::mcset es jamessconffailed2     {No se pudo entrar/conectar a la sala %s.}
::msgcat::mcset es jamessconnbroken      {La conexión se ha interrumpido inesperadamente}
::msgcat::mcset es jamessemoticonexists  {El conjunto de iconos %s ya existe.}
::msgcat::mcset es jamessemoticonfail2   {No se pudo cargar el conjunto de iconos %s.}
::msgcat::mcset es jamessenterroomretry2 {No se pudo entrar en la sala %s: %s ¿Desea reintentar?}
::msgcat::mcset es jamesserrautouphttp2  {No se pudo conectar al servidor %s para descargar los detalles de la actualización: %s}
::msgcat::mcset es jamesserrconfgetcre2  {No se pudo descargar el formulario de configuración de la sala.}
::msgcat::mcset es jamesserrinboxopen2   {No se pudo abrir el fichero entrante %s cuando se intentaba guardarlo.}
::msgcat::mcset es jamesserrinboxread2   {No se pudo leer el fichero entrante %s: %s}
::msgcat::mcset es jamesserrlastactive2  {No se pudo consultar la última actividad de %s.}
::msgcat::mcset es jamesserrnotimeinfo2  {No se pudo consultar la información horaria de %s.}
::msgcat::mcset es jamesserrregget2      {No se pudo obtener la información de registro.}
::msgcat::mcset es jamesserrregset2      {No se pudo registrar en el servicio %s.}
::msgcat::mcset es jamesserrsearch2      {No se pudo obtener el formulario de busqueda.}
::msgcat::mcset es jamesserrsend2        {No se pudo enviar el mensaje a %s.}
::msgcat::mcset es jamesserrtime2        {No se pudo consultar la hora de %s.}
::msgcat::mcset es jamesserrunreg2       {No se pudo desregistrar de %s.}
::msgcat::mcset es jamesserrvers2        {No se pudo consultar la versión de %s.}
::msgcat::mcset es jamessfailedsubsc2    {No se pudo subscribir al estado de %s. El contacto no le permite ver su estado.}
::msgcat::mcset es jamessfailsetnick2    {No se pudo cambiar el nombre o grupo de %s.}
	::msgcat::mcset es jamessfatalerr        {Se recibió un error fatal: %s La conexión se ha cerrado.}
::msgcat::mcset es jamessfiletrpterr2    {No se pudo descargar el fichero %s de %s.}
::msgcat::mcset es jamessfilenotexist    {El archivo seleccionado no existe. Seleccione uno nuevo.}
::msgcat::mcset es jamessfilemd5         {El hash MD5 no coincide. El archivo puee estar corrupto.}
::msgcat::mcset es jamessgchatfields2    {Por favor, rellene todos los campos antes de entrar en la sala.}
::msgcat::mcset es jamessgcinvite2       {%s le ha invitado a %s. ¿Desea entrar a esta sala?}
::msgcat::mcset es jamessgcnoroomname2   {Debe indicar el nombre de la sala.}
::msgcat::mcset es jamessgcnoroomnick    {Debe de introducir un nombre de usuario.}
::msgcat::mcset es jamessgeneditwarnclose2 {Ha modificado uno o más valores. ¿Desea guardar estos cambios antes de cerrar?}
::msgcat::mcset es jamessillegalchar     {El/los carácter/es no válido/s en %s son : "%s" !}
::msgcat::mcset es jamessillformresend2  {Identificador de contacto inválido: %s. Por favor, corríjalo y reenvíe.}
::msgcat::mcset es jamessimagecreateerr  {No se pudo crear una imagen de %s.}
::msgcat::mcset es jamessinvalidjid2     {Identificador de contacto inválido. Debe introducir un identificador válido en la parte de abajo de la ventana (por ejemplo username@jabber.org).}
::msgcat::mcset es jamessjidinvalid2     {Identificador de contacto inválido.}
::msgcat::mcset es jamesslocaltime2      {La hora local de %s es: %s}
::msgcat::mcset es jamesslogin409b       {No se pudo conectar debido a que este nombre de usuario lo está usando otra persona (%s).}
::msgcat::mcset es jamessloginnewprof    {El Identificador Jabber es diferente del de su perfil. ¿Desea guardar un nuevo perfil?}
::msgcat::mcset es jamesslogindiff       {Sus datos de conexión son diferentes de los almacenados en su perfil. ¿Desea guardarlos en su perfil?}
::msgcat::mcset es jamessmsgwarnquit     {Hay mensajes sin guardar. ¿Está seguro de querer cerrar?}
::msgcat::mcset es jamessnamemissing     {%s falta o es demasiado corto!}
::msgcat::mcset es jamessnofiletrpt2     {%s no soporta transferencia de ficheros.}
::msgcat::mcset es jamessnofile2         {Debe seleccionar el fichero a enviar.}
::msgcat::mcset es jamessnogroupchat2    {No se pudo encontrar ningún servicio de salas.}
::msgcat::mcset es jamessnorooms2        {No se pudieron encontrar salas en %s.}
::msgcat::mcset es jamessnosocket3       {No se pudo conectar a %s. Existen problemas un el servidor o con la conexión, o escribió incorrectamente el nombre del servidor.}
::msgcat::mcset es jamessnotconnected2   {No puede enviar cuando no se encuentra conectado.}
::msgcat::mcset es jamessokreg2          {El registro en el servicio %s se completo con éxito.}
::msgcat::mcset es jamessokunreg2        {No se ha desregistrado de %s.}
::msgcat::mcset es jamessoobask2         {%s desea enviarle este archivo: %s ¿Desea recibirlo?}
::msgcat::mcset es jamessoobbad2         {Se ha recibido una URL inválida de %s. URL: %s}
::msgcat::mcset es jamessooberr404b      {No se pudo enviar el fichero %s a %s.}
::msgcat::mcset es jamessooberr406b      {%s no aceptó el fichero %s.}
::msgcat::mcset es jamessoobfailopen2    {No se pudo abrir el fichero %s}
::msgcat::mcset es jamessoobnourl2       {%s no envió la dirección de descarga del archivo.}
::msgcat::mcset es jamessoobok2          {Transferencia de %s a %s realizada.}
::msgcat::mcset es jamessoobtimeout2     {No se pudo descargar el archivo vía HTTP: tiempo agotado.}
::msgcat::mcset es jamessoonnohttp2      {El URL de %s no usa el protocolo HTTP , sino el %s que no está soportado.}
::msgcat::mcset es jamessowntrpt2        {Esta es su propia cuenta en %s que actúa como un servicio que transporta los mensajes a ese sistema de menajería. Debe estar en su lista.. Tienes subscripción de %s: %s.}
::msgcat::mcset es jamesspasswderr2      {No se pudo cambiar la contraseña.}
::msgcat::mcset es jamesspasswdok        {La nueva contraseña ha sido registrada.}
::msgcat::mcset es jamessprofaskrem2     {El perfil seleccionado será borrado. ¿Desea también eliminar la cuenta de este perfil? Esta acción no se puede deshacer. Pulse cancelar para no eliminar ni la cuenta ni el perfil.}
::msgcat::mcset es jamessproxy-failure2  {El servidor proxy devolvió un error.}
::msgcat::mcset es jamessregerr2         {El registro falló.}
::msgcat::mcset es jamessregerrinuse2    {El registro falló porque este nombre de usuario esta siendo usado por otra persona.}
::msgcat::mcset es jamessregisterok2     {El registro en %s fue completado con éxito. Ahora debe conectar uando el mismo nombre de usuario y contraseña.}
::msgcat::mcset es jamessregloginok      {Usted está ahora identificado y automáticamente conectado como "%s"}
::msgcat::mcset es jamessregnoserver2    {Por favor, primero introduzca o seleccione un servidor.}
::msgcat::mcset es jamessremoveaccount2  {¿Realmente desea eliminar su cuenta? Esta acción no se puede deshacer.}
::msgcat::mcset es jamesssavemsg         {¿Desea guardar el mensaje?}
::msgcat::mcset es jamesssearcherr       {No se pudo buscar.}
::msgcat::mcset es jamesssearchinval2    {Hay un campo inválido. Por favor, corríjalo.}
::msgcat::mcset es jamessskipsendq2      {El identificador del contacto %s es invalido. ¿Desea omitirlo y enviar al resto?}
::msgcat::mcset es jamessstatuscust2     {Seleccione su estado y opcionalmente introduzca un mensaje.}
::msgcat::mcset es jamessstatuscustdtl2  {Las combinaciones más frecuentes están accesibles fácilmente como entradas en el menú.}
::msgcat::mcset es jamesssubscautoacc    {La petición de subscripción será aceptada en: %s segundos.}
::msgcat::mcset es jamesssubscautorej    {La petición de subscripción será rechazada en: %s segundos.}
::msgcat::mcset es jamesssubscedfancy    {%s contactos adicionales pueden ver su estado.}
::msgcat::mcset es jamesstimeconn2       {Tiempo desde que %s estuvo conectado por última vez}
::msgcat::mcset es jamesstimeoutserver2  {El servidor %s no responde: tiempo agotado.}
::msgcat::mcset es jamesstimeservstart2  {Tiempo desde que el servidor %s se inició}
::msgcat::mcset es jamesstimeused2       {Tiempo desde que el cliente %s estuvo activo por última vez}
::msgcat::mcset es jamesstrptsubsc       {el usuario de cuenta registrado con el servicio %s sera añadido a sus contactos para funcionar como un servidor de transporte con el servicio.}
::msgcat::mcset es jamessunsub2          {Debido a que %s ya no le permite ver su estado, será borrado.}
::msgcat::mcset es jamessunsubask2       {%s ya no le permite ver su estado. ¿Desea borrar %s?}
::msgcat::mcset es jamessunsubpres2      {%s ya no le permite ver su estado.}
::msgcat::mcset es jamessunsubscribed2   {Ya no puede ver el estado de %s.}
::msgcat::mcset es jamessuptime2         {El uptime/última actividad es}
::msgcat::mcset es jamesswarnexitroom2   {¿Desea salir de la sala %s?}
::msgcat::mcset es jamesswarnremove2     {¿Realmente desea borrar a este contacto? Esta acción no se puede deshacer.}
::msgcat::mcset es jamesswarnsendcanoff2 {%s no esta conectado. Si su mensaje contieme imágenes u otro cotenido multimedia, su contacto no lo vera a menos que usted este conectado cuando el/ella lea su mensaje. ¿Desea enviarlo de todos modos?}
::msgcat::mcset es jamesswbchatlost2     {¿Desea cerrar esta pizarra y perder la sesión completa?}


# This maps Defined Error Conditions to clear text messages.
# RFC 3929 (XMPP Core): 6.4 SASL Errors
# 
# These are much too formal to be used for user display and we therfore instead use the short forms below.
# Do not translate these, just for reference.
::msgcat::mcset es xmpp-stanzas-aborted  {El servidor ha recibido un comando para cancelar el proceso de inicializacion.}
::msgcat::mcset es xmpp-stanzas-incorrect-encoding {La informacion que envia no se encuentra codificada correctamente.}
::msgcat::mcset es xmpp-stanzas-invalid-authzid {El usuario es incorrecto, quizas porque no lo escribio bien o porque no esta registrado en el servidor.}
::msgcat::mcset es xmpp-stanzas-invalid-mechanism {No ha especificado un mecanismo o el mecanismo de autenticacion solicitado no es soportado por el servidor.}
::msgcat::mcset es xmpp-stanzas-mechanism-too-weak {El mecanismo solicitado para autenticar es mas inseguro que el requerido por el servidor.}
::msgcat::mcset es xmpp-stanzas-not-authorized {La autenticacion fallo debido a que no se han introducido unas credenciales validas (pej. un usuario desconocido, o una contrasena incorrecta, ...).}
::msgcat::mcset es xmpp-stanzas-temporary-auth-failure {La autenticacion fallo debido a un error temporal recibido.}

# Short messages in place of the above ones.
::msgcat::mcset es xmpp-stanzas-short-aborted {El proceso de autenticacion ha sido cancelado.}
::msgcat::mcset es xmpp-stanzas-short-incorrect-encoding {Error de protocolo: Codificacion incorrecta durante la autenticacion.}
::msgcat::mcset es xmpp-stanzas-short-invalid-authzid {Error de protocolo: Usuario incorrecto.}
::msgcat::mcset es xmpp-stanzas-short-invalid-mechanism {Error de protocolo: Mecanismo incorrecto.}
::msgcat::mcset es xmpp-stanzas-short-mechanism-too-weak {Error de protocolo: Mecanismo inseguro.}
::msgcat::mcset es xmpp-stanzas-short-not-authorized {Fallo la autenticacion porque el usuario o la contrasena es incorrecta.}
::msgcat::mcset es xmpp-stanzas-short-temporary-auth-failure {Error de protocolo: fallo durante la autenticacion.}


# Related error conditions detected by the client.
::msgcat::mcset es starttls-nofeature    {El servidor "%s" no soporta TLS.}
::msgcat::mcset es starttls-failure      {Error durante la conexion TLS con el servidor "%s".}
::msgcat::mcset es sasl-no-mechanisms    {El servidor no soporta la autenticacion via SASL.}
::msgcat::mcset es sasl-protocol-error   {La autenticación ha fallado debido a un error en el protocolo.}

# A collective description of all stream errors.
::msgcat::mcset es xmpp-streams-error    {Se ha recibido un error del servidor con el codigo: %s}


# Account xform balloon help.
# From: JEP-0077: In-Band Registration (http://www.xmpp.org/extensions/xep-0077.html#registrar-formtypes)
# Note to translators: these are tooltips and has lower priority
::msgcat::mcset es registration-address  {Direccion}
::msgcat::mcset es registration-city     {Ciudad}
::msgcat::mcset es registration-date     {Alguna fecha (ej., nacimiento, boda, alta en el servicio)}
::msgcat::mcset es registration-email    {Correo electronico  del usuario}
::msgcat::mcset es registration-first    {Primer apellido  del usuario}
::msgcat::mcset es registration-is-registered {Ha sido registrado en este servicio. Estas son las opciones actuales de su cuenta.}
::msgcat::mcset es registration-last     {Segundo apellido, del usuario}
::msgcat::mcset es registration-name     {Nombre del usuario}
::msgcat::mcset es registration-nick     {Alias del usuario}
::msgcat::mcset es registration-password {Contrasena del usuario}
::msgcat::mcset es registration-phone    {Telefono}
::msgcat::mcset es registration-state    {Provincia}
::msgcat::mcset es registration-url      {Pagina Web}
::msgcat::mcset es registration-username {Nombre de la cuenta asociada con el usuario}
::msgcat::mcset es registration-zip      {Codigo Postal}

# Map version info tags to display names.
::msgcat::mcset es version-name          {Nombre}
::msgcat::mcset es version-version       {Version}
::msgcat::mcset es version-os            {Sistema Operativo}


::msgcat::mcset es register-trpt-unreg2  {Va a desregistrarse de un transporte con contactos que dependen de él. ¿Desea borrarlos (Si), mantenerlos (No), o cancelar todo (Cancelar).}

::msgcat::mcset es reply-prefix          {En %s, %s %s escribió:}

::msgcat::mcset es printunixcmd          {Comando para imprimir, puede cambiarlo si es necesario}
::msgcat::mcset es enterpassword         {Introducir la contraseña para la cuenta "%s"}
::msgcat::mcset es wblockitem            {Proteger este elemento para no ser editado}



::msgcat::mcset es httptrptok2           {Descarga del archivo %s finalizada.}
::msgcat::mcset es httptrpterror2        {No puedo descargar el archivo %s.\nFile transport error: %s}
::msgcat::mcset es httptrpteof           {El servidor ha terminado la conexión sin respuesta.}
::msgcat::mcset es httptrptnon200a       {No puedo descargar el archivo %s.}
::msgcat::mcset es httptrptreset         {La transferencia del archivo %s ha sido reiniciada}

::msgcat::mcset es uastatpointmac        {Puntero (click : seleccionar, doble click: inspeccionar, pulse: popup)}
::msgcat::mcset es uastatpoint           {Puntero (click : seleccionar, doble click: inspeccionar, click derecho: popup)}
::msgcat::mcset es uastatmove            {Mover}
::msgcat::mcset es uastatline            {Linea}
::msgcat::mcset es uastatarrow           {Flecha}
::msgcat::mcset es uastatrect            {Rectángulo}
::msgcat::mcset es uastatoval            {Elipse}
::msgcat::mcset es uastattext            {Texto}
::msgcat::mcset es uastatdel             {Haga click para borrar}
::msgcat::mcset es uastatpen             {Pintura}
::msgcat::mcset es uastatbrush           {Brocha}
::msgcat::mcset es uastatpaint           {Relleno (+ <shift>: transparente)}
::msgcat::mcset es uastatpoly            {Polígono (<espacio>: terminar)}
::msgcat::mcset es uastatarc             {Arco (click: definir centro, <espace>: terminar)}
::msgcat::mcset es uastatarc2            {Arco (hacer click-mover)}
::msgcat::mcset es uastatrot             {Rotar (debe tener seleccionados los objetos)}


# Preferences:
::msgcat::mcset es prefaaonhidden        {Apply auto-away on hidden chat tabs}
::msgcat::mcset es prefaabusychats       {No molestar cuando (numero de conversaciones)}
::msgcat::mcset es prefchactret2         {Usar la tecla <Return> (Enter) por defecto para enviar mensajes}
::msgcat::mcset es prefchnormal          {Tratar los mensajes normales como mensajes de chat}
::msgcat::mcset es prefcu2clk            {Mensaje del doble-clic en el diálogo de los mensajes : }
::msgcat::mcset es prefcuautologin2      {Conectarse al comenzar %s}
::msgcat::mcset es prefcuopen            {Abrir el mensaje en una nueva ventana}
::msgcat::mcset es prefcuremdlgs2        {Recordar las ventanas abiertas entre sesiones}
::msgcat::mcset es prefcureply           {Responder al remitente}
::msgcat::mcset es prefcusave            {Guardar el buzón entre sesiones}
::msgcat::mcset es prefcushow            {Mostrar los mensajes en una nueva ventana}
::msgcat::mcset es prefdirsame           {Guardar las preferencias en el mismo directorio donde se encuentra el programa}
::msgcat::mcset es prefdrivesame2        {Guardar las preferencias en el mismo disco donde se encuentra el programa}
::msgcat::mcset es prefdriwdef2          {Ha escogido guardar sus preferencias en el directorio predeterminado. Si borra o mueve sus preferencias de %s, las preferencias del directorio predeterminado seran usadas la próxima vez que inicie %s. ¿Desea eliminar las preferencias antigüas?}
::msgcat::mcset es prefdriwsame          {Eligió almacenar sus preferencias en el mismo dispositivo donde reside la aplicacion. Si este es un dispositivo movil (pej. USB) sus preferencias podrian ser visibles. ¿Desea continuar?}
::msgcat::mcset es preffilecache2        {Cantidad de caché destinada a guardar archivos de pizarra recientes.}
::msgcat::mcset es preffontmsg           {Atención: cuando añada otras fuentes además de las fuentes estándar (Times, Helvetica o Courier), Aseguresé que ha instalado también estas últimas.}
::msgcat::mcset es preficonsel2          {El conjunto de iconos seleccionado se convertirá en el predeterminado.}
::msgcat::mcset es prefmidimsg           {Comando para reproducir sonidos MIDI. Solo es relevante si usa un conjunto de sonidos con archivos MIDI.}
::msgcat::mcset es prefminaw2            {Ausente después de}
::msgcat::mcset es prefminea2            {No disponible después de}
::msgcat::mcset es prefminlogout         {Desconectar despues de}
::msgcat::mcset es prefnatip2            {Usar la dirección externa}
::msgcat::mcset es prefplugctrl2         {Seleccione los plugions que desea cargar.}
::msgcat::mcset es prefpriv3             {Solo editar elemetos locales en la pizarra}
	::msgcat::mcset es prefpriv4             {Si se activa no podrá editar elementos creados por otros}
::msgcat::mcset es prefprof2             {Editar, anadir o borrar perfiles. El perfil seleccionado se convertirá en el predeterminado.}
::msgcat::mcset es prefprofname2         {Introduzca el nombre para el nuevo perfil.}
::msgcat::mcset es prefproxyexc          {Excluir direcciones (* como comodin)}
::msgcat::mcset es prefproxymsg2         {El uso de la configuración del proxy HTTP esta determinado por la configuración de cada perfil. Las transferencias de ficheros no funcionarán si usa un proxy HTTP.}
::msgcat::mcset es prefrochat2           {Abrir chat al hacer doble click en vez de un mensaje}
::msgcat::mcset es prefroclr2            {Limpiar lista de contactos al desconectar}
::msgcat::mcset es prefrorm2             {Borrar contactos sin subscripción de estado}
::msgcat::mcset es prefroshowsubno       {Ver contactos sin subscripción de estado}
::msgcat::mcset es prefsounpick2         {Activar o desactivar sonidos}
::msgcat::mcset es prefsounsynch2        {Texto-a-voz en chat}
::msgcat::mcset es prefsounsynno2        {Texto-a-voz en mensajes}
::msgcat::mcset es prefsounsynwb2        {Texto-a-voz en el texto de la pizarra}
::msgcat::mcset es prefsounvoin2         {Seleccione voz para los mensajes entrantes}
::msgcat::mcset es prefsounvoou2         {Seleccione voz para los menajes salientes}
::msgcat::mcset es prefssresize2         {Redimensionar la ventapa al tamaño de las diapositivas}
::msgcat::mcset es prefstabui2           {Usar interfaz con pestañas}
::msgcat::mcset es prefsuaasecs          {El diálogo se cierra despues de (Segundos)}
::msgcat::mcset es prefsuaatimer         {Si auto-acepta/rechaza, mostrar un diálogo con temporizador}
::msgcat::mcset es prefsuauto2           {Poner a los contactos que me añaden a su lista en}
::msgcat::mcset es prefsuif2             {Si alguien quiere ver mi estado y}
::msgcat::mcset es prefsuis2             {está en mi lista}
::msgcat::mcset es prefsuisnot2          {no está en mi lista}



# obsolete strings in the paragraph?
# EditShortcuts namespace:
namespace eval ::EditShortcuts:: {
::msgcat::mcset es shortip               {Completar la dirección IP o el nombre}
::msgcat::mcset es shortwarn             {Atención : ha modificado los atajos de teclado. ¿Desea guardarlos?}


}


::msgcat::mcset es jaactiveret           {Si esta activado, la 'Tecla Enter' enviará los mensajes; si no lo está, use la combinacion de teclas Ctrl/Cmd-Return}
::msgcat::mcset es jaauthok2             {La autenticación con el servidor %s fue completada con éxito. Descargando contactos...}
::msgcat::mcset es jachathist            {Muestra u oculta el historial del chat}
::msgcat::mcset es jacreateroom2         {Seleccione el servicio, e introduzca la sala y el apodo. Opcionalmente, podrá configurar la sala.}
::msgcat::mcset es jadisaddserv2         {Añada el servidor a descubrir para usar sus salas y el resto de sus servicios.}
::msgcat::mcset es jagchatmsg            {Elija un grupo de chat y un nombre de sala, también puede usar un alias.}
::msgcat::mcset es jagcloginmsg          {Ha entrado en la sala}
::msgcat::mcset es jagclogoutmsg         {Se ha desconectado y ha salido de la sala}
::msgcat::mcset es jagcreqnick           {Por favor, introduzca el apodo que desee esar en la sala %s}
::msgcat::mcset es jagcsyncpres2         {Sincronizar el estado en la sala con el estado global}
::msgcat::mcset es jainmsgshow           {Mostrar los mensajes entrantes en esta ventana}
::msgcat::mcset es jainvitegchat2        {Invitar a un contacto a la sala %s.}
::msgcat::mcset es jalogin               {Escribir la dirección IP o el nombre del servidor Jabber, o elegir en el menú desplegable. Usted debe tener una cuenta en este servidor.}
::msgcat::mcset es jaloginjid3           {Introduzca su cuenta como "user@example.org", o escoja un perfil. Debería tener una cuenta en este servidor.}
::msgcat::mcset es jaloginjidpure        {Introduzca su Identificador Jabber ("ejemplo@example.org"). Debería tener una cuenta en este servidor.}
::msgcat::mcset es jaloginuser           {Introduzca su usuario y password para entrar en %s.}
::msgcat::mcset es jamucentermsg2        {Seleccione el servicio, e introduzca la sala y el apodo. Puede descubrir las salas disponibles en el servicio seleccionado. Algunas salas pueden pedir contraseña.}
::msgcat::mcset es janewpass             {Elegir la contraseña para : }
::msgcat::mcset es jaopenbgimage         {Seleccione una imagen para el fondo. Para borrarla, pulse Limpiar y OK.}
::msgcat::mcset es jaregalready2         {Ya se encuentra registrado en este servicio. Estos son sus datos de registro.}
::msgcat::mcset es jaregisterex3         {Seleccione un servidor de la lista, o introduzca uno. A continiación pulse Siguiente, siga las intrucciones y pulse Registrarse}
::msgcat::mcset es jaregisterexserv2     {Registrarse en el servicio %s. Puede que necesite pulsar Siguiente para obtener las instrucciones de registro.}
::msgcat::mcset es jaregmsg3             {Seleccione un servicio y pulse Siguiente}
::msgcat::mcset es jaregnewwith          {Desea registrar una cuenta nueva en %s.}
::msgcat::mcset es jarostadd3            {Seleccione el sistema de mensajeria y el identificador del contacto que desee añadir.}
::msgcat::mcset es jarostaddopt          {El apodo y el grupo son opcionales y se pueden cambiar después.}
::msgcat::mcset es jarostset2            {Edite el apodo y el grupo de %s. Tambien puede pedir o eliminar la subscripción de estado.}
::msgcat::mcset es jarostsub2            {Pedir subscripción de estado}
::msgcat::mcset es jarostunsub2          {Borrar subscripción de estado}
::msgcat::mcset es jarostupdate          {La lista de contactos está al día}
::msgcat::mcset es jasearch2             {Buscar contactos en el servicio seleccionado. Un nuevo formulario sustituirá al anterior.}
::msgcat::mcset es jasearchwait          {Haga click en "Recibir" cuando esté listo}
::msgcat::mcset es jaseliconset2         {Seleccione el conjunto de iconos para cada grupo. Un grupo no seleccionado usará el conjunto de iconos predeterminado.}
::msgcat::mcset es jasubmulti            {%s contactos quieren ver su estado. Seleccione aquellos que desee que vean su estado.}
::msgcat::mcset es jasubopts2            {Introducir el apodo y grupo es opcional, y será solo para su uso personal.}
::msgcat::mcset es jasubwant2            {¿Debe %s poder ver su estado?}
::msgcat::mcset es jasuppimagefmts       {Los formatos de imágen soportados son}
::msgcat::mcset es jatlsnegot2           {Negociando capa de seguridad TLS}
::msgcat::mcset es jauserinnote2         {Añada sus notas personales sobre este contacto.}
::msgcat::mcset es javersinfo            {Información de la versión de %s}
::msgcat::mcset es jawaitdisco           {Esperando resultado}
::msgcat::mcset es jawaitresp            {%s contactado, en espera de una respuesta}
::msgcat::mcset es jawaitserver          {Esperando de la respuesta del servidor...}
::msgcat::mcset es jawaitform            {Descargando formulario e configuración}
::msgcat::mcset es jawaitxml             {Conectado a "%s". Iniciando la conversación XML...}
::msgcat::mcset es jaxformreq            {Las etiquetas con (*) son obligatorias}

# Setup assistant:
::msgcat::mcset es suintro1a             {Este asistente le ayudará a realizar la configuración necesaria para conenzar con %s.}
::msgcat::mcset es suintro3a             {En cualquier momento puede presionar Anterior para retroceder. Pulse Siguiente para continuar.}
::msgcat::mcset es sulang2               {Elija su idioma}
::msgcat::mcset es suservmsg2            {Seleccione o introduzca el servidor en el que desea tener la cuenta. Si ya tiene una cuenta, seleccione el servidor de su cuenta.}
::msgcat::mcset es suusermsg2            {Introduzca su nombre de usuario y contraseña. Si el nombre de usuario elegido ya lo está utilizando otro usuario, no podrá registrarlo.}
::msgcat::mcset es suregmsg2             {Haga click en el bonton de abajo para crear la nueva cuenta. Debe estar conectado a internet. Si tiene un firewall, asegurese de que no cause problemas.}
::msgcat::mcset es sufinmsg2             {Esto es todo. ;-)}

# Groupchat:
::msgcat::mcset es mucBan2               {Banear a %s de la sala %s.}
::msgcat::mcset es mucChat2ConfInv       {Convirtiendo Chat en Conferencia}
::msgcat::mcset es mucDestroy2           {¿Desea eliminar la sala %s? Opcionalmente, puede señalar a los usuarios actuales la razón e indicarles una sala alternativa.}
::msgcat::mcset es mucErrEnter2          {No se pudo entrar en la sala %s.}
::msgcat::mcset es mucErrInvite2         {No se pudo invitar a %s a %s.}
::msgcat::mcset es mucInviteText2        {%s le invita a entrar en la sala %s.}
::msgcat::mcset es mucInvitePass         {La contraseña para entrar es "%s".}
::msgcat::mcset es mucInviteQuest        {¿Esta seguro de querer entrar?}
::msgcat::mcset es mucIQError2           {No se pudo interactuar con la sala %s.}
::msgcat::mcset es mucKick               {Expulsar a %s de la sala %s.}

::msgcat::mcset es vcardget2             {Descargando la tarjeta de visita de %s}
::msgcat::mcset es vcarderrget2          {No se pudo descagar la tarjeta de visita.}
::msgcat::mcset es vcardrec2             {Tarjeta de visita descargada.}



::msgcat::mcset es autoupdatedo          {Buscar actualizaciones automáticamente}
::msgcat::mcset es oobmsg2               {Enviar un fichero a %s. La descripción es opcional.}

# Composing events
::msgcat::mcset es chatcompreply         {%s le está respondiendo.}
::msgcat::mcset es chatcompactive        {%s tiene la conversación abierta}
::msgcat::mcset es chatcompcomposing     {%s le está respondiendo}
::msgcat::mcset es chatcomppaused        {%s está pensando lo que escribe}
::msgcat::mcset es chatcompinactive      {%s abandonó temporalmente la conversación}
::msgcat::mcset es chatcompgone          {%s ha cerrado la conversación}


# Get file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset es getcontacting         {Contacto de %s. Esperando una respuesta...}
::msgcat::mcset es geteoferr             {La conexión a %s ha fallado : recibido un EOF.}
::msgcat::mcset es getconnerr            {La conexión a %s ha fallado.}
::msgcat::mcset es getnegotiate          {Cliente contactado : %s ; negociación en curso...}
::msgcat::mcset es getreaderr            {Error de respuesta del servidor %s.}
::msgcat::mcset es getunknownprot        {El servidor %s no responde usando protocolo correcto.}
::msgcat::mcset es getnot200             {El servidor %s ha respondido con el código %s (%s).}
::msgcat::mcset es getstarts             {El cliente %s ha aceptado el archivo "%s". Comienza del transferencia...}
::msgcat::mcset es getended              {La transferencia de %s ha terminado inesperadamente.}
::msgcat::mcset es getfinished           {El archivo "%s" de %s ha sido recibido.}
::msgcat::mcset es getneterr             {Error de transferencia durante la recepción de %s.}

# Put file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset es putcontacting         {Contacto de %s. Esperando una respuesta...}
::msgcat::mcset es puteoferr             {La conexión a %s ha fallado : recepción una EOF.}
::msgcat::mcset es putconnerr            {La conexión a %s ha fallado.}
::msgcat::mcset es putnegotiate          {Cliente contactado : %s ; negociación en curso...}
::msgcat::mcset es putreaderr            {Error de respuesta del servidor %s.}
::msgcat::mcset es putunknownprot        {El servidor %s no responde usando protocolo correcto.}
::msgcat::mcset es putnot200             {El servidor %s ha respondido con el código %s (%s).}
::msgcat::mcset es putstarts             {El cliente %s ha aceptado el archivo "%s". Comienza la transferencia...}
::msgcat::mcset es putended              {La transferencia de %s ha terminado inesperadamente.}
::msgcat::mcset es putfinished           {El archivo "%s" de %s ha sido recibido.}
::msgcat::mcset es putneterr             {Error de transferencia durante la recepción de %s.}

# These are specific for phones (VoIP)
::msgcat::mcset es phoneMakeCall         {Llamar a...}
::msgcat::mcset es phoneMakeForward      {Desviar la llamada actual a...}
::msgcat::mcset es phoneRing             {Ring, ring ...}
::msgcat::mcset es phoneRingFrom         {Le esta llamando %s}
::msgcat::mcset es phoneFailedCalling    {No se pudo llamar a %s}
::msgcat::mcset es phoneDial             {Marcar}
::msgcat::mcset es phoneNumber           {Numero}
::msgcat::mcset es phoneDialerCall       {Llamar a...}
::msgcat::mcset es phoneDialerForward    {Desviar a...}

# Note to translators: these strings are not yet activated
::msgcat::mcset es AddressBook           {Marcado rapido}
::msgcat::mcset es newAddressbookDlg     {Nuevo telefono de marcado rapido}
::msgcat::mcset es newAddressbook        {Nuevo telefono de marcado rapido}
::msgcat::mcset es abName                {Nombre}
::msgcat::mcset es abPhone               {Numero de telefono}
::msgcat::mcset es modifyAddressbookDlg  {Modificar telefono de marcado rapido}
::msgcat::mcset es modifyAddressbook     {Modificar telefono de marcado rapido}
::msgcat::mcset es mNewAB                {Agregar}
::msgcat::mcset es mModifyAB             {Modificar}
::msgcat::mcset es mRemoveAB             {Eliminar}

::msgcat::mcset es outCall               {Llamando a}
::msgcat::mcset es notifyCall            {Llamada entrante}
::msgcat::mcset es inboundCall           {Le esta llamando}
::msgcat::mcset es outboundCall          {Esta llamando a}
::msgcat::mcset es callAnswer            {Aceptar llamada}
::msgcat::mcset es callHungUp            {Terminar llamada}
::msgcat::mcset es callInfo              {Mas informacion}
::msgcat::mcset es callVM                {Desviar a buzon de voz}

# IAX Phone
# Note to translators: these strings are not yet activated
if {0} {
::msgcat::mcset es Codecs                {Codecs}
::msgcat::mcset es Devices               {Dispositivos}
::msgcat::mcset es Filters               {Filtros}
::msgcat::mcset es {IAX Phone}           {Teléfono IAX}
::msgcat::mcset es {IAX Account}         {Cuenta IAX}
    # translation help: http://en.wikipedia.org/wiki/Caller_id
::msgcat::mcset es {Caller ID number}    {Número de identificación del llamante}
::msgcat::mcset es {Caller ID name}      {Nombre de identificacón del llamante}
::msgcat::mcset es Microphone            {Micrófono}
::msgcat::mcset es Speakers              {Altavoces}
    # translation help: http://en.wikipedia.org/wiki/Automatic_gain_control
::msgcat::mcset es {Automatic gain control (AGC)} {Control automático de ganancia (AGC)}
::msgcat::mcset es agcTip                {Autoajustar el volumen}
    # translation help: http://lists.xiph.org/pipermail/speex-dev/2007-May/005565.html
::msgcat::mcset es {Analog automatic gain control (AAGC)} {Control aútomatico de ganancia analógica (AAGC)}
::msgcat::mcset es {Can prevent clipping} {Puede prevenir cortes}
    # translation help: http://en.wikipedia.org/wiki/Noise_reduction
::msgcat::mcset es {Noise reduction}     {Reducción de ruido}
    # translation help: http://en.wikipedia.org/wiki/Comfort_noise
::msgcat::mcset es {Comfort noise}       {Simular ruido de fondo}
::msgcat::mcset es comfortTip            {Añadir un ligero ruido de fondo para rellenar el silencio. Algunas personas encuentran incomodo el silencio absoluto.}
::msgcat::mcset es Codec                 {Codec}
    # I copied the following descriptions from the websites of these projects; do you think we should ask permission for this?
::msgcat::mcset es tooltip-ilbc          {iLBC (internet Low Bitrate Codec) es un codec gratuito adecuado para comunicación de voz sovre IP}
::msgcat::mcset es tooltip-speex         {Speex es un codec libre diseñado para voz}
::msgcat::mcset es tooltip-alaw          {Estándar usado en los sistemas de comunicación digital europeos (ITU-T)}
::msgcat::mcset es tooltip-ulaw          {Estándar usado en los sistemas de comunicación digital de Norteamérica y Japón (ITU-T)}
::msgcat::mcset es tooltip-gsm           {GSM 06.10 Estándar provisional para transcodificación (ETSI)}
}

# Messages for Mood XEP
# bug: this should be M&ood..., but this does not work!
::msgcat::mcset es mMood                 {Estado de animo}
::msgcat::mcset es mAfraid               Preocupado
::msgcat::mcset es mAmazed               Maravillado
::msgcat::mcset es mAngry                Furioso
::msgcat::mcset es mAnnoyed              Enfadado
::msgcat::mcset es mAnxious              Ansioso
::msgcat::mcset es mAroused              Despierto
::msgcat::mcset es mAshamed              Avergonzado
::msgcat::mcset es mBored                Aburrido
::msgcat::mcset es mBrave                Valiente
::msgcat::mcset es mCalm                 Tranquilo
::msgcat::mcset es mCold                 Frío
::msgcat::mcset es mConfused             Confundido
::msgcat::mcset es mContented            Contento
::msgcat::mcset es mCranky               Irritable
::msgcat::mcset es mCurious              Curioso
::msgcat::mcset es mDepressed            Deprimido
::msgcat::mcset es mDisappointed         Decepcionado
::msgcat::mcset es mDisgusted            Disgustado
::msgcat::mcset es mDistracted           Distraído
::msgcat::mcset es mEmbarrassed          Avergonzado
::msgcat::mcset es mExcited              Excitado
::msgcat::mcset es mFlirtatious          Coqueto
::msgcat::mcset es mFrustrated           Frustrado
::msgcat::mcset es mGrumpy               Malhumorado
::msgcat::mcset es mGuilty               Culpable
::msgcat::mcset es mHappy                Feliz
::msgcat::mcset es mHot                  Caliente
::msgcat::mcset es mHumbled              Humilde
::msgcat::mcset es mHumiliated           Humillado
::msgcat::mcset es mHungry               Hambriento
::msgcat::mcset es mHurt                 Herido
::msgcat::mcset es mImpressed            Impresionado
::msgcat::mcset es mIn_awe               {Atónito}
::msgcat::mcset es mIn_love               Enamorado
::msgcat::mcset es mIndignant            Indignado
::msgcat::mcset es mInterested           Interesado
::msgcat::mcset es mIntoxicated          Intoxicado
::msgcat::mcset es mInvincible           Invencible
::msgcat::mcset es mJealous              Celoso
::msgcat::mcset es mLonely               Solitario
::msgcat::mcset es mMean                 Mezquino
::msgcat::mcset es mMoody                Temperamental
::msgcat::mcset es mNervous              Nervioso
::msgcat::mcset es mNeutral              Neutral
::msgcat::mcset es mOffended             Ofendido
::msgcat::mcset es mPlayful              Juguetón
::msgcat::mcset es mProud                Orgulloso
::msgcat::mcset es mRelieved             Aliviado
::msgcat::mcset es mRemorseful           Arrepentido
::msgcat::mcset es mRestless             Cansado
::msgcat::mcset es mSad                  Triste
::msgcat::mcset es mSarcastic            Sarcástico
::msgcat::mcset es mSerious              Serio
::msgcat::mcset es mShocked              Estupefacto
::msgcat::mcset es mShy                  Tímido
::msgcat::mcset es mSick                 Enfermo
::msgcat::mcset es mSleepy               Adormilado
::msgcat::mcset es mStressed             Estresado
::msgcat::mcset es mSurprised            Sorprendido
::msgcat::mcset es mThirsty              Sediento
::msgcat::mcset es mWorried              Preocupado

::msgcat::mcset es moodEvent             {Cambio de estado de animo}
::msgcat::mcset es moodRetracted         {retracted mood}

::msgcat::mcset es heIs                  esta
::msgcat::mcset es because               porque
::msgcat::mcset es afraid                preocupado
::msgcat::mcset es amazed                maravillado
::msgcat::mcset es angry                 furioso
::msgcat::mcset es annoyed               enfadado
::msgcat::mcset es anxious               ansioso
::msgcat::mcset es aroused               despierto
::msgcat::mcset es ashamed               avergonzado
::msgcat::mcset es bored                 aburrido
::msgcat::mcset es brave                 valiente
::msgcat::mcset es calm                  tranquilo
::msgcat::mcset es cold                  frío
::msgcat::mcset es confused              confundido
::msgcat::mcset es contented             contento
::msgcat::mcset es cranky                irritable
::msgcat::mcset es curious               curioso
::msgcat::mcset es depressed             deprimido
::msgcat::mcset es disappointed          decepcionado
::msgcat::mcset es disgusted             disgustado
::msgcat::mcset es distracted            distraído
::msgcat::mcset es embarrassed           avergonzado
::msgcat::mcset es excited               excitado
::msgcat::mcset es flirtatious           coqueto
::msgcat::mcset es frustrated            frustrado
::msgcat::mcset es grumpy                malhumorado
::msgcat::mcset es guilty                culpable
::msgcat::mcset es happy                 feliz
::msgcat::mcset es hot                   caliente
::msgcat::mcset es humbled               humilde
::msgcat::mcset es humiliated            humillado
::msgcat::mcset es hungry                hambriento
::msgcat::mcset es hurt                  herido
::msgcat::mcset es impressed             impresionado
::msgcat::mcset es in_awe                {atónito}
::msgcat::mcset es in_love               enamorado
::msgcat::mcset es indignant             indignado
::msgcat::mcset es interested            interesado
::msgcat::mcset es intoxicated           intoxicado
::msgcat::mcset es invincible            invencible
::msgcat::mcset es jealous               celoso
::msgcat::mcset es lonely                solitario
::msgcat::mcset es mean                  mezquino
::msgcat::mcset es moody                 temperamental
::msgcat::mcset es nervous               nervioso
::msgcat::mcset es neutral               neutral
::msgcat::mcset es offended              ofendido
::msgcat::mcset es playful               juguetón
::msgcat::mcset es proud                 orgulloso
::msgcat::mcset es relieved              aliviado
::msgcat::mcset es remorseful            arrepentido
::msgcat::mcset es restless              vansado
::msgcat::mcset es sad                   triste
::msgcat::mcset es sarcastic             sarcastico
::msgcat::mcset es serious               serio
::msgcat::mcset es shocked               estupefacto
::msgcat::mcset es shy                   tímido
::msgcat::mcset es sick                  enfermo
::msgcat::mcset es sleepy                agotado
::msgcat::mcset es stressed              estresado
::msgcat::mcset es surprised             sorprendido
::msgcat::mcset es thirsty               sediento
::msgcat::mcset es worried               preocupado

::msgcat::mcset es {Custom Mood}         {Estado de ánimo personalizado...}
::msgcat::mcset es mCustomMood...        {&Estado de ánimo personalizado...}
::msgcat::mcset es moodPickMsg           {Seleccione el estado de ánimo que desea mostrar a sus contactos.}
::msgcat::mcset es moodPickDtl           {Solamente los contactos que usen un software compatible podrán ver la información del estado de ánimo.}

# More balloonhelp stuff.
::msgcat::mcset es tooltip-contactid     {Identificador de usuario}
::msgcat::mcset es tooltip-group         {Grupo al que este contacto debería pertenecer}
::msgcat::mcset es tooltip-localnick     {Su apodo para mostrar localmente}
::msgcat::mcset es tooltip-historymessages {Número de mensajes a mostrar}
::msgcat::mcset es tooltip-chatroomservice {Seleccione o introduzca el servicio de salas}
::msgcat::mcset es tooltip-chatroomselect {Seleccione o introduzca el nombre de una sala}
::msgcat::mcset es tooltip-snack         {Soporte para mp3, wav, y algunos formatos de sonido más}
::msgcat::mcset es tooltip-img           {Soporte para formatos de imagen comunes}
::msgcat::mcset es tooltip-tkpng         {Soporte para imágenes PNG}
::msgcat::mcset es tooltip-xanim         {Soporte para varios formatos de animación, video y audio}
::msgcat::mcset es tooltip-QuickTimeTcl  {Soporte para varios formatos de animación, video y audio}

::msgcat::mcset es tooltip-chatsubject   {Introduzca el asunto de la conversación y pulse Return}
::msgcat::mcset es tooltip-chatoffline   {Necesita estar conectado para ver el estado de este contacto}
::msgcat::mcset es tooltip-chatsendtext  {Introduzca su mensaje y pulse Return o Mayúsculas-Return}
::msgcat::mcset es tooltip-aaonhidden    {Si se activa, los usuarios en las pestañas de charla ocultas le verán auto-ausente}
::msgcat::mcset es tooltip-aabusychats   {Cuando tiene <número> o más charlas activas, su estado cambiará automaticamente a No molestar.}
::msgcat::mcset es tooltip-togglesysmsg  {Mostrar u ocultar los cambios de estado en la charla}


# Me knows :-)
::msgcat::mcset es matsShouldReplaceThis {Aún no implementado.}


# Messages for User Activity XEP
::msgcat::mcset es Activity              {Actividad}
::msgcat::mcset es mActivity...          {Acti&vidad...}
::msgcat::mcset es mCustomActivity...    {Actividad personalizada...}

::msgcat::mcset es Traveling             {Viajando}
::msgcat::mcset es Commuting             {Yendo a trabajar}
::msgcat::mcset es Cycling               {En bici}
::msgcat::mcset es Driving               {Conduciendo}
::msgcat::mcset es {In a car}            {En un coche}
::msgcat::mcset es {On a bus}            {En un autobús}
::msgcat::mcset es {On a plane}          {En un avión}
::msgcat::mcset es {On a train}          {En un tren}
::msgcat::mcset es {On a trip}           {En una excursión}
::msgcat::mcset es Walking               {Caminando}

::msgcat::mcset es Eating                {Comiendo}
::msgcat::mcset es {Having a snack}      {Tomando un aperitivo}
::msgcat::mcset es {Having breakfast}    {Desayunando}
::msgcat::mcset es {Having dinner}       {Cenando}
::msgcat::mcset es {Having lunch}        {Almorzando}

::msgcat::mcset es {Doing chores}        {Haciendo labores domésticas}
::msgcat::mcset es {Buying groceries}    {Comprando comida}
::msgcat::mcset es Cleaning              {Limpiando}
::msgcat::mcset es Cooking               {Cocinando}
::msgcat::mcset es {Doing maintenance}   {Haciendo labores de mantenimiento}
::msgcat::mcset es {Doing the dishes}    {Fregando los platos}
::msgcat::mcset es {Doing the laundry}   {Haciendo la colada}
::msgcat::mcset es Gardening             {Cuidando el jardín}
::msgcat::mcset es {Running an errand}   {Haciendo un recado}
::msgcat::mcset es {Walking the dog}     {Paseando al perro}

::msgcat::mcset es Working               {Trabajando}
::msgcat::mcset es Coding                {Programando}
::msgcat::mcset es {In a meeting}        {En una reunión}
::msgcat::mcset es Studying              {Estudiando}
::msgcat::mcset es Writing               {Escribiendo}

::msgcat::mcset es Exercising            {Haciendo ejercicio}
# Duplicate:
::msgcat::mcset es en                    {Andando en bici}
::msgcat::mcset es Hiking                {Haciendo senderismo}
::msgcat::mcset es Jogging               {Haciendo Footing}
::msgcat::mcset es {Playing sports}      {Haciendo deporte}
::msgcat::mcset es Running               {Corriendo}
::msgcat::mcset es Skiing                {Esquiando}
::msgcat::mcset es Swimming              {Nadando}
::msgcat::mcset es {Working out}         {Working out}

::msgcat::mcset es Talking               {Hablando}
::msgcat::mcset es {In real life}        {En la vida real}
::msgcat::mcset es {On the phone}        {Por teléfono}
::msgcat::mcset es {On video phone}      {Por videoconferencia}

::msgcat::mcset es Relaxing              {Relajándome}
::msgcat::mcset es Gaming                {Jugando}
::msgcat::mcset es {Going out}           {Saliendo por ahí}
::msgcat::mcset es Partying              {De fiesta}
::msgcat::mcset es Reading               {Leyendo}
::msgcat::mcset es Rehearsing            {Ensayando}
::msgcat::mcset es Shopping              {De compras}
::msgcat::mcset es Socializing           {Haciendo vida social}
::msgcat::mcset es Sunbathing            {Tomando el sol}
::msgcat::mcset es {Watching tv}         {Viendo la tele}
::msgcat::mcset es {Watching a movie}    {Viendo una película}

::msgcat::mcset es Grooming              {Arreglándome}
::msgcat::mcset es {At the spa}          {En el spa}
::msgcat::mcset es {Brushing teeth}      {Lavandome los dientes}
::msgcat::mcset es {Getting a haircut}   {Cortándome el pelo}
::msgcat::mcset es Shaving               {Afeitándome}
::msgcat::mcset es {Taking a bath}       {Bañándome}
::msgcat::mcset es {Taking a shower}     {Duchándome}

::msgcat::mcset es Drinking              {Bebiendo}
::msgcat::mcset es {Having a beer}       {Tomando una cerveza}
::msgcat::mcset es {Having coffee}       {Tomando un café}
::msgcat::mcset es {Having tea}          {Tomando té}

::msgcat::mcset es Inactive              {Inactivo}
::msgcat::mcset es {Day off}             {Día libre}
::msgcat::mcset es {Hanging out}         {Pasando el rato}
::msgcat::mcset es {On vacation}         {De vacaciones}
::msgcat::mcset es {Scheduled holiday}   {Vacadiones programadas}
::msgcat::mcset es Sleeping              {Durmiendo}

::msgcat::mcset es {Having appointment}  {En una cita}

::msgcat::mcset es activityPickMsg       {Introduzca la actividad que se mostrará a sus contactos.}
::msgcat::mcset es activityPickDtl       {Seleccione en el primer botón la actividad general, y opcionalmente, la actividad específica en el segundo botón. También puede añadir una descripción.}

# XEP-0080: User Location
::msgcat::mcset es Location              {Ubicación}
::msgcat::mcset es mLocation...          {Ubicac&ión...}
::msgcat::mcset es locationPickMsg       {Introduzca la ubicación que se mostrará a sus contactos.}
::msgcat::mcset es locationPickDtl       {Introduzca su ubicación debajo. Al menos debería introducir su latitud y longitud.}

# Note to translators: The commented strings are just there for completeness with the protocol, still not in UI
::msgcat::mcset es Altitude              {Altitud}
::msgcat::mcset es {Named Area}          {Nombre de la zona}
::msgcat::mcset es {GPS Bearing}         {Orientación GPS}
::msgcat::mcset es Building              {Edificio}
::msgcat::mcset es {GPS Datum}           {Datos GPS}
::msgcat::mcset es {GPS Error}           {Error del GPS}
::msgcat::mcset es Floor                 {Planta}
::msgcat::mcset es Latitude              {Latitud}
::msgcat::mcset es Locality              {Localidad}
::msgcat::mcset es Longitude             {Longitud}
::msgcat::mcset es Room                  {Sala}
::msgcat::mcset es Street                {Calle}
::msgcat::mcset es Text                  {Texto}
::msgcat::mcset es Timestamp             {Hora}

# Help strings:
# Note to translators: The commented strings are just there for completeness with the protocol, still not in UI
::msgcat::mcset es locationBearing       {Orientación GPS (dirección hacia la que se dirige al proximo punto de la ruta), medido en grados decimales en relación al norte}
::msgcat::mcset es locationAlt           {Altitud en metros sobre el nivel del mar}
::msgcat::mcset es locationLon           {Longitud en grados decimales Este}
::msgcat::mcset es locationError         {Error horizontal del GPS en minutos sexagesimales}
::msgcat::mcset es locationRegion        {La region administrativa, como un estado o provincia}
::msgcat::mcset es locationDescription   {El nombre en lenguaje natural de la ubicación}
::msgcat::mcset es locationText          {Un texto que resuma la información sobre la ubicación}
::msgcat::mcset es locationRoom          {Una sala particular del edificio}
::msgcat::mcset es locationPostalcode    {El código postal}
::msgcat::mcset es locationBuilding      {Un edificio específico en una calle o área}
::msgcat::mcset es locationStreet        {La calle o cruce de calles}
::msgcat::mcset es locationArea          {Área (Campus o vecindario)}
::msgcat::mcset es locationLat           {Latitud en grados decimales}
::msgcat::mcset es locationLocality      {Localidad o ciudad}
::msgcat::mcset es locationFloor         {Piso del edificio}
::msgcat::mcset es locationDatum         {GPS datum}
::msgcat::mcset es locationTimestamp     {UTC timestamp indicando el momento cuando se efectuo la lectura}
::msgcat::mcset es locationCountry       {El pais donde se encuentra el usuario}

::msgcat::mcset es {Synchronize with Google Earth} {Sincronizar con Google Earth}
::msgcat::mcset es {This is location data for} {La información del lugar para}

# Buddy pouncing:
::msgcat::mcset es budpounce-user        {Establezca acciones para eventos relacionados con %s. Seleccione los eventos usando las pestañas de abajo.}
::msgcat::mcset es budpounce-group       {Establezca acciones para eventos relacionados con cualquier contacto del grupo %s. Seleccione los eventos usando las pestañas de abajo.}
::msgcat::mcset es budpounce-any         {Establezca acciones para eventos relacionados con cualquier contacto de su lista de contactos. Seleccione los eventos usando las pestañas de abajo.}
::msgcat::mcset es budpounce-available   {%s acaba de entrar!}
::msgcat::mcset es budpounce-unavailable {%s acaba de salir!}
::msgcat::mcset es budpounce-msg         {%s te acaba de enviar un mensaje!}
::msgcat::mcset es budpounce-chat        {%s acaba de hablarte!}
::msgcat::mcset es budpounce-sendmsg     {Envia un mensaje con asunto}
::msgcat::mcset es mContactActions...    {Establecer una acción para este &Contacto...}

# Image magic:
::msgcat::mcset es immagic-msg           {Haga click en una ventana o seleccione un area rectangular para hacer una captura de pantalla e importarla a la pizarra.}
::msgcat::mcset es immagic-warn          {Dangerous in-box path name: %s}
::msgcat::mcset es immagic-rem           {Haga click en OK para borrar los ficheros: %s}

# File Types
# translation help: http://en.wikipedia.org/wiki/List_of_file_formats
# Note to translators: these strings have very low priority since the English names can be taken as definitions
::msgcat::mcset es {World Application}   {World Application}
::msgcat::mcset es {QuickDraw 3D Metafile} {QuickDraw 3D Metafile}
::msgcat::mcset es {Tcl File}            {Tcl File}
::msgcat::mcset es {Itcl File}           {Itcl File}
::msgcat::mcset es {Session Description Protocol} {Session Description Protocol}
::msgcat::mcset es {Adobe Flash Media}   {Adobe Flash Media}
::msgcat::mcset es {Mac Binary}          {Mac Binary}
::msgcat::mcset es {VTK 3D}              {VTK 3D}
::msgcat::mcset es {Generic File}        {Generic File}
::msgcat::mcset es {PDF Document}        {Documento PDF}
::msgcat::mcset es {PostScript Document} {Documento PostScript}
::msgcat::mcset es {JavaScript File}     {JavaScript File}
::msgcat::mcset es {TeX File}            {TeX File}
::msgcat::mcset es {Archive Tar}         {Archive Tar}
::msgcat::mcset es {Abi Word Document}   {Abi Word Document}
::msgcat::mcset es {Microsoft Excel Spreadsheet} {Microsoft Excel Spreadsheet}
::msgcat::mcset es {Microsoft PowerPoint Presentation} {Microsoft PowerPoint Presentation}
::msgcat::mcset es {Microsoft Word Document} {Microsoft Word Document}
::msgcat::mcset es {MPEG Audio}          {MPEG Audio}
::msgcat::mcset es {AIFF/Amiga Audio}    {AIFF/Amiga Audio}
::msgcat::mcset es {ULAW (Sun) Audio}    {ULAW (Sun) Audio}
::msgcat::mcset es {Streaming Audio}     {Streaming Audio}
::msgcat::mcset es {WAV Audio}           {WAV Audio}
::msgcat::mcset es {QCP Audio}           {QCP Audio}
::msgcat::mcset es {MIDI Audio}          {MIDI Audio}
::msgcat::mcset es {BMP Image}           {BMP Image}
::msgcat::mcset es {FlashPix Image}      {FlashPix Image}
::msgcat::mcset es {GIF Image}           {GIF Image}
::msgcat::mcset es {JPEG Image}          {JPEG Image}
::msgcat::mcset es {Macpaint Image}      {Macpaint Image}
::msgcat::mcset es {Adobe Photoshop Image} {Adobe Photoshop Image}
::msgcat::mcset es {PNG Image}           {PNG Image}
::msgcat::mcset es {PICT Image}          {PICT Image}
::msgcat::mcset es {SGI Image}           {SGI Image}
::msgcat::mcset es {Truevision Targa Image} {Truevision Targa Image}
::msgcat::mcset es {TIFF Image}          {TIFF Image}
::msgcat::mcset es {X PixMap Image}      {X PixMap Image}
::msgcat::mcset es {Plain Text Document} {Documento de texto plano}
::msgcat::mcset es {XML Document}        {XML Document}
::msgcat::mcset es {RTF Document}        {RTF Document}
::msgcat::mcset es {HTML Document}       {HTML Document}
::msgcat::mcset es {Cascading Style Sheet} {Cascading Style Sheet}
::msgcat::mcset es {QuickTime Video}     {QuickTime Video}
::msgcat::mcset es {MPEG-4 Video}        {MPEG-4 Video}
::msgcat::mcset es {DV Video}            {DV Video}
::msgcat::mcset es {MPEG Video}          {MPEG Video}
::msgcat::mcset es {Microsoft AVI Video} {Microsoft AVI Video}
::msgcat::mcset es {Autodesk's FLIC File} {Autodesk's FLIC File}

# END --------------------------------------------------------------------------


