# English language version of the Coccinella message catalog.
#
# French translation by Guillaume Ayoub (xovni at wanadoo.fr), 2004
#
# Textes standards, tels que "OK", "Annluer", etc...
# La chaîne source est utilisée comme message.
# Défini dans l'espace des chaînes de base, peut donc être repris dans n'importe quelle chaîne.

::msgcat::mcset fr Accept		{Accepter}
::msgcat::mcset fr Action		{Action}
::msgcat::mcset fr Active		{Actif}
::msgcat::mcset fr Add			{Ajouter}
::msgcat::mcset fr Address		{Adresse}
::msgcat::mcset fr Admin
::msgcat::mcset fr admin
::msgcat::mcset fr Advanced		{Avancé}
::msgcat::mcset fr Affiliation
::msgcat::mcset fr Agents		{Agents}
::msgcat::mcset fr Allow		{Autoriser}
::msgcat::mcset fr Appearance           {Apparence}
::msgcat::mcset fr Apply		{Appliquer}
::msgcat::mcset fr Available		{Disponible}

::msgcat::mcset fr Author

::msgcat::mcset fr Away			{Absent}
::msgcat::mcset fr Back
::msgcat::mcset fr Binary		{Binaire}
::msgcat::mcset fr Birthday		{Anniversaire}
::msgcat::mcset fr Block		{Bloquer}
::msgcat::mcset fr Blockers		{Bloqueur}
::msgcat::mcset fr Blocking		{Bloquant}
::msgcat::mcset fr Browser		{Navigateur}
::msgcat::mcset fr Both			{Les deux}
::msgcat::mcset fr Bookmark		{Marque-page}
::msgcat::mcset fr Bookmarks		{Marque-pages}
::msgcat::mcset fr Buffering		{Mise en cache}
::msgcat::mcset fr Cancel		{Annuler}
::msgcat::mcset fr Change		{Changer}
::msgcat::mcset fr Chat			{Discussion}
::msgcat::mcset fr Choose		{Choisir}
::msgcat::mcset fr City			{Ville}
::msgcat::mcset fr Clear		{Nettoyer}
::msgcat::mcset fr Client		{Client}
::msgcat::mcset fr Close		{Fermer}
::msgcat::mcset fr Codecs
::msgcat::mcset fr Conference		{Conférence}
::msgcat::mcset fr Connect		{Se connecter}
::msgcat::mcset fr Connection		{Connexion}
::msgcat::mcset fr Contact		{Contact}
::msgcat::mcset fr Contacts		{Contacts}
::msgcat::mcset fr Coordinates
::msgcat::mcset fr Country		{Pays}
::msgcat::mcset fr Create		{Créer}
::msgcat::mcset fr Customization	{Affichage}
::msgcat::mcset fr Date			{Date}
::msgcat::mcset fr Default		{Standard}
::msgcat::mcset fr Delete		{Supprimer}
::msgcat::mcset fr Deny			{Rejeter}
::msgcat::mcset fr Department		{Département}
::msgcat::mcset fr Description		{Description}
::msgcat::mcset fr Devices
::msgcat::mcset fr Drawing		{Dessin}
::msgcat::mcset fr Document		{Document}
::msgcat::mcset fr Done			{Fait}
::msgcat::mcset fr Edit			{Éditer}
::msgcat::mcset fr Email
::msgcat::mcset fr Enter		{Entrer}
::msgcat::mcset fr Error		{Erreur}
::msgcat::mcset fr Exit			{Sortie}
::msgcat::mcset fr File			{Fichier}
::msgcat::mcset fr File...              {Fichier...}
::msgcat::mcset fr Filter
::msgcat::mcset fr Filters
::msgcat::mcset fr Finish		{Terminer}
::msgcat::mcset fr Finished		{Terminé}

::msgcat::mcset fr Find

::msgcat::mcset fr First		{Premier}
::msgcat::mcset fr Friends              {Amis}
::msgcat::mcset fr Forward		{Faire suivre}
::msgcat::mcset fr From			{De}
::msgcat::mcset fr General		{Général}
::msgcat::mcset fr Get			{Recevoir}
::msgcat::mcset fr Getting		{Réception}
::msgcat::mcset fr Grant
::msgcat::mcset fr Group		{Groupe}
::msgcat::mcset fr Groupchat            {Groupe de discussion}
::msgcat::mcset fr Handling		{Ergonomie}
::msgcat::mcset fr Height		{Hauteur}
::msgcat::mcset fr History		{Historique}
::msgcat::mcset fr Home			{Démarrer}

::msgcat::mcset fr Icon

::msgcat::mcset fr Image		{Image}
::msgcat::mcset fr Import		{Importer}
::msgcat::mcset fr Inbox		{Messages}
::msgcat::mcset fr Info			{Infos}
::msgcat::mcset fr Invite		{Inviter}

::msgcat::mcset fr Key

::msgcat::mcset fr Language
::msgcat::mcset fr Last			{Dernier}
::msgcat::mcset fr Less			{Moins}
::msgcat::mcset fr Login		{Se connecter}
::msgcat::mcset fr Logout		{Se déconnecter}
::msgcat::mcset fr Member
::msgcat::mcset fr member
::msgcat::mcset fr Message		{Message}
::msgcat::mcset fr Middle		{Milieu}
::msgcat::mcset fr Moderator
::msgcat::mcset fr moderator
::msgcat::mcset fr Moderators		{Modérateurs}
::msgcat::mcset fr More			{Plus}
::msgcat::mcset fr Name			{Nom}
::msgcat::mcset fr Network		{Réseau}
::msgcat::mcset fr Never		{Jamais}
::msgcat::mcset fr New			{Nouveau}
::msgcat::mcset fr Next			{Suivant}
::msgcat::mcset fr Nick 		{Pseudo}
::msgcat::mcset fr Nickname 		{Pseudonyme}
::msgcat::mcset fr No			{Non}
::msgcat::mcset fr no			{non}
::msgcat::mcset fr None			{Aucun}
::msgcat::mcset fr Notes		{Notes}
::msgcat::mcset fr Occupation		{Occupé}
::msgcat::mcset fr Offline		{Déconnecté}
::msgcat::mcset fr OK			{OK}
::msgcat::mcset fr Online		{Connecté}
::msgcat::mcset fr Open			{Ouvrir}
::msgcat::mcset fr Options		{Options}
::msgcat::mcset fr Owner
::msgcat::mcset fr owner
::msgcat::mcset fr Participants		{Participants}
::msgcat::mcset fr Password		{Mot de passe}
::msgcat::mcset fr Pause		{Pause}
::msgcat::mcset fr Pick			{Choisir}
::msgcat::mcset fr Phone		{Téléphone}
::msgcat::mcset fr Play			{Jouer}
::msgcat::mcset fr Plugins		{Plugins}
::msgcat::mcset fr Port			{Port}
::msgcat::mcset fr Preferences		{Préférences}
::msgcat::mcset fr Previous		{Précédent}
::msgcat::mcset fr Print		{Imprimer}
::msgcat::mcset fr Priority		{Priorité}
::msgcat::mcset fr Privacy		{Confidentialité}
::msgcat::mcset fr Profile		{Profil}
::msgcat::mcset fr Profiles		{Profils}
::msgcat::mcset fr Progress		{Progression}
::msgcat::mcset fr Quit?		{Quitter ?}
::msgcat::mcset fr Quote		{Citer}
::msgcat::mcset fr Reason 		{Raison}
::msgcat::mcset fr Refresh
::msgcat::mcset fr Register		{S'enregistrer}
::msgcat::mcset fr Remaining		{Restant}
::msgcat::mcset fr Remove		{Enlever}
::msgcat::mcset fr Reply		{Répondre}
::msgcat::mcset fr Resource		{Ressources}
::msgcat::mcset fr Restart		{Redémarrer}
::msgcat::mcset fr Revoke
::msgcat::mcset fr Role
::msgcat::mcset fr Room			{Salon}
::msgcat::mcset fr Roster		{Contacts}
::msgcat::mcset fr Rosticons
::msgcat::mcset fr Save			{Enregistrer}
::msgcat::mcset fr Search		{Chercher}
::msgcat::mcset fr Select               {Choisir}
::msgcat::mcset fr Send			{Envoyer}
::msgcat::mcset fr Server		{Serveur}
::msgcat::mcset fr Servers		{Serveurs}
::msgcat::mcset fr Service 		{Service}
::msgcat::mcset fr Set			{Installer}
::msgcat::mcset fr Settings		{Paramètres}
::msgcat::mcset fr Shortcut		{Raccourci}
::msgcat::mcset fr Shortcuts		{Raccourcis}
::msgcat::mcset fr Size			{Taille}
::msgcat::mcset fr Sounds		{Sons}
::msgcat::mcset fr Specifications	{Spécifications}
::msgcat::mcset fr Speech		{Dialoguer}
::msgcat::mcset fr Standard
::msgcat::mcset fr State		{État}
::msgcat::mcset fr State/Region		{État/Région}
::msgcat::mcset fr Stop			{Arrêter}
::msgcat::mcset fr Subject		{Sujet}
::msgcat::mcset fr Subscribe		{S'inscrire}
::msgcat::mcset fr Subscribed		{Inscrit}
::msgcat::mcset fr Subscription		{Inscription}
::msgcat::mcset fr Subscriptions	{Inscriptions}
::msgcat::mcset fr Text			{Texte}
::msgcat::mcset fr Time			{Heure}
::msgcat::mcset fr Timeout		{Timeout}
::msgcat::mcset fr Title		{Titre}
::msgcat::mcset fr To			{À}
::msgcat::mcset fr Topic		{Thème}
::msgcat::mcset fr Transports		{Transports}
::msgcat::mcset fr Trash		{Corbeille}
::msgcat::mcset fr Type			{Type}
::msgcat::mcset fr Unregister		{Se désinscrire}
::msgcat::mcset fr Unsubscribe		{Se désinscrire}
::msgcat::mcset fr Unsubscribed		{Désinscrit}
::msgcat::mcset fr Username		{Nom}
::msgcat::mcset fr Value		{Valeur}
::msgcat::mcset fr Visitors		{Visitors}
::msgcat::mcset fr Voice
::msgcat::mcset fr voice
::msgcat::mcset fr Warning		{Attention}
::msgcat::mcset fr Welcome              {Bienvenue}
::msgcat::mcset fr Whiteboard		{Tableau}
::msgcat::mcset fr Width		{Largeur}
::msgcat::mcset fr Work			{Travail}
::msgcat::mcset fr Yes			{Oui}
::msgcat::mcset fr yes			{oui}

# A few words that are not unambiguous and have therefore a prefix.
::msgcat::mcset fr program-Application        Application


# Translate
# Canvas item options, names and values.
# Names:
::msgcat::mcset fr anchor           Anchor
::msgcat::mcset fr arrow            Arrow
::msgcat::mcset fr arrowshape       {Arrow Shape}
::msgcat::mcset fr capstyle         {Cap Style}
::msgcat::mcset fr coordinates      Coordinates
::msgcat::mcset fr dash             Dash
::msgcat::mcset fr file             File
::msgcat::mcset fr fill             Fill
::msgcat::mcset fr fontfamily       {Font Familiy}
::msgcat::mcset fr fontsize         {Font Size}
::msgcat::mcset fr fontweight       {Font Weight}
::msgcat::mcset fr image            Image
::msgcat::mcset fr joinstyle        {Join Style}
::msgcat::mcset fr justify          Justify
::msgcat::mcset fr outline          Outline
::msgcat::mcset fr outlinestipple   {Outline Stipple}
::msgcat::mcset fr smooth           Smooth
::msgcat::mcset fr stipple          Stipple
::msgcat::mcset fr tags             Tags
::msgcat::mcset fr text             Text
::msgcat::mcset fr width            Width

# Values (see item inspector to see what they mean):
# anchor
::msgcat::mcset fr n          N
::msgcat::mcset fr ne         NE
::msgcat::mcset fr e          E
::msgcat::mcset fr se         SE
::msgcat::mcset fr s          S
::msgcat::mcset fr sw         SW
::msgcat::mcset fr w          W
::msgcat::mcset fr nw         NW
::msgcat::mcset fr center     Center
# arrow
::msgcat::mcset fr last             Last
::msgcat::mcset fr first            First
::msgcat::mcset fr both             Both

::msgcat::mcset fr transparent      Transparent
::msgcat::mcset fr gray75           {Gray 75%}
::msgcat::mcset fr gray50           {Gray 50%}
::msgcat::mcset fr gray25           {Gray 25%}
::msgcat::mcset fr gray12           {Gray 12%}

::msgcat::mcset fr round            Round
::msgcat::mcset fr miter            Miter
::msgcat::mcset fr bevel            Bevel
::msgcat::mcset fr butt             Butt
::msgcat::mcset fr projecting       Projecting

::msgcat::mcset fr normal           Normal
::msgcat::mcset fr bold             Bold
::msgcat::mcset fr italic           Italic

::msgcat::mcset fr left             Left
::msgcat::mcset fr right            Right
::msgcat::mcset fr false            False
::msgcat::mcset fr true             True

# Tirets.
::msgcat::mcset fr none			{Aucun}
::msgcat::mcset fr dotted		{Points}
::msgcat::mcset fr dash-dotted		{Tirets mixtes}
::msgcat::mcset fr dashed		{Tirets}

# Status messages.
::msgcat::mcset fr available		{disponible}
::msgcat::mcset fr away		        {absent}
::msgcat::mcset fr {do not disturb}	{ne pas déranger}
::msgcat::mcset fr {not available}	{indisponible}
::msgcat::mcset fr {extended away}      {absent pour longtemps}
::msgcat::mcset fr invisible            {invisible}
::msgcat::mcset fr chat                 {discussion}
::msgcat::mcset fr subscribed           {inscrit}
::msgcat::mcset fr unsubscribed         {désinscrit}


# Titres de tous les menus ; concaténés avec 'm' pour la clé de la base de données.
::msgcat::mcset fr mFile		{Fichier}
::msgcat::mcset fr mEdit		{Édition}
::msgcat::mcset fr mPreferences		{Préférences}
::msgcat::mcset fr mJabber		{Jabber}
::msgcat::mcset fr mItems		{Outils}
::msgcat::mcset fr mLibrary		{Bibliothèques}
::msgcat::mcset fr mInfo		{Infos}
::msgcat::mcset fr mAddons		{Addons}
::msgcat::mcset fr mPlugins		{Plugins}

::msgcat::mcset fr mAboutWhiteboard   	{À propos du tableau}
::msgcat::mcset fr mAboutCoccinella   	{À propos de Coccinella...}
::msgcat::mcset fr mAboutQuickTimeTcl	{À propos de QuickTimeTcl...}
::msgcat::mcset fr mWelcome     	{Bienvenue}
::msgcat::mcset fr mNew			{&Nouveau}
::msgcat::mcset fr mNewWhiteboard	{Nouveau &tableau}
::msgcat::mcset fr mOpenConnection	{Se &connecter...}
::msgcat::mcset fr mCloseWindow		{&Fermer la fenêtre}
::msgcat::mcset fr mStartServer		{Lancer le &serveur}
::msgcat::mcset fr mOpenImage/Movie	{Ouvrir l'&image/la vidéo...}
::msgcat::mcset fr mOpenURLStream	{Lancer le s&treaming...}
::msgcat::mcset fr mPutCanvas		{Insérer un dessin}
::msgcat::mcset fr mGetCanvas		{Importer un dessin}
::msgcat::mcset fr mPutFile		{Insérer un fichier}
::msgcat::mcset fr mStopPut/Get/Open	{Arrêter l'insertion/l'ouverture}
::msgcat::mcset fr mOpenCanvas		{Ouvrir un dessin}
::msgcat::mcset fr mSaveCanvas		{Enregistrer le dessin}
::msgcat::mcset fr mSaveAs		{E&nregistrer sous...}
::msgcat::mcset fr mSaveAsItem          {Enregistrer en tant qu'objet...}
::msgcat::mcset fr mSaveImageAs         {Enregistrer l'&image sous...}
::msgcat::mcset fr mPageSetup		{&Propriétés de la page...}
::msgcat::mcset fr mPrintCanvas		{Imprimer le dessin}
::msgcat::mcset fr mQuit		{&Quitter}
::msgcat::mcset fr mAll			{&Tout sélectionner}
::msgcat::mcset fr mEraseAll		{Tout supprimer}
::msgcat::mcset fr mUndo		{Annuler}
::msgcat::mcset fr mRedo		{Refaire}
::msgcat::mcset fr mCut			{Couper}
::msgcat::mcset fr mCopy		{&Copier}
::msgcat::mcset fr mPaste		{Coller}
::msgcat::mcset fr mInspectItem		{Inspecteur}
::msgcat::mcset fr mRaise		{Monter}
::msgcat::mcset fr mLower		{Descendre}
::msgcat::mcset fr mLarger		{Plus grand}
::msgcat::mcset fr mSmaller		{Plus petit}
::msgcat::mcset fr mFlip		{Retourner}
::msgcat::mcset fr mHorizontal		{Horizontal}
::msgcat::mcset fr mVertical		{Vertical}
::msgcat::mcset fr mImageLarger		{Agrandir l'image}
::msgcat::mcset fr mImageSmaller	{Rétrécir l'image}
::msgcat::mcset fr mBackgroundColor	{Couleur d'arrière-plan...}
::msgcat::mcset fr mGrid		{Grille}
::msgcat::mcset fr mThickness		{Épaisseur}
::msgcat::mcset fr mBrushThickness	{Épaisseur de la brosse}
::msgcat::mcset fr mFill		{Remplir}
::msgcat::mcset fr mFillColor		{Remplir la couleur...}
::msgcat::mcset fr mOutlineColor	{Couleur du contour}
::msgcat::mcset fr mLineSmoothness	{Lissage de la ligne}
::msgcat::mcset fr mStraighten   	{Redresser}
::msgcat::mcset fr mArcs		{Arcs}
::msgcat::mcset fr mPieslice		{Part de gâteau}
::msgcat::mcset fr mChord		{Corde}
::msgcat::mcset fr mArc			{Arc}
::msgcat::mcset fr mDash		{Pointillés}
::msgcat::mcset fr mShiftConstrain	{Changer la contrainte}
::msgcat::mcset fr mTo90degrees		{Tourner de 90 degrés}
::msgcat::mcset fr mTo45degrees		{Tourner de 45 degrés}
::msgcat::mcset fr mFont		{Police}
::msgcat::mcset fr mSize		{Taille}
::msgcat::mcset fr mWeight		{Largeur}
::msgcat::mcset fr mNormal		{Normal}
::msgcat::mcset fr mBold		{Gras}
::msgcat::mcset fr mItalic		{Italique}
::msgcat::mcset fr mPreferences...	{&Préférences...}
::msgcat::mcset fr mNewAccount		{Nouveau compte...}
::msgcat::mcset fr mLogin		{Se connecter...}
::msgcat::mcset fr mLogout		{Se déconnecter}
::msgcat::mcset fr mLogoutWith          {Se déconnecter avec le message...}
::msgcat::mcset fr mHideMain            {Cacher}
::msgcat::mcset fr mShowMain            {Montrer}
::msgcat::mcset fr mPassword		{&Mot de passe...}
::msgcat::mcset fr mRoster/Services	{Contacts/services}
::msgcat::mcset fr mMessageInbox	{Messages}
::msgcat::mcset fr mSearch		{Cherche&r...}
::msgcat::mcset fr mAddNewUser		{Ajouter un nouvel utilisateur...}
::msgcat::mcset fr mSendMessage		{Envo&yer un message...}
::msgcat::mcset fr mChat		{Discussion}
::msgcat::mcset fr mStatus		{Statut}
::msgcat::mcset fr mDirStatus           {Statut désiré}
::msgcat::mcset fr mAvailable		{Disponible}
::msgcat::mcset fr mAway		{Absent}
::msgcat::mcset fr mDoNotDisturb	{Ne pas déranger}
::msgcat::mcset fr mNotAvailable	{Indisponible}
::msgcat::mcset fr mExtendedAway        {Absent pour longtemps}
::msgcat::mcset fr mInvisible           {Invisible}
::msgcat::mcset fr mAttachMessage	{Message joint...}
::msgcat::mcset fr mEnterRoom		{Entrer dans le salon...}
::msgcat::mcset fr mExitRoom		{Sortir du salon}
::msgcat::mcset fr mCreateRoom		{Créer un salon...}
::msgcat::mcset fr mvCard		{Carte de visite...}
::msgcat::mcset fr mRemoveAccount	{Enlever un compte}
::msgcat::mcset fr mErrorLog		{Messages d'erreur...}
::msgcat::mcset fr mDebug		{Debuggage}
::msgcat::mcset fr mOnServer		{À propos du serveur...}
::msgcat::mcset fr mOnClients		{À propos des clients...}
::msgcat::mcset fr mOnPlugins		{À propos des plugins...}
::msgcat::mcset fr mHelpOn		{Aide}
::msgcat::mcset fr mNetworkSetup	{Propriétés du réseau}
::msgcat::mcset fr mServers		{Serveurs}
::msgcat::mcset fr mJabberTransport	{Transport Jabber}
::msgcat::mcset fr mSmileyLegend	{Légende des frimousses}
::msgcat::mcset fr mSetupAssistant	{&Assistant de configuration}
::msgcat::mcset fr mImageLarger		{Agrandir l'image}
::msgcat::mcset fr mImageSmaller	{Rétrécir l'image}
::msgcat::mcset fr mExportImage		{Exporter l'image...}
::msgcat::mcset fr mExportMovie		{Exporter la vidéo...}
::msgcat::mcset fr mSyncPlayback	{Lecture synchronisée}
::msgcat::mcset fr mColor		{Couleur...}
::msgcat::mcset fr mAddSpeechBubble	{Ajouter une bulle}
::msgcat::mcset fr mUpdateCheck  	{Voir les mises-à-jour}
::msgcat::mcset fr mReloadImage  	{Recharger l'image}
::msgcat::mcset fr mCoccinellaHome  	{Dossier de Coccinella...}
::msgcat::mcset fr mComponents          {Composants...}
::msgcat::mcset fr mBugReport           {Signaler un bug...}
::msgcat::mcset fr mTakeSnapShot        {Faire une capture d'écran}
::msgcat::mcset fr mTimeCode            {}
::msgcat::mcset fr mUserInfo            {Infos utilisateur...}

# Translate
::msgcat::mcset fr mToolbar             {Toolbar}
::msgcat::mcset fr mNotebook            {Notebook}
::msgcat::mcset fr mMinimal             {Minimal}
::msgcat::mcset fr mDisco               {Disco}
::msgcat::mcset fr mFind                {Find}
::msgcat::mcset fr mFindAgain           {Find Again}
::msgcat::mcset fr mFindPrevious        {Find Previous}
::msgcat::mcset fr mCustomStatus        {Custom Status...}
::msgcat::mcset fr mImport              {Import}
::msgcat::mcset fr mExport              {Export}
::msgcat::mcset fr mEmoticonSet         {Emoticon Set...}
::msgcat::mcset fr mRoster              {Roster...}
::msgcat::mcset fr mFontSize            {Font Size}
::msgcat::mcset fr mNormalFont          {Normal}
::msgcat::mcset fr mLargerFont          {Larger}
::msgcat::mcset fr mLargeFont           {Large}


# Popups.
::msgcat::mcset fr mMessage     	{Message...}
::msgcat::mcset fr mWhiteboard     	{Tableau...}
::msgcat::mcset fr mLastLogin/Activity  {Dernière connexion/activité}
::msgcat::mcset fr mEditUser     	{Éditer l'utilisateur...}
::msgcat::mcset fr mRemoveUser     	{Supprimer l'utilisateur...}
::msgcat::mcset fr mRefreshRoster     	{Rafraîchir la liste des contacts}
::msgcat::mcset fr mVersion     	{Version}
::msgcat::mcset fr mRegister     	{S'inscrire}
::msgcat::mcset fr mUnregister     	{Se désinscrire}
::msgcat::mcset fr mRefresh     	{Rafraîchir}
::msgcat::mcset fr mAddServer     	{Ajouter un serveur...}
::msgcat::mcset fr mLocalTime     	{Heure locale...}
::msgcat::mcset fr mSendFile     	{Envoyer un message...}
::msgcat::mcset fr mChatHistory     	{Historique de la discussion}
::msgcat::mcset fr mLoginTrpt     	{Se connecter à un serveur de transport}
::msgcat::mcset fr mLogoutTrpt     	{Se déconnecter d'un serveur de transport}
::msgcat::mcset fr mRemoveContact  	{Enlever le contact...}
::msgcat::mcset fr mShow 		{Montrer}
::msgcat::mcset fr mOffline		{Déconnecté}
::msgcat::mcset fr mTransports		{Transports}
::msgcat::mcset fr mIgnore         	{Ignorer}
::msgcat::mcset fr mEditBookmarks	{Éditer les marque-pages...}

# Translate
::msgcat::mcset fr mSort                {Sort}
::msgcat::mcset fr mIncreasing          {Increasing}
::msgcat::mcset fr mDecreasing          {Decreasing}
::msgcat::mcset fr mStyle               {Style}
::msgcat::mcset fr mCall                {Call}
::msgcat::mcset fr mJiveCall            {Call}
::msgcat::mcset fr mJiveForward         {Forward Call}
::msgcat::mcset fr mBackgroundImage     {Background Image}
::msgcat::mcset fr mEditNick            {Edit Nickname}


# Courts textes uniquement. Anglais pour les clés de la base de données.
::msgcat::mcset fr {30 days}			{30 jours}
::msgcat::mcset fr {About Coccinella}		{À propos de Coccinella}
::msgcat::mcset fr {About Whiteboard}		{À propos du tableau}
::msgcat::mcset fr {About QuickTimeTcl}		{À propos de QuickTimeTcl}
::msgcat::mcset fr {About %s}                   {À propos de %s}
::msgcat::mcset fr {Active <Return>}		{Appuyer sur <entrée>}
::msgcat::mcset fr {Add New User}		{Ajouter un nouvel utilisateur}
::msgcat::mcset fr {Add permanently}		{Ajouter définitivement}
::msgcat::mcset fr {Add Server}			{Ajouter un serveur}
::msgcat::mcset fr {Add Shortcut}		{Ajouter un raccourci}
::msgcat::mcset fr {Address 1}			{Adresse 1}
::msgcat::mcset fr {Address 2}			{Adresse 2}
::msgcat::mcset fr {Advanced Setup}		{Préférences avancées}
::msgcat::mcset fr {Advanced Configuration}	{Configuration avancée}
::msgcat::mcset fr {Alert sounds}		{Sons d'alerte}
::msgcat::mcset fr {As text}			{Comme texte}
::msgcat::mcset fr {Ask each time}		{Demander chaque fois}
::msgcat::mcset fr {Auto Away}			{Départ automatique}
::msgcat::mcset fr {Auto Connect}		{Connexion automatique}
::msgcat::mcset fr {Auto Join}
::msgcat::mcset fr {Auto-accept}		{Accepter automatiquement}
::msgcat::mcset fr {Auto-reject}		{Rejeter automatiquement}
::msgcat::mcset fr {Away status}		{Statut "Absent"}
::msgcat::mcset fr {Basic Info}			{Informations de bases}
::msgcat::mcset fr {Block JID}			{Bloquage JID}
::msgcat::mcset fr {Bookmark this room}		{Ajouter ce salon à vos marque-pages}
::msgcat::mcset fr {Broken Image}
::msgcat::mcset fr {Buddy Pouncing}
::msgcat::mcset fr {Built in server port}	{Port du serveur interne}
::msgcat::mcset fr {Cache folder}		{Répertoire du cache}
::msgcat::mcset fr {Canvas Size}		{Taille du dessin}
::msgcat::mcset fr {Chat History}		{Historique de la discussion}
::msgcat::mcset fr {Chat With}			{Discuter avec}
::msgcat::mcset fr {Clear Disk Cache Now}	{Vider le cache}
::msgcat::mcset fr {Company Name}		{Nom de l'entreprise}
::msgcat::mcset fr {Component Info}		{Infos sur la fonctionnalité}
::msgcat::mcset fr {Conference server}		{Serveur de la conférence}
::msgcat::mcset fr {Connect using HTTP}
::msgcat::mcset fr {Contact Type}		{Type de contact}
::msgcat::mcset fr {Create Room}		{Créer un salon}
::msgcat::mcset fr {Default group}		{Groupe par défaut}
::msgcat::mcset fr {Default Logout Status}	{Déconnexion par défaut}
::msgcat::mcset fr {Default nickname}
::msgcat::mcset fr {Default status descriptions} {Description du statut par défaut}
::msgcat::mcset fr {Delete Profile}
::msgcat::mcset fr {Delete Rule}		{Règle de suppression}
::msgcat::mcset fr {Disk Cache}			{Cache}
::msgcat::mcset fr {Disco method}
::msgcat::mcset fr {Different Passwords}        {Différents mots de passe}
::msgcat::mcset fr {Do Not Disturb}		{Ne pas déranger}

::msgcat::mcset fr {Do not save password}

::msgcat::mcset fr {Edit Fonts}			{Éditer les polices}
::msgcat::mcset fr {Edit Item}			{Éditer l'outil}
::msgcat::mcset fr {Edit Shortcut}		{Éditer le raccourci}
::msgcat::mcset fr {Edit Shortcuts}		{Éditer les raccourcis}
::msgcat::mcset fr {Edit User}			{Éditer l'utilisateur}
::msgcat::mcset fr {Email address}		{Adresse courriel}
::msgcat::mcset fr {Email addresses}		{Adresses courriel}
::msgcat::mcset fr {Empty Fields}		{Champs libres}
::msgcat::mcset fr {Enter/Create Room}		{Entrer/Créer un salon}
::msgcat::mcset fr {Enter Room}			{Entrer dans un salon}
::msgcat::mcset fr {Every time}			{Chaque fois}
::msgcat::mcset fr {Extended Away status}	{Statut "Absent pour longtemps"}
::msgcat::mcset fr {Factory Settings}		{Propriétés par défaut}
::msgcat::mcset fr {Fatal Error}		{Erreur fatale}
::msgcat::mcset fr {File Cache}			{Cache}
::msgcat::mcset fr {File coding}		{Encodage des fichiers}
::msgcat::mcset fr {File Mappings}		{Gestion des extensions}
::msgcat::mcset fr {File suffixes}		{Extension des fichiers}
::msgcat::mcset fr {File Transfer}		{Transfert de fichiers}
::msgcat::mcset fr {File Transfer Error}	{Erreur dans le transfert}
::msgcat::mcset fr {File transfer port}
::msgcat::mcset fr {First name}			{Prénom}
::msgcat::mcset fr {Font Size}			{Taille de la police}
::msgcat::mcset fr {Font Weight}		{Épaisseur de la police}
::msgcat::mcset fr {Format mm/dd/yyyy}		{Format mm/jj/aaaa}
::msgcat::mcset fr {Get File}			{Voir le fichier}
::msgcat::mcset fr {Get File Error}		{Erreur lors de la réception du fichier}
::msgcat::mcset fr {Get vCard}			{Voir la carte de visite}
::msgcat::mcset fr {Getting available rooms...}	{Réception des salons disponibles...}
::msgcat::mcset fr {Groupchat-1.0 (fallback)}	{Groupchat 1.0 (fallback)}
::msgcat::mcset fr {Handled By}			{Géré par}
::msgcat::mcset fr {History length}		{Longueur de l'historique}
::msgcat::mcset fr {Host name}			{Nom de domaine}
::msgcat::mcset fr {HTTP port}			{Port HTTP}
::msgcat::mcset fr {>>Import>>}
::msgcat::mcset fr {Import Iconset...}		{Importer un thème d'icônes}
::msgcat::mcset fr {Import using}		{Importer en utilisant...}
::msgcat::mcset fr {Import/Remove fonts}	{Importer/Supprimer polices}
::msgcat::mcset fr {Incoming Message}		{Message entrant}
::msgcat::mcset fr {Incoming Messages}		{Messages entrants}
::msgcat::mcset fr {Incoming Presence}		{Connexion en cours}
::msgcat::mcset fr {Info Room}
::msgcat::mcset fr {Inspect Associations}	{Inspecter les associations}
::msgcat::mcset fr {Invite User}		{Inviter un utilisateur}
::msgcat::mcset fr {IP address}			{Adresse IP}
::msgcat::mcset fr {Is connected}		{Connecté}
::msgcat::mcset fr {Is safe}			{Sûr}
::msgcat::mcset fr {Is server up}		{Connecté}
::msgcat::mcset fr {Item Inspector}
::msgcat::mcset fr {Item Options}
::msgcat::mcset fr {Item Type}
::msgcat::mcset fr {Jabber address}		{Adresse Jabber}
::msgcat::mcset fr {Jabber Client}		{Client Jabber}
::msgcat::mcset fr {Jabber Server}		{Serveur Jabber}
::msgcat::mcset fr {Jabber server port}		{Port du serveur Jabber}
::msgcat::mcset fr {Jabber user ID}		{Identifiant de l'utilisateur Jabber}
::msgcat::mcset fr {Jabber ID}			{Identifiant Jabber}
::msgcat::mcset fr {JID to block}		{JID à bloquer}
::msgcat::mcset fr {Last Activity}		{Dernière activité}
::msgcat::mcset fr {Last name}			{Nom}
::msgcat::mcset fr {Launch time}		{Heure de lancement}
::msgcat::mcset fr {Local Time}			{Heure locale}
::msgcat::mcset fr {Logout With Message}        {Se déconnecter avec le message}
::msgcat::mcset fr {Logged out}                 {Déconnecter}
::msgcat::mcset fr {Login as invisible}		{Se connecter avec le statut "Invisible"}
::msgcat::mcset fr {Mailbox Error}		{Erreur de boîte aux lettres}
::msgcat::mcset fr {Make new text item for each line}
::msgcat::mcset fr {MIDI Player}
::msgcat::mcset fr {MIME type}			{Type MIME}
::msgcat::mcset fr {Movie Options}
::msgcat::mcset fr {Multi Connect}		{Connexions multiples}
::msgcat::mcset fr {My Avatar}
::msgcat::mcset fr {My nickname for own display}
::msgcat::mcset fr {My Status}			{Mon statut}
::msgcat::mcset fr {Name of list}		{Nom de liste}
::msgcat::mcset fr {Network Error}		{Erreur de Réseau}
::msgcat::mcset fr {Network Setup}		{Configuration du réseau}
::msgcat::mcset fr {New Account}		{&Nouvel utilisateur}
::msgcat::mcset fr {New Bookmark}		{Nouveau marque-page}
::msgcat::mcset fr {New chat message}		{Nouveau message dans la discussion}
::msgcat::mcset fr {New chat thread}		{Nouvelle discussion}
::msgcat::mcset fr {New Color}			{Nouvelle couleur}
::msgcat::mcset fr {New incoming message}	{Nouveau message entrant}
::msgcat::mcset fr {New Message}		{Nouveau message}
::msgcat::mcset fr {New Nickname}		{Nouveau pseudo}
::msgcat::mcset fr {New Password}		{Nouveau mot de passe}
::msgcat::mcset fr {New Profile}
::msgcat::mcset fr {New Rule}			{Nouvelle règle}
::msgcat::mcset fr {New Topic}			{Nouveau sujet}
::msgcat::mcset fr {New shortcut}		{Nouveau raccourci}
::msgcat::mcset fr {New User}			{Nouvel utilisateur}
::msgcat::mcset fr {New Version}		{Nouvelle version}
::msgcat::mcset fr {My vCard}			{Ma carte de visite}
::msgcat::mcset fr {NAT Address}		{Adresse NAT}
::msgcat::mcset fr {Nick name}			{Pseudo}
::msgcat::mcset fr {No Address}			{Pas d'adresse}
::msgcat::mcset fr {No Available}		{Aucun disponible}
::msgcat::mcset fr {No Inbox}			{Pas de message entrant}
::msgcat::mcset fr {No Printing}		{Pas d'impression}
::msgcat::mcset fr {No registered history for %s}
::msgcat::mcset fr {No Restriction}		{Pas de restriction}
::msgcat::mcset fr {Not Available}		{Indisponible}
::msgcat::mcset fr {Not available}		{Indisponible}
::msgcat::mcset fr {Not Connected}		{Déconnecté}
::msgcat::mcset fr {Not older than}		{Plus récent que}
::msgcat::mcset fr {Once per session}		{Une fois par session}
::msgcat::mcset fr {Open Canvas}		{Ouvrir dessin}
::msgcat::mcset fr {Open Failed}		{Échec de l'ouverture}
::msgcat::mcset fr {Open Helpfile}		{Ouvrir le fichier d'aide}
::msgcat::mcset fr {Open Image/Movie}		{Ouvrir image/vidéo}
::msgcat::mcset fr {Open Stream}		{Ouvrir streaming}
::msgcat::mcset fr {Outgoing Presence}		{En cours de déconnexion}
::msgcat::mcset fr {Peer-to-Peer}		{Peer-to-peer}
::msgcat::mcset fr {Personal Info}		{Infos personnelles}
::msgcat::mcset fr {Personal Information}	{Informations personnelles}
::msgcat::mcset fr {Personal URL}		{URL personnelle}
::msgcat::mcset fr {Pick Directory}		{Choisir un dossier}
::msgcat::mcset fr {Pick File}			{Choisir un fichier}
::msgcat::mcset fr {Pick Image File}
::msgcat::mcset fr {Pick skin}			{Choisir un thème}
::msgcat::mcset fr {Plugin Info}		{Infos sur le plugin}
::msgcat::mcset fr {Plugin Control}		{Contrôle du plugin}
::msgcat::mcset fr {Port number}		{Numéro de port}
::msgcat::mcset fr {Postal Code}		{Code postal}
::msgcat::mcset fr {Preferred Protocol}		{Protocole préféré}
::msgcat::mcset fr {Presence Error}		{Erreur de statut}
::msgcat::mcset fr {Privacy List}		{Liste personnelle}
::msgcat::mcset fr {Profile Name}               {Nom du profil}
::msgcat::mcset fr {Proxy Port}
::msgcat::mcset fr {Proxy Server}
::msgcat::mcset fr {Proxy Setup}		{Configuration du proxy}
::msgcat::mcset fr {Public Jabber Servers}
::msgcat::mcset fr {Put File Error}		{Erreur lors de l'insertion du fichier}
::msgcat::mcset fr {Put Image/Movie}		{Insérer image/vidéo}
::msgcat::mcset fr {Reject receive}		{Rejeter la réception}
::msgcat::mcset fr {Request To User}		{Demande à l'utilisateur}
::msgcat::mcset fr {Retype Password}		{Retaper le mot de passe}
::msgcat::mcset fr {Revert Panel}		{Annuler les changements}
::msgcat::mcset fr {Register New Account}	{Enregistrer nouveau compte}
::msgcat::mcset fr {Register Now}		{S'enregistrer maintenant}
::msgcat::mcset fr {Register Service}		{Service d'enregistrement}
::msgcat::mcset fr {Remove Item}		{Supprimer l'outil}
::msgcat::mcset fr {Remove Photo}
::msgcat::mcset fr {Room name}			{Nom du salon}
::msgcat::mcset fr {Room name (optional)}	{Nom du salon (facultatif)}
::msgcat::mcset fr {Roster & Services}		{Contacts & services}
::msgcat::mcset fr {Save As}			{Enregistrer sous}
::msgcat::mcset fr {Save As GIF}		{Enregistrer en format GIF}
::msgcat::mcset fr {Save Canvas}		{Enregistrer le dessin}
::msgcat::mcset fr {Save File}			{Enregistrer le fichier}
::msgcat::mcset fr {Save Message}		{Enregistrer le message}
::msgcat::mcset fr {Scramble password}		{Brouiller le mot de passe}
::msgcat::mcset fr {Search results}		{Chercher les résultats}
::msgcat::mcset fr {Search Service}		{Chercher le service}
::msgcat::mcset fr {Search Specifications}	{Chercher les spécifications}
::msgcat::mcset fr {Select a new nickname}	{Choisir un nouveau pseudo}
::msgcat::mcset fr {Select Font}		{Choisir police}
::msgcat::mcset fr {Select Photo}
::msgcat::mcset fr {Send File}			{Envoyer fichier}
::msgcat::mcset fr {Send Live}			{Envoyer live}
::msgcat::mcset fr {Server Info}		{Infos sur le serveur}
::msgcat::mcset fr {Service server}		{Service du serveur}
::msgcat::mcset fr {Set Directed Presence}      {Appliquer le statut désiré}
::msgcat::mcset fr {Set New Nickname}		{Appliquer le nouveau pseudo}
::msgcat::mcset fr {Set New Topic}		{Appliquer le nouveau sujet}
::msgcat::mcset fr {Set Status}			{Changer le statut}
::msgcat::mcset fr {Set windows opacity}	{Changer l'opacité des fenêtres}
::msgcat::mcset fr {Settings Panels}		{Panneau de configuration}
::msgcat::mcset fr {Setup Assistant}		{Assistant de configuration}

::msgcat::mcset fr {Show Text and Image}
::msgcat::mcset fr {Show Text}
::msgcat::mcset fr {Show Image}

::msgcat::mcset fr {Slide Show}			{Diaporama}
::msgcat::mcset fr {Slide Show Folder}		{Dossier des Diaporamas}
::msgcat::mcset fr {Smooth freehand strokes}
::msgcat::mcset fr {Software Update}		{Mise-à-jour du logiciel}
::msgcat::mcset fr {Sound Set}
::msgcat::mcset fr {Sounds & Speech}		{Sons & langage}
::msgcat::mcset fr {Start Chat}			{Lancer la discussion}
::msgcat::mcset fr {Status message}		{Message du statut}
::msgcat::mcset fr {Status when logging out}	{Statut lors de la déconnexion}
::msgcat::mcset fr {Subscription Failed}	{Échec de l'enregistrement}
::msgcat::mcset fr {Subscription Pending}	{Enregistrement imminent}
::msgcat::mcset fr {Synthetic speech}		{Langage de synthèse}
::msgcat::mcset fr {System fonts}		{Polices système}
::msgcat::mcset fr {Take Snapshot}		{Capture d'écran}
::msgcat::mcset fr {Tel (voice)}		{Tel}
::msgcat::mcset fr {Tel (fax)}			{Fax}
::msgcat::mcset fr {This IP number}		{Cette adresse IP}
::msgcat::mcset fr {Thread started}		{Flux initialisé}
::msgcat::mcset fr {To/from JID}		{À/De JID}
::msgcat::mcset fr {To Jabber ID}		{À l'ID Jabber}
::msgcat::mcset fr {To Send or Not}		{À envoyer ou non}
::msgcat::mcset fr {Type of File}		{Type de fichier}
::msgcat::mcset fr {Unknown: Prompt user}	{Inconnu : Nom d'utilisateur}
::msgcat::mcset fr {Url of homepage}		{URL de la page de démarrage}
::msgcat::mcset fr {Use proxy}
::msgcat::mcset fr {Use Secure Connection}
::msgcat::mcset fr {Use SSL for security}	{Utiliser SSL pour la sécurité}
::msgcat::mcset fr {Use TLS and SASL authentication}
::msgcat::mcset fr {Use TLS on separate port (old)}
::msgcat::mcset fr {User Info}                  {Infos utilisateur}
::msgcat::mcset fr {User is}			{L'utilisateur est}
::msgcat::mcset fr {User is offline}		{L'utilisateur est déconnecté}
::msgcat::mcset fr {User is online}		{L'utilisateur est connecté}
::msgcat::mcset fr {User Profiles}		{Profils d'utilisateur}
::msgcat::mcset fr {User's status changed}	{Le statut de l'utilisateur a changé}
::msgcat::mcset fr {Users Avatar}
::msgcat::mcset fr {Username & Password}	{Nom & mot de passe}
::msgcat::mcset fr {vCard Info}			{Infos sur la carte de visite}
::msgcat::mcset fr {Version Info}		{Infos sur la version}
::msgcat::mcset fr {Whiteboard fonts}		{Polices du tableau}
::msgcat::mcset fr {Writing file}		{Écriture du fichier}
::msgcat::mcset fr {Groupchat presence change}	{Changement de statut sur un salon}

# Translate
# Rooms.
::msgcat::mcset fr {Kick Participant}
::msgcat::mcset fr {Ban Participant}
::msgcat::mcset fr {Configure Room}
::msgcat::mcset fr {Destroy Room}
::msgcat::mcset fr {Edit Lists}
::msgcat::mcset fr {Edit the privilege to speak in the room, the voice.}
::msgcat::mcset fr {Edit the ban list}
::msgcat::mcset fr {Edit the member list}
::msgcat::mcset fr {Edit the moderator list}
::msgcat::mcset fr {Edit the admin list}
::msgcat::mcset fr {Edit the owner list}


# Time intervals.
::msgcat::mcset fr {Ten seconds}		{Dix secondes}
::msgcat::mcset fr {One minute}			{Une minute}
::msgcat::mcset fr {Ten minutes}		{Dix minutes}
::msgcat::mcset fr {One hour} 			{Une heure}
::msgcat::mcset fr {One day} 			{Un jour}
::msgcat::mcset fr {One week}	 		{Une semaine}


# Translate
# Language names.
::msgcat::mcset fr {Danish} 
::msgcat::mcset fr {Dutch} 
::msgcat::mcset fr {English} 
::msgcat::mcset fr {French} 
::msgcat::mcset fr {German} 
::msgcat::mcset fr {Italian} 
::msgcat::mcset fr {Korean}
::msgcat::mcset fr {Polish} 
::msgcat::mcset fr {Russian} 
::msgcat::mcset fr {Spanish} 
::msgcat::mcset fr {Swedish} 

# Translate
# Same languge names but with their native names.
# See the other catalogs to get these.
::msgcat::mcset fr nativeDanish     Dansk
::msgcat::mcset fr nativeDutch      Nederlands
::msgcat::mcset fr nativeEnglish    English
::msgcat::mcset fr nativeFrench     Français
::msgcat::mcset fr nativeGerman     Deutsch
::msgcat::mcset fr nativeItalian
::msgcat::mcset fr nativeKorean
::msgcat::mcset fr nativePolish 
::msgcat::mcset fr nativeRussian 
::msgcat::mcset fr nativeSpanish    Castellano
::msgcat::mcset fr nativeSwedish    Svenska 



# Écran de démarrage :
::msgcat::mcset fr splashsource 	{Mise en source du code Tcl...}
::msgcat::mcset fr splashload 		{Chargement des paquetages Tcl...}
::msgcat::mcset fr splashloadsha1 	{Chargement des paquetages sha1...}
::msgcat::mcset fr splashsourcejabb 	{Chargement des sources de Jabber...}
::msgcat::mcset fr splashhost 		{Recherche du nom d'hôte...}
::msgcat::mcset fr splashinit 		{Initialisation...}
::msgcat::mcset fr splashprefs 		{Chargement et application des préférences...}
::msgcat::mcset fr splashbuildmenu	{Construction des menus...}
::msgcat::mcset fr splashbuild 		{Construction de l'interface...}
::msgcat::mcset fr splashlook 		{Recherche de}


# Messages pour tk_messageBox :
::msgcat::mcset fr messfailedhttp	{Échec lors du démarrage du serveur http interne %s}
::msgcat::mcset fr messinfoscript	{À cause d'un bug du "script info" sous Mac, vous devez indiquer explicitement le dossier "Tableau-%s" dans la boîte de dialogue suivante}
::msgcat::mcset fr messfailedsock	{Impossible d'initialiser le flux vers le serveur. Peut-être que le réseau ne fonctionne pas ou que le serveur est indisponible. Le message d'erreur est : %s}
::msgcat::mcset fr messeofconnect	{Erreur lors de l'ouverture de la connexion : Réception d'un eof}
::msgcat::mcset fr messfailconnect	{Erreur lors de l'ouverture de la connexion à %s}
::msgcat::mcset fr messtimeout		{Temps dépassé lors de la connexion}
::msgcat::mcset fr messnoplugs		{Il n'y a pas de plugin ou d'aide détectée sur ce système}
::msgcat::mcset fr messfailopread	{Impossible d'ouvrir %s pour lire %s}
::msgcat::mcset fr messfailopwrite	{Impossible d'ouvrir %s pour écrire %s}
::msgcat::mcset fr messcanerasewarn	{Ouvrir un nouveau dessin efface tout dans le dessin actuel !}
::msgcat::mcset fr messaskreceive	{Prêt à recevoir %s, voulez-vous le recevoir ?}
::msgcat::mcset fr messfailmimeimp 	{Impossible d'importer les fichiers de type MIME %s}
::msgcat::mcset fr messfailnomime 	{Impossible de trouver le type MIME pour le fichier %s}
::msgcat::mcset fr messfailsend		{Erreur lors de l'envoi à %s}
::msgcat::mcset fr messfactorydefaults	{Vous êtes sur le point de supprimer la plupart de vos préférences. Voules-vous continuer ?}
::msgcat::mcset fr messremoveprofile	{Voulez-vous supprimer ce profil ? Votre compte ne sera pas supprimé lors de cette opération}
::msgcat::mcset fr messfillserveruser	{Vous devez au moins remplir le nom de l'utilisateur et du serveur}
::msgcat::mcset fr messprofinuse	{Ce profil est déjà utilisé, voulez-vous le remplacer ?}
::msgcat::mcset fr messblockbadjid	{Les champs du JID %s ne sont pas correctement renseignés, voulez-vous tout de même l'ajouter ?}
::msgcat::mcset fr messfieldsmissing	{Un ou plusieurs champs sont vides, recommencez ou annulez}
::msgcat::mcset fr messrmstandardfonts	{Les polices standard Times, Helvetica et Courier ne peuvent pas être supprimées}
::msgcat::mcset fr messprefschanged	{Les préférences ont été changées, voulez-vous tout de même annuler ?}
::msgcat::mcset fr messerrpreffile	{Erreur lors de l'ouverture de %s}
::msgcat::mcset fr messfailserver	{Impossible d'ouvrir le socket du serveur, vous n'êtes peut-être pas connecté}
::msgcat::mcset fr messopenhelpfile	{Vous êtes sur le point d'ouvrir un fichier d'aide dans le dessin et donc d'effacer le dessin actuel ; voulez-vous continuer ?}
::msgcat::mcset fr messprintnoextension	{Il n'y a pas d'extension Tcl qui pourrait nous aider ici :-(}
::msgcat::mcset fr messdoquit?		{Êtes-vous sûr de vouloir quitter ?}
::msgcat::mcset fr messsuassfillin	{Vérifiez que vous avez complété tous les champs avant de continuer !}
::msgcat::mcset fr messsuassclose	{Êtes-vous sûr de vouloir fermer l'assistant de configuration ? Vous pouvez le relancer ultérieurement depuis le menu}
::msgcat::mcset fr messprotocolch	{Vous avez changé la configuration du réseau, vous devez relancer l'application pour que les changements prennent effet. Voulez-vous continuer ?}
::msgcat::mcset fr messpasswddifferent  {Les deux mots de passe sont différents, Veuillez recommencer s'il vous plaît}
::msgcat::mcset fr messaupdatelatest    {Vous avez déjà la dernière version(%s)}
::msgcat::mcset fr messprefsrestart     {Vous devez redémarrer l'application pour que certains changements prennent effet}



# Messages pour tk_messageBox :
::msgcat::mcset fr jamesserrsend	{Une erreur est survenue lors de l'envoi du\
  message à "%s" ; le message d'erreur est "%s"}
::msgcat::mcset fr jamessallowsub	{L'utilisateur %s vous autorise à l'ajouter à vos contacts}
::msgcat::mcset fr jamessunsub		{L'utilisateur %s vous a enlevé de ses contacts\
  et n'est plus parmi vos contacts.}
::msgcat::mcset fr jamessunsubpres	{L'utilisateur %s vous a enlevé de ses contacts}
::msgcat::mcset fr jamessunsubask	{L'utilisateur %s vous a enlevé de ses contacts,\
  Voulez-vous enlever %s de vos contacts ?}
::msgcat::mcset fr jamessunsubscribed	{Vous ne faites plus partie des contacts de %s}
::msgcat::mcset fr jamesserrpres	{Il y a une erreur du statut "Présence",\
  Le code de l'erreur est %s (%s)}
::msgcat::mcset fr jamessautoaccepted	{Vous avez automatiquement accepté une requête\
  d'autorisation de la part de %s}
::msgcat::mcset fr jamessautoreject	{Vous avez automatiquement rejeté une requête\
  d'autorisation de la part de %s}
::msgcat::mcset fr jamessautosubs	{Vous avez automatiquement ajouté %s\
  à la liste de vos contacts}


::msgcat::mcset fr jamessconnbroken	{La connexion a été inopinément coupée}
::msgcat::mcset fr jamessautoawayset 	{Le statut "Départ automatique" a été envoyé à %s. Voulez-vous de nouveau apparaître comme "Disponible" ?}
::msgcat::mcset fr jamesserrgetpublic	{Erreur lors de la demande des données publiques de %s, le code de l'erreur est %s (%s)}
::msgcat::mcset fr jamesserrlastactive	{Erreur lors de la demande de la dernière activité de %s, le code de l'erreur est %s (%s)}
::msgcat::mcset fr jamesserrnotimeinfo	{Le client/service %s n'a pas retourné l'information de temps.}
::msgcat::mcset fr jamesstimeused	{Temps écoulé depuis la dernière activité de %s : }
::msgcat::mcset fr jamesstimeconn	{Temps écoulé depuis la dernière connexion de %s : }
::msgcat::mcset fr jamesstimeservstart	{Temps écoulé depuis le démarrage du serveur "%s" : }
::msgcat::mcset fr jamessuptime		{L'uptime (pour les services) ou la dernière activité de l'utilisateur est : }
::msgcat::mcset fr jamesserrtime	{Erreur lors de la demande d'heure à %s (%s).}
::msgcat::mcset fr jamesslocaltime	{L'heure locale de %s est : %s}
::msgcat::mcset fr jamesserrvers	{Erreur lors de la demande de version à %s (%s).}
::msgcat::mcset fr jamesserrautoupdate 	{Erreur lors de la demande de mise-à-jour du serveur à %s (%s).}
::msgcat::mcset fr jamesswarberasewb	{Voulez-vous d'abord effacer le tableau ?}
::msgcat::mcset fr jamesswarnremove	{Enlever un outil de votre liste de contacts peut être annulée. Vous devez vous réinscrire auprès de l'utilisateur si vous voulez l'ajouter de nouveau.\
  Voulez-vous tout de même continuer ?}
::msgcat::mcset fr jamessillegalchar	{Le(s) caractère(s) illégal(aux) dans %s sont : "%s" !}
::msgcat::mcset fr jamessbadjid		{Le JID "%s" est mal configuré. Voulez-vous tout de même continuer ?}
::msgcat::mcset fr jamessalreadyinrost	{Le JID "%s" est déjà dans votre liste de contacts. Voulez-vous tout de même continuer ?}
::msgcat::mcset fr jamessfailsetnick	{Erreur lors de l'attribution du pseudo ou du nom de groupe "%s". Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessnamemissing	{%s manque ou est trop court !}
::msgcat::mcset fr jamessnosocket	{Impossible de créer le serveur "%s". Peut-être que le réseau ne fonctionne pas ou que le serveur est inutilisable (%s).}
::msgcat::mcset fr jamesstimeoutserver	{Temps écoulé lors de l'accession au serveur "%s".}
::msgcat::mcset fr jamessregisterok	{L'enregistrement au serveur "%s" a fonctionné. Il ne vous reste plus qu'à vous connecter avec les mêmes noms d'utilisateur et mot de passe.}
::msgcat::mcset fr jamessremoveaccount	{Vous êtes sur le point de supprimer votre compte du serveur ; cette opération ne peut pas être annulée. Voulez-vous continuer ?}
::msgcat::mcset fr jamesserrunreg	{Erreur lors de la désinscription de "%s". Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessokunreg	{Vous n'êtes plus inscrit sur "%s".}
::msgcat::mcset fr jamesspasswddiff	{Les mots de passe ne correspondent pas. Veuillez recommencer.}
::msgcat::mcset fr jamesspasswderr	{L'enregistrement du nouveau mot de passe n'a pas fonctionné. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamesspasswdok	{Le nouveau mot de passe est enregistré.}
::msgcat::mcset fr jamessregnoserver	{Le serveur doit être configuré.}
::msgcat::mcset fr jamesserrregget	{La récupération des informations d'inscription a échoué. Code de l'erreur : %s (%s)}
::msgcat::mcset fr jamesserrregset	{L'inscription au service "%s" a échoué. Code de l'erreur : %s (%s)}
::msgcat::mcset fr jamessokreg		{L'inscription au service "%s" a été réalisée.}
::msgcat::mcset fr jamessinvalidjid	{Le JID est mal configuré. Vérifiez tout d'abord que la case en bas du tableau contient une adresse correcte, elle doit être de la forme "contact@jabber.org".}
::msgcat::mcset fr jamessnotconnected	{Vous devez vous connecter au serveur pour envoyer !}
::msgcat::mcset fr jamessaddrmiss	{Vous devez renseigner au moins une adresse correcte.}
::msgcat::mcset fr jamesschatclose	{Si vous fermez cette fenêtre, vous perdrez la conversation en cours. Voulez-vous tout de même la fermer ?}
::msgcat::mcset fr jamessnogroupchat	{Aucun service du groupe de discussion n'est reconnu.}
::msgcat::mcset fr jamessgcnoroomname   {Vous devez fournir un nom de salon.}
::msgcat::mcset fr jamessgcnoroomnick   {Vous devez fournir un pseudo.}
::msgcat::mcset fr jamessinroommiss	{Tous les champs doivent être renseignés avant d'entrer dans le salon.}
::msgcat::mcset fr jamesswarnexitroom	{Voulez-vous quitter le salon %s ?}
::msgcat::mcset fr jamesserrbrowse	{Erreur lors de la navigation dans "%s": %s}
::msgcat::mcset fr jamessenterroomempty	{Le nom du serveur et du salon doivent être indiqués correctement.}
::msgcat::mcset fr jamesserrconfget	{La récupération des infos concernant l'entrée dans le salon a échoué. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamesserrconfgetcre	{La récupération des infos concernant la création du salon a échoué. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessinroomerasewb 	{Voulez-vous effacer le tableau avant d'entrer dans le salon ?}
::msgcat::mcset fr jamessconffailed	{Erreur lors de l'entrée/la création du salon. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessconfservempty	{Le serveur doit être configuré avec un nom correct.}
::msgcat::mcset fr jamesserragentget	{Erreur lors de la récupération des agents : %s}
::msgcat::mcset fr jamesserrsearch	{Erreur lors des spécifications de la recherche. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessoobok		{Transfert de fichiers effectué.}
::msgcat::mcset fr jamessoobok2         {Transfert de %s à %s effectué.}
::msgcat::mcset fr jamessoobnourl	{Lors de la demande de téléchargement effectuée par, aucune URL n'a été spécifiée.}
::msgcat::mcset fr jamessoobask		{L'utilisateur %s à mis à votre disposition un fichier sur %s. %s Voulez-vous la télécharger ?}
::msgcat::mcset fr jamessoobbad		{L'URL de "%s" n'est pas correcte. (URL : "%s").}
::msgcat::mcset fr jamessoonnohttp	{L'URL de "%s" n'utilise pas le protocole "HTTP", mais "%s" (non supporté).}
::msgcat::mcset fr jamessoobfailopen	{L'ouverture de "%s" a échoué.}
::msgcat::mcset fr jamessoobgetfail	{L'URL "%s" n'est pas accessible (%s).}
::msgcat::mcset fr jamessoobtimeout	{Temps écoulé lors de l'accession au fichier via HTTP}
::msgcat::mcset fr jamessooberr406      {L'utilisateur %s a refusé le fichier %s.}
::msgcat::mcset fr jamessooberr404      {Erreur lors de l'envoi du fichier %s à %s. Le code était %s, et le message d'erreur "%s"}
::msgcat::mcset fr jamesserrinboxopen	{Erreur de l'ouverture du courrier entrant %s lors de la sauvegarde.}
::msgcat::mcset fr jamesserrinboxread	{Erreur lors de la lecture du message dans la boîte Jabber "%s" : %s}
::msgcat::mcset fr jamesschatclose	{Si vous fermez cette fenêtre, vous perdrez toute la conversation. Voulez-vous continuer ?}
::msgcat::mcset fr jamessgchatfields	{Tous les champs doivent être renseignés avant d'entrer dans le salon.}
::msgcat::mcset fr jamessconfmsg	{Choisissez un service de conférence et un nom de salon. Cliquez ensuite sur "Recevoir" pour obtenir les spécifications d'entrée\
  dans le salon désiré (chaque salon peut avoir ses propres spécifications).}
::msgcat::mcset fr jamesssavemsg	{Voulez-vous enregistrer le message ?}
::msgcat::mcset fr jamessskipsendq	{L'adresse "%s" est incorrecte. Voulez-vous envoyer aux autres ?}
::msgcat::mcset fr jamessillformresend	{L'adresse "%s" est incorrecte. Modifiez-la pour envoyer à nouveau.}
::msgcat::mcset fr jamesslogin409	{La connexion a échoué avec le code d'erreur %s (Ce nom d'utilisateur est déjà utilisé).\
  Si c'est vous qui utilisez ce nom, tentez plutôt de vous connecter.}
::msgcat::mcset fr jamessloginerr	{La connexion a échoué. Code de l'erreur : %s (%s).}
::msgcat::mcset fr jamessaddforeign	        {L'ajout d'un utilisateur inscrit à un système de messagerie différent de Jabber nécessite que vous ayez déjà un compte sur ce système, et que\
  vous ayez utilisé ce compte pour l'enregistrement au serveur de transport correspondant (%s). Voulez-vous faire cela maintenant ?}
::msgcat::mcset fr jamessowntrpt	        {Votre propre compte sur %s joue le rôle du service qui transporte vos messages à ce système de messagerie.\
  Il est nécessaire qu'il soit dans votre liste de contacts. Vous êtes enregistré auprès de %s : %s.}
::msgcat::mcset fr jamesswbchatlost	        {La discussion entière sera perdue si vous fermez le tableau. Voulez-vous terminer la conversation ?}
::msgcat::mcset fr jamesschatoffline            {Cet utilisateur n'est plus en ligne, le message n'est donc pas envoyé.}
::msgcat::mcset fr jamessregloginok             {Vous êtes maintenant identifié et automatiquement connecté en tant que "%s"}
::msgcat::mcset fr jamessregerrinuse            {L'inscription a échoué parce que ce nom est déjà employé par un autre utilisateur. Si vous êtes cet utilisateur,\
  essayez plutôt de vous connecter. Code de l'erreur : %s}
::msgcat::mcset fr jamessregerr                 {L'inscription a échoué avec le message d'erreur "%s"}
::msgcat::mcset fr jamesstrptsubsc              {Votre compte enregistré avec le service %s sera ajouté à vos contacts pour fonctionner comme un serveur de transport avec le service.}
::msgcat::mcset fr jamessfailedsubsc            {Échec de l'inscription à %s. L'utilisateur a refusé l'inscription.}
::msgcat::mcset fr jamessgcinvite               {Vous avez été invité dans le salon %s par %s. Voulez-vous y aller ?}
::msgcat::mcset fr jamessnorooms		{Impossible de trouver un salon sur %s.}
::msgcat::mcset fr jamesswarnsendcanoff         {The user you are sending to, "%s", is not online, and if this message contains any images or other similar entities, this user will not get them unless\
you happen to be online while this message is being read. Do you want to send it anyway?}

# Translate
::msgcat::mcset fr jamessnofiletrpt             {We couldn't see that %s supports file transfer.}
::msgcat::mcset fr jamessfiletrpterr            {Failed to get file %s from %s: %s}
::msgcat::mcset fr jamessstatuscust             {Set your message for any of the presence states.}
::msgcat::mcset fr jamessstatuscustdtl          {The most frequent states and corresponding messages are easily reachable as menu entries.}
::msgcat::mcset fr jamessproxy-failure          {The proxy server reported an error. The error code is "%s".}

# This maps Defined Error Conditions to clear text messages.
# RFC 3929 (XMPP Core): 6.4 SASL Errors
# 
# These are much too formal to be used for user display and we therfore instead use the short forms below.

::msgcat::mcset fr xmpp-stanzas-aborted             {The receiving entity acknowledges an abort element sent by the initiating entity.}
::msgcat::mcset fr xmpp-stanzas-incorrect-encoding  {The data provided by the initiating entity could not be processed because the [BASE64] encoding is incorrect.}
::msgcat::mcset fr xmpp-stanzas-invalid-authzid     {The authzid provided by the initiating entity is invalid, either because it is incorrectly formatted or because the initiating entity does not have permissions to authorize that ID.}
::msgcat::mcset fr xmpp-stanzas-invalid-mechanism   {The initiating entity did not provide a mechanism or requested a mechanism that is not supported by the receiving entity.}
::msgcat::mcset fr xmpp-stanzas-mechanism-too-weak  {The mechanism requested by the initiating entity is weaker than server policy permits for that initiating entity.}
::msgcat::mcset fr xmpp-stanzas-not-authorized      {The authentication failed because the initiating entity did not provide valid credentials (this includes but is not limited to the case of an unknown username).}
::msgcat::mcset fr xmpp-stanzas-temporary-auth-failure {The authentication failed because of a temporary error condition within the receiving entity.}

# Short messages in place of the above ones.
::msgcat::mcset fr xmpp-stanzas-short-aborted             {The login process was aborted.}
::msgcat::mcset fr xmpp-stanzas-short-incorrect-encoding  {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-invalid-authzid     {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-invalid-mechanism   {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-mechanism-too-weak  {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-not-authorized      {Login failed because of unknown user or wrong password.}
::msgcat::mcset fr xmpp-stanzas-short-temporary-auth-failure {Protocol error during the login process.}


# Related error conditions detected by the client.
::msgcat::mcset fr starttls-nofeature     {Le serveur "%s" ne supporte pas le TLS.}
::msgcat::mcset fr starttls-failure       {Erreur lors de la sécurisation TLS avec le serveur "%s".}
::msgcat::mcset fr sasl-no-mechanisms     {The server has no support for SASL authentication.}
::msgcat::mcset fr sasl-protocol-error    {Authentication failed due to internal protocol error.}

# A collective description of all stream errors.
::msgcat::mcset fr xmpp-streams-error {We received a stream error from the server with code: %s}


# Account xform balloon help.
# From: JEP-0077: In-Band Registration 
::msgcat::mcset fr registration-username        {Account name associated with the user}
::msgcat::mcset fr registration-nick            {Familiar name of the user}
::msgcat::mcset fr registration-password        {Password or secret for the user}
::msgcat::mcset fr registration-name            {Full name of the user}
::msgcat::mcset fr registration-first           {First name or given name of the user}
::msgcat::mcset fr registration-last            {Last name, surname, or family name of the user}
::msgcat::mcset fr registration-email           {Email address of the user}
::msgcat::mcset fr registration-address         {Street portion of a physical or mailing address}
::msgcat::mcset fr registration-city            {Locality portion of a physical or mailing address}
::msgcat::mcset fr registration-state           {Region portion of a physical or mailing address}
::msgcat::mcset fr registration-zip             {Postal code portion of a physical or mailing address}
::msgcat::mcset fr registration-phone           {Telephone number of the user}
::msgcat::mcset fr registration-url             {URL to web page describing the user}
::msgcat::mcset fr registration-date            {Some date (e.g., birth date, hire date, sign-up date)}
::msgcat::mcset fr registration-is-registered   {You are already registered with this service. These are your current settings of your login parameters.}

# Map version info tags to display names.
::msgcat::mcset fr version-name                 {Name}
::msgcat::mcset fr version-version              {Version}
::msgcat::mcset fr version-os                   {Operating system}

::msgcat::mcset fr register-trpt-unreg          {You are about to unregister a transport with a number of dependent users. Do you want to remove these users as well (Yes), keep them (No), or cancel the whole thing (Cancel).}


::msgcat::mcset fr openquicktime		{Ouvrir le streaming QuickTime}
::msgcat::mcset fr writeurl			{Écrire l'URL ou choisir le raccourci : }
::msgcat::mcset fr openquicktimeurlmsg		{Ouvrir l'URL d'un fichier SDP avec l'extension .mov pour un streaming QuickTime. Cela peut être du son (radio) ou de la vidéo (TV).\
  Vous pouvez également utiliser votre navigateur pour trouver le fichier SDP, l'enregistrer sur le disque et l'ouvrir comme une vidéo classique.}
::msgcat::mcset fr printunixcmd                 {Commande d'impression, peut être changée}
::msgcat::mcset fr enterpassword                {Entrez le mot de passe pour le compte "%s"}

# Translate
::msgcat::mcset fr wblockitem                   {Lock this item from being edited}


::msgcat::mcset fr httptrptok                   {Fin du télachargement du fichier %s}
::msgcat::mcset fr httptrpterror                {Erreur de transfert lors du téléchargement du fichier %s : %s}
::msgcat::mcset fr httptrpteof                  {Le serveur a arrêté la connexion sans réponse.}
::msgcat::mcset fr httptrptnon200               {Erreur de transfert lors du téléchargement du fichier %s : code %s ; %s}
::msgcat::mcset fr httptrptreset                {Le transfert du fichier %s a été relancé}


::msgcat::mcset fr uastatpointmac 	{Pointeur (clic : marquer, double clic : inspecter, press : popup)}
::msgcat::mcset fr uastatpoint		{Pointeur (clic : marquer, double clic : inspecter, clic droit : popup)}
::msgcat::mcset fr uastatmove		{Déplacer}
::msgcat::mcset fr uastatline		{Ligne}
::msgcat::mcset fr uastatarrow		{Croix}
::msgcat::mcset fr uastatrect		{Rectangle}
::msgcat::mcset fr uastatoval		{Ellipse}
::msgcat::mcset fr uastattext		{Texte}
::msgcat::mcset fr uastatdel		{Cliquez pour supprimer}
::msgcat::mcset fr uastatpen		{Crayon}
::msgcat::mcset fr uastatbrush		{Brosse}
::msgcat::mcset fr uastatpaint		{Peinture (+ <shift> : transparent)}
::msgcat::mcset fr uastatpoly		{Polygone (<espace> : annuler)}
::msgcat::mcset fr uastatarc		{Arc (clic : définir le centre, <espace> : annuler)}
::msgcat::mcset fr uastatarc2		{Arc (cliquer-déplacer)}
::msgcat::mcset fr uastatrot		{Rotation (d'abord sélectionner les objets)}


# Préférences :
::msgcat::mcset fr prefsounsynwb {Synthèse du texte saisi dans le tableau}
::msgcat::mcset fr prefsounsynno {Synthèse des messages normaux}
::msgcat::mcset fr prefsounsynch {Synthèse des discussions}
::msgcat::mcset fr prefsounvoin  {Choisir une voix pour le texte entrant :}
::msgcat::mcset fr prefsounvoou  {Choisir une voix pour le texte écrit :}
::msgcat::mcset fr prefsounpick  {Choisir les alertes sonores pour les évènements ci-dessous :}
::msgcat::mcset fr prefshortcut  {Ici, vous pouvez ajouter ou modifier les raccourcis applicables uniquement aux connexions peer-to-peer, non utilisées\
  par le système Jabber. Si vous n'avez pas choisi explicitement choisi l'option "peer-to-peer" dans le panneau "Configuration du réseau", ces raccourcis ne seront pas appliqués.}
::msgcat::mcset fr prefprof      {Ici, vous pouvez modifier les options spécifiques aux comptes Jabber. Le serveur que vous indiquez ici est également celui sur lequel vous vous connecterez.}
::msgcat::mcset fr prefpers      {Vos informations personnelles sont enregistrées dans le fichier de vos préférences, mais peuvent également l'être dans le dossier utilisateur Jabber.\
  Les informations enregistrées par le serveur sont accessibles par n'importe quel utilisateur.}
::msgcat::mcset fr prefaaset     {Mettre le statut "Départ automatique" : }
::msgcat::mcset fr prefminaw     {Minutes avant le statut "Absent" : }
::msgcat::mcset fr prefminea     {Minutes avant le statut "Absent pour longtemps" : }
::msgcat::mcset fr prefsuif      {Si quelqu'un veut m'ajouter à ses contacts et...}
::msgcat::mcset fr prefsuis      {...est déjà dans mes contacts : }
::msgcat::mcset fr prefsuisnot   {...ne fait pas partie de mes contacts : }
::msgcat::mcset fr prefsuauto    {S'enregistrer automatiquement chez ceux qui m'enregistrent}
::msgcat::mcset fr prefrorm      {Enlever l'utilisateur s'il n'est pas enregistré}
::msgcat::mcset fr prefroallow   {Autoriser les utilisateurs non-enregistrés}
::msgcat::mcset fr prefroclr     {Nettoyer la liste de contacts à la déconnexion}
::msgcat::mcset fr prefrochat    {Double-clic : discuter, clic : message normal}
::msgcat::mcset fr prefrosysicons {Utiliser les icônes système du protocole de messagerie étranger}
::msgcat::mcset fr prefrohideoff {Ne pas montrer les utilisateurs déconnectés}
::msgcat::mcset fr prefrohidetrpt {Ne pas montrer les transports}
::msgcat::mcset fr prefblonly    {N'accepter que les messages de mes contacts}
::msgcat::mcset fr prefblbl      {Bloquer les JIDs suivants (* étoile pour "tous") : }
::msgcat::mcset fr prefblmsg     {Écrire la JID complète pour les utilisateurs que vous voulez bloquer (les JID sont de la forme "utilisateur@jabber.org)}
::msgcat::mcset fr prefcufont    {Sélectionner la police pour la fenêtre de discussions : }
::msgcat::mcset fr prefcushow    {Montrer les messages dans une nouvelle fenêtre}
::msgcat::mcset fr prefcuautologin  {Se connecter automatiquement au démarrage}
::msgcat::mcset fr prefcusave    {Enregistrer la boîte de courriers entrants entre les sessions}
::msgcat::mcset fr prefcu2clk    {Message du double-clic dans la boîte des messages : }
::msgcat::mcset fr prefcuopen    {Ouvrir le message dans une nouvelle fenêtre}
::msgcat::mcset fr prefcureply   {Répondre à l'expéditeur}
::msgcat::mcset fr prefcudisc    {Méthode "Découverte des services" préférée : }
::msgcat::mcset fr prefcubrowse  {Naviguer dans les services si la méthode est disponible}
::msgcat::mcset fr prefcuagent   {Toujours utiliser la méthode des agents}
::msgcat::mcset fr prefcuupdate  {Chercher automatiquement les mises-à-jour de Coccinella}
::msgcat::mcset fr prefcuremdlgs {Se rappeler les fenêtres ouvertes pour les prochaines sessions}
::msgcat::mcset fr preffmhelp    {Plugins d'aide pour les types de fichiers}
::msgcat::mcset fr preffmsave    {Juste "sauver sur le disque" dans le dossier entrant}
::msgcat::mcset fr preffontmsg   {Attention : en important d'autres polices\
que les polices standard (Times, Helvetica ou Courier), vous devez vous assurer que vos correspondants ont également installé ces polices.}
::msgcat::mcset fr prefcahow     {Comment gérer les fichiers déjà reçus : }
::msgcat::mcset fr prefcanev     {Ne jamais accepter les fichiers en cache, toujours télécharger}
::msgcat::mcset fr prefcaalw     {Toujours accepter les fichiers en cache, ne jamais télécharger} 
::msgcat::mcset fr prefcaor      {...ou accepter les fichiers en cache s'ils ne datent pas de plus de : }
::msgcat::mcset fr prefpriv      {En cochant la case "Confidentialité", vous n'êtes autorisé à modifier que vos propres outils de dessin. Les outils\
  créés par les autres utilisateurs ne sont pas modifiables.}
::msgcat::mcset fr prefshortip   {Compléter l'adresse IP ou le nom}
::msgcat::mcset fr prefshortwa   {Attention : vous avez édité les raccourcis.. Voulez-vous les enregistrer ?}

::msgcat::mcset fr preffilecache {Le cache est utilisé pour garder en local une copie des fichiers des autres utilisateur, ce qui réduit le trafic du réseau. La taille du cache\
  est limitée par l'utilisateur grâce aux paramètres ci-dessous : }
::msgcat::mcset fr prefcachecmp  {Comparer les fichiers du cache avec les fichiers distants}
::msgcat::mcset fr prefnatip     {Utiliser les adresses IP suivantes comme vues de l'extérieur}
::msgcat::mcset fr prefmucconf   {Utiliser les discussions multi-utilisateur avec le retour "conférence"}
::msgcat::mcset fr prefrostbgim  {Utiliser l'image de fond (gif) dans la liste de contacts}
::msgcat::mcset fr preftheme     {Choisir un thème (Coccinella doit être redémarré)}
::msgcat::mcset fr prefplugctrl  {Vous pouvez désélectionner ces paquetages pour ne pas avoir à les charger. Coccinella doit être redémarré pour que les changements soient pris en compte.}
::msgcat::mcset fr prefchactret  {Toujours activer <Entrée> dans la boîte de discussion}
::msgcat::mcset fr prefchnormal  {Traiter les messages normaux comme des messages de discussion}
::msgcat::mcset fr prefprofname  {Entrez le nom du profil d'utilisateur}
::msgcat::mcset fr prefstabui    {Utiliser l'interface du bloc-notes avec les onglets}
::msgcat::mcset fr prefsusesasl  {Utiliser la méthode d'authentification SASL}
::msgcat::mcset fr prefprivmsg {Chaque utilisateur peut administrer aucune ou plusieurs listes. Seule la liste active ou par défaut est affectée. Toute liste active affecte seulement la session. La liste par défaut est concernée seulement si aucune n'est active.}
::msgcat::mcset fr prefprivunav {Options de filtres indisponibles hors-connexion}
::msgcat::mcset fr prefprivnotex {Options de filtres indisponibles sur ce serveur}
::msgcat::mcset fr prefprivobtained {Listes de filtres téléchargées du serveur}
::msgcat::mcset fr prefprivgetlist {Téléchargement de la liste de filtes "%s"}
::msgcat::mcset fr prefprivrules {Chaque liste contient une ou plusieurs lettres, chaque règle spécifie le type d'évènements sur lequel il agit et l'action qu'elle doit effectuer. Si vous spécifiez de bloquer un groupe, il doit exister dans vos contacts.}
::msgcat::mcset fr prefuserinactive {L'utilisateur a été inactif un moment}
::msgcat::mcset fr preficonsel {Le thème d'icônes sera actif après une sauvegarde}
::msgcat::mcset fr prefwbscroll {Vous devez mettre une taille supérieure à celle par défaut %sx%s}
::msgcat::mcset fr prefssbts {Montrer les boutons précédent et suivant}
::msgcat::mcset fr prefssresize {Redimensionner automatiquement le dessin pour l'ajuster à l'image}

#--- Translate!
::msgcat::mcset fr prefavashare {Share this avatar with other users}
::msgcat::mcset fr prefproxymsg {Usage of the Http proxy is determined by each profile settings. File transfers wont work if you use Http proxy!}
::msgcat::mcset fr prefproxyexc {Exclude addresses (* as wildcard)}

::msgcat::mcset fr prefdrivesame {Always store user preferences on same drive as program}
::msgcat::mcset fr prefdriwsame  {You have chosen to store your preferences on the same drive as the application. If this drive is not a removable device your personal settings could be visible.\
  Do you want to continue?}
::msgcat::mcset fr prefdriwdef   {You have chosen to store your preferences in the default place. Unless you also remove or move your personal settings at "%s"\
  it will automatically be used the next time you launch Coccinella. Do you want them removed now?}
#---


# Espace EditShortcuts :
namespace eval ::EditShortcuts:: {
	::msgcat::mcset fr shortip       {Compléter l'adresse IP ou le nom}
	::msgcat::mcset fr shortwarn     {Attention : vous avez édité les raccourcis. Voulez-vous les enregistrer ?}


}


::msgcat::mcset fr jalogin 	{Écrire l'adresse IP ou le nom du serveur Jabber, ou choisir à partir du menu pop-up. Vous devez déjà avoir un compte sur ce serveur.}
::msgcat::mcset fr janewaccount {Écrire l'adresse IP ou le nom du serveur Jabber, choisir un nom d'utilisateur et un mot de passe.}
::msgcat::mcset fr janewpass    {Choisir le mot de passe pour : }
::msgcat::mcset fr jasubwant    {L'utilisateur "%s" veut vous ajouter à ses contacts.}
::msgcat::mcset fr jasubopts    {Choisissez une option ci-dessous. Choisir un pseudo et un groupe est optionnel, pour votre usage personnel seulement.}
::msgcat::mcset fr jasubgetvcard {Voir la carte de visite de cette personne}
::msgcat::mcset fr jasubsndmsg  {Envoyer un message à cette personne : }
::msgcat::mcset fr jasuballow   {Autoriser "%s" à voir ma présence}
::msgcat::mcset fr jasubadd     {Ajouter "%s" à mes contacts}
::msgcat::mcset fr jarostadd	{Ajouter un utilisateur Jabber à mes contacts. Le pseudo et le groupe peuvent être changés à tout moment.\
  Pour ajouter un utilisateur d'un autre système de messagerie, vous devez avoir un compte actif sur ce système qui doit être enregistré sur les serveurs de transport Jabber.}
::msgcat::mcset fr jarostset	{Choisir un pseudo et un groupe à l'utilisateur "%s". Ces informations peuvent être modifiées ultérieurement..}
::msgcat::mcset fr jarostsub	{S'inscrire auprès de cet utilisateur}
::msgcat::mcset fr jarostunsub	{Se désinscrire auprès de cet utilisateur}
::msgcat::mcset fr jasearch	{Rechercher l'utilisateur avec le service spécifié. Cliquer sur le bouton "Recevoir" pour obtenir un nouveau formulaire à remplir.}
::msgcat::mcset fr jasearchwait	{Cliquez sur "Recevoir" lorsque vous êtes prêt}
::msgcat::mcset fr jaservclosed	{Connexion au serveur fermée}
::msgcat::mcset fr jarostupdate {La liste de contacts est à jour}
::msgcat::mcset fr jawaitresp 	{%s est contacté, en attente d'une réponse}
::msgcat::mcset fr jawaitxml 	{Connecté à "%s". Initialisation du flux XML...}
::msgcat::mcset fr jasendauth	{Réponse du serveur "%s". Envoi de la demande d'autorisation.}
::msgcat::mcset fr jaerrlogin	{La connexion à %s a échoué : %s}
::msgcat::mcset fr jaauthok	{Autorisation du serveur "%s" obtenue. Chargement de la liste des contacts...}
::msgcat::mcset fr jagchatmsg	{Choisissez un groupe de discussion et un nom de salon, ainsi que votre pseudo.}
::msgcat::mcset fr jacreateroom	{Sélectionnez un service de conférence et accessoirement un nom de salon. Cliquez ensuite sur "Recevoir" pour obtenir les spécifications pour créer le salon\
  désiré (chaque serveur peut avoir des spécifications différentes).}
::msgcat::mcset fr jawaitserver	{En attente de la réponse du serveur...}
::msgcat::mcset fr jaregmsg	{Enregistrement pour un service spécifique pour ce serveur. Si vous êtes déjà enregistré, vous pouvez perdre des informations personnelles.}
::msgcat::mcset fr jastatavailable {Disponible}
::msgcat::mcset fr jastatchat	{Discussion : disponible pour un contact immédiat}
::msgcat::mcset fr jastataway	{Absent : en ligne, mais inactif depuis un petit moment}
::msgcat::mcset fr jastatxa	{Absent pour longtemps : en ligne, mais inactif depuis un long moment}
::msgcat::mcset fr jastatdnd	{Ne pas déranger}
::msgcat::mcset fr jastatinvisible {Invisible}
::msgcat::mcset fr javersinfo	{Informations de la version de %s}
::msgcat::mcset fr jabrowseaddserver	{Entrer la JID du serveur que vous voulez ajouter à la liste des services (de la forme jabber.org).}
::msgcat::mcset fr jaupdatemsg	{Une nouvelle version de Coccinella est disponible}
::msgcat::mcset fr jaupdatevers	{La version actuelle est : %s}
::msgcat::mcset fr jaupdatepri	{La mise-à-jour est %s}
::msgcat::mcset fr jaupdatenewver {La nouvelle version est : %s}
::msgcat::mcset fr jaupdateremind {Ne plus me rappeler cela}
::msgcat::mcset fr jasettopic2  {Mettre un nouveau titre à ce salon.}
::msgcat::mcset fr jadirpresmsg {Envoyer le statut désiré à l'utilisateur "%s".}
::msgcat::mcset fr jatlsnegot   {Sécurisation TLS...}
::msgcat::mcset fr jamucentermsg {Tapez votre pseudo et appuyez sur Entrée pour entrer dans le salon. Vous pouvez Parcourir pour trouver la liste des salons chaque service. Les salons privés peuvent vous demander un mot de passe.}
::msgcat::mcset fr jainmsgshow {Montrer les messages entrants dans cette fenêtre}
::msgcat::mcset fr jadisaddserv {Découvrir un autre serveur pour les salons de discussions et autres services. Vous pouvez ajouter un serveur définitivement quand il est découvert automatiquement. Le serveur de connexion est automatiquement découvert.}
::msgcat::mcset fr jadisrmall {Enlever les serveurs qui étaient automatiquement et définitivement découverts.}
::msgcat::mcset fr jauserinnote {Ajouter vos notes personnelles sur cet utilisateur}
::msgcat::mcset fr jaregisterex {Indiquez le nom du serveur Jabber sur lequel vous voulez vous enregistrer. Cliquez ensuite su le bouton Recevoir pour obtenir les informations d'inscription. Remplissez ces informations et inscrivez-vous.}
::msgcat::mcset fr jaloginjid   {Entrez votre adresse ("joey@myjabb.org" par exemple) ou choisissez un profil. Vous devez déjà avoir un compte sur ce serveur.}
::msgcat::mcset fr jaregalready {Vous êtes déjà inscrit à ce service. Voici vos paramètres actuels d'inscription.}
::msgcat::mcset fr jaactiveret {Si coché, la touche Entrée envoie les messages ; sinon Ctrl/Cmd-Entrée}
::msgcat::mcset fr jainvitegchat {Inviter un utilisateur à discuter dans le salon %s}
::msgcat::mcset fr jaxformreq   {Paramètres avec (*) requis}
::msgcat::mcset fr jagcsyncpres {Mettre à jour la liste des personnes sur le salon}

#--- Translate ---
::msgcat::mcset fr jaseliconset {Select iconsets to be used for each group. Each group may be deselected.}
::msgcat::mcset fr jaloginuser {Enter your username and password to login to %s.}
::msgcat::mcset fr jaregnewwith {Do you want to register a new account with %s.}
::msgcat::mcset fr jaregisterexserv {Register with the service %s. You may need to press the Get button if not registration info obtained automatically.}
::msgcat::mcset fr jachathist {Show or hide the chat history}
::msgcat::mcset fr jawaitdisco {Waiting for disco result...}
::msgcat::mcset fr jagclogoutmsg {You have logged out and exited the room}
::msgcat::mcset fr jagcreqnick  {Please enter your desired nick name for the room %s}
::msgcat::mcset fr InfoRoomDesc {This dialog makes available a number of options and actions for a room. Your role and affiliation determines your privilege to act. Further restrictions may exist depending on specific room configuration.}
#--- Translate ---

# Assistant de configuration :
::msgcat::mcset fr suintro1 	{Bienvenue sur l'assistant de configuration qui vous aidera à remplir les informations nécessaires pour un ancien ou nouveau compte sur un serveur Jabber.}
::msgcat::mcset fr suintro2 	{Si vous voulez utiliser le mode peer-to-peer, vous devez juste l'indiquer dans le panneau de préférences et redémarrer Coccinella.}
::msgcat::mcset fr suintro3 	{À tout moment vous pouvez cliquer sur "Précédent" pour revenir en arrière. Suivez les instructions sur chaque page et cliquez sur "Suivant"\
  dès que vous avez terminé.}
::msgcat::mcset fr sulang       {Choisissez votre langue. Si vous changez la langue, les modifications ne seront effectuées que sur les éléments d'interface chargés après la modification.}
::msgcat::mcset fr suservmsg	{Indiquez le nom du serveur Jabber sur lequel vous voulez être enregistré. Si vous avez déjà un compte, indiquez le serveur sur lequel vous êtes inscrit\
  (de la forme jabber.org).}
::msgcat::mcset fr suusermsg	{Indiquez votre nom d'utilisateur et votre mot de passe. Le nom d'utilisateur ne doit pas être utilisé par quelqu'un d'autre sur le serveur spécifié.\
  Si c'est le cas, vous recevrez un message vous l'indiquant lorsque vous tenterez de vous enregistrer.}
::msgcat::mcset fr suregmsg	{Voulez-vous enregistrer votre compte maintenant (si c'est un nouveau compte) ? Vous devez être connecté au réseau (sans firewall).}
::msgcat::mcset fr sufinmsg	{C'est tout ! Quoi qu'il en soit, soyez gentil avec l'insecte ;-)}
::msgcat::mcset fr suheadtxt	{Assistant de configuration de Coccinella}

# Translate
::msgcat::mcset fr supubserv    {Get list of public and open Jabber servers}
::msgcat::mcset fr suservlist   {List of open Jabber servers}

# Groupchat:
::msgcat::mcset fr mucErrEnter      {We got an error when entering room "%s".}
::msgcat::mcset fr mucErrCode       {The error code is %s: %s}
::msgcat::mcset fr mucErrEnterTitle {Error Enter Room}
::msgcat::mcset fr mucErrInvite     {Invitation to %s to join room %s failed.}
::msgcat::mcset fr mucErrInviteCode {Error message: %s}
::msgcat::mcset fr mucInviteText    {You have received an invitation from %s to join a groupchat in the room %s.}
::msgcat::mcset fr mucInviteReason  {The reason: %s}
::msgcat::mcset fr mucInvitePass    {The password "%s" is needed for entry.}
::msgcat::mcset fr mucInviteQuest   {Do you want to join right away?}
::msgcat::mcset fr mucInvite        {Invitation}
::msgcat::mcset fr mucDestroy       {You are about to destroy the room "%s". Optionally you may give any present room participants an alternative room JID and a reason.}
::msgcat::mcset fr mucIQError       {We received an error when interaction with the room "%s": %s}
::msgcat::mcset fr mucChat2ConfInv  {Converting Chat into Conference}


::msgcat::mcset fr vcardget	{Chargement de la carte de visite de l'utilisateur %s.. En attente de la réponse du serveur...}
::msgcat::mcset fr vcarderrget	{Le chargement de la carte de visite a échoué (%s).}
::msgcat::mcset fr vcardrec	{La carte de visite a été reçue.}



::msgcat::mcset fr autoupdatenot        {Ne pas vérifier automatiquement les mises-à-jour}
::msgcat::mcset fr oobmsg               {Laisser l'utilisateur %s télécharger un de vos fichiers sur le serveur. La description est facultative.}

# Translate
# Composing events
::msgcat::mcset fr chatcompreply      {%s rédige une réponse}
::msgcat::mcset fr chatcompactive     {%s is on the chat}
::msgcat::mcset fr chatcompcomposing  {%s is composing a reply}
::msgcat::mcset fr chatcomppaused     {%s is thinking what to write}
::msgcat::mcset fr chatcompinactive   {%s has left the chat for a while}
::msgcat::mcset fr chatcompgone       {%s has closed the chat}

# Réception de fichiers
::msgcat::mcset fr getcontacting   {Contact de %s. En attente d'une réponse...}
::msgcat::mcset fr geteoferr       {La connexion à %s a échoué : réception d'une EOF.}
::msgcat::mcset fr getconnerr      {La connexion à %s a échoué.}
::msgcat::mcset fr getnegotiate    {Client contacté : %s ; négociations en cours...}
::msgcat::mcset fr getreaderr      {Erreur de réponse du serveur %s.}
::msgcat::mcset fr getunknownprot  {Le serveur %s ne répond en utilisant le bon protocole.}
::msgcat::mcset fr getnot200       {Le serveur %s a répondu avec le code %s (%s).}
::msgcat::mcset fr getstarts       {Le client %s a accepté le fichier "%s". Début du transfert...}
::msgcat::mcset fr getended        {Le transfert de %s s'est terminé prématurément.}
::msgcat::mcset fr getfinished     {Le fichier "%s" de %s a été reçu.}
::msgcat::mcset fr getneterr       {Erreur de transfert lors de la réception de %s.}

# Envoi de fichiers
::msgcat::mcset fr putcontacting   {Contact de %s. En attente d'une réponse...}
::msgcat::mcset fr puteoferr       {La connexion à %s a échoué : réception d'une EOF.}
::msgcat::mcset fr putconnerr      {La connexion à %s a échoué.}
::msgcat::mcset fr putnegotiate    {Client contacté : %s ; négociations en cours...}
::msgcat::mcset fr putreaderr      {Erreur de réponse du serveur %s.}
::msgcat::mcset fr putunknownprot  {Le serveur %s ne répond en utilisant le bon protocole.}
::msgcat::mcset fr putnot200       {Le serveur %s a répondu avec le code %s (%s).}
::msgcat::mcset fr putstarts       {Le client %s a accepté le fichier "%s". Début du transfert...}
::msgcat::mcset fr putended        {Le transfert de %s s'est terminé prématurément.}
::msgcat::mcset fr putfinished     {Le fichier "%s" de %s a été reçu.}
::msgcat::mcset fr putneterr       {Erreur de transfert lors de la réception de %s.}

# Translate
# These are specific for phones (VoIP)
::msgcat::mcset fr phoneMakeCall           {Make a call}
::msgcat::mcset fr phoneMakeForward        {Forward current call to...}
::msgcat::mcset fr phoneRing               {Ring, ring...}
::msgcat::mcset fr phoneRingFrom           {Phone is ringing from %s}
::msgcat::mcset fr phoneFailedCalling      {Failed calling %s}
::msgcat::mcset fr phoneDial               {Dial}
::msgcat::mcset fr phoneNumber             {Number}
::msgcat::mcset fr phoneDialerCall         {Call to...}
::msgcat::mcset fr phoneDialerForward      {Forward to...}

::msgcat::mcset fr AddressBook		{Address Book}
::msgcat::mcset fr newAddressbookDlg	{New address book}
::msgcat::mcset fr newAddressbook       {New address book}
::msgcat::mcset fr abName		{Name}
::msgcat::mcset fr abPhone		{Phone number}
::msgcat::mcset fr modifyAddressbookDlg {Modify address book}
::msgcat::mcset fr modifyAddressbook	{Modify address book}
::msgcat::mcset fr mNewAB		{New}
::msgcat::mcset fr mModifyAB		{Modify}
::msgcat::mcset fr mRemoveAB		{Remove}

::msgcat::mcset fr outCall              {Make Call}
::msgcat::mcset fr notifyCall           {Notify Call}
::msgcat::mcset fr inboundCall          {Inbound Call}
::msgcat::mcset fr outboundCall         {Outbound Call}
::msgcat::mcset fr callAnswer           {Answer}
::msgcat::mcset fr callHungUp           {Hung Up}
::msgcat::mcset fr callInfo             {Info}
::msgcat::mcset fr callVM               {Call VM?}

# Fore some of these generic names could be used?
::msgcat::mcset fr iaxPhone             {IAX Phone}
::msgcat::mcset fr iaxPhoneAccount      {IAX Account}
::msgcat::mcset fr iaxPhoneUser         {User}
::msgcat::mcset fr iaxPhonePassword     {Password}
::msgcat::mcset fr iaxPhoneHost         {Host}
::msgcat::mcset fr iaxPhoneCidNum       {Cid Number}
::msgcat::mcset fr iaxPhoneCidName      {Cid Name}
::msgcat::mcset fr iaxPhoneInputDev     {Input Device}
::msgcat::mcset fr iaxPhoneOutputDev    {Output Device}
::msgcat::mcset fr iaxPhoneAGC          {AGC}
::msgcat::mcset fr iaxPhoneAAGC         {AAGC}
::msgcat::mcset fr iaxPhoneNoise        {Noise}
::msgcat::mcset fr iaxPhoneComfort      {Comfort}
::msgcat::mcset fr iaxPhoneCodec        {Codec}

# Messages for Mood PEP
::msgcat::mcset fr mMood Mood
::msgcat::mcset fr mAngry Angry
::msgcat::mcset fr mAnxious Anxious
::msgcat::mcset fr mAshamed Ashamed
::msgcat::mcset fr mBored Bored
::msgcat::mcset fr mCurious Curious
::msgcat::mcset fr mDepressed Depressed
::msgcat::mcset fr mExcited Excited
::msgcat::mcset fr mHappy Happy
::msgcat::mcset fr mInLove {In love}
::msgcat::mcset fr mInvincible Invincible
::msgcat::mcset fr mJealous Jealous
::msgcat::mcset fr mNervous Nervous
::msgcat::mcset fr mSad Sad
::msgcat::mcset fr mSleepy Sleepy
::msgcat::mcset fr mStressed Stressed
::msgcat::mcset fr mWorried Worried

::msgcat::mcset fr moodEvent {Mood change}
::msgcat::mcset fr heIs is
::msgcat::mcset fr because because
::msgcat::mcset fr angry angry
::msgcat::mcset fr anxious anxious
::msgcat::mcset fr ashamed ashamed
::msgcat::mcset fr bored bored
::msgcat::mcset fr curious curious
::msgcat::mcset fr depressed depressed
::msgcat::mcset fr excited excited
::msgcat::mcset fr happy happy
::msgcat::mcset fr in_love {in love}
::msgcat::mcset fr invincible invincible
::msgcat::mcset fr jealous jealous
::msgcat::mcset fr nervous nervous
::msgcat::mcset fr sad sad
::msgcat::mcset fr sleepy sleepy
::msgcat::mcset fr stressed stressed
::msgcat::mcset fr worried worried
::msgcat::mcset fr moodDlg Mood
::msgcat::mcset fr selectCustomMood {Select a mood}
::msgcat::mcset fr moodMessage {Reason for mood}
::msgcat::mcset fr mCustomMood {Custom mood}

# END --------------------------------------------------------------------------

