# English language version of the Coccinella message catalog.
#
# French translation by Guillaume Ayoub (xovni at wanadoo.fr), 2004
#
# Spanish translation from french by Néstor Díaz (nestordiaz at equusdigital.com) 2004
#
# Textos estándar "OK", "Cancelar", etc...
# La cana fuente se usa como mensaje.

::msgcat::mcset es Accept		{Aceptar}
#::msgcat::mcset es Action {}
#::msgcat::mcset es Active {}
::msgcat::mcset es Add			{Añadir}
::msgcat::mcset es Address		{Dirección}
::msgcat::mcset es Advanced		{Avanzado}
::msgcat::mcset es Agents		{Agentes}
#::msgcat::mcset es Allow {}
::msgcat::mcset es Appearance           {Apariencia}
::msgcat::mcset es Apply		{Aplicar}
::msgcat::mcset es Available		{Disponible}
::msgcat::mcset es Away			{Alejado}
::msgcat::mcset es Binary		{Binario}
::msgcat::mcset es Birthday		{Cumpleaños}
#::msgcat::mcset es Block {}
::msgcat::mcset es Blockers		{Bloqueadores}
::msgcat::mcset es Blocking		{Bloqueando}
::msgcat::mcset es Browser		{Navigador}
::msgcat::mcset es Both			{Ambos}
::msgcat::mcset es Buffering		{Buffer}
::msgcat::mcset es Cancel		{Cancelar}
::msgcat::mcset es Change		{Cambiar}
::msgcat::mcset es Chat			{Chat}
::msgcat::mcset es Choose		{Elegir}
::msgcat::mcset es City			{Ciudad}
::msgcat::mcset es Clear		{Limpiar}
#::msgcat::mcset es Client
::msgcat::mcset es Close		{Cerrar}
::msgcat::mcset es Conference		{Conferencia}
::msgcat::mcset es Connect		{Conectarse}
::msgcat::mcset es Connection		{Conexión}
::msgcat::mcset es Contact		{Contacto}
::msgcat::mcset es Contacts             {Contactos}
::msgcat::mcset es Country		{País}
::msgcat::mcset es Create		{Crear}
::msgcat::mcset es Customization	{Personalizar}
::msgcat::mcset es Date			{Fecha}
::msgcat::mcset es Default		{Por defecto}
::msgcat::mcset es Delete		{Eliminiar}
::msgcat::mcset es Deny			{Denegar}
::msgcat::mcset es Department		{Departamento}
::msgcat::mcset es Description		{Descripción}
::msgcat::mcset es Drawing		{Dibujo}
::msgcat::mcset es Document		{Documento}
::msgcat::mcset es Done			{Hecho}
::msgcat::mcset es Edit			{Editar}
::msgcat::mcset es Enter		{Entrar}
::msgcat::mcset es Error		{Error}
::msgcat::mcset es Exit			{Salir}
::msgcat::mcset es File			{Archivo}
::msgcat::mcset es Finish		{Terminar}
::msgcat::mcset es Finished		{Terminado}
::msgcat::mcset es First		{Primero}
::msgcat::mcset es Friends              {Amigos}
::msgcat::mcset es Forward		{Avanzar}
::msgcat::mcset es From			{De}
::msgcat::mcset es General		{General}
::msgcat::mcset es Get			{Recibir}
::msgcat::mcset es Getting		{Recibiendo}
::msgcat::mcset es Group		{Grupo}
::msgcat::mcset es Groupchat            {Grupo de chat}
::msgcat::mcset es Handling		{Ergonomia}
#::msgcat::mcset es Height {}
::msgcat::mcset es History		{Historial}
::msgcat::mcset es Home			{Inicio}
#::msgcat::mcset es Image {}
::msgcat::mcset es Import		{Importar}
::msgcat::mcset es Inbox		{Mensajes}
::msgcat::mcset es Info			{Info}
::msgcat::mcset es Invite		{Invitar}
::msgcat::mcset es Last			{Último}
::msgcat::mcset es Less			{Menos}
::msgcat::mcset es Login		{Conectarse}
::msgcat::mcset es Logout		{Desconectarse}
::msgcat::mcset es Message		{Mensage}
::msgcat::mcset es Middle		{Medio}
::msgcat::mcset es Moderators		{Moderadores}
::msgcat::mcset es More			{Más}
#::msgcat::mcset es Name {}
::msgcat::mcset es Never		{Nunca}
::msgcat::mcset es New			{Nuevo}
::msgcat::mcset es Next			{Siguiente}
::msgcat::mcset es No			{No}
::msgcat::mcset es no			{no}
::msgcat::mcset es None			{Ningún}
#::msgcat::mcset es Notes
::msgcat::mcset es Occupation		{Profesión}
::msgcat::mcset es Offline		{Desconectado}
::msgcat::mcset es OK			{OK}
::msgcat::mcset es Online		{Conectado}
::msgcat::mcset es Open			{Abrir}
::msgcat::mcset es Options		{Opciones}
::msgcat::mcset es Participants		{Participantes}
::msgcat::mcset es Password		{Contraseña}
::msgcat::mcset es Pick			{Elegir}
::msgcat::mcset es Phone		{Teléfono}
::msgcat::mcset es Play			{Jugar}
::msgcat::mcset es Plugins		{Plugins}
::msgcat::mcset es Port			{Puerto}
::msgcat::mcset es Preferences		{Preferencias}
::msgcat::mcset es Previous		{Anterior}
::msgcat::mcset es Print		{Imprimir}
::msgcat::mcset es Priority		{Prioridad}
::msgcat::mcset es Privacy		{Privacidad}
::msgcat::mcset es Profile		{Perfil}
::msgcat::mcset es Profiles		{Perfiles}
::msgcat::mcset es Progress		{Progreso}
::msgcat::mcset es Quit?		{Abandonar?}
::msgcat::mcset es Quote		{Citar}
::msgcat::mcset es Register		{Registrarse}
::msgcat::mcset es Remaining		{Restante}
::msgcat::mcset es Remove		{Borrar}
::msgcat::mcset es Reply		{Responder}
::msgcat::mcset es Resource		{Recursos}
::msgcat::mcset es Room			{Sala}
::msgcat::mcset es Roster		{Contactos}
::msgcat::mcset es Save			{Guardar}
::msgcat::mcset es Search		{Buscar}
::msgcat::mcset es Select               {Elegir}
::msgcat::mcset es Send			{Enviar}
::msgcat::mcset es Server		{Servidor}
::msgcat::mcset es Servers		{Servidores}
::msgcat::mcset es Set			{Instalar}
::msgcat::mcset es Settings		{Opciones}
::msgcat::mcset es Shortcut		{Atajo}
::msgcat::mcset es Shortcuts		{Atajos}
::msgcat::mcset es Sounds		{Sonidos}
::msgcat::mcset es Specifications	{Especificaciones}
::msgcat::mcset es Speech		{Dialogar}
::msgcat::mcset es State		{Estado}
::msgcat::mcset es State/Region		{Estado/Región}
::msgcat::mcset es Stop			{Parar}
::msgcat::mcset es Subject		{Asunto}
::msgcat::mcset es Subscribe		{Subscribirse}
::msgcat::mcset es Subscribed		{Subscrito}
::msgcat::mcset es Subscription		{Subscripción}
::msgcat::mcset es Subscriptions	{Subscripciones}
::msgcat::mcset es Text			{Texto}
::msgcat::mcset es Time			{Hora}
::msgcat::mcset es Timeout		{Fin de tiempo}
::msgcat::mcset es Title		{Título}
::msgcat::mcset es To			{Para}
::msgcat::mcset es Topic		{Tópico}
#::msgcat::mcset es Transports
::msgcat::mcset es Trash		{Basura}
#::msgcat::mcset es Type {}
::msgcat::mcset es Unregister		{Desregistrarse}
::msgcat::mcset es Unsubscribe		{Desubscribirse}
::msgcat::mcset es Unsubscribed		{Desubscrito}
::msgcat::mcset es Username		{Nombre}
#::msgcat::mcset es Value {}
::msgcat::mcset es Visitors		{Visitantes}
::msgcat::mcset es Warning		{Atención}
::msgcat::mcset es Welcome              {Bienvenido}
::msgcat::mcset es Whiteboard		{Pizarra}
#::msgcat::mcset es Width {}
::msgcat::mcset es Work			{Trabajo}
::msgcat::mcset es Yes			{Sí}
::msgcat::mcset es yes			{sí}

# Trazos.
::msgcat::mcset es none			{Ninguno}
::msgcat::mcset es dotted		{Punteado}
::msgcat::mcset es dash-dotted		{Guiones-puntos}
::msgcat::mcset es dashed		{Guiones}

# Status messages.
::msgcat::mcset es available            {disponible}
::msgcat::mcset es away                 {alejado}
::msgcat::mcset es {do not disturb}     {no molestar}
::msgcat::mcset es {not available}      {no disponible}
::msgcat::mcset es {extended away}      {alejado por mucho tiempo}
::msgcat::mcset es invisible            {invisible}
::msgcat::mcset es chat                 {chat}
::msgcat::mcset es subscribed           {subscrito}
::msgcat::mcset es unsubscribed         {desubscrito}


# Titulos de todos los menués ; concatenados con 'm' para la clave de la base de datos.
::msgcat::mcset es mFile		{Archivo}
::msgcat::mcset es mEdit		{Editar}
::msgcat::mcset es mPreferences		{Preferencias}
::msgcat::mcset es mJabber		{Jabber}
::msgcat::mcset es mItems		{Elementos}
::msgcat::mcset es mLibrary		{Biblioteca}
::msgcat::mcset es mInfo		{Información}
::msgcat::mcset es mAddons		{Añadidos}
::msgcat::mcset es mPlugins		{Plugins}

::msgcat::mcset es mAboutWhiteboard   	{Acerca de la pizarra}
::msgcat::mcset es mAboutCoccinella   	{Acerca de Coccinella...}
::msgcat::mcset es mAboutQuickTimeTcl	{Acerca de QuickTimeTcl...}
::msgcat::mcset es mWelcome     	{Bienvenido}
::msgcat::mcset es mNew			{&Nuevo}
::msgcat::mcset es mNewWhiteboard	{Nueva &pizarra}
::msgcat::mcset es mOpenConnection	{&Conectarse...}
::msgcat::mcset es mCloseWindow		{&Cerrar la ventana}
::msgcat::mcset es mStartServer		{Arrancar le &servidor}
::msgcat::mcset es mOpenImage/Movie	{Abrir la &imagen o video...}
::msgcat::mcset es mOpenURLStream	{Arrancar el s&treaming...}
::msgcat::mcset es mPutCanvas		{Insertar un dibujo}
::msgcat::mcset es mGetCanvas		{Importar un dibujo}
::msgcat::mcset es mPutFile		{Insertar un archivo}
::msgcat::mcset es mStopPut/Get/Open	{Parar la inserción o apertura}
::msgcat::mcset es mOpenCanvas		{Abrir un dibujo}
::msgcat::mcset es mSaveCanvas		{Guardar el dibujo}
::msgcat::mcset es mSaveAs		{G&uardar como...}
::msgcat::mcset es mSaveAsItem          {Guarar como objeto...}
::msgcat::mcset es mSaveImageAs         {Guardar la &imagen como...}
::msgcat::mcset es mPageSetup		{&Propiedades de la página...}
::msgcat::mcset es mPrintCanvas		{Imprimir el dibujo}
::msgcat::mcset es mQuit		{&Abandonar}
::msgcat::mcset es mAll			{Seleccionar &todo}
::msgcat::mcset es mEraseAll		{Borrar todo}
::msgcat::mcset es mUndo		{Deshacer}
::msgcat::mcset es mRedo		{Rehacer}
::msgcat::mcset es mCut			{Cortar}
::msgcat::mcset es mCopy		{&Copiar}
::msgcat::mcset es mPaste		{Pegar}
::msgcat::mcset es mInspectItem		{Inspeccionar}
::msgcat::mcset es mRaise		{Elevar}
::msgcat::mcset es mLower		{Bajar}
::msgcat::mcset es mLarger		{Agrandar}
::msgcat::mcset es mSmaller		{Reducir}
::msgcat::mcset es mFlip		{Reflejar}
::msgcat::mcset es mHorizontal		{Horizontal}
::msgcat::mcset es mVertical		{Vertical}
::msgcat::mcset es mImageLarger		{Agrandar la imagen}
::msgcat::mcset es mImageSmaller	{Reducir la imagen}
::msgcat::mcset es mBackgroundColor	{Color de fondo...}
::msgcat::mcset es mGrid		{Rejilla}
::msgcat::mcset es mThickness		{Grosor}
::msgcat::mcset es mBrushThickness	{Grosor de la brocha}
::msgcat::mcset es mFill		{Rellenar}
::msgcat::mcset es mFillColor		{Rellenar con el color...}
::msgcat::mcset es mOutlineColor	{Color del borde}
::msgcat::mcset es mLineSmoothness	{Suavizado de la línea}
::msgcat::mcset es mStraighten   	{Enderezar}
::msgcat::mcset es mArcs		{Arcos}
::msgcat::mcset es mPieslice		{Tartas}
::msgcat::mcset es mChord		{Cuerda}
::msgcat::mcset es mArc			{Arco}
::msgcat::mcset es mDash		{Punteado}
::msgcat::mcset es mShiftConstrain	{Giro}
::msgcat::mcset es mTo90degrees		{Girar 90 grados}
::msgcat::mcset es mTo45degrees		{Girar 45 grados}
::msgcat::mcset es mFont		{Fuente}
::msgcat::mcset es mSize		{Tamaño}
::msgcat::mcset es mWeight		{Tamaño}
::msgcat::mcset es mNormal		{Normal}
::msgcat::mcset es mBold		{Negrita}
::msgcat::mcset es mItalic		{Cursiva}
::msgcat::mcset es mPreferences...	{&Preferencias...}
::msgcat::mcset es mNewAccount		{Nueva cuenta...}
::msgcat::mcset es mLogin		{Conectarse...}
::msgcat::mcset es mLogout		{Desconectarse}
::msgcat::mcset es mLogoutWith          {Desconectarse con el mensaje...}
::msgcat::mcset es mHideMain            {Ocultar}
::msgcat::mcset es mShowMain            {Mostrar}
::msgcat::mcset es mPassword		{&Contraseña...}
::msgcat::mcset es mRoster/Services	{Contactos/servicios}
::msgcat::mcset es mMessageInbox	{Mensajes}
::msgcat::mcset es mSearch		{Busca&r...}
::msgcat::mcset es mAddNewUser		{Añadir un nuevo usuario...}
::msgcat::mcset es mSendMessage		{En&viar un mensaje...}
::msgcat::mcset es mChat		{Chat}
::msgcat::mcset es mStatus		{Estado}
::msgcat::mcset es mDirStatus           {Estado deseado}
::msgcat::mcset es mAvailable		{Disponible}
::msgcat::mcset es mAway		{Alejado}
::msgcat::mcset es mDoNotDisturb	{No molestar}
::msgcat::mcset es mNotAvailable	{No disponible}
::msgcat::mcset es mExtendedAway        {Alejado por mucho tiempo}
::msgcat::mcset es mInvisible           {Invisible}
::msgcat::mcset es mAttachMessage	{Adjuntar mensaje...}
::msgcat::mcset es mEnterRoom		{Entrar en la sala...}
::msgcat::mcset es mExitRoom		{Salir de la sala}
::msgcat::mcset es mCreateRoom		{Crear una sala...}
::msgcat::mcset es mvCard		{Tarjeta de visita...}
::msgcat::mcset es mRemoveAccount	{Borrar una cuenta}
::msgcat::mcset es mErrorLog		{Mesnages de error...}
::msgcat::mcset es mDebug		{Debug}
::msgcat::mcset es mOnServer		{Acerca de servidor...}
::msgcat::mcset es mOnClients		{Acerca de los clientes...}
::msgcat::mcset es mOnPlugins		{Acerca de los plugins...}
::msgcat::mcset es mHelpOn		{Ayuda}
::msgcat::mcset es mNetworkSetup	{Propiedades de red}
::msgcat::mcset es mServers		{Servidores}
::msgcat::mcset es mJabberTransport	{Transporte Jabber}
::msgcat::mcset es mSmileyLegend	{Leyenda de las caritas}
::msgcat::mcset es mSetupAssistant	{&Asistente de configuración}
::msgcat::mcset es mImageLarger		{Agrandar la imagen}
::msgcat::mcset es mImageSmaller	{Reducir la imagen}
::msgcat::mcset es mExportImage		{Exportar la imagen...}
::msgcat::mcset es mExportMovie		{Exportar la video...}
::msgcat::mcset es mSyncPlayback	{Lectura sincronizada}
::msgcat::mcset es mColor		{Color...}
::msgcat::mcset es mAddSpeechBubble	{Añadir un bocadillo}
::msgcat::mcset es mUpdateCheck  	{Comprobar actualizaciones}
::msgcat::mcset es mReloadImage  	{Recargar la imagen}
::msgcat::mcset es mCoccinellaHome  	{Inicio de Coccinella...}
::msgcat::mcset es mComponents          {Componentes...}
::msgcat::mcset es mBugReport           {Informar de un fallo...}
#::msgcat::mcset es mTakeSnapShot        {Take Snapshot}
#::msgcat::mcset es mTimeCode            {Timecode}
#::msgcat::mcset es mUserInfo            {User Info...}


# Popups.
::msgcat::mcset es mMessage     	{Mensage...}
::msgcat::mcset es mWhiteboard     	{Pizarra...}
::msgcat::mcset es mLastLogin/Activity  {Última conexión/actividad}
::msgcat::mcset es mEditUser     	{Editar el usuario...}
::msgcat::mcset es mRemoveUser     	{Borrar el usuario...}
::msgcat::mcset es mRefreshRoster     	{Refrescar la lista de contactos}
::msgcat::mcset es mVersion     	{Versión}
::msgcat::mcset es mRegister     	{Registrarse}
::msgcat::mcset es mUnregister     	{Desregistrarse}
::msgcat::mcset es mRefresh     	{Refrescar}
::msgcat::mcset es mAddServer     	{Añadir un servidor...}
::msgcat::mcset es mLocalTime     	{Hora local...}
::msgcat::mcset es mSendFile     	{Enviar un mensaje...}
::msgcat::mcset es mChatHistory     	{Historial del chat}
::msgcat::mcset es mLoginTrpt     	{Conectarse a un servidor de transporte}
::msgcat::mcset es mLogoutTrpt     	{Desconectarse de un servidor de transporte}
::msgcat::mcset es mRemoveContact  	{Borrar el contacto...}



# Textos cortos únicamente.
::msgcat::mcset es {30 days}			{30 días}
::msgcat::mcset es {About Coccinella}		{Acerca de Coccinella}
::msgcat::mcset es {About Whiteboard}		{Acerca de la pizarra}
::msgcat::mcset es {About QuickTimeTcl}		{Acerca de QuickTimeTcl}
::msgcat::mcset es {About %s}                   {Acerca de %s}
::msgcat::mcset es {Active <Return>}		{Enviar automático}
::msgcat::mcset es {Add New User}		{Añadir un nuevo usuario}
#::msgcat::mcset es {Add permanently} {}
::msgcat::mcset es {Add Server}			{Añadir un servidor}
::msgcat::mcset es {Add Shortcut}		{Añadir un atajo}
::msgcat::mcset es {Address 1}			{Dirección 1}
::msgcat::mcset es {Address 2}			{Dirección 2}
::msgcat::mcset es {Advanced Setup}		{Preferencias avanzadas}
::msgcat::mcset es {Advanced Configuration}	{Configuración avanzada}
::msgcat::mcset es {Alert sounds}		{Sonidos de alerta}
::msgcat::mcset es {As text}			{Como texto}
::msgcat::mcset es {Ask each time}		{Preguntar cada vez}
::msgcat::mcset es {Auto Away}			{Alejado automático}
::msgcat::mcset es {Auto Connect}		{Conexión automática}
::msgcat::mcset es {Auto-accept}		{Accepter automáticamente}
::msgcat::mcset es {Auto-reject}		{Rechazar automáticamente}
::msgcat::mcset es {Away status}		{Estado "Alejado"}
::msgcat::mcset es {Basic Info}			{Información básica}
::msgcat::mcset es {Block JID}			{Bloqueo JID}
::msgcat::mcset es {Built in server port}	{Puerto del servidor interno}
::msgcat::mcset es {Cache folder}		{Directorio de caché}
#::msgcat::mcset es {Canvas Size} {}
::msgcat::mcset es {Chat History}		{Historial del chat}
::msgcat::mcset es {Chat With}			{Chatear con}
::msgcat::mcset es {Clear Disk Cache Now}	{Limpiar la caché}
::msgcat::mcset es {Company Name}		{Nombre de la empresa}
::msgcat::mcset es {Component Info}		{Infos del componente}
::msgcat::mcset es {Conference server}		{Servidor de conferencia}
::msgcat::mcset es {Contact Type}		{Tipo de contacto}
::msgcat::mcset es {Create Room}		{Crear una sala}
::msgcat::mcset es {Default group}		{Grupo por defecto}
::msgcat::mcset es {Default Logout Status}	{Desconexión por defecto}
#::msgcat::mcset es {Delete Rule} {}
::msgcat::mcset es {Disk Cache}			{Caché}
::msgcat::mcset es {Different Passwords}        {Contraseñas distintas}
::msgcat::mcset es {Do Not Disturb}		{No molestar}
::msgcat::mcset es {Edit Fonts}			{Editar las fuentes}
::msgcat::mcset es {Edit Item}			{Editar el objeto}
::msgcat::mcset es {Edit Shortcut}		{Editar el atajo}
::msgcat::mcset es {Edit Shortcuts}		{Editar los atajos}
::msgcat::mcset es {Edit User}			{Editar el usuario}
::msgcat::mcset es {Email address}		{Dirección email}
::msgcat::mcset es {Email addresses}		{Direcciones email}
::msgcat::mcset es {Empty Fields}		{Campos libres}
::msgcat::mcset es {Enter/Create Room}		{Entrar/Crear una sala}
::msgcat::mcset es {Enter Room}			{Entrar en una sala}
::msgcat::mcset es {Every time}			{Cada vez}
::msgcat::mcset es {Extended Away status}	{Estado "Alejado por mucho tiempo"}
::msgcat::mcset es {Factory Settings}		{Propiedades por defecto}
::msgcat::mcset es {Fatal Error}		{Error fatal}
::msgcat::mcset es {File Cache}			{Caché}
::msgcat::mcset es {File coding}		{Codificación de los archivos}
::msgcat::mcset es {File Mappings}		{Mapeado de los archivos}
::msgcat::mcset es {File suffixes}		{Extensión de los archivos}
::msgcat::mcset es {File Transfer}		{Transferencia de archivos}
::msgcat::mcset es {File Transfer Error}	{Error en la transferencia}
::msgcat::mcset es {First name}			{Nombre}
::msgcat::mcset es {Font size}			{Tamaño de la fuente}
::msgcat::mcset es {Font weight}		{Grosor de la fuente}
::msgcat::mcset es {Format mm/dd/yyyy}		{Formato mm/jj/aaaa}
::msgcat::mcset es {Get File}			{Ver el archivo}
::msgcat::mcset es {Get File Error}		{Error durante recepción del archivo}
::msgcat::mcset es {Get vCard}			{Ver la tarjeta}
::msgcat::mcset es {Group chat in room}		{Agrupar el chat en la sala}
::msgcat::mcset es {Groupchat-1.0 (fallback)}	{Groupchat 1.0 (fallback)}
::msgcat::mcset es {Handled By}			{Manejado por}
::msgcat::mcset es {Host name}			{Nombre de dominio}
::msgcat::mcset es {HTTP port}			{Puerto HTTP}
::msgcat::mcset es {Import using}		{Importar usando...}
::msgcat::mcset es {Import/Remove fonts}	{Importar/Borrar fuentes}
::msgcat::mcset es {Incoming Message}		{Mesnage entrante}
#::msgcat::mcset es {Incoming Messages} {}
#::msgcat::mcset es {Incoming Presence} {}
::msgcat::mcset es {Inspect Associations}	{Inspeccionar las asociaciones}
::msgcat::mcset es {IP address}			{Dirección IP}
#::msgcat::mcset es {Is connected} {}
::msgcat::mcset es {Is conectad}		{Conectado}
::msgcat::mcset es {Is safe}			{Seguro}
::msgcat::mcset es {Is server up}		{Conectado}
::msgcat::mcset es {Jabber address}		{Dirección Jabber}
::msgcat::mcset es {Jabber Client}		{Client Jabber}
::msgcat::mcset es {Jabber Server}		{Servidor Jabber}
::msgcat::mcset es {Jabber server port}		{Puerto del servidor Jabber}
::msgcat::mcset es {Jabber user id}		{Identificación del usuario Jabber}
::msgcat::mcset es {Jabber Id}			{Identificación Jabber}
::msgcat::mcset es {JID to block}		{JID a bloquear}
::msgcat::mcset es {Last Activity}		{Última actividad}
::msgcat::mcset es {Last name}			{Nombre}
::msgcat::mcset es {Launch time}		{Hora de ejecución}
::msgcat::mcset es {Local Time}			{Hora local}
::msgcat::mcset es {Logout With Message}        {Desconectarse con el mensaje}
::msgcat::mcset es {Logged out}                 {Desconectado}
::msgcat::mcset es {Login as invisible}		{Conectarse con el estado "Invisible"}
::msgcat::mcset es {Mailbox Error}		{Error de buzón}
::msgcat::mcset es {MIME type}			{Tipo MIME}
::msgcat::mcset es {Multi Connect}		{Conexiones múltiples}
::msgcat::mcset es {My Status}			{Mi estado}
#::msgcat::mcset es {Name of list} {}
::msgcat::mcset es {Network Error}		{Error de Red}
::msgcat::mcset es {Network Setup}		{Configuración de red}
::msgcat::mcset es {New Account}		{Nuevo usuario}
::msgcat::mcset es {New chat message}		{Nuevo mensaje en el chat}
::msgcat::mcset es {New chat thread}		{Nuevo chat}
::msgcat::mcset es {New Color}			{Nuevo color}
::msgcat::mcset es {New incoming message}	{Nuevo mensaje entrante}
::msgcat::mcset es {New Message}		{Nuevo mensaje}
#::msgcat::mcset es {New Nickname} {}
::msgcat::mcset es {New password}		{Nueva contraseña}
#::msgcat::mcset es {New Rule} {}
::msgcat::mcset es {New Topic}			{Nuevo tópico}
::msgcat::mcset es {New shortcut}		{Nuevo atajo}
::msgcat::mcset es {New User}			{Nuevo usuario}
::msgcat::mcset es {New Version}		{Nueva versión}
::msgcat::mcset es {My vCard}			{Mi tarjeta}
::msgcat::mcset es {NAT Address}		{Dirección NAT}
::msgcat::mcset es {Nick name}			{Alias}
::msgcat::mcset es {No Address}			{Sin dirección}
::msgcat::mcset es {No Inbox}			{Sin buzón}
::msgcat::mcset es {No Printing}		{Sin impresión}
::msgcat::mcset es {Not Available}		{No disponible}
::msgcat::mcset es {Not available}		{No disponible}
::msgcat::mcset es {Not Connected}		{Desconectado}
::msgcat::mcset es {Once per session}		{Una vez por sesión}
::msgcat::mcset es {One hour} 			{Una hora}
::msgcat::mcset es {One day} 			{Un día}
::msgcat::mcset es {One week}	 		{Una semana}
::msgcat::mcset es {Open Canvas}		{Abrir dibujo}
::msgcat::mcset es {Open Failed}		{Fallo al abrir}
::msgcat::mcset es {Open Helpfile}		{Abrir el archivo de ayuda}
::msgcat::mcset es {Open Image/Movie}		{Abrir imagen/vídeo}
::msgcat::mcset es {Open Stream}		{Abrir streaming}
#::msgcat::mcset es {Outgoing Presence} {}
::msgcat::mcset es {Peer-to-Peer}		{Punto-a-punto}
::msgcat::mcset es {Personal Info}		{Información personales}
::msgcat::mcset es {Personal Information}	{Información personales}
::msgcat::mcset es {Personal URL}		{URL personal}
::msgcat::mcset es {Pick Directory}		{Elegir un directorio}
::msgcat::mcset es {Pick File}			{Elegir un archivo}
::msgcat::mcset es {Plugin Info}		{Información sobre el plugin}
::msgcat::mcset es {Plugin Control}		{Control del plugin}
::msgcat::mcset es {Port number}		{Número de puerto}
::msgcat::mcset es {Postal Code}		{Código postal}
::msgcat::mcset es {Preferred Protocol}		{Protocolo preferido}
::msgcat::mcset es {Presence Error}		{Error de estado}
#::msgcat::mcset es {Privacy List} {}
::msgcat::mcset es {Profile Name}               {Nombre del perfil}
::msgcat::mcset es {Proxy Setup}		{Configuración del proxy}
::msgcat::mcset es {Put File Error}		{Error al insertar el archivo}
::msgcat::mcset es {Put Image/Movie}		{Insertar imagen/vídeo}
::msgcat::mcset es {Reject receive}		{Rechazar la recepción}
::msgcat::mcset es {Request To User}		{Pedir al usuario}
::msgcat::mcset es {Retype password}		{Reescribir la contraseña}
::msgcat::mcset es {Revert Panel}		{Deshacer los cambios}
::msgcat::mcset es {Register New Account}	{Registrar una nueva cuenta}
::msgcat::mcset es {Register Now}		{Registrarse ahora}
::msgcat::mcset es {Register Service}		{Servicio de registro}
::msgcat::mcset es {Remove Item}		{Borrar el objeto}
::msgcat::mcset es {Room name}			{Nombre de la sala}
::msgcat::mcset es {Room name (optional)}	{Nombre de la sala (opcional)}
::msgcat::mcset es {Roster & Services}		{Contactos y servicios}
::msgcat::mcset es {Save As}			{Guardar como}
::msgcat::mcset es {Save As GIF}		{Guardar como GIF}
::msgcat::mcset es {Save Canvas}		{Guardar el dibujo}
::msgcat::mcset es {Save File}			{Guardar el archivo}
::msgcat::mcset es {Save Message}		{Guardar el mensaje}
::msgcat::mcset es {Scramble password}		{Ocultar contraseña}
::msgcat::mcset es {Search results}		{Buscar resultados}
::msgcat::mcset es {Search Service}		{Buscar servicio}
::msgcat::mcset es {Search Specifications}	{Buscar especificaciones}
#::msgcat::mcset es {Select a new nickname} {}
::msgcat::mcset es {Select Font}		{Elegir fuente}
::msgcat::mcset es {Send File}			{Enviar archivo}
::msgcat::mcset es {Send Live}			{Enviar en directo}
::msgcat::mcset es {Server Info}		{Información sobre el servidor}
::msgcat::mcset es {Service server}		{Servidor de servicios}
::msgcat::mcset es {Set Directed Presence}      {Aplicar el estado deseado}
#::msgcat::mcset es {Set New Nickname} {}
::msgcat::mcset es {Set New Topic}		{Elegir nuevo tópico}
::msgcat::mcset es {Set Status}			{Elegir estado}
::msgcat::mcset es {Settings Panels}		{Paneles de configuración}
::msgcat::mcset es {Setup Assistant}		{Asistente de configuración}
::msgcat::mcset es {Slide Show}			{Presentación}
::msgcat::mcset es {Slide Show Folder}		{Directorio para las Presentaciones}
::msgcat::mcset es {Software Update}		{Actualización del programa}
::msgcat::mcset es {Sounds & Speech}		{Sonidos e idioma}
::msgcat::mcset es {Start Chat}			{Comenzar chat}
::msgcat::mcset es {Status message}		{Mensage de estado}
::msgcat::mcset es {Status when logging out}	{Estado durante la desconexión}
::msgcat::mcset es {Subscription Failed}	{Fallo de registro}
::msgcat::mcset es {Subscription Pending}	{Registro pendiente}
::msgcat::mcset es {Synthetic speech}		{Idioma sintetizado}
::msgcat::mcset es {System fonts}		{Fuentes del sistema}
::msgcat::mcset es {Take Snapshot}		{Capturar la pantalla}
::msgcat::mcset es {Tel (voice)}		{Teléfono}
::msgcat::mcset es {Tel (fax)}			{Fax}
::msgcat::mcset es {This IP number}		{Está dirección IP}
::msgcat::mcset es {Thread started}		{Hilo empezado}
::msgcat::mcset es {To/from JID}		{Para/Desde JID}
::msgcat::mcset es {To Jabber id}		{Para el ID Jabber}
::msgcat::mcset es {To Send or Not}		{Enviar o no}
::msgcat::mcset es {Type of File}		{Tipo de archivo}
::msgcat::mcset es {Unknown: Prompt user}	{Desconocido : Nombre de usuario}
::msgcat::mcset es {Url of homepage}		{URL de la página de inicio}
::msgcat::mcset es {Use SSL for security}	{Usar SSL para la seguridad}
::msgcat::mcset es {User is}			{El usuario está}
::msgcat::mcset es {User is offline}		{El usuario está desconectado}
::msgcat::mcset es {User is online}		{El usuario está conectado}
::msgcat::mcset es {User Profiles}		{Perfiles de usuario}
::msgcat::mcset es {User's status changed}	{El estado del usuario ha cambiado}
::msgcat::mcset es {Username & Password}	{Nombre y contraseña}
::msgcat::mcset es {vCard Info}			{Información de la tarjeta}
::msgcat::mcset es {Version Info}		{Información de la version}
::msgcat::mcset es {Whiteboard fonts}		{Fuentes de la pizarra}
::msgcat::mcset es {Writing file}		{Écriture del archivo}
#::msgcat::mcset en {Groupchat presence change}


# Écran de arranque :
::msgcat::mcset es splashsource 	{Cargando el código fuente Tcl...}
::msgcat::mcset es splashload 		{Cargando los paquetes Tcl...}
::msgcat::mcset es splashloadsha1 	{Cargando los paquetes sha1...}
::msgcat::mcset es splashsourcejabb 	{Cargando los recursos de Jabber...}
::msgcat::mcset es splashhost 		{Buscando un dominio...}
::msgcat::mcset es splashinit 		{Iniciando...}
::msgcat::mcset es splashprefs 		{Cargando y aplicando las preferencias...}
::msgcat::mcset es splashbuildmenu	{Construyendo los menúes...}
::msgcat::mcset es splashbuild 		{Construyendo la interfaz...}
::msgcat::mcset es splashlook 		{Buscando}


# Messages for tk_messageBox:
::msgcat::mcset es messfailedhttp	{Fallo durante el arranque del servidor http interno %s}
::msgcat::mcset es messinfoscript	{A causa de un fallo del "script info" bajo Mac, Usted debe indicar explícitamente el directorio "Pizarra-%s" en el cuadro diálogo siguiente}
::msgcat::mcset es messfailedsock	{Imposible iniciar la conexión con el servidor. Puede ser que la red no funcione o que el servidor no esté disponible. El mensaje de error es : %s}
::msgcat::mcset es messeofconnect	{Error durante la apertura de la conexión : Recibido un EOF}
::msgcat::mcset es messfailconnect	{Error durante la apertura de la conexión con %s}
::msgcat::mcset es messtimeout		{El tiempo para la conexión a caducado}
::msgcat::mcset es messnoplugs		{No hay plugin o ayuda detectado en este sistema}
::msgcat::mcset es messfailopread	{Imposible abrir %s para leer %s}
::msgcat::mcset es messfailopwrite	{Imposible abrir %s para escribir %s}
::msgcat::mcset es messcanerasewarn	{Abrir un nuevo dibujo y borrar todo el dibujo actual !}
::msgcat::mcset es messaskreceive	{A punto de recibir %s, acepta la recepción?}
::msgcat::mcset es messfailmimeimp 	{Imposible importar los archivos de type MIME %s}
::msgcat::mcset es messfailnomime 	{Imposible encontrar el tipo MIME para el archivo %s}
::msgcat::mcset es messfailsend		{Error durante el envío a %s}
::msgcat::mcset es messfactorydefaults	{Usted está a punto de borrar la mayoría de sus preferencias. ¿Desea continuar ?}
::msgcat::mcset es messremoveprofile	{¿Desea borrar este perfil? su cuenta no será suprimida en esta operación}
::msgcat::mcset es messfillserveruser	{Usted debe al menos introducir el nombre de usuario y el servidor}
::msgcat::mcset es messprofinuse	{Este perfil ya está utilizado, ¿desea sustituirlo?}
::msgcat::mcset es messblockbadjid	{Los campos del JID %s no están correctamente rellenados, ¿desea añadir de todas maneras?}
::msgcat::mcset es messfieldsmissing	{Un o más campos faltan, comenzar o cancelar}
::msgcat::mcset es messrmstandardfonts	{Las fuentes standard Times, Helvetica y Courier no pueden ser eliminadas}
::msgcat::mcset es messprefschanged	{Las preferencias han cambiado, desea cancelar de todas maneras?}
::msgcat::mcset es messerrpreffile	{Error durante la apertura de %s}
::msgcat::mcset es messfailserver	{Imposible abrir el socket del servidor, puede que usted no esté conectado}
::msgcat::mcset es messopenhelpfile	{Usted está a punto de abrir un archivo de ayuda en el dibujo y además borrar el dibujo actual ; ¿desea continuar?}
::msgcat::mcset es messprintnoextension	{No hay una extensión Tcl nos pueda ayudar aquí.}
::msgcat::mcset es messdoquit?		{¿Está seguro de que quiere salir?}
::msgcat::mcset es messsuassfillin	{Verifique que ha completado todos los campos antes de continuar}
::msgcat::mcset es messsuassclose	{¿Está seguro de querer cerrar el asistente de configuración? Puede volverlo a ejecutar posteriormente desde el menú}
::msgcat::mcset es messprotocolch	{Ha cambiado la configuración de red, Usted debe reiniciar la aplicación para activar los cambios. ¿Desea continuar?}
::msgcat::mcset es messpasswddifferent  {Las dos contraseñas son diferentes, Puede volver a introducirlas, por favor}
::msgcat::mcset es messaupdatelatest    {Usted ya tiene la última versión(%s)}
::msgcat::mcset es messprefsrestart     {Usted debe reiniciar la aplicación para que ciertos cambios tengan efecto}



# Messages for tk_messageBox:
::msgcat::mcset es jamesserrsend	{Un error ha ocurrido durante el envío del\
  mensaje a "%s" ; el código de error es "%s"}
::msgcat::mcset es jamessallowsub	{El usuario %s le autoriza a añadirle a sus contactos}
::msgcat::mcset es jamessunsub		{El usuario %s ha sido borrado de sus contactos\
  y no está permitido volver a los contactos.}
::msgcat::mcset es jamessunsubpres	{El usuario %s ha sido borrado de sus contactos}
::msgcat::mcset es jamessunsubask	{El usuario %s ha sido borrado de sus contactos,\
  Desea borrarlo %s de los contactos de usted?}
::msgcat::mcset es jamessunsubscribed	{Usted no forma parte de los contactos de %s}
::msgcat::mcset es jamesserrpres	{Hay un error en el estado "Presente",\
  El código de error es %s (%s)}
::msgcat::mcset es jamessautoaccepted	{Usted automáticamente ha aceptado una petición\
  de autorización de parte de %s}
::msgcat::mcset es jamessautoreject	{Usted automáticamente ha rechazado una petición\
  de autorización de parte de %s}
::msgcat::mcset es jamessautosubs	{Usted automáticamente ha añadido %s\
 a su lista de contactos}
::msgcat::mcset es jamessconnbroken	{La conexión ha sido inesperadamente cortada}
::msgcat::mcset es jamessautoawayset 	{El estado "Alejado automático" ha sido enviado a %s. Desea de nuevo aparecer como "Disponible" ?}
::msgcat::mcset es jamesserrgetpublic	{Error durante la solicitud de datos públicos de %s, el código de error es %s (%s)}
::msgcat::mcset es jamesserrlastactive	{Error durante la solicitud de la última actividad de %s, el código de error es %s (%s)}
::msgcat::mcset es jamesserrnotimeinfo	{El cliente/servicio %s no ha devuelto la información del tiempo.}
::msgcat::mcset es jamesstimeused	{Tiempo transcurrido desde la última actividad de %s : }
::msgcat::mcset es jamesstimeconn	{Tiempo transcurrido desde la última conexión de %s : }
::msgcat::mcset es jamesstimeservstart	{Tiempo transcurrido desde el arranque del servidor "%s" : }
::msgcat::mcset es jamessuptime		{El tiempo Activo (para los servicios) o la última actividad del usuario es: }
::msgcat::mcset es jamesserrtime	{Error durante la solicitud de hora a %s (%s).}
::msgcat::mcset es jamesslocaltime	{La hora local de %s es: %s}
::msgcat::mcset es jamesserrvers	{Error durante la solicitud de version a %s (%s).}
::msgcat::mcset es jamesserrautoupdate 	{Error durante la solicitud de actualización del servidor %s (%s).}
::msgcat::mcset es jamesswarberasewb	{¿Desea borrar la pizarra?}
::msgcat::mcset es jamesswarnremove	{Borrar un elemento de la lista de contactos puede estar desactivado. Usted debe estar registrado antes quiere añadirle de nuevo.\
  Desea continuar de todas maneras?}
::msgcat::mcset es jamessillegalchar	{El/los carácter/es no válido/s en %s son : "%s" !}
::msgcat::mcset es jamessbadjid		{El JID "%s" est mal configurado. ¿Desea continuar de todas maneras?}
::msgcat::mcset es jamessalreadyinrost	{El JID "%s" ya siendo utilizado en la lista de contactos. ¿Desea continuar de todas maneras?}
::msgcat::mcset es jamessfailsetnick	{Error durante la asignación del alias o del nombre de grupo "%s". Código del error: %s (%s).}
::msgcat::mcset es jamessnamemissing	{%s falta o es demasiado corto!}
::msgcat::mcset es jamessnosocket	{Imposible crear el servidor "%s". Puede ser que la red no funcione o que el servidor está inutilizable (%s).}
::msgcat::mcset es jamesstimeoutserver	{Tiempo transcurrido durante el acceso al servidor "%s".}
::msgcat::mcset es jamessregisterok	{El registro en el servidor "%s" ha sido correcto. Ahora le queda conectarse con su nombre de usuario y contraseña.}
::msgcat::mcset es jamessremoveaccount	{Usted está a punto de borrar su cuenta en el servidor ; esta operación no puede ser desecha. ¿Desea continuar?}
::msgcat::mcset es jamesserrunreg	{Error durante la desinscripción de "%s". Código del error : %s (%s).}
::msgcat::mcset es jamessokunreg	{Usted ya no está subscrito en "%s".}
::msgcat::mcset es jamesspasswddiff	{Las contraseñas no concuerdan. Necesita volver a empezar.}
::msgcat::mcset es jamesspasswderr	{El registro de la nueva contraseña no ha resultado. Código del error : %s (%s).}
::msgcat::mcset es jamesspasswdok	{La nueva contraseña ha sido registrada.}
::msgcat::mcset es jamessregnoserver	{El servidor debe estar configurado.}
::msgcat::mcset es jamesserrregget	{La recuperación de la información de inscripción ha fallado. Código del error : %s (%s)}
::msgcat::mcset es jamesserrregset	{La inscripción en el servicio "%s" ha fallado. Código del error : %s (%s)}
::msgcat::mcset es jamessokreg		{La inscripción en el servicio "%s" ha sido realizada.}
::msgcat::mcset es jamessinvalidjid	{El JID está mal configurado. Verifique todo d'abord que la case en bas del pizarra contient una dirección correcta, debe ser con la forma "contacto@jabber.org".}
::msgcat::mcset es jamessnotconnected	{Usted debe estar conectado con el servidor para enviar !}
::msgcat::mcset es jamessaddrmiss	{Usted debe cumplimentar con al menos una dirección correcta.}
::msgcat::mcset es jamesschatclose	{Si cierra esta ventana, perderá la conversación en curso. ¿Desea cerrar de todas maneras?}
::msgcat::mcset es jamessnogroupchat	{No se reconoce ningún servicio de grupo de chat.}
::msgcat::mcset es jamessinroommiss	{Todos los campos ser cumplimentados antes de entrar en la sala.}
::msgcat::mcset es jamesswarnexitroom	{Desea salir de la sala %s ?}
::msgcat::mcset es jamesserrbrowse	{Error durante la navigación en "%s": %s}
::msgcat::mcset es jamessenterroomempty	{El nombre del servidor y de la sala deben ser indicados correctamente.}
::msgcat::mcset es jamesserrconfget	{La recuperación de la información de entrada a la sala ha fallado. Código del error : %s (%s).}
::msgcat::mcset es jamesserrconfgetcre	{La recuperación de la información de creación de la sala ha fallado. Código del error : %s (%s).}
::msgcat::mcset es jamessinroomerasewb 	{¿Desea borrar la pizarra antes de entrar en la sala?}
::msgcat::mcset es jamessconffailed	{Error durante la entrada/la creación de la sala. Código del error : %s (%s).}
::msgcat::mcset es jamessconfservempty	{El servidor debe estar configurado con un nombre correcto.}
::msgcat::mcset es jamesserragentget	{Error durante la recuperación de los agentes : %s}
::msgcat::mcset es jamesserrsearch	{Error durante las especificaciones de la búsqueda. Código del error : %s (%s).}
::msgcat::mcset es jamessoobok		{Transferencia de archivos realizada.}
::msgcat::mcset es jamessoobok2         {Transferencia de %s a %s realizada.}
::msgcat::mcset es jamessoobnourl	{Para solicitud de descarga efectuada ninguna URL ha sido especificada.}
::msgcat::mcset es jamessoobask		{El usuario %s à mis à uso disposition un archivo sobre %s. Description : %s. Desea la descargar ?}
::msgcat::mcset es jamessoobbad		{La URL de "%s" no es correcta. (URL : "%s").}
::msgcat::mcset es jamessoonnohttp	{La URL de "%s" no utiliza el protocolo "HTTP", pero "%s" (no soportado).}
::msgcat::mcset es jamessoobfailopen	{La apertura de "%s" ha fallado.}
::msgcat::mcset es jamessoobgetfail	{La URL "%s" no está accessible (%s).}
::msgcat::mcset es jamessoobtimeout	{Tiempo transcurrido durante el acceso al archivo vía HTTP}

# translate!!!!
::msgcat::mcset es jamessooberr406      {The user %s rejected to accept the file %s.}
::msgcat::mcset es jamessooberr404      {Got an error when trying to send the file %s to %s. The code was %s, and error message: %s}
# translate!!!!

::msgcat::mcset es jamessnogchat	{Ningún servicio propuesto para la sala es reconocido.}
::msgcat::mcset es jamesserrinboxopen	{Error de la apertura del correo entrante %s durante la copia de seguridad.}
::msgcat::mcset es jamesserrinboxread	{Error durante la lectura del mensaje en el diálogo Jabber "%s" : %s}
::msgcat::mcset es jamesschatclose	{Si cierra esta ventana, perderá toda la conversation. ¿Desea continuar?}
::msgcat::mcset es jamessgchatfields	{Todos los campos deben estar cumplimentados antes de entrar en la sala.}
::msgcat::mcset es jamessconfmsg	{Elija un servicio de conferencia y un nombre de sala. Haga click en "Recibir" para obtener las especificaciones de entrada\
  en la sala deseada (cada sala puede tener sus proprias especificaciones).}
::msgcat::mcset es jamesssavemsg	{¿Desea guardar el mensaje?}
::msgcat::mcset es jamessskipsendq	{La dirección "%s" es incorrecta. ¿Desea enviar a las otras?}
::msgcat::mcset es jamessillformresend	{La dirección "%s" es incorrecta. Modifiquela para enviar de nuevo.}
::msgcat::mcset es jamesslogin409	{La conexión ha fallado con el código de error %s (Este nombre de usuario ya está utilizado).\
  Si es usted quien utiliza este nombre, vuelva a intentar conectarse.}
::msgcat::mcset es jamessloginerr	{La conexión ha fallado. Código del error : %s (%s).}
::msgcat::mcset es jamessaddforeign	        {Para añadir un usuario subscrito a un sistema de mensajería distinto de Jabber necesitar previamente tener una cuenta en este sistema, y que\
  haya utilizado dicha cuenta para el registro en el servidor de transporte correspondiente (%s). ¿Desea hacerlo ahora ?}
::msgcat::mcset es jamessowntrpt	        {uso propre cuenta sobre %s joue el rôle del service qui transporte vos messages à ce sistema de mensajería.\
  Es necesario qu'il soit en uso lista de contactos. Usted está registrado auprès de %s : %s.}
::msgcat::mcset es jamesswbchatlost	        {La chat entero se perderá si cierra la pizarra. ¿Desea terminar la conversación?}
::msgcat::mcset es jamesschatoffline            {Cet usuario n'est plus en línea, le message n'est donc pas enviado.}
::msgcat::mcset es jamessregloginok             {Usted está ahora identificado y automáticamente conectado como que "%s"}
::msgcat::mcset es jamessregerrinuse            {La inscripción ha fallado parce que ce nombre est déjà employé par un otro usuario. Si usted está cet usuario,\
  essayez plutôt de vous conectar. Código del error : %s}
::msgcat::mcset es jamessregerr                 {La inscripción ha fallado con el message de error "%s"}
::msgcat::mcset es jamesstrptsubsc              {uso cuenta registrado con el service %s sera añadido a sus contacts para funcioner como un servidor de transport con el service.}
::msgcat::mcset es jamessfailedsubsc            {Fallo de subscripción con %s. El usuario ha rechazado la subscripción.}
::msgcat::mcset es jamessstarttls-nofeature     {El servidor "%s" ne supporte pas el TLS.}
::msgcat::mcset es jamessstarttls-failure       {Error durante la sécurisation TLS con el servidor "%s".}

# translate!!!!
::msgcat::mcset es jamessgcinvite               {You have been invited to the groupchat room %s by %s. Do you want to join?}



::msgcat::mcset es openquicktime		{Abrir el streaming QuickTime}
::msgcat::mcset es writeurl			{Escribir el'URL o elegir el atajo : }
::msgcat::mcset es openquicktimeurlmsg		{Abrir l'URL de un archivo SDP con la extensión .mov para un streaming QuickTime. Cela puede estar del son (radio) ou de la video (TV).\
  Vous pouvez également utilizar uso navigateur para encontrar el archivo SDP, l'enregistrer sobre el disque y l'ouvrir como una video classique.}
::msgcat::mcset es printunixcmd                 {Commande d'impression, puede estar changée}
::msgcat::mcset es enterpassword                {Introducir la contraseña para el cuenta "%s"}



::msgcat::mcset es httptrptok                   {Fin de la descarga del archivo %s}
::msgcat::mcset es httptrpterror                {Error de transferencia durante la descarga del archivo %s : %s}
::msgcat::mcset es httptrpteof                  {El servidor ha terminado la conexión sin respuesta.}
::msgcat::mcset es httptrptnon200               {Error de transferencia durante la descarga del archivo %s : code %s ; %s}
::msgcat::mcset es httptrptreset                {Le transferencia del archivo %s ha sido relancé}


::msgcat::mcset es uastatpointmac 	{Puntero (click : seleccionar, doble click: inspeccionar, pulse: popup)}
::msgcat::mcset es uastatpoint		{Puntero (click : seleccionar, doble click: inspeccionar, click derecho: popup)}
::msgcat::mcset es uastatmove		{Mover}
::msgcat::mcset es uastatline		{Linea}
::msgcat::mcset es uastatarrow		{Flecha}
::msgcat::mcset es uastatrect		{Rectángulo}
::msgcat::mcset es uastatoval		{Elipse}
::msgcat::mcset es uastattext		{Texto}
::msgcat::mcset es uastatdel		{Haga click para borrar}
::msgcat::mcset es uastatpen		{Pintura}
::msgcat::mcset es uastatbrush		{Brocha}
::msgcat::mcset es uastatpaint		{Relleno (+ <shift>: transparente)}
::msgcat::mcset es uastatpoly		{Polígono (<espacio>: terminar)}
::msgcat::mcset es uastatarc		{Arco (click: definir centro, <espace>: terminar)}
::msgcat::mcset es uastatarc2		{Arco (hacer click-mover)}
::msgcat::mcset es uastatrot		{Rotar (debe tener seleccionados los objetos)}


# Preferencias:
::msgcat::mcset es prefnetconf  {Configuración de Red y Servidor}
::msgcat::mcset es prefnethead  {Usted puede conectarse a un servidor Jabber, o bien directement a otro cliente. Muchos elementos de la interfaz dependerán\
  de la configuración que elija.}
::msgcat::mcset es prefnetauto  {Si un cliente se conecta a este servidor, una conexión con el servidor de este cliente será automáticamente realizada.}
::msgcat::mcset es prefnetjabb  {El sistema de servidor Jabber. Configuración avanzada via el menú "Jabber". Utilice un protocolo basado en XML.}
::msgcat::mcset es prefnetmulti {Conectar automáticamente a todos los clientes de esta red durante la conexión entre algunos de ellos.}
::msgcat::mcset es prefnetadv   {Si un client arranca normalmente dos servidores diferentes, el servidor integrado (siempre presente en el caso de punto-a-punto),\
  y el servidor HTTP. El servidor Jabber se refiere normalmente a un servidor distante por el puerto 5222. Usted debe reiniciar Coccinella para que los nuevos números de puerto sean tenidos en cuenta.}
::msgcat::mcset es prefsounsynwb {Sintetizar el texto que aparezca en la pizarra}
::msgcat::mcset es prefsounsynno {Sintetizar los mensajes normales}
::msgcat::mcset es prefsounsynch {Sintetizar las charlas}
::msgcat::mcset es prefsounvoin  {Elegir una voz para el texto entrante:}
::msgcat::mcset es prefsounvoou  {Elegir una voz para el texto saliente:}
::msgcat::mcset es prefsounpick  {Elegir las alertas sonoras para los eventos a continuación:}
::msgcat::mcset es prefshortcut  {Aquí podrá añadir o modificar los atajos aplicables únicamente a las conexiones punto-a-punto, no utilizadas\
  por el sistema Jabber. Si no ha elegido explícitamente la opción "punto-a-punto" en el panel "Configuración de red", estos atajos no serán aplicados.}
::msgcat::mcset es prefprof      {Aquí podrá modificar las opciones específicas de las cuentas Jabber. El servidor que indique aquí será el mismo con el que se conectará.}
::msgcat::mcset es prefpers      {Su información personal queda registrada en el archivo de preferencias, pero también puede estar en el directorio de usuario Jabber.\
  La información registrada por el servidor es accessible por cualquier usuario.}
::msgcat::mcset es prefaaset     {Introduzca el estado "Alejado automático": }
::msgcat::mcset es prefminaw     {Minutos antes de estado "Alejado": }
::msgcat::mcset es prefminea     {Minutos antes de estado "Alejado para mucho tiempo": }
::msgcat::mcset es prefsuif      {Si alguien quiere añadirme a sus contactos y...}
::msgcat::mcset es prefsuis      {...ya se encuentra en mis contactos: }
::msgcat::mcset es prefsuisnot   {...no forma parte de mis contactos : }
::msgcat::mcset es prefsuauto    {Registrarse automáticamente con aquellos que me registren}
::msgcat::mcset es prefrorm      {Borrar el usuario si no está registrado}
::msgcat::mcset es prefroallow   {Autorizar los usuarios no registrados}
::msgcat::mcset es prefroclr     {Limpiar la lista de contactos en la desconexión}
::msgcat::mcset es prefrochat    {Doble-click: charlar, click: mensaje normal}
::msgcat::mcset es prefrosysicons {Usar los iconos del sistema del protocolo de mensajería ajeno}

# translate
::msgcat::mcset es prefrohideoff {Do not show offline users}
::msgcat::mcset es prefrohidetrpt {Do not show transports}

::msgcat::mcset es prefblonly    {Sólo aceptar mensajes de mis contactos}
::msgcat::mcset es prefblbl      {Bloquear los JIDs siguientes (* asterísco para "todos") : }
::msgcat::mcset es prefblmsg     {Escribir la JID completo para les usuarios que quiera bloquear (les JID sont con la forma "usuario@jabber.org)}
::msgcat::mcset es prefcufont    {Seleccionar la fuente para la ventana de charlas : }
::msgcat::mcset es prefcushow    {Mostrar los mensajes en una nueva ventana}
::msgcat::mcset es prefcuautologin  {Conectarse automáticamente en el arranque}
::msgcat::mcset es prefcusave    {Guardar el buzón entre sesiones}
::msgcat::mcset es prefcu2clk    {Message del double-clic en la diálogo los mensajes : }
::msgcat::mcset es prefcuopen    {Abrir el message en una nueva ventana}
::msgcat::mcset es prefcureply   {Responder al remitente}
::msgcat::mcset es prefcudisc    {Método "Explorar los servicios" preferido : }
::msgcat::mcset es prefcubrowse  {Explorar los servicios si el método está disponible}
::msgcat::mcset es prefcuagent   {Siempre utilizar el método de los agentes}
::msgcat::mcset es prefcuupdate  {Buscar automáticamente actualizaciones de Coccinella}

# translate
::msgcat::mcset es prefcuremdlgs {Remember open dialogs between sessions}

::msgcat::mcset es preffmhelp    {Plugins de ayuda para los tipos de archivos}
::msgcat::mcset es preffmsave    {Juste "guardar en disco" en el directorio entrante}
::msgcat::mcset es preffontmsg   {Atención: cuando añada otras fuentes\
además de las fuentes estándar (Times, Helvetica o Courier), Aseguresé que ha instalado igualmente estas últimas.}
::msgcat::mcset es prefcahow     {Como tratar los archivos recibidos: }
::msgcat::mcset es prefcanev     {Nunca guardar los archivos en caché, siempre descargar}
::msgcat::mcset es prefcaalw     {Siempre guardar los archivos en caché, nunca descargar} 
::msgcat::mcset es prefcaor      {...o aceptar los archivos en cache si no son más antiguos de: }
::msgcat::mcset es prefpriv      {Seleccionando "Privacidad", sólo está autorizado a modificar sus propios objetos del dibujo. Los objetos\
  creados por otros usuarios no son modificables.}
::msgcat::mcset es prefshortip   {Completar la dirección IP o el nombre}
::msgcat::mcset es prefshortwa   {Atención : ha editado los atajos.. Desea ¿guardarlos?}

::msgcat::mcset es preffilecache {La caché se usa para guardar localmente una copia de los archivos de otros usuarios, para reducir el tráfico de red. El tamaño de la caché\
  se limita por usuario en los parámetros a continuación: }
::msgcat::mcset es prefcachecmp  {comparar los archivos de la caché con los archivos remotos}
::msgcat::mcset es prefnatip     {Usar las siguientes direcciones IP como salida al exterior}
::msgcat::mcset es prefmucconf   {Usar las charlas multi-usuario en "conferencia"}
::msgcat::mcset es prefrostbgim  {Usar la imagen de fondo (gif) en la lista de contactos}
::msgcat::mcset es preftheme     {Elegir un tema (Coccinella debe ser reiniciado)}
::msgcat::mcset es prefplugctrl  {Puede deseleccionar estos paquetes para no tener que cargarlos. Coccinella debe reiniciarse para que los cambios tengan efecto.}
::msgcat::mcset es prefchactret  {Siempre activar <Enter> en el cuadro diálogo de chat}
::msgcat::mcset es prefchnormal  {Tratar los mensajes normales como mensajes de chat}
::msgcat::mcset es prefprofname  {Introducir el nombre del perfil de usuario}
::msgcat::mcset es prefstabui    {Usar la interfaz del bloc de notas con pestañas}
::msgcat::mcset es prefsusesasl  {Usar método de autentificación SASL}

#--- Translate ---
::msgcat::mcset es prefprivmsg {Each user may administrate zero or many lists. Only the active or default list affect message processing. Any active list affects only the session. The default list is processed if there is no active list.}
::msgcat::mcset es prefprivunav {Filter options unavailable while not connected}
::msgcat::mcset es prefprivnotex {Filter options unavailable at this server}
::msgcat::mcset es prefprivobtained {Filter lists obtained from server}
::msgcat::mcset es prefprivgetlist {Getting filter list "%s"}
::msgcat::mcset es prefprivrules {Each list contains one or many rules, each rule specify the type of events it acts on, and the action it shall take. If you specify a group to block it must exist in your roster.}
::msgcat::mcset es prefuserinactive {User has been inactive for a while}
::msgcat::mcset es preficonsel {The selected iconset will take action when you save}
::msgcat::mcset es prefwbscroll {You may set a larger size than the default %sx%s}
::msgcat::mcset es prefssbts {Show next and previous buttons}
::msgcat::mcset es prefssresize {Resize canvas automatically to fit image}
#--- Translate ---



# Espace EditShortcuts :
namespace eval ::EditShortcuts:: {
	::msgcat::mcset es shortip       {Completar la dirección IP o el nombre}
	::msgcat::mcset es shortwarn     {Atención : usted ha editado los atajos.. Desea registrarse?}


}


::msgcat::mcset es jalogin 	{Escribir la dirección IP o el nombre del servidor Jabber, o elegir en el menú desplegable. Usted debe tener una cuenta en este servidor.}
::msgcat::mcset es janewaccount {Escribir la dirección IP o el nombre del servidor Jabber, elegir un nombre de usuario y un contraseña.}
::msgcat::mcset es janewpass    {Elegir la contraseña para : }
::msgcat::mcset es jasubwant    {El usuario "%s" quiere añadirlo a sus contactos.}
::msgcat::mcset es jasubopts    {Elija una opción debajo. Elegir un alias y un grupo es opcional, es para su uso personal solamente.}
::msgcat::mcset es jasubgetvcard {Ver la tarjeta de esta persona}
::msgcat::mcset es jasubsndmsg  {Enviar un mensaje a esta persona : }
::msgcat::mcset es jasuballow   {Autorizar "%s" a ver mi presencia}
::msgcat::mcset es jasubadd     {Añadir "%s" a mis contactos}
::msgcat::mcset es jarostadd	{Añadir un usuario Jabber a mis contactos. Le alias y el grupo pueden ser cambiados en cualquier momento.\
  Para añadir un usuario de otro sistema de mensajería, Usted debe tener una cuenta activa en este sistema qui debe estar registrado sobre les servidores de transporte Jabber.}
::msgcat::mcset es jarostset	{Elegir un alias y un grupo para el usuario "%s". Esta información puede ser cambiada en cualquier momento..}
::msgcat::mcset es jarostsub	{Subscribirse auprès de este usuario}
::msgcat::mcset es jarostunsub	{Desregistrarse auprès de este usuario}
::msgcat::mcset es jasearch	{Buscar el usuario con el service spécifié. Haga click en el botón "Recibir" para obtener un nuevo formulario à introducir.}
::msgcat::mcset es jasearchwait	{Haga click en "Recibir" cuando esté listo}
::msgcat::mcset es jaservclosed	{Conexión con el servidor cerrada}
::msgcat::mcset es jarostupdate {La lista de contactos está al día}
::msgcat::mcset es jawaitresp 	{%s est contacté, en attente una respuesta}
::msgcat::mcset es jawaitxml 	{Conectado à "%s". Iniciando del flux XML...}
::msgcat::mcset es jasendauth	{Respuesta del servidor "%s". Envoi de la solicitud de autorización.}
::msgcat::mcset es jaerrlogin	{La conexión à %s ha fallado : %s}
::msgcat::mcset es jaauthok	{Autorización del servidor "%s" obtenida. Cargando la lista de contactos...}
::msgcat::mcset es jagchatmsg	{Elija un grupo de chat y un nombre de sala, también puede usar un alias.}
::msgcat::mcset es jacreateroom	{Seleccione un servicio de conferencia y opcionalmente un nombre de sala. Haga click en "Recibir" para obtener las especificaciones para crear la sala\
  deseada (cada servidor puede tener especificaciones diferentes).}
::msgcat::mcset es jawaitserver	{Esperando de la respuesta del servidor...}
::msgcat::mcset es jaregmsg	{Registro para un servicio spécifique para este servidor. Si usted ya está registrado, podrá perdre des informations personales.}
::msgcat::mcset es jastatavailable {Disponible}
::msgcat::mcset es jastatchat	{Chat : disponible para un contacto inmediato}
::msgcat::mcset es jastataway	{Alejado : en línea, mais parti para un petit moment}
::msgcat::mcset es jastatxa	{Alejado para mucho tiempo : en línea, mais inactivo después un largo rato}
::msgcat::mcset es jastatdnd	{No molestar}
::msgcat::mcset es jastatinvisible {Invisible}
::msgcat::mcset es javersinfo	{Información de la versión de %s}
::msgcat::mcset es jabrowseaddserver	{Introducir la JID del servidor que quiera añadir a la lista los servicios (con la forma jabber.org).}
::msgcat::mcset es jaupdatemsg	{Una nueva version de Coccinella está disponible}
::msgcat::mcset es jaupdatevers	{La versión actual es : %s}
::msgcat::mcset es jaupdatepri	{La fecha es %s}
::msgcat::mcset es jaupdatenewver {La nueva versión es : %s}
::msgcat::mcset es jaupdateremind {No recordarme esto}
::msgcat::mcset es jasettopic   {Introduzca un nueva tema para este grupo de chat}
::msgcat::mcset es jadirpresmsg {Enviar el estado deseado al usuario "%s".}
::msgcat::mcset es jatlsnegot   {Seguridad TLS...}

#--- Translate ---
::msgcat::mcset es jamucentermsg {Enter your nick name and press Enter to go into the room. You may Browse to get the available rooms for the specific service.	Members only room may require a password.}
::msgcat::mcset es jainmsgshow {Show incoming messages in this window}
::msgcat::mcset es jadisaddserv {Discover another server for groupchat rooms and other services. You may add a server permanently which is then automatically discovered. The login server is always discovered.}
::msgcat::mcset es jadisrmall {Remove all servers that are automatically and permanently discovered.}
::msgcat::mcset es jauserinnote {Add your personal notes about this user}
#--- Translate ---



# Assistant de configuration :
::msgcat::mcset es suintro1 	{Bienvenido al asistente de configuración que le ayudará introducir la información necesaria para añadir una cuenta antigua o nueva sobre un servidor Jabber.}
::msgcat::mcset es suintro2 	{Si quiera utilizar el modo peer-to-peer, Deberá indicarlo en el panel de preferencias y reiniciar Coccinella.}
::msgcat::mcset es suintro3 	{En cualquier momento podrá hacer click sobre "Anterior" para revenir en arrière. Siga las instrucciones de cada página y haga click en "Siguiente"\
  hasta que haya terminado.}
::msgcat::mcset es sulang       {Elija su idioma. Si cambia el idioma, los cambios no serán efectuados hasta que se vuelvan a cargar los elementos de la interfaz.}
::msgcat::mcset es suservmsg	{Indique el nombre del servidor Jabber sobre el quiera estar registrado. Si ya tiene una cuenta, indique el servidor al que usted está subscrito\
  (con la forma jabber.org).}
::msgcat::mcset es suusermsg	{Indique su nombre de usuario y su contraseña. El nombre de usuario no puede estar siendo utilizado por otro usuario en el servidor elegido.\
  Si este es el caso, obtendrá un mensaje indicando lorsque vous tenterez de registrarse.}
::msgcat::mcset es suregmsg	{Desea registrar su cuenta ahora (si es una nueva cuenta)? Deberá estar conectado a la red (sin cortafuegos).}
::msgcat::mcset es sufinmsg	{¡Es todo! Si el registro ha funcionado, no queda más que hacer click sobre "Conectarse", o elegir en el menu Jabber/Conexión.\
  Quoi qu'il en soit, soyez gentil con l'insecte ;-)}
::msgcat::mcset es suheadtxt	{Asistente de configuración de Coccinella}



::msgcat::mcset es vcardget	{Cargando de la tarjeta del usuario %s.. Esperando de la respuesta del servidor...}
::msgcat::mcset es vcarderrget	{La carga de la tarjeta ha fallado (%s).}
::msgcat::mcset es vcardrec	{La tarjeta ha sido recibida.}



::msgcat::mcset es autoupdatenot        {No comprobar automáticamente las actualizaciones}
::msgcat::mcset es oobmsg               {Dejar al usuario %s descargar uno de sus archivos sobre el servidor. La descrición es obligatoria.}
::msgcat::mcset es chatcompreply        {%s escriba una respuesta}

# Recibido de archivos
::msgcat::mcset es getcontacting   {Contacto de %s. Esperando una respuesta...}
::msgcat::mcset es geteoferr       {La conexión a %s ha fallado : recibido un EOF.}
::msgcat::mcset es getconnerr      {La conexión a %s ha fallado.}
::msgcat::mcset es getnegotiate    {Cliente contactado : %s ; negociación en curso...}
::msgcat::mcset es getreaderr      {Error de respuesta del servidor %s.}
::msgcat::mcset es getunknownprot  {El servidor %s no responde usando protocolo correcto.}
::msgcat::mcset es getnot200       {El servidor %s ha respondido con el código %s (%s).}
::msgcat::mcset es getstarts       {El cliente %s ha aceptado el archivo "%s". Comienza del transferencia...}
::msgcat::mcset es getended        {La transferencia de %s ha terminado inesperadamente.}
::msgcat::mcset es getfinished     {El archivo "%s" de %s ha sido recibido.}
::msgcat::mcset es getneterr       {Error de transferencia durante la recepción de %s.}

# Envoi de archivos
::msgcat::mcset es putcontacting   {Contacto de %s. Esperando una respuesta...}
::msgcat::mcset es puteoferr       {La conexión a %s ha fallado : recepción una EOF.}
::msgcat::mcset es putconnerr      {La conexión a %s ha fallado.}
::msgcat::mcset es putnegotiate    {Cliente contactado : %s ; negociación en curso...}
::msgcat::mcset es putreaderr      {Error de respuesta del servidor %s.}
::msgcat::mcset es putunknownprot  {El servidor %s no responde usando protocolo correcto.}
::msgcat::mcset es putnot200       {El servidor %s ha respondido con el código %s (%s).}
::msgcat::mcset es putstarts       {El cliente %s ha aceptado el archivo "%s". Comienza la transferencia...}
::msgcat::mcset es putended        {La transferencia de %s ha terminado inesperadamente.}
::msgcat::mcset es putfinished     {El archivo "%s" de %s ha sido recibido.}
::msgcat::mcset es putneterr       {Error de transferencia durante la recepción de %s.}

# END --------------------------------------------------------------------------
