# French language version of the Coccinella message catalog.
#
#       The English catalog is the master of all other catalogs
#
#       Translators:
#         cs  David Stancl (david.stancl at seznam.cz), 2007-2008
#         da  Mogens Pedersen  (Mogens.Pedersen at skolekom.dk), 2006
#         de  Hermann J. Beckers (hj dot beckers at onlinehome dot de), 2004-2008
#         es  Néstor Díaz (n3storm at grupoikusnet.com), 2004
#             Antonio F. Cano (antonio at grupoikusnet.com), 2006
#             Agustin Vericat (agustin at grupoikusnet.com), 2006
#             César Alcalde (lambda512 at gmail.com), 2008
#         fr  Guillaume Ayoub (xovni at wanadoo.fr), 2004-2005
#             Nicolas Vérité (xmpp:nyco@jabber.fr, nicolas.verite at gmail.com), 2008
#         it  Mirko Graziani (contatto at imatica.it), 2006-2008
#         ko  Dylan Park, Korea NVC Center (hanmaum AT krnvc.org), 2006
#         nl  Sander Devrieze (s.devrieze at pandora.be), 2004-2008
#             Bart Van Hove (bartvanhove at skynet.be), 2004
#         pl  Zbigniew Baniewski (zb at ispid.com.pl), 2005-2008
#         ru  Alexander Balezin (xmpp:gescheit@jabber.ttn.ru, gescheit at list.ru), 2005-2007
#         sv  Mats Bengtsson, 2002-2008
#
# General type of text, such as "OK", "Cancel", and the like. 
# We use the source string as the message.
# Defined in global namespace and may therefore be used in any namespace.
# 
#   $Id: fr.msg,v 1.99 2008-09-24 18:37:59 sdevrieze Exp $

::msgcat::mcset fr Abort                 {Abandonner}
::msgcat::mcset fr Action                {Action}
::msgcat::mcset fr Add                   {Ajouter}
::msgcat::mcset fr Address               {Adresse}
::msgcat::mcset fr Admin                 {Admin}
::msgcat::mcset fr admin                 {admin}
::msgcat::mcset fr Affiliation           {Affiliation}
::msgcat::mcset fr Always                {Toujours}
::msgcat::mcset fr Any                   {Tous/toutes}
::msgcat::mcset fr Appearance            {Apparence}
::msgcat::mcset fr Author                {Auteur}
::msgcat::mcset fr Avatar                {Avatar}
::msgcat::mcset fr Binary                {Binaire}
::msgcat::mcset fr Birthday              {Anniversaire}
::msgcat::mcset fr Bookmarks             {Marque-pages}
::msgcat::mcset fr Browser               {Navigateur}
::msgcat::mcset fr Cancel                {Annuler}
::msgcat::mcset fr Chatroom              {Salon de discussion}
::msgcat::mcset fr City                  {Ville}
::msgcat::mcset fr Clear                 {Nettoyer}
::msgcat::mcset fr Client                {Client}
::msgcat::mcset fr Close                 {Fermer}
::msgcat::mcset fr Color                 {Couleur}
::msgcat::mcset fr Company               {Entreprise}
::msgcat::mcset fr Configure             {Configurer}
::msgcat::mcset fr Connection            {Connexion}
::msgcat::mcset fr Contact               {Contact}
::msgcat::mcset fr Contacts              {Contacts}
::msgcat::mcset fr Coordinates           {Coordonnées}
::msgcat::mcset fr Country               {Pays}
::msgcat::mcset fr Create                {Créer}
::msgcat::mcset fr Customization         {Personnalisation}
::msgcat::mcset fr Date                  {Date}
::msgcat::mcset fr Default               {Défaut}
::msgcat::mcset fr Delete                {Supprimer}
::msgcat::mcset fr Deny                  {Rejeter}
::msgcat::mcset fr Department            {Département}
::msgcat::mcset fr Description           {Description}
::msgcat::mcset fr Detect                {Detecter}
::msgcat::mcset fr Discover              {Découvrir}
::msgcat::mcset fr Downloading           {En téléchargement}
::msgcat::mcset fr Edit                  {Éditer}
::msgcat::mcset fr Email                 {E-mail}
::msgcat::mcset fr Emoticons             {Emoticônes}
::msgcat::mcset fr Encoding              {Codage}
::msgcat::mcset fr Enter                 {Entrer}
::msgcat::mcset fr Error                 {Erreur}
::msgcat::mcset fr Exit                  {Sortir}
::msgcat::mcset fr Export                {Exporter}
::msgcat::mcset fr Extensions            {Extensions}
::msgcat::mcset fr File                  {Fichier}
::msgcat::mcset fr Filter                {Filtrer}
::msgcat::mcset fr Finish                {Terminer}
::msgcat::mcset fr Finished              {Terminé}
::msgcat::mcset fr First                 {Premier}
::msgcat::mcset fr Fonts                 {Fonts}
::msgcat::mcset fr Forward               {Faire suivre}
::msgcat::mcset fr From                  {De}
::msgcat::mcset fr General               {Général}
::msgcat::mcset fr Get                   {Recevoir}
::msgcat::mcset fr Getting               {Réception}
::msgcat::mcset fr Grant                 {Accorder}
::msgcat::mcset fr Group                 {Groupe}
::msgcat::mcset fr Height                {Hauteur}
::msgcat::mcset fr History               {Historique}
::msgcat::mcset fr Home                  {Démarrer}
::msgcat::mcset fr Host                  {Hôte}
::msgcat::mcset fr Icon                  {Icône}
::msgcat::mcset fr Image                 {Image}
::msgcat::mcset fr Import                {Importer}
::msgcat::mcset fr Inbox                 {Messages}
::msgcat::mcset fr Info                  {Infos}
::msgcat::mcset fr Invite                {Inviter}
::msgcat::mcset fr Invitation            {Invitation}
::msgcat::mcset fr Key                   {Clé}
::msgcat::mcset fr Language              {Langage}
::msgcat::mcset fr Last                  {Dernier}
::msgcat::mcset fr Less                  {Moins}
::msgcat::mcset fr Login                 {Se connecter}
::msgcat::mcset fr Logout                {Se déconnecter}
::msgcat::mcset fr Member                {Membre}
::msgcat::mcset fr member                {membre}
::msgcat::mcset fr Message               {Message}
::msgcat::mcset fr Middle                {Milieu}
::msgcat::mcset fr Minutes               {Minutes}
::msgcat::mcset fr Moderator             {Modérateur}
::msgcat::mcset fr moderator             {modérateur}
::msgcat::mcset fr Moderators            {Modérateurs}
::msgcat::mcset fr More                  {Plus}
::msgcat::mcset fr Name                  {Nom}
::msgcat::mcset fr Network               {Réseau}
::msgcat::mcset fr Never                 {Jamais}
::msgcat::mcset fr New                   {Nouveau}
::msgcat::mcset fr Next                  {Suivant}
::msgcat::mcset fr Nickname              {Pseudonyme}
::msgcat::mcset fr No                    {Non}
::msgcat::mcset fr no                    {non}
::msgcat::mcset fr None                  {Aucun}
::msgcat::mcset fr Notes                 {Notes}
::msgcat::mcset fr Occupation            {Occupé}
::msgcat::mcset fr Offline               {Déconnecté}
::msgcat::mcset fr OK                    {OK}
::msgcat::mcset fr Online                {Connecté}
::msgcat::mcset fr Open                  {Ouvrir}
::msgcat::mcset fr Owner                 {Propriétaire}
::msgcat::mcset fr owner                 {propriétaire}
::msgcat::mcset fr Participants          {Participants}
::msgcat::mcset fr Password              {Mot de passe}
::msgcat::mcset fr Personal              {Personnel}
::msgcat::mcset fr Phone                 {Téléphone}
::msgcat::mcset fr Play                  {Lire}
::msgcat::mcset fr Plugins               {Greffons}
::msgcat::mcset fr Port                  {Port}
::msgcat::mcset fr Ports                 {Ports}
::msgcat::mcset fr Preferences           {Préférences}
::msgcat::mcset fr Previous              {Précédent}
::msgcat::mcset fr Print                 {Imprimer}
::msgcat::mcset fr Priority              {Priorité}
::msgcat::mcset fr Profile               {Profil}
::msgcat::mcset fr Profiles              {Profils}
::msgcat::mcset fr Progress              {Progression}
::msgcat::mcset fr Proxy                 {Proxy}
::msgcat::mcset fr Quit?                 {Quitter ?}
::msgcat::mcset fr Quote                 {Citer}
::msgcat::mcset fr Rate                  {Noter}
::msgcat::mcset fr Region                {Région}
::msgcat::mcset fr Register              {S'enregistrer}
::msgcat::mcset fr Remaining             {Restant}
::msgcat::mcset fr Remove                {Enlever}
::msgcat::mcset fr Reply                 {Répondre}
::msgcat::mcset fr Resource              {Ressources}
::msgcat::mcset fr Revoke                {Révoquer}
::msgcat::mcset fr Role                  {Rôle}
::msgcat::mcset fr Running               {En cours}
::msgcat::mcset fr Save                  {Enregistrer}
::msgcat::mcset fr Search                {Chercher}
::msgcat::mcset fr Secured               {Sécurisé}
::msgcat::mcset fr Send                  {Envoyer}
::msgcat::mcset fr Server                {Serveur}
::msgcat::mcset fr Service               {Service}
::msgcat::mcset fr Services              {Services}
::msgcat::mcset fr Settings              {Paramètres}
::msgcat::mcset fr Shortcut              {Raccourci}
::msgcat::mcset fr Shortcuts             {Raccourcis}
::msgcat::mcset fr Size                  {Taille}
::msgcat::mcset fr Skin                  {Skin}
::msgcat::mcset fr Sleep                 {Sleep}
::msgcat::mcset fr Sounds                {Sons}
::msgcat::mcset fr Specific              {Spécifique}
::msgcat::mcset fr Status                {Statut}
::msgcat::mcset fr Stop                  {Arrêter}
::msgcat::mcset fr Subject               {Sujet}
::msgcat::mcset fr System                {Système}
::msgcat::mcset fr Text                  {Texte}
::msgcat::mcset fr Theme                 {Thème}
::msgcat::mcset fr Time                  {Heure}
::msgcat::mcset fr Timeout               {Timeout}
::msgcat::mcset fr Title                 {Titre}
::msgcat::mcset fr Topic                 {Thème}
::msgcat::mcset fr Transports            {Transports}
::msgcat::mcset fr Type                  {Type}
::msgcat::mcset fr Unregister            {Se désinscrire}
::msgcat::mcset fr Username              {Nom d'utilisateur}
::msgcat::mcset fr Version               {Version}
::msgcat::mcset fr Visitors              {Visiteurs}
::msgcat::mcset fr Voice                 {Voix}
::msgcat::mcset fr voice                 {voix}
::msgcat::mcset fr Volume                {Volume}
::msgcat::mcset fr Warning               {Attention}
::msgcat::mcset fr Website               {Site web}
::msgcat::mcset fr Whiteboard            {Tableau blanc}
::msgcat::mcset fr Width                 {Largeur}
::msgcat::mcset fr Work                  {Travailler}
::msgcat::mcset fr Yes                   {Oui}
::msgcat::mcset fr yes                   {oui}

# A few words that are not unambiguous and have therefore a prefix:
# Note to translators: this means "Application" as in computer program.
::msgcat::mcset fr program-Application   {Application}
::msgcat::mcset fr machine-Sleep         {Sleep}

# Try to move next strings to normal strings
# Canvas item options, names and values.
# Names:
::msgcat::mcset fr anchor                {Ancre}
::msgcat::mcset fr arrow                 {Flèche}
::msgcat::mcset fr arrowshape            {Forme de flèche}
::msgcat::mcset fr capstyle              {Cap Style}
::msgcat::mcset fr dash                  {Tiret}
::msgcat::mcset fr fill                  {Remplir}
::msgcat::mcset fr fontfamily            {Famille de police}
::msgcat::mcset fr fontsize              {Taille de police}
::msgcat::mcset fr fontweight            {Graisse de police}
::msgcat::mcset fr image                 {Image}
::msgcat::mcset fr joinstyle             {Style de jointure}
::msgcat::mcset fr justify               {Justifier}
::msgcat::mcset fr outline               {Surligner}
::msgcat::mcset fr outlinestipple        {Outline Stipple}
::msgcat::mcset fr smooth                {Smooth}
::msgcat::mcset fr stipple               {Stipple}
::msgcat::mcset fr tags                  {Tags}
::msgcat::mcset fr text                  {Texte}
::msgcat::mcset fr width                 {Largeur}

# Values (see item inspector to see what they mean):
# anchor
::msgcat::mcset fr n                     {N}
::msgcat::mcset fr ne                    {NE}
::msgcat::mcset fr e                     {E}
::msgcat::mcset fr se                    {SE}
::msgcat::mcset fr s                     {S}
::msgcat::mcset fr sw                    {SO}
::msgcat::mcset fr w                     {O}
::msgcat::mcset fr nw                    {NO}
::msgcat::mcset fr center                {Centre}
# arrow
::msgcat::mcset fr last                  {Dernier}
::msgcat::mcset fr first                 {Premier}
::msgcat::mcset fr both                  {Les deux}

::msgcat::mcset fr transparent           {Transparent}
::msgcat::mcset fr gray75                {Gris 75%}
::msgcat::mcset fr gray50                {Gris 50%}
::msgcat::mcset fr gray25                {Gris 25%}
::msgcat::mcset fr gray12                {Gris 12%}

::msgcat::mcset fr round                 {Round}
::msgcat::mcset fr miter                 {Miter}
::msgcat::mcset fr bevel                 {Bevel}
::msgcat::mcset fr butt                  {Butt}
::msgcat::mcset fr projecting            {Projecting}

::msgcat::mcset fr normal                {Normal}
::msgcat::mcset fr bold                  {Gras}
::msgcat::mcset fr italic                {Italique}

::msgcat::mcset fr left                  {Gauche}
::msgcat::mcset fr right                 {Droite}
::msgcat::mcset fr false                 {Faux}
::msgcat::mcset fr true                  {Vrai}

# dashes
::msgcat::mcset fr none                  {Aucun}
::msgcat::mcset fr dotted                {Points}
::msgcat::mcset fr dash-dotted           {Tirets mixtes}
::msgcat::mcset fr dashed                {Tirets}


# Status messages.
::msgcat::mcset fr available             {disponible}
::msgcat::mcset fr away                  {absent}
::msgcat::mcset fr {do not disturb}      {ne pas déranger}
::msgcat::mcset fr {not available}       {indisponible}
::msgcat::mcset fr {extended away}       {absent pour longtemps}
::msgcat::mcset fr invisible             {invisible}
::msgcat::mcset fr chat                  {discussion}

# All menu labels; concateneted and prepended with 'm' for the database key.
::msgcat::mcset fr mAboutCoccinella      {À propos de Coccinella...}
::msgcat::mcset fr mAboutQuickTimeTcl    {À propos de QuickTimeTcl}
::msgcat::mcset fr mAction               {Action}
::msgcat::mcset fr mAddToDictionary      {Ajouter au dictionnaire}
::msgcat::mcset fr mAdHocCommands        {Commandes Ad-Hoc}
::msgcat::mcset fr mAddContact...        {&Ajouter contact...}
::msgcat::mcset fr mAddSpeechBubble      {Ajouter une bulle}
::msgcat::mcset fr mAll                  {Tous}
::msgcat::mcset fr mArc                  {Arc}
::msgcat::mcset fr mArcs                 {Arcs}
::msgcat::mcset fr mAttachMessage        {Message joint...}
::msgcat::mcset fr mAvailable            {Disponible}
::msgcat::mcset fr mAway                 {Absent}
::msgcat::mcset fr mBackgroundColor...   {Couleur de fonds...}
::msgcat::mcset fr mBackgroundImage      {Image de fonds}
::msgcat::mcset fr mBackgroundImage...   {Image de fonds...}
::msgcat::mcset fr mBold                 {Gras}
::msgcat::mcset fr mBrushThickness       {Épaisseur de la brosse}
::msgcat::mcset fr mBugReport...         {&Rapporter un bug...}
::msgcat::mcset fr mBusinessCard...      {Visionner la carte de visite (&b)...}
::msgcat::mcset fr mBC...                {Carte de visite (&b)...}
::msgcat::mcset fr mCall                 {Appeler}
::msgcat::mcset fr mChat                 {Discussion}
::msgcat::mcset fr mChat...              {Discussion...}
::msgcat::mcset fr mChord                {Corde}
::msgcat::mcset fr mClear                {Effacer}
::msgcat::mcset fr mClearMenu            {Effacer menu}
::msgcat::mcset fr mCloseWindow          {&Fermer la fenêtre}
::msgcat::mcset fr mCoccinellaHome...    {&Page de Coccinella...}
::msgcat::mcset fr mColor...             {Couleur...}
::msgcat::mcset fr mContacts...          {&Contacts...}
::msgcat::mcset fr mControlPanel         {Panneau de contrôle}
::msgcat::mcset fr mCopy                 {&Copier}
::msgcat::mcset fr mCreateRoom...        {&Créer un salon de discussion...}
::msgcat::mcset fr mCustomStatus...      {Statut personnalisé...}
::msgcat::mcset fr mCut                  {Couper}
::msgcat::mcset fr mDash                 {Pointillés}
::msgcat::mcset fr mDebug                {Débuggage}
::msgcat::mcset fr mDecreasing           {Descendant}
::msgcat::mcset fr mDictionaries         {Dictionnaires}
::msgcat::mcset fr mDiscoverServer...    {&Découvertes du serveur...}
::msgcat::mcset fr mDoNotDisturb         {Ne pas déranger}
::msgcat::mcset fr mEdit                 {Édition}
::msgcat::mcset fr mEditBookmarks...     {Éditer les marque-pages...}
::msgcat::mcset fr mEditBC...            {Éditer la carte de visite (&b)...}
::msgcat::mcset fr mEditContact...       {&Éditer le contact...}
::msgcat::mcset fr mEditItem...          {&Éditer l'entrée...}
::msgcat::mcset fr mEditNick             {Éditer pseudonyme}
::msgcat::mcset fr mEditProfiles...      {&Éditer les profils...}
::msgcat::mcset fr mEnterRoom...         {Ent&rer dans le salon de discussion...}
::msgcat::mcset fr mErrorLog             {Messages d'erreur...}
::msgcat::mcset fr mExport               {Exporter}
::msgcat::mcset fr mExportImage...       {Exporter image...}
::msgcat::mcset fr mExportMovie...       {Exporter film...}
::msgcat::mcset fr mExtendedAway         {Absent pour longtemps}
::msgcat::mcset fr mFile                 {Fichier}
::msgcat::mcset fr mFill                 {Remplir}
::msgcat::mcset fr mFillColor...         {Remplir couleur...}
::msgcat::mcset fr mFind                 {Trouver}
::msgcat::mcset fr mFindNext             {Trouver le suivant}
::msgcat::mcset fr mFindPrevious         {Trouver le précédent}
::msgcat::mcset fr mFlip                 {Retourner}
::msgcat::mcset fr mFont                 {Police}
::msgcat::mcset fr mFontSize             {Taille de police}
::msgcat::mcset fr mGrid                 {Grille}
::msgcat::mcset fr mHideControlPanel     {Cacher le panneau de contrôle}
::msgcat::mcset fr mHistory...           {&Historique...}
::msgcat::mcset fr mHorizontal           {Horizontal}
::msgcat::mcset fr mHugeFont             {Géant}
::msgcat::mcset fr mIconSet...           {En&semble d'icônes...}
::msgcat::mcset fr mIgnore               {Ignorer}
::msgcat::mcset fr mImageLarger          {Agrandir l'image}
::msgcat::mcset fr mImageSmaller         {Réduire l'image}
::msgcat::mcset fr mImport               {Importer}
::msgcat::mcset fr mImportImage/Movie... {&Importer image/film...}
::msgcat::mcset fr mInbox...             {Bo&ïte de réception...}
::msgcat::mcset fr mIncreasing           {Ascendant}
::msgcat::mcset fr mInfo                 {Infos}
::msgcat::mcset fr mInvisible            {Invisible}
::msgcat::mcset fr mItalic               {Italique}
::msgcat::mcset fr mJiveCall             {Appeler}
::msgcat::mcset fr mJiveForward          {Faire suivre l'appel}
::msgcat::mcset fr mLargeFont            {Grand}
::msgcat::mcset fr mLarger               {Plus grand}
::msgcat::mcset fr mLargerFont           {Plus grande golice}
::msgcat::mcset fr mLastLogin/Activity   {Dernière connexion/activité}
::msgcat::mcset fr mLibrary              {Bibliothèque}
::msgcat::mcset fr mLineSmoothness       {Lissage de la ligne}
::msgcat::mcset fr mLocalTime            {Heure locale...}
::msgcat::mcset fr mLogin...             {Se connecter...}
::msgcat::mcset fr mLoginTo              {Se connecter à %s}
::msgcat::mcset fr mLoginTrpt            {Se connecter à un transport}
::msgcat::mcset fr mLogout               {Se déconnecter}
::msgcat::mcset fr mLogoutFrom           {Se déconnecter de %s}
::msgcat::mcset fr mLogoutTrpt           {Se déconnecter d'un transport}
::msgcat::mcset fr mLogoutWith...        {Se déconnecter avec le message...}
::msgcat::mcset fr mLower                {Descendre}
::msgcat::mcset fr mMessage...           {&Message...}
::msgcat::mcset fr mMinimal              {Minimal}
::msgcat::mcset fr mMinimize             {Mi&nimiser}
::msgcat::mcset fr mNewAccount...        {Nouveau compte...}
::msgcat::mcset fr mNewWindow            {Nouvelle frenêtre(&w)}
::msgcat::mcset fr mNormal               {Normal}
::msgcat::mcset fr mNotAvailable         {Indisponible}
::msgcat::mcset fr mOffline              {Déconnecté(e)}
::msgcat::mcset fr mOpenFile...          {&Ouvrir Fichier...}
::msgcat::mcset fr mOpenFolder...        {&Ouvrir Dossier...}
::msgcat::mcset fr mOpenStream...        {Ouv&rir flux...}
::msgcat::mcset fr mOutlineColor         {Couleur du contour}
::msgcat::mcset fr mPageSetup            {&Propriétés de la page...}
::msgcat::mcset fr mNewPassword...       {Nouveau mot de p&asse...}
::msgcat::mcset fr mPaste                {Coller}
::msgcat::mcset fr mPieslice             {Part de gâteau}
::msgcat::mcset fr mPlugins              {Greffons}
::msgcat::mcset fr mPreferences          {Préférences}
::msgcat::mcset fr mPreferences...       {&Préférences...}
::msgcat::mcset fr mPrint...             {Im&primer...}
::msgcat::mcset fr mQuit                 {&Quitter}
::msgcat::mcset fr mRaise                {Monter}
::msgcat::mcset fr mRedo                 {Refaire}
::msgcat::mcset fr mRefresh              {Rafraîchir}
::msgcat::mcset fr mRegister...          {S'enregistrer...}
::msgcat::mcset fr mRemoveAccount...     {Efface&r compte...}
::msgcat::mcset fr mRemoveContact        {Enlever le contact...}
::msgcat::mcset fr mRemoveListing        {Enlever le listing}
::msgcat::mcset fr mRestore              {&Restaurer}
::msgcat::mcset fr mSave                 {&Sauvegarder...}
::msgcat::mcset fr mSaveAs               {E&nregistrer sous...}
::msgcat::mcset fr mSaveAsItem           {Enregistrer en tant qu'objet...}
::msgcat::mcset fr mSaveCanvas           {Enregistrer le dessin}
::msgcat::mcset fr mSaveImageAs          {Enregistrer l'&image sous...}
::msgcat::mcset fr mSearch...            {Cherche&r...}
::msgcat::mcset fr mSelectAll            {Selectionner tout (&a)}
::msgcat::mcset fr mSendFile...          {Envoyer un message...}
::msgcat::mcset fr mServer               {&Serveur}
::msgcat::mcset fr mSetupAssistant...    {&Assistant de configuration}
::msgcat::mcset fr mShiftConstrain       {Changer la contrainte}
::msgcat::mcset fr mShow                 {Montrer}
::msgcat::mcset fr mShowControlPanel     {Montrer le panneau de contrôle}
::msgcat::mcset fr mSize                 {Taille}
::msgcat::mcset fr mSlideShow            {Diaporama}
::msgcat::mcset fr mSmaller              {Plus petit}
::msgcat::mcset fr mSort                 {Trier}
::msgcat::mcset fr mCheckSpell           {Vérifier l'orthographe}
::msgcat::mcset fr mStatus               {Statut}
::msgcat::mcset fr mStopTrans            {Stopper les &transactions}
::msgcat::mcset fr mStraighten           {Redresser}
::msgcat::mcset fr mStyle                {Style}
::msgcat::mcset fr mSyncPlayback         {Lecture synchronisée}
::msgcat::mcset fr mTabs                 {Ongle&ts}
::msgcat::mcset fr mTakeSnapShot         {Capturer d'écran}
::msgcat::mcset fr mThickness            {Épaisseur}
::msgcat::mcset fr mTimeCode             {code temporel}
::msgcat::mcset fr mTo45degrees          {Pivoter de 45 degrés}
::msgcat::mcset fr mTo90degrees          {Pivoter de 90 degrés}
::msgcat::mcset fr mToolbar              {Barre d'outils}
::msgcat::mcset fr mTransports           {Transports}
::msgcat::mcset fr mUndo                 {Annuler}
::msgcat::mcset fr mUnregister           {Se désinscrire}
::msgcat::mcset fr mUpdateCheck          {Vérifier les mises-à-jour}
::msgcat::mcset fr mVersion              {Version}
::msgcat::mcset fr mVertical             {Vertical}
::msgcat::mcset fr mWeight               {Largeur}
::msgcat::mcset fr mWhiteboard           {Tableau blanc...}


# Short texts only. Use english text as database key.
::msgcat::mcset fr {About %s}            {À propos de %s}
::msgcat::mcset fr {About QuickTimeTcl}  {À propos de QuickTimeTcl}
::msgcat::mcset fr {Add Contact}         {Ajouter contact}
::msgcat::mcset fr {Add File Type}       {Ajouter un type de fichier}
::msgcat::mcset fr {Add/Edit File Type}  {Ajouter/éditer un type de fichier}
::msgcat::mcset fr {Add Profile}         {Ajouter profil}
::msgcat::mcset fr {Alert sounds}        {Sons d'alerte}
::msgcat::mcset fr {All Supported Files} {Tous les fichiers pris en charge}
::msgcat::mcset fr {Alternative chatroom} {Salon de discussion alternatif}
::msgcat::mcset fr {Always ask}          {Toujours demander}
::msgcat::mcset fr {Application Status}  {Statut de l'application}
::msgcat::mcset fr {Auto Away}           {Départ automatique}
::msgcat::mcset fr {Auto Join}           {Rejoindre automatiquement}
::msgcat::mcset fr {Auto Reply}          {Réponse automatique}
::msgcat::mcset fr Auto-accept           {Accepter automatiquement}
::msgcat::mcset fr Auto-reject           {Rejeter automatiquement}
::msgcat::mcset fr {Blocking support}    {Prise en charge du blocage}
::msgcat::mcset fr {Bookmark this chatroom} {Marquer de salon de discussion}
::msgcat::mcset fr {Broken Image}        {Image cassée}
::msgcat::mcset fr {Buffering support}   {Prise en charge du tampon}
::msgcat::mcset fr {Built in server}     {Serveur intégré}
::msgcat::mcset fr {Business Card}       {Carte de visite}
::msgcat::mcset fr {Cache folder}        {Répertoire du cache}
::msgcat::mcset fr {Changes since previous release} {Changements depuis la précédente version}
::msgcat::mcset fr {Chat system}         {Système de chat}
::msgcat::mcset fr {Chat window}         {Fenêtre de chat}
::msgcat::mcset fr {Chat With}           {Discuter avec}
::msgcat::mcset fr {Chatroom presence change} {Changement de présence dans le salon de discussion}
::msgcat::mcset fr {Clear Cache}         {Purger le cache}
::msgcat::mcset fr {Close page}          {Fermer la page}
::msgcat::mcset fr {Close Slot}         {Fermer le slot}
::msgcat::mcset fr {Close tab}           {Fermer l'onglet}
::msgcat::mcset fr {Configure Chatroom}  {Configurer le salon de discussion}
::msgcat::mcset fr {Contact Actions}     {Cations sur le contact}
::msgcat::mcset fr {Contact Icons}       {Icônes de contact}
::msgcat::mcset fr {Contact ID}          {Identifiant de contact}
::msgcat::mcset fr {Contact Name}        {Nom du contact}
::msgcat::mcset fr {Create Chatroom}     {Créer un salon de discussion}
::msgcat::mcset fr {Create new item for each line of text} {Créer un nouvel objet pour chaque ligne de texte}
::msgcat::mcset fr {Custom Status}       {Statut personnalisé}
::msgcat::mcset fr {Default Applications} {Applications par défaut}
::msgcat::mcset fr {Default group}       {Groupe par défaut}
::msgcat::mcset fr {Default nickname}    {Pseudonyme par défaut}
::msgcat::mcset fr {Delete Profile}      {Effacer le profil}
::msgcat::mcset fr {Disable All}         {Tout désactiver}
::msgcat::mcset fr {Discover permanently} {Découvrir en permanence}
::msgcat::mcset fr {Discover Server}     {Découvrir le serveur}
::msgcat::mcset fr {Disk cache size}     {Taille de cache sur disque}
::msgcat::mcset fr {Edit Bookmarks}      {Éditer les marque-pages}
::msgcat::mcset fr {Do you want to hang up?} {Voulez-vous raccrocher ?}
::msgcat::mcset fr {Edit Business Card}  {Éditer la carte de visite}
::msgcat::mcset fr {Edit Contact}        {Éditer contact}
::msgcat::mcset fr {Edit File Type}      {Éditer le type de fichier}
::msgcat::mcset fr {Edit Item}           {Éditer l'outil}
::msgcat::mcset fr {Edit Profiles}       {Éditer les profils}
::msgcat::mcset fr {Email addresses}     {Adresses courriel}
::msgcat::mcset fr {Email client}        {Client e-mail}
::msgcat::mcset fr {Enable nickname coloring} {Activer la coloration du pseudonyme}
::msgcat::mcset fr {Enter Chatroom}      {Entrer dans le salon de discussion}
::msgcat::mcset fr {Enter/Create Chatroom} {Créer ou entrer dans un salon de discussion}
::msgcat::mcset fr {Exit room}           {Sortir du salon}
::msgcat::mcset fr {Error code}          {Code d'erreur}
::msgcat::mcset fr {External Midi Player} {Lecteur MIDI externe}
::msgcat::mcset fr {Factory Settings}    {Propriétés par défaut}
::msgcat::mcset fr {File Cache}          {Cache}
::msgcat::mcset fr {File Transfer}       {Transfert de fichiers}
::msgcat::mcset fr {File Transfer Error} {Erreur dans le transfert}
::msgcat::mcset fr {File transfer}       {Transfert de fichier}
::msgcat::mcset fr {File Type}           {Type de fichier}
::msgcat::mcset fr {File Types}          {Types de fichier}
::msgcat::mcset fr {First name}          {Prénom}
::msgcat::mcset fr {Font size}           {Taille de police}
::msgcat::mcset fr {Font weight}         {Graisse de police}
::msgcat::mcset fr {Format: mm/dd/yyyy}  {Format : mm/dd/yyyy}
::msgcat::mcset fr {Forwarded message}   {Message transmis}
::msgcat::mcset fr {Full Name}           {Nom complet}
::msgcat::mcset fr {Hide all on system tray click}   {Tout cacher lors d'un clic sur l'icône de notification}
::msgcat::mcset fr {History length}      {Longueur de l'historique}
::msgcat::mcset fr {Import Iconset}      {Importer un ensemble d'icônes}
::msgcat::mcset fr {Incoming Message}    {Message entrant}
::msgcat::mcset fr {Insert emoticon}     {Insérer émoticône}
::msgcat::mcset fr {Invite Contact}      {Inviter contact}
::msgcat::mcset fr {Logged in}           {Connecté(e)}
::msgcat::mcset fr {Iconset Archive}     {Archiver l'ensemble d'icônes}
::msgcat::mcset fr {Jabber ID}           {Identifiant Jabber/XMPP}
::msgcat::mcset fr {Last Activity}       {Dernière activité}
::msgcat::mcset fr {Last name}           {Nom de famille}
::msgcat::mcset fr {Loading available chatrooms} {Chargement des salons de discussion disponibles}
::msgcat::mcset fr {Local nickname}      {Pseudonyme local}
::msgcat::mcset fr {Local Time}          {Heure locale}
::msgcat::mcset fr {Logged out}          {Déconnecté(e)}
::msgcat::mcset fr {Login as invisible}  {Se connecter avec le statut "Invisible"}
::msgcat::mcset fr {Logout on sleep}     {Se déconnecter lors d'un sleep}
::msgcat::mcset fr {Logout With Message} {Se déconnecter avec le message}
::msgcat::mcset fr {MIDI command}        {Commande MIDI}
::msgcat::mcset fr {MIDI Player}         {Lecteur MIDI}
::msgcat::mcset fr {MIME type}           {Type MIME}
::msgcat::mcset fr {My Status}           {Mon statut}
::msgcat::mcset fr {NAT Address}         {Adresse NAT}
::msgcat::mcset fr {New Account}         {&Nouvel utilisateur}
::msgcat::mcset fr {New Bookmark}        {Nouveau marque-page}
::msgcat::mcset fr {New Form}            {Nouveau formulaire}
::msgcat::mcset fr {New Message}         {Nouveau message}
::msgcat::mcset fr {New password}        {Nouveau mot de passe}
::msgcat::mcset fr {New Password}        {Nouveau mot de passe}
::msgcat::mcset fr {New Profile}         {Nouveau profil}
::msgcat::mcset fr {New Topic}           {Nouveau sujet}
::msgcat::mcset fr {New Version}         {Nouvelle version}
::msgcat::mcset fr {Incoming chat}       {Discussion entrante}
::msgcat::mcset fr {New chat thread}     {Nouvelle discussion}
::msgcat::mcset fr {Incoming message}    {Message entrant}
::msgcat::mcset fr {New shortcut}        {Nouveau raccourci}
::msgcat::mcset fr {No restriction}      {Pas de restriction}
::msgcat::mcset fr {No registered history for} {Pas d'historique enregistré pour}
::msgcat::mcset fr {More recent than}    {Plus récent que}
::msgcat::mcset fr {Once per session}    {Une fois par session}
::msgcat::mcset fr {Open Business Card}  {Ouvrir la carte de visite}
::msgcat::mcset fr {Open Failed}         {Échec de l'ouverture}
::msgcat::mcset fr {Open File}           {Ouvrir fichier}
::msgcat::mcset fr {Open Folder}         {Ouvrir dossier}
::msgcat::mcset fr {Open Helpfile}       {Ouvrir le fichier d'aide}
::msgcat::mcset fr {Open Image/Movie}    {Ouvrir image/vidéo}
::msgcat::mcset fr {Open Stream}         {Ouvrir streaming}
::msgcat::mcset fr {Open with}           {Ouvrir avec}
::msgcat::mcset fr {Own Contact ID}      {Own identifiant du contact}
::msgcat::mcset fr {Own Full Contact ID} {Own identifiant complet du contact}
::msgcat::mcset fr {Plain text password} {Mot de passe plein texte}
::msgcat::mcset fr {Play sound}          {Jouer le son}
::msgcat::mcset fr {Postal code}         {Code postal}
::msgcat::mcset fr {Presence Control}    {Contrôle de la présence}
::msgcat::mcset fr {Presence Error}      {Erreur de présence}
::msgcat::mcset fr {Presence Subscription} {Souscription à la présence}
::msgcat::mcset fr {Profile Name}        {Nom du profil}
::msgcat::mcset fr {Receive File}        {Recevoir fichier}
::msgcat::mcset fr {Recent Avatars}      {Avatars récents}
::msgcat::mcset fr {Reject file}         {Rejeter fichier}
::msgcat::mcset fr {Relogin on activity} {Se reconnecter lors d'une activité}
::msgcat::mcset fr {Relogin on wakeup}   {Se reconnecter lors d'un réveil}
::msgcat::mcset fr {Remove Account}      {Effacer compte}
::msgcat::mcset fr {Remove Avatar}       {Effacer avatar}
::msgcat::mcset fr {Remove Contact}      {Effacer contact}
::msgcat::mcset fr {Remove Item}         {Supprimer l'entrée}
::msgcat::mcset fr {Requires a restart of} {Requiert un redémarrage de %s}
::msgcat::mcset fr {Retype password}     {Retaper le mot de passe}
::msgcat::mcset fr {Right click to open menu} {Cliquer-droit pour ouvrir le menu}
::msgcat::mcset fr {Save As}             {Enregistrer sous}
::msgcat::mcset fr {Save As GIF}         {Enregistrer en format GIF}
::msgcat::mcset fr {Save Canvas Item}    {Sauvegarder l'entrée canvas}
::msgcat::mcset fr {Save File}           {Enregistrer le fichier}
::msgcat::mcset fr {Save Message}        {Enregistrer le message}
::msgcat::mcset fr {Save password}       {Sauver le mot de passe}
::msgcat::mcset fr {Save to disk}        {Sauvegarder sur disque}
::msgcat::mcset fr {Search People}       {Rechercher des contacts}
::msgcat::mcset fr {Search results}      {Chercher les résultats}
::msgcat::mcset fr {Select Avatar}       {Selectionner avatar}
::msgcat::mcset fr {Select File}         {Selectionner fichier}
::msgcat::mcset fr {Select Font}         {Choisir police}
::msgcat::mcset fr {Select Server}       {Selectionner serveur}
::msgcat::mcset fr {Send File}           {Envoyer fichier}
::msgcat::mcset fr {Send Live}           {Envoyer live}
::msgcat::mcset fr {Set Status}          {Changer le statut}
::msgcat::mcset fr {Setup Assistant}     {Assistant de configuration}
::msgcat::mcset fr {Show Icon}           {Montrer l'icône}
::msgcat::mcset fr {Show navigation buttons} {Montrer les boutons de navigation}
::msgcat::mcset fr {Show notifier window} {Monter la fenêtre de notification}
::msgcat::mcset fr {Show popup}          {Montrer popup}
::msgcat::mcset fr {Show offline users}  {Montrer les utilisateurs en hors ligne}
::msgcat::mcset fr {Show Text}           {Montrer texte}
::msgcat::mcset fr {Show Text and Icon}  {Montrer texte et icônes}
::msgcat::mcset fr {Show transports}     {Montrer transports}
::msgcat::mcset fr {Smooth freehand strokes} {Smooth freehand strokes}
::msgcat::mcset fr {Sound set}           {Ensemble de sons}
::msgcat::mcset fr {Start chat}          {Démarrer discussion}
::msgcat::mcset fr {Start minimized in system tray} {Démarrer minimisé dans la zone de notification}
::msgcat::mcset fr {Start minimized in taskbar} {Démarrer minimisé dans la barre des tâches}
::msgcat::mcset fr {Status Info}         {Info de statut}
::msgcat::mcset fr {Status message}      {Message du statut}
::msgcat::mcset fr {Subscription Failed} {Échec de l'enregistrement}
::msgcat::mcset fr {Subscription Pending} {Enregistrement en attente}
::msgcat::mcset fr {Synchronise cache}   {Synchroniser le cache}
::msgcat::mcset fr {Take Snapshot}       {Capture d'écran}
::msgcat::mcset fr {Tel (fax)}           {Fax}
::msgcat::mcset fr {Tel (voice)}         {Téléphone}
::msgcat::mcset fr Text-to-Speech        {Synthèse vocale}
::msgcat::mcset fr {Thread started}      {Flux initialisé}
::msgcat::mcset fr {Update Check}        {Vérifier les mises à jour}
::msgcat::mcset fr {Use HTTP transport}  {Utiliser un transport HTTP}
::msgcat::mcset fr {Use SASL authentication} {Utiliser l'authentification SASL}
::msgcat::mcset fr {Use SSL for security} {Utiliser SSL pour la sécurité}
::msgcat::mcset fr {Use TLS and SASL}    {Utiliser TLS et SASL}
::msgcat::mcset fr {Use TLS on separate port (old)} {Utiliser TLS sur un port séparé (ancien)}
::msgcat::mcset fr {Use proxy}           {Utiliser un proxy}
::msgcat::mcset fr {Use secure connection} {Utiliser une connexion sécurisée}
::msgcat::mcset fr {Use compression}     {Utiliser la compression}
::msgcat::mcset fr {User Activity}       {Activité de l'utilisateur}
::msgcat::mcset fr {Contact is offline}  {Le contact est hors ligne}
::msgcat::mcset fr {Contact is online}   {Le contact est en ligne}
::msgcat::mcset fr {Contact presence change} {Changement de présence du contact}
::msgcat::mcset fr {Username & Password} {Nom et mot de passe}
::msgcat::mcset fr {View Business Card}  {Voir la carte de visite}
::msgcat::mcset fr {View business card}  {Voir la carte de visite}

::msgcat::mcset fr {Windows opacity}     {Opacité de la fenêtre}
::msgcat::mcset fr {Writing file}        {Écriture du fichier}

# Chatrooms.
::msgcat::mcset fr {Kick Participant}    {Éjecter participant}
::msgcat::mcset fr {Ban Participant}     {Bannir participant}
::msgcat::mcset fr {Destroy Chatroom}    {Détruire le salon de discussion}
::msgcat::mcset fr {Edit Lists}          {Éditer les listes}
::msgcat::mcset fr {Edit the voice list} {Éditer la liste des voice}
::msgcat::mcset fr {Edit the ban list}   {Éditer la liste des bannissements}
::msgcat::mcset fr {Edit the member list} {Éditer la liste des membres}
::msgcat::mcset fr {Edit the moderator list} {Éditer la liste des modérateurs}
::msgcat::mcset fr {Edit the admin list} {Éditer la liste des administrateurs}
::msgcat::mcset fr {Edit the owner list} {Éditer la liste des propriétaires}

# Naming of protocol systems and their identifiers.
# Low priority.
::msgcat::mcset fr Email                 {E-mail}
::msgcat::mcset fr {Screen Name}         {Screen Name}
::msgcat::mcset fr {Gadu-Gadu Number}    {Numéro Gadu-Gadu}
::msgcat::mcset fr {ICQ Number}          {Numéro ICQ}
::msgcat::mcset fr IRC                   {IRC}
::msgcat::mcset fr {MSN Address}         {Adresse MSN}
::msgcat::mcset fr {Email Address}       {Adresse E-mail}
::msgcat::mcset fr {QQ Number}           {Numéro QQ}
::msgcat::mcset fr {Tlen Address}        {Adresse Tlen}
::msgcat::mcset fr {Jabber ID}           {Identifiant Jabber}
::msgcat::mcset fr {Yahoo ID}            {Identifiant Yahoo}

# Time intervals.
::msgcat::mcset fr {Ten seconds}         {Dix secondes}
::msgcat::mcset fr {One minute}          {Une minute}
::msgcat::mcset fr {Ten minutes}         {Dix minutes}
::msgcat::mcset fr {One hour}            {Une heure}

# Language names.
::msgcat::mcset fr Czech                 {Tchèque}
::msgcat::mcset fr Danish                {Danois}
::msgcat::mcset fr Dutch                 {Néerlandais}
::msgcat::mcset fr English               {Anglais}
::msgcat::mcset fr French                {Français}
::msgcat::mcset fr German                {Allemand}
::msgcat::mcset fr Italian               {Italien}
::msgcat::mcset fr Korean                {Coréen}
::msgcat::mcset fr Polish                {Polonais}
::msgcat::mcset fr Russian               {Russe}
::msgcat::mcset fr Spanish               {Espagnol}
::msgcat::mcset fr Swedish               {Suédois}

# Same languge names but with their native names.
# See the other catalogs to get these.
::msgcat::mcset fr nativeCzech           {Čeština}
::msgcat::mcset fr nativeDanish          {Dansk}
::msgcat::mcset fr nativeDutch           {Nederlands}
::msgcat::mcset fr nativeEnglish         {English}
::msgcat::mcset fr nativeFrench          {Français}
::msgcat::mcset fr nativeGerman          {Deutsch}
::msgcat::mcset fr nativeItalian         {Italiano}
::msgcat::mcset fr nativeKorean          {한국어}
::msgcat::mcset fr nativePolish          {Polski}
::msgcat::mcset fr nativeRussian         {русский}
::msgcat::mcset fr nativeSpanish         {Castellano}
::msgcat::mcset fr nativeSwedish         {Svenska}


# Splash screen:
::msgcat::mcset fr splashsource          {Mise en source du code Tcl...}
::msgcat::mcset fr splashload            {Chargement des paquetages Tcl...}
::msgcat::mcset fr splashsourcejabb      {Chargement des sources de Jabber...}
::msgcat::mcset fr splashhost            {Recherche du nom d'hôte...}
::msgcat::mcset fr splashinit            {Initialisation...}
::msgcat::mcset fr splashprefs           {Chargement et application des préférences...}
::msgcat::mcset fr splashlook            {Recherche de}

# Subscriptions:
::msgcat::mcset fr subscriptionBoth      {Vous et votre contact pouvez voir la présence de chacun.}
::msgcat::mcset fr subscriptionFrom      {Vous ne pouvez pas voir la présence de votre contact, mais votre contact peut voir la vôtre.}
::msgcat::mcset fr subscriptionNone      {Vous et votre contact ne pouvez pas voir la présence d'aucun.}
::msgcat::mcset fr subscriptionTo        {Vous pouvez voir la présence de votre contact, mais votre contact ne peut pas voir la vôtre.}


# Messages for tk_messageBox:
::msgcat::mcset fr messaskreceive        {Prêt à recevoir %s, voulez-vous le recevoir ?}
::msgcat::mcset fr messaupdatelatest     {Vous avez déjà la dernière version (%s)}
::msgcat::mcset fr messcanerasewarn2     {Ouvrir un fichier de tableau blanc efface le tableau blanc courant !}
::msgcat::mcset fr messdoquit?           {Êtes-vous sûr de vouloir quitter ?}
::msgcat::mcset fr messerrpreffile2      {Ouverture de %s impossible}
::msgcat::mcset fr messfactorydefaults2  {Voulez-vous réellement effecer vos personalisations et revenir aux réglages d'usine ?}
::msgcat::mcset fr messfailedhttp2       {Démarrage du serveur HTTP interne impossible : %s}
::msgcat::mcset fr messfailmimeimp2      {Pas d'import pour le type MIME %s}
::msgcat::mcset fr messfailopread2       {Lecture impossible de %s : %s}
::msgcat::mcset fr messfailopwrite2      {Écriture impossible sur %s : %s}
::msgcat::mcset fr messfailserver2       {Démarrage du socket serveur impossible, peut-être que vous n'êtes pas connecté(e)}
::msgcat::mcset fr messfieldsmissing     {Un ou plusieurs champs sont vides, recommencez ou annulez}
::msgcat::mcset fr messfillserveruser    {Vous devez au moins remplir le nom de l'utilisateur et du serveur}
::msgcat::mcset fr messnoplugs           {Il n'y a pas de plugin ou d'aide détectée sur ce système}
::msgcat::mcset fr messpasswddifferent2  {Les mots de passes son différents, réessayer}
::msgcat::mcset fr messprefschanged      {Les préférences ont été changées, voulez-vous tout de même annuler ?}
::msgcat::mcset fr messprefsrestart2     {Au moins un réglage nécessite un redémarrage de %s.}
::msgcat::mcset fr messprintnoextension2 {Extension Tcl introuvable}
::msgcat::mcset fr messrmstandardfonts   {Les polices standard Times, Helvetica et Courier ne peuvent pas être supprimées}
::msgcat::mcset fr messsuassclose        {Êtes-vous sûr de vouloir fermer l'assistant de configuration ? Vous pouvez le relancer ultérieurement depuis le menu}
::msgcat::mcset fr messsuassfillin       {Vérifiez que vous avez complété tous les champs avant de continuer !}
::msgcat::mcset fr messtimeout           {Temps dépassé lors de la connexion}
::msgcat::mcset fr messunsavedmsgQ2      {Ce tableau blanc a changé}
::msgcat::mcset fr messunsaveddtl2       {Voulez-vous sauvegarder les changements ?}

# Messages for tk_messageBox:
::msgcat::mcset fr jamessaddforeign2     {Pour ajouter un contact d'un système de messagerie instantanée non-fédéré, vous devez posséder un compte sur ce système fermé, de plus vous devez enregistrer ce compte sur le transport correspondant (%s). Voulez-vous effectuer ceci maintenant ?}
::msgcat::mcset fr jamessaddrmiss        {Vous devez renseigner au moins une adresse correcte}
::msgcat::mcset fr jamessallowsub2       {%s vous autorise à voir sa présence}
::msgcat::mcset fr jamessalreadyinrost2  {%s est déjà dans votre liste de contacts, voulez-vous continuer ?}
::msgcat::mcset fr jamessaskregister     {Voulez-vous enregistrer un nouveau compte ?}
::msgcat::mcset fr jamessautoaccepted2   {%s peut voir votre présence}
::msgcat::mcset fr jamessautoreject2     {%s ne peut pas voir votre présence}
::msgcat::mcset fr jamessautosubs2       {Vous pouvez voir la présence de %s}
::msgcat::mcset fr jamessavaerrsize      {L'avatar doit être carré de taille %s}
::msgcat::mcset fr jamessbadjid2         {%s est invalide, voulez-vous continuer ?}
::msgcat::mcset fr jamesschatclose2      {Do you want to close this chat window and loose the complete conversation?}
::msgcat::mcset fr jamesschatinvite      {Do you want to invite this contact to a new chatroom?}
::msgcat::mcset fr jamesschatoffline2    {This contact is not online anymore and the message is therfore not sent.}

::msgcat::mcset fr jamessconffailed2     {Cannot enter/create chatroom %s.}
::msgcat::mcset fr jamessconnbroken      {La connexion a été inopinément coupée}
::msgcat::mcset fr jamessemoticonexists  {Iconset %s already exists.}
::msgcat::mcset fr jamessemoticonfail2   {Cannot load iconset %s.}
::msgcat::mcset fr jamessenterroomretry2 {Cannot enter chatroom %s: %s Do you want to retry?}
::msgcat::mcset fr jamesserrautouphttp2  {Cannot connect to server %s to download update details: %s}
::msgcat::mcset fr jamesserrconfgetcre2  {Cannot download the configuration form of the chatroom.}
::msgcat::mcset fr jamesserrinboxopen2   {Cannot open the inbox file %s when trying to save it.}
::msgcat::mcset fr jamesserrinboxread2   {Cannot read the inbox file %s: %s}
::msgcat::mcset fr jamesserrlastactive2  {Cannot query %s's last activity.}
::msgcat::mcset fr jamesserrnotimeinfo2  {Cannot query %s's local time information.}
::msgcat::mcset fr jamesserrregget2      {Cannot obtain registration information.}
::msgcat::mcset fr jamesserrregset2      {Cannot register with service %s.}
::msgcat::mcset fr jamesserrsearch2      {Cannot obtain search form.}
::msgcat::mcset fr jamesserrsend2        {Cannot send message to %s.}
::msgcat::mcset fr jamesserrtime2        {Cannot query %s's local time.}
::msgcat::mcset fr jamesserrunreg2       {Cannot unregister from %s.}
::msgcat::mcset fr jamesserrvers2        {Cannot query %s's version.}
::msgcat::mcset fr jamessfailedsubsc2    {Cannot subscribe to %s's presence. The contact does not allow you to see his/her presence.}
::msgcat::mcset fr jamessfailsetnick2    {Cannot set %s's nickname or group.}
::msgcat::mcset fr jamessfatalerr        {Receieved a fatal error: %s The connection is closed.}
::msgcat::mcset fr jamessfiletrpterr2    {Cannot download file %s from %s.}
::msgcat::mcset fr jamessfilenotexist    {The selected file does not exist. Select a new one.}
::msgcat::mcset fr jamessfilemd5         {The MD5 checksums did not match. The file may be corrupt.}
::msgcat::mcset fr jamessgchatfields2    {Please fill in all fields before entering chatroom.}
::msgcat::mcset fr jamessgcinvite2       {%s invited you to %s. Do you want to enter this chatroom?}
::msgcat::mcset fr jamessgcnoroomname2   {You must provide a chatroom name.}
::msgcat::mcset fr jamessgcnoroomnick    {Vous devez fournir un pseudo.}
::msgcat::mcset fr jamessgeneditwarnclose2 {You changed one or more values. Do you want to save them before closing?}
::msgcat::mcset fr jamessillegalchar     {Le(s) caractère(s) illégal(aux) dans %s sont : "%s" !}
::msgcat::mcset fr jamessillformresend2  {Invalid Contact ID: %s. Please correct and resend.}
::msgcat::mcset fr jamessimagecreateerr  {Cannot create an image from %s.}
::msgcat::mcset fr jamessinvalidjid2     {Invalid Contact ID. You need to enter a valid one at the bottom (e.g. username@jabber.org).}
::msgcat::mcset fr jamessjidinvalid2     {Invalid Contact ID.}
::msgcat::mcset fr jamesslocaltime2      {%s's local time is: %s}
::msgcat::mcset fr jamesslogin409b       {Cannot login because this username is already in use by someone else (%s).}
::msgcat::mcset fr jamessloginnewprof    {The Contact ID differs from your profile. Do you want to save a new profile?}
::msgcat::mcset fr jamesslogindiff       {Your current login settings differ from your profile settings. Do you want to save them to your profile?}
::msgcat::mcset fr jamessmsgwarnquit     {There are unsaved messages. Do you still want to quit?}
::msgcat::mcset fr jamessnamemissing     {%s manque ou est trop court !}
::msgcat::mcset fr jamessnofiletrpt2     {%s does not support file transfer.}
::msgcat::mcset fr jamessnofile2         {You must select a file to send.}
::msgcat::mcset fr jamessnogroupchat2    {Cannot find any chatroom service.}
::msgcat::mcset fr jamessnorooms2        {Cannot find any chatrooms at %s.}
::msgcat::mcset fr jamessnosocket3       {Cannot connect to %s. Either there are server or network issues, or you misspelled the server's name.}
::msgcat::mcset fr jamessnotconnected2   {Cannot send when not logged in.}
::msgcat::mcset fr jamessokreg2          {Registration with service %s was successful.}
::msgcat::mcset fr jamessokunreg2        {You are unregistered from %s.}
::msgcat::mcset fr jamessoobask2         {%s wants to send you this file: %sDo you want to receive this file?}
::msgcat::mcset fr jamessoobbad2         {Received invallid URL from %s. URL: %s}
::msgcat::mcset fr jamessooberr404b      {Cannot send the file %s to %s.}
::msgcat::mcset fr jamessooberr406b      {%s did not accepted the file %s.}
::msgcat::mcset fr jamessoobfailopen2    {Cannot open file %s}
::msgcat::mcset fr jamessoobnourl2       {%s did not sent the download location of the file.}
::msgcat::mcset fr jamessoobok2          {Transfert de %s à %s effectué.}
::msgcat::mcset fr jamessoobtimeout2     {Cannot download file over HTTP: timeout.}
::msgcat::mcset fr jamessoonnohttp2      {The URL from %s does not use the HTTP protocol, but instead %s which is not supported.}
::msgcat::mcset fr jamessowntrpt2        {This is your own account at %s that acts as a service that transports messages to that IM system. It needs to be in your list. You have a subscription for %s: %s.}
::msgcat::mcset fr jamesspasswderr2      {Cannot set new password.}
::msgcat::mcset fr jamesspasswdok        {Le nouveau mot de passe est enregistré.}
::msgcat::mcset fr jamessprofaskrem2     {The selected profile will be deleted. Do you also want to delete the account for this profile? This action cannot be undone. Press Cancel to abort deletion of account and profile.}
::msgcat::mcset fr jamessproxy-failure2  {The proxy server reported an error.}
::msgcat::mcset fr jamessregerr2         {The registration failed.}
::msgcat::mcset fr jamessregerrinuse2    {The registration failed because this username is already in use by someone else.}
::msgcat::mcset fr jamessregisterok2     {The registration with %s was successful. Now you just need to Login using the same username and password.}
::msgcat::mcset fr jamessregloginok      {Vous êtes maintenant identifié et automatiquement connecté en tant que "%s"}
::msgcat::mcset fr jamessregnoserver2    {Please enter or select first a server.}
::msgcat::mcset fr jamessremoveaccount2  {Do you really want to remove your account? This process cannot be undone.}
::msgcat::mcset fr jamesssavemsg         {Voulez-vous enregistrer le message ?}
::msgcat::mcset fr jamesssearcherr       {Cannot search.}
::msgcat::mcset fr jamesssearchinval2    {There was an invalid field. Please correct it.}
::msgcat::mcset fr jamessskipsendq2      {Contact ID %s is invalid. Do you want to skip it and send to the rest?}
::msgcat::mcset fr jamessstatuscust2     {Select a presence state and optionally enter a message.}
::msgcat::mcset fr jamessstatuscustdtl2  {The most frequent combinations are easily reachable as menu entries.}
::msgcat::mcset fr jamesssubscautoacc    {Subscription request will be accepted in: %s secs.}
::msgcat::mcset fr jamesssubscautorej    {Subscription request will be rejected in: %s secs.}
::msgcat::mcset fr jamesssubscedfancy    {%s additional contacts can see your presence.}
::msgcat::mcset fr jamesstimeconn2       {Time since %s was last connected}
::msgcat::mcset fr jamesstimeoutserver2  {Server %s did not respond: timeout.}
::msgcat::mcset fr jamesstimeservstart2  {Time since server %s was started}
::msgcat::mcset fr jamesstimeused2       {Time since client %s was last active}
::msgcat::mcset fr jamesstrptsubsc       {Votre compte enregistré avec le service %s sera ajouté à vos contacts pour fonctionner comme un serveur de transport avec le service.}
::msgcat::mcset fr jamessunsub2          {Because %s does not allow you to see his/her presence anymore, he/she is removed.}
::msgcat::mcset fr jamessunsubask2       {%s does not allow you to see his/her presence anymore. Do you want to remove %s?}
::msgcat::mcset fr jamessunsubpres2      {%s does not allow you to see his/her presence anymore.}
::msgcat::mcset fr jamessunsubscribed2   {You cannot see %s's presence anymore.}
::msgcat::mcset fr jamessuptime2         {The uptime/last activity is}
::msgcat::mcset fr jamesswarnexitroom2   {Do you want to exit the chatroom %s?}
::msgcat::mcset fr jamesswarnremove2     {Do you really want to remove this contact? This action cannot be undone.}
::msgcat::mcset fr jamesswarnsendcanoff2 {%s is not online. If your message contains any images or other multimedia, your contact will not see them unless you are online while he/she reads your message. Do you want to send it anyway?}
::msgcat::mcset fr jamesswbchatlost2     {Do you want to close this whiteboard and lose the complete session?}


# This maps Defined Error Conditions to clear text messages.
# RFC 3929 (XMPP Core): 6.4 SASL Errors
# 
# These are much too formal to be used for user display and we therfore instead use the short forms below.
# Do not translate these, just for reference.
::msgcat::mcset fr xmpp-stanzas-aborted  {The receiving entity acknowledges an abort element sent by the initiating entity.}
::msgcat::mcset fr xmpp-stanzas-incorrect-encoding {The data provided by the initiating entity could not be processed because the [BASE64] encoding is incorrect.}
::msgcat::mcset fr xmpp-stanzas-invalid-authzid {The authzid provided by the initiating entity is invalid, either because it is incorrectly formatted or because the initiating entity does not have permissions to authorize that ID.}
::msgcat::mcset fr xmpp-stanzas-invalid-mechanism {The initiating entity did not provide a mechanism or requested a mechanism that is not supported by the receiving entity.}
::msgcat::mcset fr xmpp-stanzas-mechanism-too-weak {The mechanism requested by the initiating entity is weaker than server policy permits for that initiating entity.}
::msgcat::mcset fr xmpp-stanzas-not-authorized {The authentication failed because the initiating entity did not provide valid credentials (this includes but is not limited to the case of an unknown username).}
::msgcat::mcset fr xmpp-stanzas-temporary-auth-failure {The authentication failed because of a temporary error condition within the receiving entity.}

# Short messages in place of the above ones.
::msgcat::mcset fr xmpp-stanzas-short-aborted {The login process was aborted.}
::msgcat::mcset fr xmpp-stanzas-short-incorrect-encoding {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-invalid-authzid {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-invalid-mechanism {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-mechanism-too-weak {Protocol error during the login process.}
::msgcat::mcset fr xmpp-stanzas-short-not-authorized {Login failed because of unknown user or wrong password.}
::msgcat::mcset fr xmpp-stanzas-short-temporary-auth-failure {Protocol error during the login process.}


# Related error conditions detected by the client.
::msgcat::mcset fr starttls-nofeature    {Le serveur "%s" ne supporte pas le TLS.}
::msgcat::mcset fr starttls-failure      {Erreur lors de la sécurisation TLS avec le serveur "%s".}
::msgcat::mcset fr sasl-no-mechanisms    {The server has no support for SASL authentication.}
::msgcat::mcset fr sasl-protocol-error   {Authentication failed due to internal protocol error.}

# A collective description of all stream errors.
::msgcat::mcset fr xmpp-streams-error    {We received a stream error from the server with code: %s}


# Account xform balloon help.
# From: JEP-0077: In-Band Registration (http://www.xmpp.org/extensions/xep-0077.html#registrar-formtypes)
# Note to translators: these are tooltips and has lower priority
::msgcat::mcset fr registration-address  {Street portion of a physical or mailing address}
::msgcat::mcset fr registration-city     {Locality portion of a physical or mailing address}
::msgcat::mcset fr registration-date     {Some date (e.g., birth date, hire date, sign-up date)}
::msgcat::mcset fr registration-email    {Email address of the user}
::msgcat::mcset fr registration-first    {First name or given name of the user}
::msgcat::mcset fr registration-is-registered {You are already registered with this service. These are your current settings of your login parameters.}
::msgcat::mcset fr registration-last     {Last name, surname, or family name of the user}
::msgcat::mcset fr registration-name     {Full name of the user}
::msgcat::mcset fr registration-nick     {Familiar name of the user}
::msgcat::mcset fr registration-password {Password or secret for the user}
::msgcat::mcset fr registration-phone    {Telephone number of the user}
::msgcat::mcset fr registration-state    {Region portion of a physical or mailing address}
::msgcat::mcset fr registration-url      {URL to web page describing the user}
::msgcat::mcset fr registration-username {Account name associated with the user}
::msgcat::mcset fr registration-zip      {Postal code portion of a physical or mailing address}

# Map version info tags to display names.
::msgcat::mcset fr version-name          {Name}
::msgcat::mcset fr version-version       {Version}
::msgcat::mcset fr version-os            {Operating system}


::msgcat::mcset fr register-trpt-unreg2  {You are about to unregister a transport with a number of dependent contacts. Do you want to remove these contacts as well (Yes), keep them (No), or cancel everything (Cancel).}

::msgcat::mcset fr reply-prefix          {On %s, %s %s wrote:}

::msgcat::mcset fr printunixcmd          {Commande d'impression, peut être changée}
::msgcat::mcset fr enterpassword         {Entrez le mot de passe pour le compte "%s"}
::msgcat::mcset fr wblockitem            {Lock this item from being edited}



::msgcat::mcset fr httptrptok2           {Download of file %s finished.}
::msgcat::mcset fr httptrpterror2        {Cannot download the file %s.\nFile transport error: %s}
::msgcat::mcset fr httptrpteof           {Le serveur a arrêté la connexion sans réponse.}
::msgcat::mcset fr httptrptnon200a       {Cannot download the file %s.}
::msgcat::mcset fr httptrptreset         {Le transfert du fichier %s a été relancé}

::msgcat::mcset fr uastatpointmac        {Pointeur (clic : marquer, double clic : inspecter, press : popup)}
::msgcat::mcset fr uastatpoint           {Pointeur (clic : marquer, double clic : inspecter, clic droit : popup)}
::msgcat::mcset fr uastatmove            {Déplacer}
::msgcat::mcset fr uastatline            {Ligne}
::msgcat::mcset fr uastatarrow           {Croix}
::msgcat::mcset fr uastatrect            {Rectangle}
::msgcat::mcset fr uastatoval            {Ellipse}
::msgcat::mcset fr uastattext            {Texte}
::msgcat::mcset fr uastatdel             {Cliquez pour supprimer}
::msgcat::mcset fr uastatpen             {Crayon}
::msgcat::mcset fr uastatbrush           {Brosse}
::msgcat::mcset fr uastatpaint           {Peinture (+ <shift> : transparent)}
::msgcat::mcset fr uastatpoly            {Polygone (<espace> : annuler)}
::msgcat::mcset fr uastatarc             {Arc (clic : définir le centre, <espace> : annuler)}
::msgcat::mcset fr uastatarc2            {Arc (cliquer-déplacer)}
::msgcat::mcset fr uastatrot             {Rotation (d'abord sélectionner les objets)}


# Preferences:
::msgcat::mcset fr prefaaonhidden        {Apply auto-away on hidden chat tabs}
::msgcat::mcset fr prefaabusychats       {Do Not Disturb when (active chat sessions)}
::msgcat::mcset fr prefchactret2         {By default use active <Return> to send messages}
::msgcat::mcset fr prefchnormal          {Traiter les messages normaux comme des messages de discussion}
::msgcat::mcset fr prefcu2clk            {Message du double-clic dans la boîte des messages : }
::msgcat::mcset fr prefcuautologin2      {Login on %s startup}
::msgcat::mcset fr prefcuopen            {Ouvrir le message dans une nouvelle fenêtre}
::msgcat::mcset fr prefcuremdlgs2        {Remember open windows between sessions}
::msgcat::mcset fr prefcureply           {Répondre à l'expéditeur}
::msgcat::mcset fr prefcusave            {Enregistrer la boîte de courriers entrants entre les sessions}
::msgcat::mcset fr prefcushow            {Montrer les messages dans une nouvelle fenêtre}
::msgcat::mcset fr prefdirsame           {Store preferences in same folder as program}
::msgcat::mcset fr prefdrivesame2        {Store preferences on same drive as program}
::msgcat::mcset fr prefdriwdef2          {You have chosen to store your preferences in the default location. If you remove or move your personal settings at %s, the preferences in the default location will be used the next time you start %s. Do you want to remove the old preferences?}
::msgcat::mcset fr prefdriwsame          {You have chosen to store your preferences on the same drive as the application. If this drive is not a removable device your personal settings could be visible. Do you want to continue?}
::msgcat::mcset fr preffilecache2        {Amount of cache to store recent whiteboard files to increase speed.}
::msgcat::mcset fr preffontmsg           {Attention : en important d'autres polices que les polices standard (Times, Helvetica ou Courier), vous devez vous assurer que vos correspondants ont également installé ces polices.}
::msgcat::mcset fr preficonsel2          {The selected iconset will become the default.}
::msgcat::mcset fr prefmidimsg           {Set command to use for playing MIDI sounds. This option is only relevant if you use a sound set with MIDI files.}
::msgcat::mcset fr prefminaw2            {Away after}
::msgcat::mcset fr prefminea2            {Extended Away after}
::msgcat::mcset fr prefminlogout         {Logout after}
::msgcat::mcset fr prefnatip2            {Use the following external address}
::msgcat::mcset fr prefplugctrl2         {Select the plugins you want to be loaded.}
::msgcat::mcset fr prefpriv3             {Only edit local whiteboard items}
::msgcat::mcset fr prefpriv4             {Items created by others cannot be edited when enabled}
::msgcat::mcset fr prefprof2             {Edit, add or delete profiles. The selected profile will become the default.}
::msgcat::mcset fr prefprofname2         {Enter the name for the new profile.}
::msgcat::mcset fr prefproxyexc          {Exclude addresses (* as wildcard)}
::msgcat::mcset fr prefproxymsg2         {Usage of this HTTP proxy settings is determined by each profile's settings. File transfers will not work if you use an HTTP proxy.}
::msgcat::mcset fr prefrochat2           {Chat on double-click instead of message}
::msgcat::mcset fr prefroclr2            {Clear list of contacts on logout}
::msgcat::mcset fr prefrorm2             {Remove contact without presence subscription}
::msgcat::mcset fr prefroshowsubno       {Show contacts without any subscription}
::msgcat::mcset fr prefsounpick2         {Enable or disable sounds below}
::msgcat::mcset fr prefsounsynch2        {Text-to-speech for chat}
::msgcat::mcset fr prefsounsynno2        {Text-to-speech for messages}
::msgcat::mcset fr prefsounsynwb2        {Text-to-speech for whiteboard text}
::msgcat::mcset fr prefsounvoin2         {Select voice for incoming text}
::msgcat::mcset fr prefsounvoou2         {Select voice for outgoing write}
::msgcat::mcset fr prefssresize2         {Resize window to fit slides}
::msgcat::mcset fr prefstabui2           {Use tabbed interface}
::msgcat::mcset fr prefsuaasecs          {The dialog is closed after (Seconds)}
::msgcat::mcset fr prefsuaatimer         {If auto-accept/reject show dialog with timer}
::msgcat::mcset fr prefsuauto2           {Put contacts who add me to their list in}
::msgcat::mcset fr prefsuif2             {If someone wants to see my presence and}
::msgcat::mcset fr prefsuis2             {is in my list}
::msgcat::mcset fr prefsuisnot2          {is not in my list}



# obsolete strings in the paragraph?
# EditShortcuts namespace:
namespace eval ::EditShortcuts:: {
::msgcat::mcset fr shortip               {Compléter l'adresse IP ou le nom}
::msgcat::mcset fr shortwarn             {Attention : vous avez édité les raccourcis. Voulez-vous les enregistrer ?}


}


::msgcat::mcset fr jaactiveret           {Si coché, la touche Entrée envoie les messages ; sinon Ctrl/Cmd-Entrée}
::msgcat::mcset fr jaauthok2             {Authorization to server %s was successful. Downloading contacts...}
::msgcat::mcset fr jachathist            {Show or hide the chat history}
::msgcat::mcset fr jacreateroom2         {Select a service, and enter a chatroom and nickname. Optionally, you can configure the chatroom.}
::msgcat::mcset fr jadisaddserv2         {Add a server to discover and use its chatrooms and other services.}
::msgcat::mcset fr jagchatmsg            {Choisissez un groupe de discussion et un nom de salon, ainsi que votre pseudo.}
::msgcat::mcset fr jagcloginmsg          {You entered the chatroom}
::msgcat::mcset fr jagclogoutmsg         {You have logged out and exited the room}
::msgcat::mcset fr jagcreqnick           {Please enter your desired nick name for the room %s}
::msgcat::mcset fr jagcsyncpres2         {Synchronize chatroom presence with global presence}
::msgcat::mcset fr jainmsgshow           {Montrer les messages entrants dans cette fenêtre}
::msgcat::mcset fr jainvitegchat2        {Invite contact to chatroom %s.}
::msgcat::mcset fr jalogin               {Écrire l'adresse IP ou le nom du serveur Jabber, ou choisir à partir du menu pop-up. Vous devez déjà avoir un compte sur ce serveur.}
::msgcat::mcset fr jaloginjid3           {Enter your account as "user@example.org", or choose a profile. You should already have an account.}
::msgcat::mcset fr jaloginjidpure        {Enter your JID as "joey@myjabb.org". You should already have an account with this server.}
::msgcat::mcset fr jaloginuser           {Enter your username and password to login to %s.}
::msgcat::mcset fr jamucentermsg2        {Select a service, and enter a chatroom and nickname. You can discover the available chatrooms on the selected service. Some chatrooms may require a password.}
::msgcat::mcset fr janewpass             {Choisir le mot de passe pour : }
::msgcat::mcset fr jaopenbgimage         {Select an image file for the background. To remove a background image press Remove and Save.}
::msgcat::mcset fr jaregalready2         {You are already registered with this service. These are your current registration settings.}
::msgcat::mcset fr jaregisterex3         {Select a server from the list or manually enter one. Then press Next to retrieve the registration instructions. Follow the instructions and hit Register.}
::msgcat::mcset fr jaregisterexserv2     {Register with the service %s. You may need to press the Next button to retrieve the registration instructions.}
::msgcat::mcset fr jaregmsg3             {Select a service and press Next}
::msgcat::mcset fr jaregnewwith          {Do you want to register a new account with %s.}
::msgcat::mcset fr jarostadd3            {Select the chat system and contact ID of the contact you would like to add.}
::msgcat::mcset fr jarostaddopt          {Nickname and group are optional and can be set or changed later.}
::msgcat::mcset fr jarostset2            {Edit nickname and group of %s. You also can request or remove presence subscription.}
::msgcat::mcset fr jarostsub2            {Request presence subscription}
::msgcat::mcset fr jarostunsub2          {Remove presence subscription}
::msgcat::mcset fr jarostupdate          {La liste de contacts est à jour}
::msgcat::mcset fr jasearch2             {Search contacts with the selected service. A new search form will empty the previous one.}
::msgcat::mcset fr jasearchwait          {Cliquez sur "Recevoir" lorsque vous êtes prêt}
::msgcat::mcset fr jaseliconset2         {Select iconsets for each group. A deselected group will use the normal iconset.}
::msgcat::mcset fr jasubmulti            {%s contacts want to see your presence. Select those who may see your presence.}
::msgcat::mcset fr jasubopts2            {Entering a nickname and group is optional, and for your personal use only.}
::msgcat::mcset fr jasubwant2            {May %s see your presence?}
::msgcat::mcset fr jasuppimagefmts       {The supported image formats are}
::msgcat::mcset fr jatlsnegot2           {Negotiating TLS security}
::msgcat::mcset fr jauserinnote2         {Add your personal notes about this contact.}
::msgcat::mcset fr javersinfo            {Informations de la version de %s}
::msgcat::mcset fr jawaitdisco           {Waiting for disco result}
::msgcat::mcset fr jawaitresp            {%s est contacté, en attente d'une réponse}
::msgcat::mcset fr jawaitserver          {En attente de la réponse du serveur...}
::msgcat::mcset fr jawaitform            {Downloading configuration form}
::msgcat::mcset fr jawaitxml             {Connecté à "%s". Initialisation du flux XML...}
::msgcat::mcset fr jaxformreq            {Paramètres avec (*) requis}

# Setup assistant:
::msgcat::mcset fr suintro1a             {This setup assistant will help you to configure the most important settings to get started with %s.}
::msgcat::mcset fr suintro3a             {Any time you can press Previous to go back. Press Next to proceed.}
::msgcat::mcset fr sulang2               {Choose your language}
::msgcat::mcset fr suservmsg2            {Select or enter a server you wish to have your account on. If you already have an account, use the server of this account.}
::msgcat::mcset fr suusermsg2            {Enter your username and password. If the chosen username is already in use by someone else, you will not be able to register.}
::msgcat::mcset fr suregmsg2             {Click on the button below to create a new account. You must be connected to with the Internet. Pay attention to a possible firewall!}
::msgcat::mcset fr sufinmsg2             {That's all. Also, be nice to the bug and his friends ;-)}

# Groupchat:
::msgcat::mcset fr mucBan2               {Ban %s from the chatroom %s.}
::msgcat::mcset fr mucChat2ConfInv       {Converting Chat into Conference}
::msgcat::mcset fr mucDestroy2           {Do you want to destroy the chatroom %s? Optionally, you can point present chatroom participants to an alternative chatroom and tell why the chatroom is destroyed.}
::msgcat::mcset fr mucErrEnter2          {Cannot enter chatroom %s.}
::msgcat::mcset fr mucErrInvite2         {Cannot invitate %s to %s.}
::msgcat::mcset fr mucInviteText2        {%s invites you to join chatroom %s.}
::msgcat::mcset fr mucInvitePass         {The password "%s" is needed for entry.}
::msgcat::mcset fr mucInviteQuest        {Do you want to join right away?}
::msgcat::mcset fr mucIQError2           {Cannot interact with the chatroom %s.}
::msgcat::mcset fr mucKick               {Kick %s from the chatroom %s.}

::msgcat::mcset fr vcardget2             {Downloading business card from %s}
::msgcat::mcset fr vcarderrget2          {Cannot download business card.}
::msgcat::mcset fr vcardrec2             {Business card downloaded.}



::msgcat::mcset fr autoupdatedo          {Automatically check for updates}
::msgcat::mcset fr oobmsg2               {Send a file to %s. A description is optional.}

# Composing events
::msgcat::mcset fr chatcompreply         {%s rédige une réponse}
::msgcat::mcset fr chatcompactive        {%s is on the chat}
::msgcat::mcset fr chatcompcomposing     {%s is composing a reply}
::msgcat::mcset fr chatcomppaused        {%s is thinking what to write}
::msgcat::mcset fr chatcompinactive      {%s has left the chat for a while}
::msgcat::mcset fr chatcompgone          {%s has closed the chat}


# Get file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset fr getcontacting         {Contact de %s. En attente d'une réponse...}
::msgcat::mcset fr geteoferr             {La connexion à %s a échoué : réception d'une EOF.}
::msgcat::mcset fr getconnerr            {La connexion à %s a échoué.}
::msgcat::mcset fr getnegotiate          {Client contacté : %s ; négociations en cours...}
::msgcat::mcset fr getreaderr            {Erreur de réponse du serveur %s.}
::msgcat::mcset fr getunknownprot        {Le serveur %s ne répond en utilisant le bon protocole.}
::msgcat::mcset fr getnot200             {Le serveur %s a répondu avec le code %s (%s).}
::msgcat::mcset fr getstarts             {Le client %s a accepté le fichier "%s". Début du transfert...}
::msgcat::mcset fr getended              {Le transfert de %s s'est terminé prématurément.}
::msgcat::mcset fr getfinished           {Le fichier "%s" de %s a été reçu.}
::msgcat::mcset fr getneterr             {Erreur de transfert lors de la réception de %s.}

# Put file
# Note to translators: these strings are marked EOL (EndOfLife) since the file transfer protocol will be changed.
::msgcat::mcset fr putcontacting         {Contact de %s. En attente d'une réponse...}
::msgcat::mcset fr puteoferr             {La connexion à %s a échoué : réception d'une EOF.}
::msgcat::mcset fr putconnerr            {La connexion à %s a échoué.}
::msgcat::mcset fr putnegotiate          {Client contacté : %s ; négociations en cours...}
::msgcat::mcset fr putreaderr            {Erreur de réponse du serveur %s.}
::msgcat::mcset fr putunknownprot        {Le serveur %s ne répond en utilisant le bon protocole.}
::msgcat::mcset fr putnot200             {Le serveur %s a répondu avec le code %s (%s).}
::msgcat::mcset fr putstarts             {Le client %s a accepté le fichier "%s". Début du transfert...}
::msgcat::mcset fr putended              {Le transfert de %s s'est terminé prématurément.}
::msgcat::mcset fr putfinished           {Le fichier "%s" de %s a été reçu.}
::msgcat::mcset fr putneterr             {Erreur de transfert lors de la réception de %s.}

# These are specific for phones (VoIP)
::msgcat::mcset fr phoneMakeCall         {Make a call}
::msgcat::mcset fr phoneMakeForward      {Forward current call to...}
::msgcat::mcset fr phoneRing             {Ring, ring...}
::msgcat::mcset fr phoneRingFrom         {Phone is ringing from %s}
::msgcat::mcset fr phoneFailedCalling    {Failed calling %s}
::msgcat::mcset fr phoneDial             {Dial}
::msgcat::mcset fr phoneNumber           {Number}
::msgcat::mcset fr phoneDialerCall       {Call to...}
::msgcat::mcset fr phoneDialerForward    {Forward to...}

# Note to translators: these strings are not yet activated
::msgcat::mcset fr AddressBook           {Address Book}
::msgcat::mcset fr newAddressbookDlg     {New address book}
::msgcat::mcset fr newAddressbook        {New address book}
::msgcat::mcset fr abName                {Name}
::msgcat::mcset fr abPhone               {Phone number}
::msgcat::mcset fr modifyAddressbookDlg  {Modify address book}
::msgcat::mcset fr modifyAddressbook     {Modify address book}
::msgcat::mcset fr mNewAB                {New}
::msgcat::mcset fr mModifyAB             {Modify}
::msgcat::mcset fr mRemoveAB             {Remove}

::msgcat::mcset fr outCall               {Make Call}
::msgcat::mcset fr notifyCall            {Notify Call}
::msgcat::mcset fr inboundCall           {Inbound Call}
::msgcat::mcset fr outboundCall          {Outbound Call}
::msgcat::mcset fr callAnswer            {Answer}
::msgcat::mcset fr callHungUp            {Hung Up}
::msgcat::mcset fr callInfo              {Info}
::msgcat::mcset fr callVM                {Call VM?}

# IAX Phone
# Note to translators: these strings are not yet activated
if {0} {
::msgcat::mcset fr Codecs                {Codecs}
::msgcat::mcset fr Devices               {Devices}
::msgcat::mcset fr Filters               {Filters}
::msgcat::mcset fr {IAX Phone}           {IAX Phone}
::msgcat::mcset fr {IAX Account}         {IAX Account}
    # translation help: http://en.wikipedia.org/wiki/Caller_id
::msgcat::mcset fr {Caller ID number}    {Caller ID number}
::msgcat::mcset fr {Caller ID name}      {Caller ID name}
::msgcat::mcset fr Microphone            {Microphone}
::msgcat::mcset fr Speakers              {Speakers}
    # translation help: http://en.wikipedia.org/wiki/Automatic_gain_control
::msgcat::mcset fr {Automatic gain control (AGC)} {Automatic gain control (AGC)}
::msgcat::mcset fr agcTip                {Automatically adjust volume levels}
    # translation help: http://lists.xiph.org/pipermail/speex-dev/2007-May/005565.html
::msgcat::mcset fr {Analog automatic gain control (AAGC)} {Analog automatic gain control (AAGC)}
::msgcat::mcset fr {Can prevent clipping} {Can prevent clipping}
    # translation help: http://en.wikipedia.org/wiki/Noise_reduction
::msgcat::mcset fr {Noise reduction}     {Noise reduction}
    # translation help: http://en.wikipedia.org/wiki/Comfort_noise
::msgcat::mcset fr {Comfort noise}       {Comfort noise}
::msgcat::mcset fr comfortTip            {Artificial background noise to fill silence}
::msgcat::mcset fr Codec                 {Codec}
    # I copied the following descriptions from the websites of these projects; do you think we should ask permission for this?
::msgcat::mcset fr tooltip-ilbc          {iLBC (internet Low Bitrate Codec) is a free speech codec suitable for robust voice communication over IP}
::msgcat::mcset fr tooltip-speex         {Speex is an Open Source/Free Software patent-free audio compression format designed for speech}
::msgcat::mcset fr tooltip-alaw          {Standard used in European digital communication systems (ITU-T)}
::msgcat::mcset fr tooltip-ulaw          {Standard used in digital communication systems in North America and Japan (ITU-T)}
::msgcat::mcset fr tooltip-gsm           {GSM 06.10 provisional standard for full-rate speech transcoding (ETSI)}
}

# Messages for Mood XEP
# bug: this should be M&ood..., but this does not work!
::msgcat::mcset fr mMood            Mood 
::msgcat::mcset fr mAfraid          Afraid
::msgcat::mcset fr mAmazed          Amazed
::msgcat::mcset fr mAngry           Angry
::msgcat::mcset fr mAnnoyed         Annoyed
::msgcat::mcset fr mAnxious         Anxious
::msgcat::mcset fr mAroused         Aroused
::msgcat::mcset fr mAshamed         Ashamed
::msgcat::mcset fr mBored           Bored
::msgcat::mcset fr mBrave           Brave
::msgcat::mcset fr mCalm            Calm
::msgcat::mcset fr mCold            Cold
::msgcat::mcset fr mConfused        Confused
::msgcat::mcset fr mContented       Contented
::msgcat::mcset fr mCranky          Cranky
::msgcat::mcset fr mCurious         Curious
::msgcat::mcset fr mDepressed       Depressed
::msgcat::mcset fr mDisappointed    Disappointed
::msgcat::mcset fr mDisgusted       Disgusted
::msgcat::mcset fr mDistracted      Distracted
::msgcat::mcset fr mEmbarrassed     Embarrassed
::msgcat::mcset fr mExcited         Excited
::msgcat::mcset fr mFlirtatious     Flirtatious
::msgcat::mcset fr mFrustrated      Frustrated
::msgcat::mcset fr mGrumpy          Grumpy
::msgcat::mcset fr mGuilty          Guilty
::msgcat::mcset fr mHappy           Happy
::msgcat::mcset fr mHot             Hot
::msgcat::mcset fr mHumbled         Humbled
::msgcat::mcset fr mHumiliated      Humiliated
::msgcat::mcset fr mHungry          Hungry
::msgcat::mcset fr mHurt            Hurt
::msgcat::mcset fr mImpressed       Impressed
::msgcat::mcset fr mIn_awe          {In awe}
::msgcat::mcset fr mIn_love         {In love}
::msgcat::mcset fr mIndignant       Indignant
::msgcat::mcset fr mInterested      Interested
::msgcat::mcset fr mIntoxicated     Intoxicated
::msgcat::mcset fr mInvincible      Invincible
::msgcat::mcset fr mJealous         Jealous
::msgcat::mcset fr mLonely          Lonely
::msgcat::mcset fr mMean            Mean
::msgcat::mcset fr mMoody           Moody
::msgcat::mcset fr mNervous         Nervous
::msgcat::mcset fr mNeutral         Neutral
::msgcat::mcset fr mOffended        Offended
::msgcat::mcset fr mPlayful         Playful
::msgcat::mcset fr mProud           Proud
::msgcat::mcset fr mRelieved        Relieved
::msgcat::mcset fr mRemorseful      Remorseful
::msgcat::mcset fr mRestless        Restless
::msgcat::mcset fr mSad             Sad
::msgcat::mcset fr mSarcastic       Sarcastic
::msgcat::mcset fr mSerious         Serious
::msgcat::mcset fr mShocked         Shocked
::msgcat::mcset fr mShy             Shy
::msgcat::mcset fr mSick            Sick
::msgcat::mcset fr mSleepy          Sleepy
::msgcat::mcset fr mStressed        Stressed
::msgcat::mcset fr mSurprised       Surprised
::msgcat::mcset fr mThirsty         Thirsty
::msgcat::mcset fr mWorried         Worried

::msgcat::mcset fr moodEvent   {Mood change}
::msgcat::mcset fr moodRetracted {retracted mood}

::msgcat::mcset fr heIs        is
::msgcat::mcset fr because     because
::msgcat::mcset fr afraid   afraid
::msgcat::mcset fr amazed   amazed
::msgcat::mcset fr angry   angry
::msgcat::mcset fr annoyed   annoyed
::msgcat::mcset fr anxious   anxious
::msgcat::mcset fr aroused   aroused
::msgcat::mcset fr ashamed   ashamed
::msgcat::mcset fr bored   bored
::msgcat::mcset fr brave   brave
::msgcat::mcset fr calm   calm
::msgcat::mcset fr cold   cold
::msgcat::mcset fr confused   confused
::msgcat::mcset fr contented   contented
::msgcat::mcset fr cranky   cranky
::msgcat::mcset fr curious   curious
::msgcat::mcset fr depressed   depressed
::msgcat::mcset fr disappointed   disappointed
::msgcat::mcset fr disgusted   disgusted
::msgcat::mcset fr distracted   distracted
::msgcat::mcset fr embarrassed   embarrassed
::msgcat::mcset fr excited   excited
::msgcat::mcset fr flirtatious   flirtatious
::msgcat::mcset fr frustrated   frustrated
::msgcat::mcset fr grumpy   grumpy
::msgcat::mcset fr guilty   guilty
::msgcat::mcset fr happy   happy
::msgcat::mcset fr hot   hot
::msgcat::mcset fr humbled   humbled
::msgcat::mcset fr humiliated   humiliated
::msgcat::mcset fr hungry   hungry
::msgcat::mcset fr hurt   hurt
::msgcat::mcset fr impressed   impressed
::msgcat::mcset fr in_awe   {in awe}
::msgcat::mcset fr in_love   {in love}
::msgcat::mcset fr indignant   indignant
::msgcat::mcset fr interested   interested
::msgcat::mcset fr intoxicated   intoxicated
::msgcat::mcset fr invincible   invincible
::msgcat::mcset fr jealous   jealous
::msgcat::mcset fr lonely   lonely
::msgcat::mcset fr mean   mean
::msgcat::mcset fr moody   moody
::msgcat::mcset fr nervous   nervous
::msgcat::mcset fr neutral   neutral
::msgcat::mcset fr offended   offended
::msgcat::mcset fr playful   playful
::msgcat::mcset fr proud   proud
::msgcat::mcset fr relieved   relieved
::msgcat::mcset fr remorseful   remorseful
::msgcat::mcset fr restless   restless
::msgcat::mcset fr sad   sad
::msgcat::mcset fr sarcastic   sarcastic
::msgcat::mcset fr serious   serious
::msgcat::mcset fr shocked   shocked
::msgcat::mcset fr shy   shy
::msgcat::mcset fr sick   sick
::msgcat::mcset fr sleepy   sleepy
::msgcat::mcset fr stressed   stressed
::msgcat::mcset fr surprised   surprised
::msgcat::mcset fr thirsty   thirsty
::msgcat::mcset fr worried   worried

::msgcat::mcset fr {Custom Mood}         {Custom Mood}
::msgcat::mcset fr mCustomMood...        {&Custom Mood...}
::msgcat::mcset fr moodPickMsg           {Select your mood to show to your contacts.}
::msgcat::mcset fr moodPickDtl           {Only contacts with compatible software will see your mood.}

# More balloonhelp stuff.
::msgcat::mcset fr tooltip-contactid     {Chat address}
::msgcat::mcset fr tooltip-group         {Group to which this contact should belong to}
::msgcat::mcset fr tooltip-localnick     {Your nickname for local display}
::msgcat::mcset fr tooltip-historymessages {Number of messages to display}
::msgcat::mcset fr tooltip-chatroomservice {Select or manually enter a chatroom service}
::msgcat::mcset fr tooltip-chatroomselect {Select or manually enter the name of a chatroom}
::msgcat::mcset fr tooltip-snack         {Support for mp3, wav, and a few other audio formats}
::msgcat::mcset fr tooltip-img           {Support for common image formats}
::msgcat::mcset fr tooltip-tkpng         {Support for PNG images}
::msgcat::mcset fr tooltip-xanim         {Support for several animation, video and audio formats}
::msgcat::mcset fr tooltip-QuickTimeTcl  {Support for several animation, image, video and audio formats}

::msgcat::mcset fr tooltip-chatsubject   {Enter the subject of the conversation, set by pressing Return}
::msgcat::mcset fr tooltip-chatoffline   {You need to be logged in to see the presence of this contact}
::msgcat::mcset fr tooltip-chatsendtext     {Enter your message and press Return or Shift-Return}
::msgcat::mcset fr tooltip-aaonhidden    {If activated then directed auto-away presence will be sent to users on hidden chat tabs}
::msgcat::mcset fr tooltip-aabusychats   {When you have <number> or more active chat sessions, presence state will be automatically changed to Do Not Disturb.}
::msgcat::mcset fr tooltip-togglesysmsg     {Show or hide status changes in chat}


# Me knows :-)
::msgcat::mcset fr matsShouldReplaceThis {Not yet implemented.}


# Messages for User Activity XEP
::msgcat::mcset fr Activity              {Activity}
::msgcat::mcset fr mActivity...          {Acti&vity...}
::msgcat::mcset fr mCustomActivity... {Custom Activity...}

::msgcat::mcset fr Traveling             {Traveling}
::msgcat::mcset fr Commuting             {Commuting}
::msgcat::mcset fr Cycling               {Cycling}
::msgcat::mcset fr Driving               {Driving}
::msgcat::mcset fr {In a car}            {In a car}
::msgcat::mcset fr {On a bus}            {On a bus}
::msgcat::mcset fr {On a plane}          {On a plane}
::msgcat::mcset fr {On a train}          {On a train}
::msgcat::mcset fr {On a trip}           {On a trip}
::msgcat::mcset fr Walking               {Walking}

::msgcat::mcset fr Eating                {Eating}
::msgcat::mcset fr {Having a snack}      {Having a snack}
::msgcat::mcset fr {Having breakfast}    {Having breakfast}
::msgcat::mcset fr {Having dinner}       {Having dinner}
::msgcat::mcset fr {Having lunch}        {Having lunch}

::msgcat::mcset fr {Doing chores}        {Doing chores}
::msgcat::mcset fr {Buying groceries}    {Buying groceries}
::msgcat::mcset fr Cleaning              {Cleaning}
::msgcat::mcset fr Cooking               {Cooking}
::msgcat::mcset fr {Doing maintenance}   {Doing maintenance}
::msgcat::mcset fr {Doing the dishes}    {Doing the dishes}
::msgcat::mcset fr {Doing the laundry}   {Doing the laundry}
::msgcat::mcset fr Gardening             {Gardening}
::msgcat::mcset fr {Running an errand}   {Running an errand}
::msgcat::mcset fr {Walking the dog}     {Walking the dog}

::msgcat::mcset fr Working               {Working}
::msgcat::mcset fr Coding                {Coding}
::msgcat::mcset fr {In a meeting}        {In a meeting}
::msgcat::mcset fr Studying              {Studying}
::msgcat::mcset fr Writing               {Writing}

::msgcat::mcset fr Exercising            {Exercising}
# Duplicate:
::msgcat::mcset fr en                    {Cycling}
::msgcat::mcset fr Hiking                {Hiking}
::msgcat::mcset fr Jogging               {Jogging}
::msgcat::mcset fr {Playing sports}      {Playing sports}
::msgcat::mcset fr Running               {Running}
::msgcat::mcset fr Skiing                {Skiing}
::msgcat::mcset fr Swimming              {Swimming}
::msgcat::mcset fr {Working out}         {Working out}

::msgcat::mcset fr Talking               {Talking}
::msgcat::mcset fr {In real life}        {In real life}
::msgcat::mcset fr {On the phone}        {On the phone}
::msgcat::mcset fr {On video phone}      {On video phone}

::msgcat::mcset fr Relaxing              {Relaxing}
::msgcat::mcset fr Gaming                {Gaming}
::msgcat::mcset fr {Going out}           {Going out}
::msgcat::mcset fr Partying              {Partying}
::msgcat::mcset fr Reading               {Reading}
::msgcat::mcset fr Rehearsing            {Rehearsing}
::msgcat::mcset fr Shopping              {Shopping}
::msgcat::mcset fr Socializing           {Socializing}
::msgcat::mcset fr Sunbathing            {Sunbathing}
::msgcat::mcset fr {Watching tv}         {Watching tv}
::msgcat::mcset fr {Watching a movie}    {Watching a movie}

::msgcat::mcset fr Grooming              {Grooming}
::msgcat::mcset fr {At the spa}          {At the spa}
::msgcat::mcset fr {Brushing teeth}      {Brushing teeth}
::msgcat::mcset fr {Getting a haircut}   {Getting a haircut}
::msgcat::mcset fr Shaving               {Shaving}
::msgcat::mcset fr {Taking a bath}       {Taking a bath}
::msgcat::mcset fr {Taking a shower}     {Taking a shower}

::msgcat::mcset fr Drinking              {Drinking}
::msgcat::mcset fr {Having a beer}       {Having a beer}
::msgcat::mcset fr {Having coffee}       {Having coffee}
::msgcat::mcset fr {Having tea}          {Having tea}

::msgcat::mcset fr Inactive              {Inactive}
::msgcat::mcset fr {Day off}             {Day off}
::msgcat::mcset fr {Hanging out}         {Hanging out}
::msgcat::mcset fr {On vacation}         {On vacation}
::msgcat::mcset fr {Scheduled holiday}   {Scheduled holiday}
::msgcat::mcset fr Sleeping              {Sleeping}

::msgcat::mcset fr {Having appointment}  {Having appointment}

::msgcat::mcset fr activityPickMsg       {Set your activity that will be shown to your contacts.}
::msgcat::mcset fr activityPickDtl       {Select from the first button your general activity, and optionally, your specific actvity from the second button. You may also add a descriptive text.}

# XEP-0080: User Location
::msgcat::mcset fr Location              {Localisation}
::msgcat::mcset fr mLocation...          {Localisat&ion...}
::msgcat::mcset fr locationPickMsg       {Entrer la localisation qui va être montrée à vos contacts}
::msgcat::mcset fr locationPickDtl       {Enter your location details below. At least you should set latitude and longitude.}

# Note to translators: The commented strings are just there for completeness with the protocol, still not in UI
::msgcat::mcset fr Altitude              {Altitude}
::msgcat::mcset fr {Named Area}          {Named Area}
::msgcat::mcset fr {GPS Bearing}         {GPS Bearing}
::msgcat::mcset fr Building              {Building}
::msgcat::mcset fr {GPS Datum}           {GPS Datum}
::msgcat::mcset fr {GPS Error}           {GPS Error}
::msgcat::mcset fr Floor                 {Floor}
::msgcat::mcset fr Latitude              {Latitude}
::msgcat::mcset fr Locality              {Locality}
::msgcat::mcset fr Longitude             {Longitude}
::msgcat::mcset fr Room                  {Salon}
::msgcat::mcset fr Street                {Street}
::msgcat::mcset fr Text                  {Texte}
::msgcat::mcset fr Timestamp             {Timestamp}

# Help strings:
# Note to translators: The commented strings are just there for completeness with the protocol, still not in UI
::msgcat::mcset fr locationBearing       {GPS bearing (direction in which the entity is heading to reach its next waypoint), measured in decimal degrees relative to true north}
::msgcat::mcset fr locationAlt           {Altitude in meters above or below sea level}
::msgcat::mcset fr locationLon           {Longitude in decimal degrees East}
::msgcat::mcset fr locationError         {Horizontal GPS error in arc minutes}
::msgcat::mcset fr locationRegion        {An administrative region of the nation, such as a state or province}
::msgcat::mcset fr locationDescription   {A natural-language name for or description of the location}
::msgcat::mcset fr locationText          {A catch-all element that captures any other information about the location}
::msgcat::mcset fr locationRoom          {A particular room in a building}
::msgcat::mcset fr locationPostalcode    {A code used for postal delivery}
::msgcat::mcset fr locationBuilding      {A specific building on a street or in an area}
::msgcat::mcset fr locationStreet        {A thoroughfare within the locality, or a crossing of two thoroughfares}
::msgcat::mcset fr locationArea          {A named area such as a campus or neighborhood}
::msgcat::mcset fr locationLat           {Latitude in decimal degrees North}
::msgcat::mcset fr locationLocality      {A locality within the administrative region, such as a town or city}
::msgcat::mcset fr locationFloor         {A particular floor in a building}
::msgcat::mcset fr locationDatum         {GPS datum}
::msgcat::mcset fr locationTimestamp     {UTC timestamp specifying the moment when the reading was taken}
::msgcat::mcset fr locationCountry       {The nation where the user is located}

::msgcat::mcset fr {Synchronize with Google Earth} {Synchronize with Google Earth}
::msgcat::mcset fr {This is location data for} {This is location data for}

# Buddy pouncing:
::msgcat::mcset fr budpounce-user        {Set a specific action for events related to %s. Select events using the tabs below.}
::msgcat::mcset fr budpounce-group       {Set a specific action for events related to any contact belonging to the group %s. Select events using the tabs below.}
::msgcat::mcset fr budpounce-any         {Set a specific action for events related to any contact in your contact list. Select events using the tabs below.}
::msgcat::mcset fr budpounce-available   {%s just went online!}
::msgcat::mcset fr budpounce-unavailable {%s just went offline!}
::msgcat::mcset fr budpounce-msg         {%s just sent you a message!}
::msgcat::mcset fr budpounce-chat        {%s just started a chat!}
::msgcat::mcset fr budpounce-sendmsg     {Send message with subject}
::msgcat::mcset fr mContactActions...    {&Contact Actions...}

# Image magic:
::msgcat::mcset fr immagic-msg           {Click on a window or drag a rectangular area to import a snapshot into the current whiteboard.}
::msgcat::mcset fr immagic-warn          {Dangerous in-box path name: %s}
::msgcat::mcset fr immagic-rem           {Click OK to remove files: %s}

# File Types
# translation help: http://en.wikipedia.org/wiki/List_of_file_formats
# Note to translators: these strings have very low priority since the English names can be taken as definitions
::msgcat::mcset fr {World Application}   {World Application}
::msgcat::mcset fr {QuickDraw 3D Metafile} {QuickDraw 3D Metafile}
::msgcat::mcset fr {Tcl File}            {Tcl File}
::msgcat::mcset fr {Itcl File}           {Itcl File}
::msgcat::mcset fr {Session Description Protocol} {Session Description Protocol}
::msgcat::mcset fr {Adobe Flash Media}   {Adobe Flash Media}
::msgcat::mcset fr {Mac Binary}          {Mac Binary}
::msgcat::mcset fr {VTK 3D}              {VTK 3D}
::msgcat::mcset fr {Generic File}        {Generic File}
::msgcat::mcset fr {PDF Document}        {PDF Document}
::msgcat::mcset fr {PostScript Document} {PostScript Document}
::msgcat::mcset fr {JavaScript File}     {JavaScript File}
::msgcat::mcset fr {TeX File}            {TeX File}
::msgcat::mcset fr {Archive Tar}         {Archive Tar}
::msgcat::mcset fr {Abi Word Document}   {Abi Word Document}
::msgcat::mcset fr {Microsoft Excel Spreadsheet} {Microsoft Excel Spreadsheet}
::msgcat::mcset fr {Microsoft PowerPoint Presentation} {Microsoft PowerPoint Presentation}
::msgcat::mcset fr {Microsoft Word Document} {Microsoft Word Document}
::msgcat::mcset fr {MPEG Audio}          {MPEG Audio}
::msgcat::mcset fr {AIFF/Amiga Audio}    {AIFF/Amiga Audio}
::msgcat::mcset fr {ULAW (Sun) Audio}    {ULAW (Sun) Audio}
::msgcat::mcset fr {Streaming Audio}     {Streaming Audio}
::msgcat::mcset fr {WAV Audio}           {WAV Audio}
::msgcat::mcset fr {QCP Audio}           {QCP Audio}
::msgcat::mcset fr {MIDI Audio}          {MIDI Audio}
::msgcat::mcset fr {BMP Image}           {BMP Image}
::msgcat::mcset fr {FlashPix Image}      {FlashPix Image}
::msgcat::mcset fr {GIF Image}           {GIF Image}
::msgcat::mcset fr {JPEG Image}          {JPEG Image}
::msgcat::mcset fr {Macpaint Image}      {Macpaint Image}
::msgcat::mcset fr {Adobe Photoshop Image} {Adobe Photoshop Image}
::msgcat::mcset fr {PNG Image}           {PNG Image}
::msgcat::mcset fr {PICT Image}          {PICT Image}
::msgcat::mcset fr {SGI Image}           {SGI Image}
::msgcat::mcset fr {Truevision Targa Image} {Truevision Targa Image}
::msgcat::mcset fr {TIFF Image}          {TIFF Image}
::msgcat::mcset fr {X PixMap Image}      {X PixMap Image}
::msgcat::mcset fr {Plain Text Document} {Plain Text Document}
::msgcat::mcset fr {XML Document}        {XML Document}
::msgcat::mcset fr {RTF Document}        {RTF Document}
::msgcat::mcset fr {HTML Document}       {HTML Document}
::msgcat::mcset fr {Cascading Style Sheet} {Cascading Style Sheet}
::msgcat::mcset fr {QuickTime Video}     {QuickTime Video}
::msgcat::mcset fr {MPEG-4 Video}        {MPEG-4 Video}
::msgcat::mcset fr {DV Video}            {DV Video}
::msgcat::mcset fr {MPEG Video}          {MPEG Video}
::msgcat::mcset fr {Microsoft AVI Video} {Microsoft AVI Video}
::msgcat::mcset fr {Autodesk's FLIC File} {Autodesk's FLIC File}

# END --------------------------------------------------------------------------


