# Korean language version of the Coccinella message catalog.
#
# General type of text, such as "OK", "Cancel", and the like. 
# We use the source string as the message.
# Defined in global namespace and may therefore be used in any namespace.

# The Korean catalog provided by Dylan Park, Korea NVC Center
#     (hanmaum@krnvc.org) 

::msgcat::mcset kr Accept	  수락하기
::msgcat::mcset kr Action	  활동
::msgcat::mcset kr Active	  활성
::msgcat::mcset kr Add		  보태기
::msgcat::mcset kr Address	  주소
::msgcat::mcset kr Admin	  관리자
::msgcat::mcset kr admin	  관리자
::msgcat::mcset kr Advanced	  고급
::msgcat::mcset kr Affiliation	  가입
::msgcat::mcset kr Agents	  대리인
::msgcat::mcset kr Allow	  허용하기
::msgcat::mcset kr Appearance	  모양
::msgcat::mcset kr Apply	  적용
::msgcat::mcset kr Author	  저자
::msgcat::mcset kr Available	  가능한
::msgcat::mcset kr Away		  나감
::msgcat::mcset kr Back		  뒤로
::msgcat::mcset kr Binary	  이진
::msgcat::mcset kr Birthday	  생일
::msgcat::mcset kr Block	  장벽
::msgcat::mcset kr Blockers	  방해자
::msgcat::mcset kr Blocking	  방해
::msgcat::mcset kr Bookmark	  북마크
::msgcat::mcset kr Bookmarks	  북마크
::msgcat::mcset kr Browser	  브라우져
::msgcat::mcset kr Both		  둘다
::msgcat::mcset kr Buffering	  버퍼링
::msgcat::mcset kr Cancel	  취소
::msgcat::mcset kr Change	  바꾸기
::msgcat::mcset kr Chat		  대화
::msgcat::mcset kr Choose	  선택
::msgcat::mcset kr City		  도시
::msgcat::mcset kr Clear	  지우기
::msgcat::mcset kr Client	  고객
::msgcat::mcset kr Close	  닫기
::msgcat::mcset kr Codecs	  코덱
::msgcat::mcset kr Conference	  회의
::msgcat::mcset kr Connect	  연결하기
::msgcat::mcset kr Connection	  연결
::msgcat::mcset kr Contact	  {+대화상대}
::msgcat::mcset kr Contacts	  {대화 상대}
::msgcat::mcset kr Coordinates	  코디네이트
::msgcat::mcset kr Country	  국가
::msgcat::mcset kr Create	  만들기
::msgcat::mcset kr Customization  커스터마이징
::msgcat::mcset kr Date		  일자
::msgcat::mcset kr Default	  디폴트
::msgcat::mcset kr Delete	  지우기
::msgcat::mcset kr Deny		  거부하기
::msgcat::mcset kr Department	  부서
::msgcat::mcset kr Description	  설명
::msgcat::mcset kr Devices	  디바이스
::msgcat::mcset kr Drawing	  그림
::msgcat::mcset kr Document	  문서
::msgcat::mcset kr Done		  마침
::msgcat::mcset kr Edit		  쓰기
::msgcat::mcset kr Email	  메일
::msgcat::mcset kr Emoticons	  느낌아이콘
::msgcat::mcset kr Enter	  들어가기
::msgcat::mcset kr Error	  에러
::msgcat::mcset kr Exit		  나가기
::msgcat::mcset kr File		  파일
::msgcat::mcset kr File...	  파일...
::msgcat::mcset kr Filter	  필터
::msgcat::mcset kr Filters	  필터들
::msgcat::mcset kr Find		  찾기
::msgcat::mcset kr Finish	  마치기
::msgcat::mcset kr Finished	  종료됨
::msgcat::mcset kr First	  처음
::msgcat::mcset kr Friends	  동무
::msgcat::mcset kr Forward	  앞으로
::msgcat::mcset kr From		  부터
::msgcat::mcset kr General	  일반적
::msgcat::mcset kr Get		  가져오기
::msgcat::mcset kr Getting	  가져옴
::msgcat::mcset kr Grant	  권한
::msgcat::mcset kr Group	  그룹
::msgcat::mcset kr Groupchat	  그룹대화
::msgcat::mcset kr Handling	  조정하기
::msgcat::mcset kr Height	  높이
::msgcat::mcset kr History	  기록
::msgcat::mcset kr Home		  홈
::msgcat::mcset kr Icon		  아이콘
::msgcat::mcset kr Image	  이미지
::msgcat::mcset kr Import	  자져오기
::msgcat::mcset kr Inbox	  받은함
::msgcat::mcset kr Info		  정보
::msgcat::mcset kr Invite	  초대하기
::msgcat::mcset kr Jabber	  재버
::msgcat::mcset kr Key		  열쇠
::msgcat::mcset kr Language	  언어
::msgcat::mcset kr Last		  끝
::msgcat::mcset kr Less		  덜
::msgcat::mcset kr Login	  로그인
::msgcat::mcset kr Logout	  로그아웃
::msgcat::mcset kr Member	  회원
::msgcat::mcset kr member	  회원
::msgcat::mcset kr Message	  메세지
::msgcat::mcset kr Middle	  중간
::msgcat::mcset kr Moderator	  진행자
::msgcat::mcset kr moderator	  진행자
::msgcat::mcset kr Moderators	  진행자
::msgcat::mcset kr More		  더
::msgcat::mcset kr Name		  이름

::msgcat::mcset kr Network

::msgcat::mcset kr Never	  결코
::msgcat::mcset kr New		  새
::msgcat::mcset kr Next		  다음
::msgcat::mcset kr Nick		  별명
::msgcat::mcset kr Nickname	  별명
::msgcat::mcset kr No		  아니오
::msgcat::mcset kr no		  아니오
::msgcat::mcset kr None		  아무도없음
::msgcat::mcset kr Notes	  노트
::msgcat::mcset kr Occupation	  직업
::msgcat::mcset kr Offline	  오프라인
::msgcat::mcset kr OK		  OK
::msgcat::mcset kr Online	  온라인
::msgcat::mcset kr Open		  열기
::msgcat::mcset kr Options	  옵션
::msgcat::mcset kr Owner	  소유자
::msgcat::mcset kr owner	  소유자
::msgcat::mcset kr Participants	  참가자
::msgcat::mcset kr Password	  암호
::msgcat::mcset kr Pause	  잠시
::msgcat::mcset kr Pick		  집다
::msgcat::mcset kr Phone	  전화
::msgcat::mcset kr Play		  놀다
::msgcat::mcset kr Plugins	  플러그인
::msgcat::mcset kr Port		  포트
::msgcat::mcset kr Preferences	  설정
::msgcat::mcset kr Previous	  앞
::msgcat::mcset kr Print	  인쇄하기
::msgcat::mcset kr Priority	  우선권
::msgcat::mcset kr Privacy	  프라이버시
::msgcat::mcset kr Profile	  프로필
::msgcat::mcset kr Profiles	  프로필
::msgcat::mcset kr Progress	  진전
::msgcat::mcset kr Quit?	  나가나요?
::msgcat::mcset kr Quote	  인용
::msgcat::mcset kr Reason	  이유
::msgcat::mcset kr Refresh	  새롭게하기
::msgcat::mcset kr Register	  예약하기
::msgcat::mcset kr Remaining	  나머지
::msgcat::mcset kr Remove	  지우기
::msgcat::mcset kr Reply	  답하기
::msgcat::mcset kr Resource	  자원
::msgcat::mcset kr Restart	  재시작
::msgcat::mcset kr Revoke	  취소하기
::msgcat::mcset kr Role		  역할
::msgcat::mcset kr Rosticons	  {목록용 아이콘}
::msgcat::mcset kr Room		  방
::msgcat::mcset kr Roster	  등록부
::msgcat::mcset kr Save		  저장하기
::msgcat::mcset kr Search	  찾기
::msgcat::mcset kr Select	  고루기
::msgcat::mcset kr Send		  보내기
::msgcat::mcset kr Server	  서버
::msgcat::mcset kr Servers	  서버
::msgcat::mcset kr Service	  서비스
::msgcat::mcset kr Set		  설정하기
::msgcat::mcset kr Settings	  설정
::msgcat::mcset kr Shortcut	  단축그림
::msgcat::mcset kr Shortcuts	  단축그림
::msgcat::mcset kr Size		  크기
::msgcat::mcset kr Sounds	  소리
::msgcat::mcset kr Specifications 특이사항
::msgcat::mcset kr Speech	  연설
::msgcat::mcset kr Standard	  표준
::msgcat::mcset kr State	  주
::msgcat::mcset kr State/Region	  주/지역
::msgcat::mcset kr Stop		  정지
::msgcat::mcset kr Subject	  주제
::msgcat::mcset kr Subscribe	  신청
::msgcat::mcset kr Subscribed	  신청록된
::msgcat::mcset kr Subscription	  신청
::msgcat::mcset kr Subscriptions  신청
::msgcat::mcset kr Text		  문자
::msgcat::mcset kr Time		  시간
::msgcat::mcset kr Timeout	  종료
::msgcat::mcset kr Title	  제목
::msgcat::mcset kr To		  받는이
::msgcat::mcset kr Topic	  토픽
::msgcat::mcset kr Transports	  수송
::msgcat::mcset kr Trash	  휴지통
::msgcat::mcset kr Type		  형태
::msgcat::mcset kr Unregister	  예약해지
::msgcat::mcset kr Unsubscribe	  등록해지
::msgcat::mcset kr Unsubscribed	  등록해지된
::msgcat::mcset kr Username	  사용자명
::msgcat::mcset kr Value	  가치
::msgcat::mcset kr Visitors	  방문자
::msgcat::mcset kr Voice	  목소리
::msgcat::mcset kr voice	  목소리
::msgcat::mcset kr Warning	  경고
::msgcat::mcset kr Welcome	  환영합니다
::msgcat::mcset kr Whiteboard	  칠판
::msgcat::mcset kr Width	  폭
::msgcat::mcset kr Work		  일
::msgcat::mcset kr Yes		  예
::msgcat::mcset kr yes		  예

# A few words that are not unambiguous and have therefore a prefix.
::msgcat::mcset kr program-Application        응용프로그램


# Canvas item options, names and values.
# Names:
::msgcat::mcset kr anchor           닻
::msgcat::mcset kr arrow            화살표
::msgcat::mcset kr arrowshape       {화살표 모양}
::msgcat::mcset kr capstyle         {모자 스타일}
::msgcat::mcset kr coordinates      좌표축
::msgcat::mcset kr dash             대쉬
::msgcat::mcset kr file             파일
::msgcat::mcset kr fill             채우기
::msgcat::mcset kr fontfamily       글씨체
::msgcat::mcset kr fontsize         {글씨 크기}
::msgcat::mcset kr fontweight       {글씨 두께}
::msgcat::mcset kr image            그림
::msgcat::mcset kr joinstyle        {합치는 형태}
::msgcat::mcset kr justify          {단락 맞춤}
::msgcat::mcset kr outline          윤곽선
::msgcat::mcset kr outlinestipple   {점 윤곽선}
::msgcat::mcset kr smooth           부드러움
::msgcat::mcset kr stipple          점선
::msgcat::mcset kr tags             태그
::msgcat::mcset kr text             문자
::msgcat::mcset kr width            폭

# Values (see item inspector to see what they mean):
# anchor
::msgcat::mcset kr n          북
::msgcat::mcset kr ne         북동
::msgcat::mcset kr e          동
::msgcat::mcset kr se         남동
::msgcat::mcset kr s          남
::msgcat::mcset kr sw         남서
::msgcat::mcset kr w          서
::msgcat::mcset kr nw         북서
::msgcat::mcset kr center     중앙
# arrow
::msgcat::mcset kr last             끝
::msgcat::mcset kr first            처음
::msgcat::mcset kr both             양쪽

::msgcat::mcset kr transparent      투명한
::msgcat::mcset kr gray75           {회색 75%}
::msgcat::mcset kr gray50           {회색 50%}
::msgcat::mcset kr gray25           {회색 25%}
::msgcat::mcset kr gray12           {회색 12%}

::msgcat::mcset kr round            둥근이음
::msgcat::mcset kr miter            연귀이음
::msgcat::mcset kr bevel            빗각이음
::msgcat::mcset kr butt             뭉뚱이음
::msgcat::mcset kr projecting       돌출이음

::msgcat::mcset kr normal           일반
::msgcat::mcset kr bold             굵게
::msgcat::mcset kr italic           이탤릭체

::msgcat::mcset kr left             왼쪽
::msgcat::mcset kr right            오른쪽
::msgcat::mcset kr false            틀림
::msgcat::mcset kr true             맞음

# dashes
::msgcat::mcset kr none             없음
::msgcat::mcset kr dotted           점선
::msgcat::mcset kr dash-dotted      대쉬점선
::msgcat::mcset kr dashed           대쉬선


# Status messages.
::msgcat::mcset kr available	    {접속 가능함}
::msgcat::mcset kr away		    나감
::msgcat::mcset kr {do not disturb} {일에 집중하고 있어요}
::msgcat::mcset kr {not available}  {연결 못함}
::msgcat::mcset kr {extended away}  {멀리 나감}
::msgcat::mcset kr invisible	    안보임
::msgcat::mcset kr chat		    대화
::msgcat::mcset kr subscribed	    등록된
::msgcat::mcset kr unsubscribed	    등록해지된


# All menu labels; concateneted and prepended with 'm' for the database key.
::msgcat::mcset kr mFile		{파일}
::msgcat::mcset kr mEdit		{편집}
::msgcat::mcset kr mPreferences		{설정}
::msgcat::mcset kr mJabber		{재버}
::msgcat::mcset kr mItems		{아이템}
::msgcat::mcset kr mLibrary		{스텐실}
::msgcat::mcset kr mInfo		{정보}
::msgcat::mcset kr mAddons		{첨부기능}
::msgcat::mcset kr mPlugins		{플러그인}

::msgcat::mcset kr mAboutWhiteboard   	{칠판에 대해...}
::msgcat::mcset kr mAboutCoccinella   	{Coccinella에 대해...}
::msgcat::mcset kr mAboutQuickTimeTcl	{QuickTimeTcl에 대해...}
::msgcat::mcset kr mWelcome     	{어서오세요}
::msgcat::mcset kr mNew			{새로 만들기}
::msgcat::mcset kr mNewWhiteboard	{새 칠판}
::msgcat::mcset kr mOpenConnection	{연결 열기...}
::msgcat::mcset kr mCloseWindow		{원도우 닫기}
::msgcat::mcset kr mStartServer		{서버 시작하기}
::msgcat::mcset kr mOpenImage/Movie	{이미지/동영상 열기...}
::msgcat::mcset kr mOpenURLStream	{URL 스트림 열기...}
::msgcat::mcset kr mPutCanvas		{캔버스 보내기}
::msgcat::mcset kr mGetCanvas		{캔버스 받기...}
::msgcat::mcset kr mPutFile		{파일 보내기...}
::msgcat::mcset kr mStopPut/Get/Open	{보내기/받기/열기 중지하기}
::msgcat::mcset kr mOpenCanvas		{캔버스 열기...}
::msgcat::mcset kr mSaveCanvas		{캔버스 저장히기...}
::msgcat::mcset kr mSaveAs		{다른이름으로 저장하기...}
::msgcat::mcset kr mSaveAsItem          {아이템으로 저장하기...}
::msgcat::mcset kr mSaveImageAs         {다른이름으로 이미지 저장하기...}
::msgcat::mcset kr mPageSetup		{쪽 설정하기...}
::msgcat::mcset kr mPrintCanvas		{캔버스 인쇄하기...}
::msgcat::mcset kr mQuit		{나가기}
::msgcat::mcset kr mAll			{모두}
::msgcat::mcset kr mEraseAll		{모두 지우기}
::msgcat::mcset kr mUndo		{취소하기}
::msgcat::mcset kr mRedo		{다시하기}
::msgcat::mcset kr mCut			{자르기}
::msgcat::mcset kr mCopy		{빼끼기}
::msgcat::mcset kr mPaste		{붙이기}
::msgcat::mcset kr mInspectItem		{아이템 살펴보기...}
::msgcat::mcset kr mRaise		{높이기}
::msgcat::mcset kr mLower		{낮추기}
::msgcat::mcset kr mLarger		{큰 것}
::msgcat::mcset kr mSmaller		{작은 것}
::msgcat::mcset kr mFlip		{뒤집기}
::msgcat::mcset kr mHorizontal		{수평의}
::msgcat::mcset kr mVertical		{수직의}
::msgcat::mcset kr mImageLarger		{이미지 큰 것}
::msgcat::mcset kr mImageSmaller	{이미지 작은 것}
::msgcat::mcset kr mBackgroundColor	{배경색...}
::msgcat::mcset kr mGrid		{격자눈금}
::msgcat::mcset kr mThickness		{선 두께}
::msgcat::mcset kr mBrushThickness	{붓 두께}
::msgcat::mcset kr mFill		{채우기}
::msgcat::mcset kr mFillColor		{색 채우기...}
::msgcat::mcset kr mOutlineColor	{윤곽선 색}
::msgcat::mcset kr mLineSmoothness	{선 부드럽기}
::msgcat::mcset kr mStraighten   	{직선화}
::msgcat::mcset kr mArcs		{아크}
::msgcat::mcset kr mPieslice		{파이 조작}
::msgcat::mcset kr mChord		{현}
::msgcat::mcset kr mArc			{호}
::msgcat::mcset kr mDash		{대쉬}
::msgcat::mcset kr mShiftConstrain	{제한점 옮기기}
::msgcat::mcset kr mTo90degrees		{90도로}
::msgcat::mcset kr mTo45degrees		{45도로}
::msgcat::mcset kr mFont		{서체}
::msgcat::mcset kr mSize		{크기}
::msgcat::mcset kr mWeight		{굵기}
::msgcat::mcset kr mNormal		{일반}
::msgcat::mcset kr mBold		{굵은체}
::msgcat::mcset kr mItalic		{이탤릭체}
::msgcat::mcset kr mPreferences...	{설정...}
::msgcat::mcset kr mNewAccount		{새 계정...}
::msgcat::mcset kr mLogin		{로그인...}
::msgcat::mcset kr mLogout		{로그아웃}
::msgcat::mcset kr mLogoutWith          {메세지를 두고 로그아웃...}
::msgcat::mcset kr mHideMain            {주메뉴 감추기}
::msgcat::mcset kr mShowMain            {주메뉴 보이기}
::msgcat::mcset kr mPassword		{암호...}
::msgcat::mcset kr mRoster/Services	{명부/서비스}
::msgcat::mcset kr mMessageInbox	{받은 메세지함}
::msgcat::mcset kr mSearch		{찾기...}
::msgcat::mcset kr mAddNewUser		{새 사용자 더하기...}
::msgcat::mcset kr mSendMessage		{메세지 보내기...}
::msgcat::mcset kr mChat		{대화}
::msgcat::mcset kr mStatus		{상태}
::msgcat::mcset kr mDirStatus           {지시된 상태}
::msgcat::mcset kr mAvailable		{접속 가능}
::msgcat::mcset kr mAway		{자리비움}
::msgcat::mcset kr mDoNotDisturb	{업무에 집중}
::msgcat::mcset kr mNotAvailable	{접속 안됨}
::msgcat::mcset kr mExtendedAway        {멀리나감}
::msgcat::mcset kr mInvisible           {안보임}
::msgcat::mcset kr mAttachMessage	{메세지 첨부하기...}
::msgcat::mcset kr mEnterRoom		{방에 들어가기...}
::msgcat::mcset kr mExitRoom		{방 나가기}
::msgcat::mcset kr mCreateRoom		{방 만들기...}
::msgcat::mcset kr mvCard		{vCard...}
::msgcat::mcset kr mRemoveAccount	{계정 지우기}
::msgcat::mcset kr mErrorLog		{에러 로그...}
::msgcat::mcset kr mDebug		{디버그}
::msgcat::mcset kr mOnServer		{서버 켜기...}
::msgcat::mcset kr mOnClients		{클라이언트 켜기...}
::msgcat::mcset kr mOnPlugins		{플러그인 켜기...}
::msgcat::mcset kr mHelpOn		{도움말 켜기}
::msgcat::mcset kr mNetworkSetup	{네트워크 설정}
::msgcat::mcset kr mServers		{서버}
::msgcat::mcset kr mJabberTransport	{재버 송수신}
::msgcat::mcset kr mSmileyLegend	{스마일리 범례}
::msgcat::mcset kr mSetupAssistant	{설정 도움...}
::msgcat::mcset kr mImageLarger		{그림 큰 것}
::msgcat::mcset kr mImageSmaller	{그림 작은 것}
::msgcat::mcset kr mExportImage		{그림 보내기...}
::msgcat::mcset kr mExportMovie		{동영상 보내기...}
::msgcat::mcset kr mSyncPlayback	{동조시켜 다시실행}
::msgcat::mcset kr mColor		{색...}
::msgcat::mcset kr mAddSpeechBubble	{말 풍선 더하기}
::msgcat::mcset kr mUpdateCheck  	{갱신 점검}
::msgcat::mcset kr mReloadImage  	{그림 다시부르기}
::msgcat::mcset kr mCoccinellaHome  	{Coccinella 홈...}
::msgcat::mcset kr mComponents 	        {구성 요소...}
::msgcat::mcset kr mBugReport  	        {버그 보고서작성...}
::msgcat::mcset kr mTakeSnapShot        {스냅사진 만들기}
::msgcat::mcset kr mTimeCode            {시간표시}
::msgcat::mcset kr mUserInfo            {사용자 정보...}
::msgcat::mcset kr mEditBookmarks       {북마크 편집하기...}
::msgcat::mcset kr mToolbar         	{툴바}
::msgcat::mcset kr mNotebook         	{공책}
::msgcat::mcset kr mMinimal         	{Minimal}
::msgcat::mcset kr mDisco         	{Disco}
::msgcat::mcset kr mFind         	{찾기}
::msgcat::mcset kr mFindAgain         	{다시 찾기}

::msgcat::mcset kr mFindPrevious        {Find Previous}
::msgcat::mcset kr mFontSize            {Font Size}
::msgcat::mcset kr mNormalFont          {Normal}
::msgcat::mcset kr mLargerFont          {Larger}
::msgcat::mcset kr mLargeFont           {Large}

# Popups
::msgcat::mcset kr mMessage     	{메세지...}
::msgcat::mcset kr mWhiteboard     	{칠판...}
::msgcat::mcset kr mLastLogin/Activity  {최근 로그인/사용}
::msgcat::mcset kr mEditUser     	{사용자 편집...}
::msgcat::mcset kr mRemoveUser     	{사용자 제거...}
::msgcat::mcset kr mRefreshRoster     	{명부 정리}
::msgcat::mcset kr mVersion     	{버전}
::msgcat::mcset kr mRegister     	{등록}
::msgcat::mcset kr mUnregister     	{등록해지}
::msgcat::mcset kr mRefresh     	{정리}
::msgcat::mcset kr mAddServer     	{서버 더하기...}
::msgcat::mcset kr mLocalTime     	{지역 시간...}
::msgcat::mcset kr mSendFile     	{파일 보내기...}
::msgcat::mcset kr mChatHistory     	{대화 기록}
::msgcat::mcset kr mLoginTrpt     	{Login To Transport}
::msgcat::mcset kr mLogoutTrpt     	{Logout From Transport}
::msgcat::mcset kr mRemoveContact  	{대화상대 지우기...}
::msgcat::mcset kr mShow         	{보여주기}
::msgcat::mcset kr mOffline         	{오프라인}
::msgcat::mcset kr mTransports         	{Transports}
::msgcat::mcset kr mIgnore         	{무시하기}
::msgcat::mcset kr mSort         	{정렬하기}
::msgcat::mcset kr mIncreasing         	{증가}
::msgcat::mcset kr mDecreasing         	{감소}
::msgcat::mcset kr mStyle         	{스타일}
::msgcat::mcset kr mCall         	{콜}
::msgcat::mcset kr mJiveCall         	{콜}
::msgcat::mcset kr mJiveForward         {콜 전달하기}
::msgcat::mcset kr mBackgroundImage     {배경 그림}

::msgcat::mcset kr mEditNick            {Edit Nickname}


# Short texts only. Use english text as database key.
::msgcat::mcset kr {30 days}		      {30 일}
::msgcat::mcset kr {About Coccinella}	      {Coccinella에 대하여}
::msgcat::mcset kr {About Whiteboard}	      {칠판에 대하여}
::msgcat::mcset kr {About QuickTimeTcl}	      {QuickTimeTcl에 대하여}
::msgcat::mcset kr {About %s}		      {%s에 대하여}
::msgcat::mcset kr {Active <Return>}	      {<Return> 활성화}
::msgcat::mcset kr {Add New User}	      {새 사용자 더하기}
::msgcat::mcset kr {Add permanently}	      {영구적으로 더하기}
::msgcat::mcset kr {Add Server}		      {서버 더하기}
::msgcat::mcset kr {Add Shortcut}	      {단축키 더하기}
::msgcat::mcset kr {Address 1}		      {주소(대략)}
::msgcat::mcset kr {Address 2}		      {주소(상게)}
::msgcat::mcset kr {Advanced Setup}	      {고급 설정}
::msgcat::mcset kr {Advanced Configuration}   {고급 조정}
::msgcat::mcset kr {Alert sounds}	      {경고음}
::msgcat::mcset kr {As text}		      {문자로}
::msgcat::mcset kr {Ask each time}	      {매 시간 요청하기}
::msgcat::mcset kr {Auto Away}		      {자동으로 나가기}
::msgcat::mcset kr {Auto Connect}	      {자동 연결}
::msgcat::mcset kr {Auto Join}		      {자동 합류}
::msgcat::mcset kr {Auto-accept}	      {자동 허용}
::msgcat::mcset kr {Auto-reject}	      {자동 거절}
::msgcat::mcset kr {Away status}	      {자리비움 상태}
::msgcat::mcset kr {Basic Info}		      {기본 정보}
::msgcat::mcset kr {Block JID}		      {JID 방해물}
::msgcat::mcset kr {Bookmark this room}	      {현재 방 북마크하기}
::msgcat::mcset kr {Broken Image}	      {깨진 그림}
::msgcat::mcset kr {Buddy Pouncing}	      {친구로 참견하기}
::msgcat::mcset kr {Built in server port}     {서버 포트에 구축하기}
::msgcat::mcset kr {Cache folder}	      {캐쉬 폴더}
::msgcat::mcset kr {Canvas Size}	      {캔버스 크기}
::msgcat::mcset kr {Chat History}	      {대화 기록}
::msgcat::mcset kr {Chat With}		      {함께 대화}
::msgcat::mcset kr {Clear Disk Cache Now}     {지금 캐쉬 디스크 지우기}
::msgcat::mcset kr {Company Name}	      {회사명}
::msgcat::mcset kr {Component Info}	      {구성 요소 정보}
::msgcat::mcset kr {Conference server}	      {회의 서버}
::msgcat::mcset kr {Connect using HTTP}	      {HTTP로 연결하기}
::msgcat::mcset kr {Contact Type}	      {연결 형태}
::msgcat::mcset kr {Create Room}	      {방 만들기}
::msgcat::mcset kr {Default group}	      {기본 그룹}
::msgcat::mcset kr {Default Logout Status}    {기본 로그아웃 상태}
::msgcat::mcset kr {Default nickname}	      {기본 별명}
::msgcat::mcset kr {Default status descriptions}  {기본 상태 기술}
::msgcat::mcset kr {Delete Rule}	      {기본 규칙}
::msgcat::mcset kr {Delete Profile}	      {기본 프로파일}
::msgcat::mcset kr {Different Passwords}      {다른 암호}
::msgcat::mcset kr {Disk Cache}		      {디스크 캐쉬}
::msgcat::mcset kr {Disco method}	      {Disco 방법}
::msgcat::mcset kr {Do Not Disturb}	      {집중하고 싶어요}
::msgcat::mcset kr {Do not save password}     {암호 저장 않기}
::msgcat::mcset kr {Edit Fonts}		      {서체 편집하기}
::msgcat::mcset kr {Edit Item}		      {아이템 편집하기}
::msgcat::mcset kr {Edit Shortcut}	      {단축키 편집하기}
::msgcat::mcset kr {Edit Shortcuts}	      {단축키들 편집하기}
::msgcat::mcset kr {Edit User}		      {사용자 편집하기}
::msgcat::mcset kr {Email address}	      {이메일 주소}
::msgcat::mcset kr {Email addresses}	      {이메일 주소들}
::msgcat::mcset kr {Empty Fields}	      {비어있는 필드}
::msgcat::mcset kr {Enter/Create Room}	      {방 만들고/들어가기}
::msgcat::mcset kr {Enter Room}		      {방 들어가기}
::msgcat::mcset kr {Every time}		      {모든 시간}
::msgcat::mcset kr {Extended Away status}     {멀리나감 상태}
::msgcat::mcset kr {Factory Settings}	      {공장 설정}
::msgcat::mcset kr {Fatal Error}	      {치명적 오류}
::msgcat::mcset kr {File Cache}		      {파일 캐쉬}
::msgcat::mcset kr {File coding}	      {파일 코딩}
::msgcat::mcset kr {File Mappings}	      {파일 줄잇기}
::msgcat::mcset kr {File suffixes}	      {파일 구분자}
::msgcat::mcset kr {File Transfer}	      {파일 전송}
::msgcat::mcset kr {File Transfer Error}      {파일 전송 오류}
::msgcat::mcset kr {File transfer port}	      {파일 전송 포트}
::msgcat::mcset kr {First name}		      {이름}
::msgcat::mcset kr {Font Size}		      {서체 크기}
::msgcat::mcset kr {Font Weight}	      {서체 굵기}
::msgcat::mcset kr {Format mm/dd/yyyy}	      {포맷 mm/dd/yyyy}
::msgcat::mcset kr {Get File}		      {파일 받기}
::msgcat::mcset kr {Get File Error}	      {파일 받기 오류}
::msgcat::mcset kr {Get vCard}		      {vCard 받기}
::msgcat::mcset kr {Getting available rooms...}	 {가능한 방 찾기...}
::msgcat::mcset kr {Groupchat presence change}	 {모둠대화 수 바꾸기}
::msgcat::mcset kr {Groupchat-1.0 (fallback)}	 {모둠대화-1.0 (조처)}
::msgcat::mcset kr {Handled By}		      {안내자:}
::msgcat::mcset kr {History length}	      {기록 길이}
::msgcat::mcset kr {Host name}		      {호스트 이름}
::msgcat::mcset kr {HTTP port}		      {HTTP 포트}
::msgcat::mcset kr {>>Import>>}		      {>>받아오기>>}
::msgcat::mcset kr {Import Iconset...}	      {아이콘 세트 받아오기}
::msgcat::mcset kr {Import using}	      {사용 받아오기}
::msgcat::mcset kr {Import/Remove fonts}      {서체 받아오기/없애기}
::msgcat::mcset kr {Incoming Message}	      {받은 메세지}
::msgcat::mcset kr {Incoming Messages}	      {받은 메세지}
::msgcat::mcset kr {Incoming Presence}	      {받은 존재?}
::msgcat::mcset kr {Info Room}		      {정보 방}
::msgcat::mcset kr {Inspect Associations}     {연합체 살펴보기}
::msgcat::mcset kr {Invite User}	      {사용자 초대하기}
::msgcat::mcset kr {IP address}		      {IP 주소}
::msgcat::mcset kr {Is connected}	      {연결됨}
::msgcat::mcset kr {Is safe}		      {안전함}
::msgcat::mcset kr {Is server up}	      {서버 켜집}
::msgcat::mcset kr {Item Inspector}	      {아이템 살피기}
::msgcat::mcset kr {Item Options}	      {아이쳄 옵션}
::msgcat::mcset kr {Item Type}		      {아이템 형태}
::msgcat::mcset kr {Jabber address}	      {재버 주소}
::msgcat::mcset kr {Jabber Client}	      {재버 고객}
::msgcat::mcset kr {Jabber Server}	      {재버 서버}
::msgcat::mcset kr {Jabber server port}	      {재버 서버 포트}
::msgcat::mcset kr {Jabber user ID}	      {재버 사용자 ID}
::msgcat::mcset kr {Jabber ID}		      {재버 ID}
::msgcat::mcset kr {JID to block}	      {막을 JID}
::msgcat::mcset kr {Last Activity}	      {최근 활동}
::msgcat::mcset kr {Last name}		      {성}
::msgcat::mcset kr {Launch time}	      {착수 시간}
::msgcat::mcset kr {Local Time}		      {지역 시간}
::msgcat::mcset kr {Logout With Message}      {메세지 두고 로그아웃}
::msgcat::mcset kr {Logged out}		      {로그아웃}
::msgcat::mcset kr {Login as invisible}	      {안보이게 로그인}
::msgcat::mcset kr {Mailbox Error}	      {메일함 오류}
::msgcat::mcset kr {Make new text item for each line}  {매 줄 새 문자 아이템 만들기}
::msgcat::mcset kr {MIDI Player}	      {미디 플레이어}
::msgcat::mcset kr {MIME type}		      {MIME 형}
::msgcat::mcset kr {Movie Options}	      {동영상 옵션}
::msgcat::mcset kr {Multi Connect}	      {다중 연결}
::msgcat::mcset kr {My Avatar}		      {내 아바타}
::msgcat::mcset kr {My nickname for own display}	{자신에게 보이는 별명}
::msgcat::mcset kr {My Status}		      {내 상태}
::msgcat::mcset kr {My vCard}		      {내 vCard}
::msgcat::mcset kr {Name of list}	      {목록명}
::msgcat::mcset kr {Network Error}	      {네트워크 오류}
::msgcat::mcset kr {Network Setup}	      {네트워크 설정}
::msgcat::mcset kr {New Account}	      {새 계정}
::msgcat::mcset kr {New Bookmark}	      {새 북마크}
::msgcat::mcset kr {New chat message}	      {새 대화 메세지}
::msgcat::mcset kr {New chat thread}	      {새 대화 연결}
::msgcat::mcset kr {New Color}		      {새 색}
::msgcat::mcset kr {New incoming message}     {새 받은 메세지}
::msgcat::mcset kr {New Message}	      {새 메세지}
::msgcat::mcset kr {New Nickname}	      {새 별명}
::msgcat::mcset kr {New Password}	      {새 암호}
::msgcat::mcset kr {New Profile}	      {새 프로파일}
::msgcat::mcset kr {New Rule}		      {새 규칙}
::msgcat::mcset kr {New Topic}		      {새 토픽}
::msgcat::mcset kr {New shortcut}	      {새 단축키}
::msgcat::mcset kr {New User}		      {새 사용자}
::msgcat::mcset kr {New Version}	      {새 버전}
::msgcat::mcset kr {NAT Address}	      {NAT 주소}
::msgcat::mcset kr {Nick name}		      {별명}
::msgcat::mcset kr {No Address}		      {주소 없음}
::msgcat::mcset kr {No Available}	      {접속가능하지 않음}
::msgcat::mcset kr {No Inbox}		      {받는함 없름}
::msgcat::mcset kr {No Printing}	      {출력 없음}
::msgcat::mcset kr {No registered history for %s}    {%s에 대해 등록된 기록이 없음}
::msgcat::mcset kr {No Restriction}	      {제한 없음}
::msgcat::mcset kr {Not Available}	      {접속가능하지 않음}
::msgcat::mcset kr {Not available}	      {접속가능하지 않음}
::msgcat::mcset kr {Not Connected}	      {연결 안됨}
::msgcat::mcset kr {Not older than}	      {다음 시간 이전:}
::msgcat::mcset kr {Once per session}	      {세션당 한번씩}
::msgcat::mcset kr {Open Canvas}	      {캔버지 열기}
::msgcat::mcset kr {Open Failed}	      {열기 실패}
::msgcat::mcset kr {Open Helpfile}	      {도움파일 열기}
::msgcat::mcset kr {Open Image/Movie}	      {그림/동영상 열기}
::msgcat::mcset kr {Open Stream}	      {스트림 열기}
::msgcat::mcset kr {Outgoing Presence}	      {우호적 존재}
::msgcat::mcset kr {Peer-to-Peer}	      {Peer-to-Peer}
::msgcat::mcset kr {Personal Info}	      {개인 정보}
::msgcat::mcset kr {Personal Information}     {개인 정보}
::msgcat::mcset kr {Personal URL}	      {개인 URL}
::msgcat::mcset kr {Pick Directory}	      {디렉토리 집기}
::msgcat::mcset kr {Pick File}		      {파일 집기}
::msgcat::mcset kr {Pick Image File}	      {그림 파일 집기}
::msgcat::mcset kr {Pick skin}		      {스킨 집기}
::msgcat::mcset kr {Plugin Info}	      {플러그인 정보}
::msgcat::mcset kr {Plugin Control}	      {플러그인 조절}
::msgcat::mcset kr {Port number}	      {포트 번호}
::msgcat::mcset kr {Postal Code}	      {우편 번호}
::msgcat::mcset kr {Preferred Protocol}	      {선호하는 통신 프로토콜}
::msgcat::mcset kr {Presence Error}	      {존제 오류}
::msgcat::mcset kr {Privacy List}	      {프라이버시 목록}
::msgcat::mcset kr {Profile Name}	      {프로파일 명}
::msgcat::mcset kr {Proxy Port}		      {프록시 포트}
::msgcat::mcset kr {Proxy Server}	      {프록시 서버}
::msgcat::mcset kr {Proxy Setup}	      {프록시 설정}
::msgcat::mcset kr {Public Jabber Servers}    {공개 재버 서버}
::msgcat::mcset kr {Put File Error}	      {파일 보내기 오류}
::msgcat::mcset kr {Put Image/Movie}	      {그림/동영상 보내기}
::msgcat::mcset kr {Reject receive}	      {받기 거절하기}
::msgcat::mcset kr {Request To User}	      {사용자에게 요청하기}
::msgcat::mcset kr {Retype Password}	      {암호 다시치기}
::msgcat::mcset kr {Revert Panel}	      {판 뒤집기}
::msgcat::mcset kr {Register New Account}     {새 계정 등록하기}
::msgcat::mcset kr {Register Now}	      {지금 등록하기}
::msgcat::mcset kr {Register Service}	      {등록 서비스}
::msgcat::mcset kr {Remove Item}	      {아이템 제거하기}
::msgcat::mcset kr {Remove Photo}	      {사진 제거하기}
::msgcat::mcset kr {Room name}		      {방 번호}
::msgcat::mcset kr {Room name (optional)}     {방 이름(옵션)}
::msgcat::mcset kr {Roster & Services}	      {명부 & 서버스}
::msgcat::mcset kr {Save As}		      {다른이름으로 저장하기}
::msgcat::mcset kr {Save As GIF}	      {GIF 파일로 저장하기}
::msgcat::mcset kr {Save Canvas}	      {캔버스 저장하기}
::msgcat::mcset kr {Save File}		      {파일 저장하기}
::msgcat::mcset kr {Save Message}	      {메세지 저장하기}

::msgcat::mcset kr {Save password}

::msgcat::mcset kr {Scramble password}	      {암호 뒤섞기}
::msgcat::mcset kr {Search results}	      {찾은 결과}
::msgcat::mcset kr {Search Service}	      {찾기 서비스}
::msgcat::mcset kr {Search Specifications}    {명세 착지}
::msgcat::mcset kr {Select a new nickname}    {새 별명 선택하기}
::msgcat::mcset kr {Select Font}	      {서체 선택하기}
::msgcat::mcset kr {Select Photo}	      {사진 선택하기}
::msgcat::mcset kr {Send File}		      {파일 보내기}
::msgcat::mcset kr {Send Live}		      {라이브 보내기}
::msgcat::mcset kr {Server Info}	      {서버 정보}
::msgcat::mcset kr {Service server}	      {서비스 서버}
::msgcat::mcset kr {Set Directed Presence}    {지정된 존재 설정하기}
::msgcat::mcset kr {Set New Nickname}	      {새 별명 설정하기}
::msgcat::mcset kr {Set New Topic}	      {새 토픽 설정하기}
::msgcat::mcset kr {Set Status}		      {상태 설정하기}
::msgcat::mcset kr {Set windows opacity}      {원도우 투명도 설정하기}
::msgcat::mcset kr {Settings Panels}	      {판 설정}
::msgcat::mcset kr {Setup Assistant}	      {보조 설정하기}

::msgcat::mcset kr {Show Text and Image}
::msgcat::mcset kr {Show Text}
::msgcat::mcset kr {Show Image}

::msgcat::mcset kr {Slide Show}		      {슬라이드 쇼}
::msgcat::mcset kr {Slide Show Folder}	      {슬라이드 쇼 폴더}
::msgcat::mcset kr {Smooth freehand strokes}  {손으로 쓴 것 부드럽게 하기}
::msgcat::mcset kr {Software Update}	      {프로그램 업데이트}
::msgcat::mcset kr {Sound Set} 		      {음 세트}
::msgcat::mcset kr {Sounds & Speech}	      {음과 말}
::msgcat::mcset kr {Start Chat}		      {대화 시작하기}
::msgcat::mcset kr {Status message}	      {상태 메세지}
::msgcat::mcset kr {Status when logging out}  {로그아웃때의 상태}
::msgcat::mcset kr {Subscription Failed}      {서명 실패}
::msgcat::mcset kr {Subscription Pending}     {서명 지체}
::msgcat::mcset kr {Synthetic speech}	      {동기화된 말}
::msgcat::mcset kr {System fonts}	      {시스템 서체}
::msgcat::mcset kr {Take Snapshot}	      {스냅샷 찍기}
::msgcat::mcset kr {Tel (voice)}	      {전화}
::msgcat::mcset kr {Tel (fax)}		      {팩스}
::msgcat::mcset kr {This IP number}	      {현 IP 주소}
::msgcat::mcset kr {Thread started}	      {연결 시작}
::msgcat::mcset kr {To/from JID}	      {JID 로/부터}
::msgcat::mcset kr {To Jabber ID}	      {재버 ID 로}
::msgcat::mcset kr {To Send or Not}	      {보내거나 말거나}
::msgcat::mcset kr {Type of File}	      {파일 형}
::msgcat::mcset kr {Unknown: Prompt user}     {알수 없음: 즉석 사용자}
::msgcat::mcset kr {Url of homepage}	      {홈페이지 주소}
::msgcat::mcset kr {Use proxy}		      {프록시 사용하기}
::msgcat::mcset kr {Use Secure Connection}    {암호화된 연결 사용}
::msgcat::mcset kr {Use SSL for security}     {암호화를 위해 SSL 사용}
::msgcat::mcset kr {Use TLS and SASL authentication}   {사용자 인증을 위해 TLS와 SASL 사용}
::msgcat::mcset kr {Use TLS on separate port (old)}    {분리된 포트상에서 TLS 사용 (이전형태)}
::msgcat::mcset kr {User Info}		      {사용자 정보}
::msgcat::mcset kr {User is}		      {사용자는}
::msgcat::mcset kr {User is offline}	      {사용자는 오프라인 상태}
::msgcat::mcset kr {User is online}	      {사용자는 온라인 상태}
::msgcat::mcset kr {User Profiles}	      {사용자 프로파일}
::msgcat::mcset kr {User's status changed}    {사용자 상태 변화됨}
::msgcat::mcset kr {Users Avatar}	      {사용자 아바타}
::msgcat::mcset kr {Username & Password}      {사용자명과 암호}
::msgcat::mcset kr {vCard Info}		      {vCard 정보}
::msgcat::mcset kr {Version Info}	      {버전 정보}
::msgcat::mcset kr {Whiteboard fonts}	      {칠판 서체}
::msgcat::mcset kr {Writing file}	      {파일 쓰기}

# Rooms.
::msgcat::mcset kr {Kick Participant}	      {쫒아내기}
::msgcat::mcset kr {Ban Participant}	      {참여 막기} 
::msgcat::mcset kr {Configure Room}	      {방 설정하기}
::msgcat::mcset kr {Destroy Room}	      {방 부수기}
::msgcat::mcset kr {Edit Lists}		      {목록 편집하기}
::msgcat::mcset kr {Edit the privilege to speak in the room, the voice.}    {방에서, 말하는 우선권 편집하기}
::msgcat::mcset kr {Edit the ban list}	      {거부 목록 편집하기}
::msgcat::mcset kr {Edit the member list}     {회원 목록 편집하기}
::msgcat::mcset kr {Edit the moderator list}  {진행자 목록 편집하기}
::msgcat::mcset kr {Edit the admin list}      {관리자 목록 편집하기}
::msgcat::mcset kr {Edit the owner list}      {소유자 목록 편집하기}

# Time intervals.
::msgcat::mcset kr {Ten seconds}	      {10 초}
::msgcat::mcset kr {One minute}		      {1 분}
::msgcat::mcset kr {Ten minutes}	      {10 분}
::msgcat::mcset kr {One hour} 		      {1 시간}
::msgcat::mcset kr {One day} 		      {하루}
::msgcat::mcset kr {One week} 		      {한 주}

# Language names.
::msgcat::mcset kr {Danish} 		      {덴마크어}
::msgcat::mcset kr {Dutch} 		      {네덜란드어}
::msgcat::mcset kr {English} 		      {영어}
::msgcat::mcset kr {French} 		      {불어}
::msgcat::mcset kr {German} 		      {독일어}
::msgcat::mcset kr {Italian}		      {이태리어}

::msgcat::mcset kr {Korean}

::msgcat::mcset kr {Polish} 		      {폴란드어}
::msgcat::mcset kr {Russian} 		      {러시아어}
::msgcat::mcset kr {Spanish} 		      {스페인어}
::msgcat::mcset kr {Swedish} 		      {스웨던어}

# Same languge names but with their native names.
# See the other catalogs to get these.
::msgcat::mcset kr nativeDanish     Danish
::msgcat::mcset kr nativeDutch      Dutch
::msgcat::mcset kr nativeEnglish    English
::msgcat::mcset kr nativeFrench     Francais
::msgcat::mcset kr nativeGerman     Deutsch
::msgcat::mcset kr nativeItalian
::msgcat::mcset kr nativeKorean
::msgcat::mcset kr nativePolish 
::msgcat::mcset kr nativeRussian 
::msgcat::mcset kr nativeSpanish    Castellano
::msgcat::mcset kr nativeSwedish    Svenska 


# Splash screen:
::msgcat::mcset kr splashsource 	{Tcl 코드 소스...}
::msgcat::mcset kr splashload 		{Tcl 퍄캐지 로딩중...}
::msgcat::mcset kr splashloadsha1 	{sha1 패키지 로딩중...}
::msgcat::mcset kr splashsourcejabb 	{재버 코드 소스...}
::msgcat::mcset kr splashhost 		{자체 호스트명 검색중...}
::msgcat::mcset kr splashinit 		{초기화...}
::msgcat::mcset kr splashprefs 		{설정 구성중...}
::msgcat::mcset kr splashbuildmenu	{메뉴 구성중...}
::msgcat::mcset kr splashbuild 		{사용자 환경 구성중...}
::msgcat::mcset kr splashlook 		{찾는중}


# Messages for tk_messageBox:
::msgcat::mcset kr messfailedhttp	{내부 웹 서버 구동 실패: %s}
::msgcat::mcset kr messinfoscript	{맥의 '내부 스크립트'버그에 의해, 다음 대화창에 '칠판-%s'폴더를 집어내야 합니다.}
::msgcat::mcset kr messfailedsock	{서버에 네트워크 소켓을 만들지 못했습니다. 아마 네트워크에 문제가 있던지 서버가 죽어있습니다. 에러문: %s}
::msgcat::mcset kr messeofconnect	{연결중 문제가 발생했습니다. 파일의 마지막으로 갑니다.}	
::msgcat::mcset kr messfailconnect	{%s에 연결중 문제가 발생했습니다.}
::msgcat::mcset kr messtimeout		{열기 시도중 시간초과되었습니다.}
::msgcat::mcset kr messnoplugs		{이 시스템에는 지정한 플러그인이나 지원 프로그램이 없습니다.}
::msgcat::mcset kr messfailopread	{%s 읽기위해 열수 없음: %s}
::msgcat::mcset kr messfailopwrite	{%s 쓰기위해 열수 없음: %s}
::msgcat::mcset kr messcanerasewarn	{캔버스를 여는 것은 현재의 캔버스를 다 지웁니다!}
::msgcat::mcset kr messaskreceive	{지금 막 %s 파일을 받았습니다. 당신도 받기를 원하나요?}
::msgcat::mcset kr messfailmimeimp 	{MIME type %s 에 해당하는 응용프로그램을 찾지 못했습니다.}
::msgcat::mcset kr messfailnomime 	{파일 %s 에 대한 MIME type 을 찾지 못했습니다.}
::msgcat::mcset kr messfailsend		{%s 로 보내는 과정에서 에러가 생겼습니다.}
::msgcat::mcset kr messfactorydefaults	{당신의 설정 대부분을 지금 막 지우려 하고 있습니다. 정말로 그러실 거예요?}
::msgcat::mcset kr messremoveprofile	{이 프로파일을 정말로 지우려합니까? 이 과정중에 당신 계정을 지우는 일은 일어나지 않습니다.}
::msgcat::mcset kr messfillserveruser	{최소한 서버이름과 사용자이름을 넣어주셔야 합니다.}
::msgcat::mcset kr messprofinuse	{이 프로파일은 이미 사용중입니다. 바꾸길 원하나요?}
::msgcat::mcset kr messblockbadjid	{JID "%s" 는 잘 구성된 것이 아니군요. 어쨋든 이를 부가시켜놓을 건가요?}
::msgcat::mcset kr messfieldsmissing	{하나이상의 필드가 빠져있군요. 다시 해주시던지 취소해 주세요.}
::msgcat::mcset kr messrmstandardfonts	{표준 폰트 (타임체, 큐리어체등)은 제거되지 않습니다.}
::msgcat::mcset kr messprefschanged	{설정이 변경되었습니다. 어쨋든 취소하고 싶은가요?}
::msgcat::mcset kr messerrpreffile	{%s 파일을 여는 데 오류발생.}
::msgcat::mcset kr messfailserver	{서버 소켓을 시작하지 못했습니다. 아마 연결되지 않았습니다.}
::msgcat::mcset kr messopenhelpfile	{캔버스에서 도움말을 열러고 했는데, 이는 현재의 도구들을 지우게 됩니다. 그러길 원하나요?}
::msgcat::mcset kr messprintnoextension	{여기서는 도와줄 tcl확장이 없는 것 같은데요 :-(}
::msgcat::mcset kr messdoquit?		{정말 나가고 싶으세요?}
::msgcat::mcset kr messsuassfillin	{계속하기 전에 모든 항목을 채웟는지 확인하세요}
::msgcat::mcset kr messsuassclose	{정말 설정 도우미를 닫기를 원하나요? 나중에 메뉴에서 언제든지 다시 사용할 수 있습니다.}
::msgcat::mcset kr messprotocolch	{네트워크 설정을 바꾸었습니다. 프로그램을 다시 시작하면 적용됩니다. 계속하길 원하나요?}
::msgcat::mcset kr messpasswddifferent  {두 암호가 서로 맞지 않습니다. 다시해 주세요.}
::msgcat::mcset kr messaupdatelatest    {이미 최신 버전(%s) 을 설치했습니다.}
::msgcat::mcset kr messprefsrestart     {설정은 프로그램 재시작시 적용됩니다.}

# Messages for tk_messageBox:
::msgcat::mcset kr jamesserrsend	{"%s"에 메세지를 보내는 중에 오류가 발생하였습니다. 오류코드는 %s 입니다. 오류 메세지: %s}
::msgcat::mcset kr jamessallowsub	{%s님이 상대 등록을 허용했습니다.}
::msgcat::mcset kr jamessunsub		{%s님이 등록해지 했으며, 당신의 대화상대 목록에서 지워졌습니다.}
::msgcat::mcset kr jamessunsubpres	{%s님이 등록해지했습니다.}
::msgcat::mcset kr jamessunsubask	{%s님이 등록해지했습니다. 당신의 목록에서 %s님을 지우시길 원하시나요?}
::msgcat::mcset kr jamessunsubscribed	{%s님의 목록에서 삭제되었습니다.}
::msgcat::mcset kr jamesserrpres	{현 목록에 대한 오류가 발생했습니다. 오류 코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamessautoaccepted	{%s님의 등록신청을 자동으로 허용했습니다.}
::msgcat::mcset kr jamessautoreject	{%s님의 등록신청을 자동으로 거절했습니다.}
::msgcat::mcset kr jamessautosubs	{%s님의 등록신청을 자동으로 목록에 등록했습니다.}


::msgcat::mcset kr jamessconnbroken	{연결이 불연듯 끊어졌습니다.}
::msgcat::mcset kr jamessautoawayset 	{%s에 자동적으로 나가게 되었습니다. 다시 보이길 원하나요?}
::msgcat::mcset kr jamesserrgetpublic	{%s로 부터 공용 데이터를 받는 중에 오류가 생겼습니다. 에러코드는 %s입니다. 에러문: %s}
::msgcat::mcset kr jamesserrlastactive	{최근 작업에 대해 %s 질의에 대해 오류가 생겼습니다. 에러문: %s}
::msgcat::mcset kr jamesserrnotimeinfo	{%s 가 시간 정보를 보내지 않습니다.}
::msgcat::mcset kr jamesstimeused	{"%s" 프로그램이 최근 시작된 후의 시간: }
::msgcat::mcset kr jamesstimeconn	{ "%s" 사용자가 연결된 후의 시간: }
::msgcat::mcset kr jamesstimeservstart	{"%s" 서버가 시작한 후의 시간: }
::msgcat::mcset kr jamessuptime		{사용자의 최근 사용시간: }
::msgcat::mcset kr jamesserrtime	{시간에 대한 문의 %s 에 대해 오류가 발생했습니다. 오류문: %s}
::msgcat::mcset kr jamesslocaltime	{%s에 대한 지역 시간: %s}
::msgcat::mcset kr jamesserrvers	{버전에 대한 문의 %s 에 대해 오류가 발생했습니다. 오류문: %s}
::msgcat::mcset kr jamesserrautoupdate 	{사용자 프로그램의 업데이트에 대한 문의 %s 에 대해 오류가 발생했습니다. 오류문: %s}
::msgcat::mcset kr jamesswarberasewb	{우선 필판을 지우시길 원하시나요?}
::msgcat::mcset kr jamesswarnremove	{그대의 목록에서 아이템을 지우는 것은 실행되지 않는 프로세스입니다. 다시 되돌리려고 하시면, 한번 더 등록해야 합니다. 어쨋든 계속하시겠습니까?}
::msgcat::mcset kr jamessillegalchar	{%s에 허용되지 않은 문자가 있습니다: "%s"!}
::msgcat::mcset kr jamessbadjid		{jid "%s" 가 잘 구성되지 않았습니다.  어쨋든 계속하시겠습니까?}
::msgcat::mcset kr jamessalreadyinrost	{jid "%s" 는 이미 그대의 목록에 있습니다.  어쨋든 계속하시겠습니까?}
::msgcat::mcset kr jamessfailsetnick	{"%s"님에 대한 별명이나 그룹을 설정하는데 오류가 발생했습니다. 오류코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamessnamemissing	{%s 는 읽어버린 것이거나 너무 짧습니다!}
::msgcat::mcset kr jamessnosocket	{서버 "%s"에 대한 소켓을 만들지 못합니다. 네트워크가 죽었거나 서버가 죽었습니다. 메세지: %s}
::msgcat::mcset kr jamesstimeoutserver	{서버 "%s"를 기다리다가 시간이 넘었습니다.}
::msgcat::mcset kr jamessregisterok	{서버 "%s" 에 대한 등록이 성공했습니다. 이제 사용자명과 암호로 로그인 하시면 됩니다.}
::msgcat::mcset kr jamessremoveaccount	{이 서버에서 당신계정을 지우셨습니다. 이 프로세스는 진행되지 않을 것입니다. 정말 계속하길 원하나요?}
::msgcat::mcset kr jamesserrunreg	{"%s"에서 등록해지를 하려는 중에 오류가 발생했습니다. 오류 코드는 %s입니다. 오류문: %s}
::msgcat::mcset kr jamessokunreg	{"%s"에서 등록해지 되었습니다.}
::msgcat::mcset kr jamesspasswddiff	{암호가 맞지않습니다. 한번 점검해 주세요.}
::msgcat::mcset kr jamesspasswderr	{새암호 설정이 오류가 났습니다. 오류코드는 %s입니다. 오류문: "%s"}
::msgcat::mcset kr jamesspasswdok	{새암호설정이 성공했습니다}
::msgcat::mcset kr jamessregnoserver	{서버 설치가 필요합니다.}
::msgcat::mcset kr jamesserrregget	{등록정보를 받아오지 못했습니다. 오류코드는 %s입니다. 오류문: %s}
::msgcat::mcset kr jamesserrregset	{서비스 "%s"의 등록 실패. 오류코드는 %s입니다. 오류문: %s}
::msgcat::mcset kr jamessokreg		{서비스 "%s"의 등록 성공}
::msgcat::mcset kr jamessinvalidjid	{JID 주소가 제대로 구성되지 않았습니다. 제대로 된 주소인지 칠판 밑칸을 확인해 보세요.\
  아마도, 다음과 같이 되어 있을 것입니다. 'username@jabber.org'.}
::msgcat::mcset kr jamessnotconnected	{서버에 연결되지 않아서 보낼 수 없습니다}
::msgcat::mcset kr jamessaddrmiss	{적어도 하나이상 제대로 된 주소가 필요합니다}
::msgcat::mcset kr jamesschatclose	{이 대화방을 닫으면 전체 대화를 잃게됩니다. 그래도 닫으실래요?}
::msgcat::mcset kr jamessnogroupchat	{그룹대화에 해당하는 서비스를 인식할 수 없습니다}
::msgcat::mcset kr jamessgcnoroomname   {방 이름을 적어주셔야 합니다.}
::msgcat::mcset kr jamessgcnoroomnick   {별명을 제공하셔야 합니다.}
::msgcat::mcset kr jamessinroommiss	{방에 들어가기 전에 모든 칸이 채워져야 합니다}
::msgcat::mcset kr jamesswarnexitroom	{"%s" 방을 나가시려고 합니까?}
::msgcat::mcset kr jamesserrbrowse	{"%s"를 돌아보는데 오류가 생겼습니다: %s}
::msgcat::mcset kr jamessenterroomempty	{서버와 방 이름에 제대로 된 이름이 필요합니다.}
::msgcat::mcset kr jamesserrconfget	{방에 들어가기 위한 정보를 얻는데 실패했습니다. 오류코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamesserrconfgetcre	{방을 만들기 위한 정보를 얻는데 실패했습니다. 오류코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamessinroomerasewb 	{새 방에 들어가기 전에 칠판을 지우길 원하시나요?}
::msgcat::mcset kr jamessconffailed	{"%s"방을 들어가거나/만들기에 실패했습니다. 오류코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamessconfservempty	{서버에 대한 제대로된 이름이 필요합니다.}
::msgcat::mcset kr jamesserragentget	{에이전트를 구성하는데 오류가 생겼습니다: %s}
::msgcat::mcset kr jamesserrsearch	{명세를 찾는데 실패했습니다. 오류코드는 %s 입니다. 오류문: %s}
::msgcat::mcset kr jamessoobok		{파일 전송에 성공했습니다}
::msgcat::mcset kr jamessoobok2         {%s의 "%s" 로의 파일 전송 ok}
::msgcat::mcset kr jamessoobnourl	{"%s"님이 파일을 보내주길 원할 때, 해당 url를 받지 못했습니다.}
::msgcat::mcset kr jamessoobask		{"%s"님이 파일 %s 를 보내려 합니다. %s 를 원하시나요?}
::msgcat::mcset kr jamessoobbad		{"%s"님으로 받은 url이 제대로 구성되어 있지 않습니다. url: "%s"}
::msgcat::mcset kr jamessoonnohttp	{"%s"님으로 부터 받은 url 은 http 프로토콜을 지원하지 않습니다. 지원되지 않는 것은 %s  입니다.}
::msgcat::mcset kr jamessoobfailopen	{%s을 여는데 실패했습니다}
::msgcat::mcset kr jamessoobgetfail	{url "%s"를 얻는데 실패했습니다: %s}
::msgcat::mcset kr jamessoobtimeout	{http를 통해 파일을 받는 동안 시간초과 되었습니다.}

::msgcat::mcset kr jamessooberr406      {%s님은 %s 을 받는것이 거절되었습니다.}
::msgcat::mcset kr jamessooberr404      {%s를 %s님에게 보내는 중에 오류가 생겼습니다. 오류코드는 %s 입니다. 오류문: %s}

::msgcat::mcset kr jamesserrinboxopen	{받은 파일 %s 을 저장하려는 중에 오류가 생겼습니다.}
::msgcat::mcset kr jamesserrinboxread	{재버 메세지 박스의 "%s"를 읽으려는 데 실패했습니다: %s}
::msgcat::mcset kr jamesschatclose	{이 대화창을 닫으면, 전 대화기록을 잃게됩니다. 그래도 될까요?}
::msgcat::mcset kr jamessgchatfields	{방에 들어가기전에 모든 항목이 채워져야 합니다.}
::msgcat::mcset kr jamessconfmsg	{회의 서비스와 방 이름을 선택하라. 각각 다른 요청사항이 있는 서버와 방에서 원하는 방에 들어가기 위한 명세를 얻기 위해 "Get"을 클릭하라.}
::msgcat::mcset kr jamesssavemsg	{닫기전에 이 메세지를 저장하길 원하나요?}
::msgcat::mcset kr jamessskipsendq	{주소 "%s"는 제대로 구성되어 있지 않습니다. 건너뛰고 나마지를 보낼까요?}
::msgcat::mcset kr jamessillformresend	{주소 "%s"는 제대로 구성되어 있지 않습니다. 다시 작성하여 다시 보내주세요.}
::msgcat::mcset kr jamesslogin409	{로그인에 실패했습니다. 오류코드: %s 사용자명을 다른 분이 사용하고 있습니다.}
::msgcat::mcset kr jamessloginerr	{로그인에 실패했습니다. 오류코드: %s , 오류문: %s}
::msgcat::mcset kr jamessaddforeign	        {비-재버 메신저 시스템으로 부터 사용자를 추가하는 것은 해당 시스템에서의 계정을 가지고 있어야 합니다. 그리고, 이 계정 정보를 이용하여\
해당 서버의 전송 요소 %s 를 등록을 할 수 있습니다 지금 하실길 원하시나요?}
::msgcat::mcset kr jamessowntrpt	        {그 메신저 시스템으로 메세지를 전송하는 서버 서비스 %s로 작동하는 당신 자신의 계정입니다. 당신의 목록에 있어야 합니다.\
%s에 대한 등록사항을 가지고 있습니다: %s.}
::msgcat::mcset kr jamesswbchatlost	        {대화 칠판을 닫으면, 전 대화내용을 잃게됩니다. 이 대화를 끝내길 원하시나요?}
::msgcat::mcset kr jamesschatoffline            {이 사용자는 온라인상에 없으며, 메세지를 보낼 수 없습니다.}
::msgcat::mcset kr jamessregloginok             {지금 등록했으며 자동으로 "%s"로 로그인 됩니다.}
::msgcat::mcset kr jamessregerrinuse            {다른 사용자가 사용자명을 이미 사용하고 있어 등록에 실패했습니다. 오류문: %s}
::msgcat::mcset kr jamessregerr                 {등록에 실패했습니다. 오류문: %s}
::msgcat::mcset kr jamesstrptsubsc              {%s 서비스에 등록된 당신 계정은 목록에 추가되며 이 서비스에 정송처로 사용됩니다.}
::msgcat::mcset kr jamessfailedsubsc            {%s에 등록하는데 실패했습니다. 등록거부되었습니다.}
::msgcat::mcset kr jamessgcinvite               {그룹대화 방 %s 에 %s님이 당신을 초대했습니다. 함께하실래요?}
::msgcat::mcset kr jamessnorooms                {%s에서 방을 찾지 못했습니다.}
::msgcat::mcset kr jamessnofiletrpt             {%s가 파일 전송을 지원하는 지 알 수 없습니다.}
::msgcat::mcset kr jamessfiletrpterr            {%s 라는 파일을 %s로부터 받아오는데 실패했습니다: %s}
::msgcat::mcset kr jamesswarnsendcanoff         {당신이 보내고자 하는 상대인 "%s"님이 온라인에 없습니다. 이 메세지에 그림같은 것이 있다면, 이메세지를 볼 동안 당신이 온라인에 있어야만 볼 수 있습니다.\
그래도 보내시겠습니까?}

::msgcat::mcset kr jamessstatuscust             {Set your message for any of the presence states.}
::msgcat::mcset kr jamessstatuscustdtl          {The most frequent states and corresponding messages are easily reachable as menu entries.}
::msgcat::mcset kr jamessproxy-failure          {The proxy server reported an error. The error code is "%s".}


# This maps Defined Error Conditions to clear text messages.
# RFC 3929 (XMPP Core): 6.4 SASL Errors
# 
# These are much too formal to be used for user display and we therfore instead use the short forms below.

::msgcat::mcset kr xmpp-stanzas-aborted             {시작 개체가 보낸 요소 삭제를 수신 개체가 인식하였다.}
::msgcat::mcset kr xmpp-stanzas-incorrect-encoding  {시작 개체가 제공하는 데이터가 [BASE64]엔코딩이 맞지않다는 이유로 진행되지 못했습니다.}
::msgcat::mcset kr xmpp-stanzas-invalid-authzid     {시작 개체에 의해 제공된 authzid가 맞지 않습니다. 잘못 구성되어 있거나 시작 개체가 해당 ID를 인증하기 위한 권한이 없기 때문입니다.}
::msgcat::mcset kr xmpp-stanzas-invalid-mechanism   {시작 개체는 수신 개체가 제공하지 않는 메카니즘을 제공하거나 요청하지 않습니다.}
::msgcat::mcset kr xmpp-stanzas-mechanism-too-weak  {시작 개체가 요청하는 메카니즘은 서버 정책이 시작 개체에 허용하는 범위내에 있습니다.}
::msgcat::mcset kr xmpp-stanzas-not-authorized      {시작개체가 제대로 된 증명(알수 없는 사용자의 경우 등을 포함한다)를 제공하지 않아, 인증 실패했습니다.}
::msgcat::mcset kr xmpp-stanzas-temporary-auth-failure {수신 개체에 있는 일시적인 오류 조건에 의해 인증실패 했습니다.}

# Short messages in place of the above ones.
::msgcat::mcset kr xmpp-stanzas-short-aborted             {로그인 과정이 중단되었습니다.}
::msgcat::mcset kr xmpp-stanzas-short-incorrect-encoding  {로그인 과정중에 프로토콜 오류가 생겼습니다.}
::msgcat::mcset kr xmpp-stanzas-short-invalid-authzid     {로그인 과정중에 프로토콜 오류가 생겼습니다.}
::msgcat::mcset kr xmpp-stanzas-short-invalid-mechanism   {로그인 과정중에 프로토콜 오류가 생겼습니다.}
::msgcat::mcset kr xmpp-stanzas-short-mechanism-too-weak  {로그인 과정중에 프로토콜 오류가 생겼습니다.}
::msgcat::mcset kr xmpp-stanzas-short-not-authorized      {사용자 명이나 암호가 잘못되어 로그인 실패했습니다.}
::msgcat::mcset kr xmpp-stanzas-short-temporary-auth-failure {로그인 과정중에 프로토콜 오류가 생겼습니다.}


# Related error conditions detected by the client.
::msgcat::mcset kr starttls-nofeature     {"%s"서버는 TLS에 대해 지원하지 않습니다.}
::msgcat::mcset kr starttls-failure       {"%s" 서버와의 TLS 교신 실패.}
::msgcat::mcset kr sasl-no-mechanisms     {이 서버는 SASL 인증을 지원하지 않습니다.}

::msgcat::mcset kr sasl-protocol-error    {Authentication failed due to internal protocol error.}

# A collective description of all stream errors.
::msgcat::mcset kr xmpp-streams-error     {서버로 부터 다음 코드의 스트림 오류 코드를 받았습니다: %s}


# Account xform balloon help.
# From: JEP-0077: In-Band Registration 
::msgcat::mcset kr registration-username        {사용자에 관련된 계정 명}
::msgcat::mcset kr registration-nick            {사용자에게 친근한 이름}
::msgcat::mcset kr registration-password        {사용자를 위한 암호나 비밀}
::msgcat::mcset kr registration-name            {사용자의 전체 이름}
::msgcat::mcset kr registration-first           {사용자의 이름}
::msgcat::mcset kr registration-last            {사용자의 성씨}
::msgcat::mcset kr registration-email           {사용자의 전자우편}
::msgcat::mcset kr registration-address         {우편 세부 주소}
::msgcat::mcset kr registration-city            {우편 지역 주소}
::msgcat::mcset kr registration-state           {우편 도시 주소}
::msgcat::mcset kr registration-zip             {우편 번호}
::msgcat::mcset kr registration-phone           {사용자 전화번호}
::msgcat::mcset kr registration-url             {사용자 관련 URL}
::msgcat::mcset kr registration-date            {기념일 (예: 생일, 공요일, 등록일등)}
::msgcat::mcset kr registration-is-registered   {당신이 이 서비스에 이미 등록했습니다. 당신 계정의 현재 설정값입니다.}

# Map version info tags to display names.
::msgcat::mcset kr version-name                 {이름}
::msgcat::mcset kr version-version              {버전}
::msgcat::mcset kr version-os                   {운영 시스템}


::msgcat::mcset kr register-trpt-unreg          {몇몇의 사용자들에 연계된 전송을 등록해지 하려고 합니다. 이 사용자들을 제거하는 것을 원하시나요?(Yes), 아미녀, 그대로 두나요(No), 또는 전체 진행을 취소하시나요(Cancel).}


::msgcat::mcset kr openquicktime		{QuickTime 라이브 스트림 열기}
::msgcat::mcset kr writeurl			{URL을 쓰거나 단축키에서 고르세요choose from shortcut:}
::msgcat::mcset kr openquicktimeurlmsg		{QuickTime 실시간 라이즈 스트리밍을 위한 파일 확장자 .mov의 SDF 파일을 포함하는 URL 열기. 오디오(라디오) 나 비디오(TV).\
달리, 실시간 전송을 위한 SDF 파일을 웹 브라우져를 잉요하여 찾아서, 디스크에 다운로드라여 일반적 영화를 열듯이 하라.}
::msgcat::mcset kr printunixcmd                 {쉡 프린트 명령어, 원하면 편집하세요}
::msgcat::mcset kr enterpassword                {"%s" 계정에 대한 암호를 치세요}
::msgcat::mcset kr wblockitem                   {편집을 못하도록 이 아이템을 잠그세요}



::msgcat::mcset kr httptrptok                   {%s을 받는 것을 마침}
::msgcat::mcset kr httptrpterror                {%s받는 중에 파일 전송 오류: %s}
::msgcat::mcset kr httptrpteof                  {서버가 답변없이 소켓을 닫았습니다.}
::msgcat::mcset kr httptrptnon200               {%s받는 중에 파일 전송 오류: 오류코드 %s; %s}
::msgcat::mcset kr httptrptreset                {%s 파일 전송 재시작됨}

::msgcat::mcset kr uastatpointmac 	{점 도구, 표시하려면 클릭, 드려다보려면 더블클릭, 팝업을 위해서는 누르세요}
::msgcat::mcset kr uastatpoint		{점 도구, 표시하려면 클릭, 드려다보려면 더블클릭, 팝업을 오른쪽 클릭 하세요}
::msgcat::mcset kr uastatmove		{이동 도구}
::msgcat::mcset kr uastatline		{선 도구}
::msgcat::mcset kr uastatarrow		{화살표 도구}
::msgcat::mcset kr uastatrect		{사각형 도구}
::msgcat::mcset kr uastatoval		{둥근형 도구}
::msgcat::mcset kr uastattext		{문자 도구}
::msgcat::mcset kr uastatdel		{지우기위해 틀릭하세요}
::msgcat::mcset kr uastatpen		{펜 도구}
::msgcat::mcset kr uastatbrush		{붓 도구}
::msgcat::mcset kr uastatpaint		{페인트 도구, shift-click은 투명도 조정}
::msgcat::mcset kr uastatpoly		{다각형 도구, 취소를 하려면 스페이스바}
::msgcat::mcset kr uastatarc		{호 도구, 중심설정을 위해서 클릭, 취소를 하려면 스페이스바}
::msgcat::mcset kr uastatarc2		{호 도구, 클릭하고 끌기}
::msgcat::mcset kr uastatrot		{회전 도구, 우선 아이템을 고르세요}


# Preferences:
::msgcat::mcset kr prefsounsynwb {칠판에 쓰여진 문자의 합성 음성을 듣기}
::msgcat::mcset kr prefsounsynno {일반 메세지의 합성 음성을 듣기}
::msgcat::mcset kr prefsounsynch {대화의 합성 음성을 듣기}
::msgcat::mcset kr prefsounvoin  {들어오는 문자에 해당하는 목소리 집기:}
::msgcat::mcset kr prefsounvoou  {당신이 쓰는 문자의 목소리 집기:}
::msgcat::mcset kr prefsounpick  {아래의 적혀진 이벤트에 해당하는 경고음 집기:}
::msgcat::mcset kr prefshortcut  {여기서 "P-P"네트워크 연결에만 사용되는 단축키을 붙이거나 편집할 수 있다. 이는 제버 시스템에서는 사용할 수 없다.\
"네트워크 설정"에서 "p-p"연결을 명백하게 선택하지 않았다면, 이 단축키은 사용할 수 없다.}
::msgcat::mcset kr prefprof      {여기서 재버 시스템 계정에 요구되는 것을 설정할 수 있다. 여기서 선택한 서버가 당신이 로그인하게되는 서버이다.}
::msgcat::mcset kr prefpers      {당신 개인 정보는 설정 파일에 저장되나, 또한 재버 사용자 디렉토리에도 저장됩니다. 서버에 저장된 정보는 다른 사용자의 검색에 사용됩니다.}
::msgcat::mcset kr prefaaset     {자동으로 자리비움 상태 설정:}
::msgcat::mcset kr prefminaw     {자리비움 상태 설정은 다음 시간(분) 후:}
::msgcat::mcset kr prefminea     {멀리나감 상태 설정은 다음 시간(분) 후:}
::msgcat::mcset kr prefsuif      {어떤이가 나의 목록에 신청하였다면, ...}
::msgcat::mcset kr prefsuis      {...이미 내 목록에 있음:}
::msgcat::mcset kr prefsuisnot   {...내 목록에 없음:}
::msgcat::mcset kr prefsuauto    {자동으로 내 목록에 신청 접수 처리됨}
::msgcat::mcset kr prefrorm      {신청 반려하면 사용자 지워집니다}
::msgcat::mcset kr prefroallow   {신청없이 목록에 등록합니다}
::msgcat::mcset kr prefroclr     {로그아웃하면 목록에서 사라집니다}
::msgcat::mcset kr prefrochat    {사용자를 더블 클릭하면 대화를 할 수 있습니다. 또는 메세지를 보내게 됩니다}
::msgcat::mcset kr prefrosysicons {외부 메신저 아이콘 사용하기}
::msgcat::mcset kr prefrohideoff {오프라인 사용자는 보이지 않게됩니다}
::msgcat::mcset kr prefrohidetrpt {정송을 보여주지 않습니다}
::msgcat::mcset kr prefblonly    {목록에 있는 이들로 부터만 메세지를 허용합니다}
::msgcat::mcset kr prefblbl      {다음 JID 들을 막습니다 (* 와이트카드 사용가능):}
::msgcat::mcset kr prefblmsg     {당신이 막기 원하는 완전한 JID를 적어라. JID 는 "joewest@jabber.org" 형태여야 한다.}
::msgcat::mcset kr prefcufont    {대화창의 글씨체를 고르세요:}
::msgcat::mcset kr prefcushow    {새창에다 메세지 보여주기}
::msgcat::mcset kr prefcusave    {세션간 받은 메세지 저장하기}
::msgcat::mcset kr prefcuautologin  {작동시 자동 로그인}
::msgcat::mcset kr prefcu2clk    {받은 함의 메세지를 더블클릭하세요:}
::msgcat::mcset kr prefcuopen    {새창에서 메세지 열기}
::msgcat::mcset kr prefcureply   {보낸 이에게 답하기}
::msgcat::mcset kr prefcudisc    {선호하는 서비스 조사 방법:}
::msgcat::mcset kr prefcubrowse  {가능한 서비스 찾아보기}
::msgcat::mcset kr prefcuagent   {항상 대리인 방법 사용하기}
::msgcat::mcset kr prefcuupdate  {자동으로 새 Coccinella 버젼 확인하기}
::msgcat::mcset kr prefcuremdlgs {세션간의 공개 대화 기억하기}
::msgcat::mcset kr preffmhelp    {파일 형에 대한 도움기능 플러그임}
::msgcat::mcset kr preffmsave    {받는 디렉토리에 바로 저장하기}
::msgcat::mcset kr preffontmsg   {경고: 표즌 서체(타임체, 헬베티가체, 큐리에체) 대신 다른 서체를 구성할 때에는, 다른 이들의 시스템에도 이 서체가 있어야 한다.}
::msgcat::mcset kr prefcahow     {이미 받은 파일을 다루는 방법:}
::msgcat::mcset kr prefcanev     {캐시 저장된 파일 사용하지 않기, 항상 새로운 파일 받기}
::msgcat::mcset kr prefcaalw     {항상 캐시 저장된 파일 받기, 절대 새로 파일을 받지 않는다} 
::msgcat::mcset kr prefcaor      {..또는 다음의 것보다 오래되지 않는 것은 캐시된 파일을 사용하기:}
::msgcat::mcset kr prefpriv      {프라이버스 버튼을 체크해 두면, 자신만의 캔버스 아이템을 편집할 수 있다. 다른 이가 작업한 아이템은 편집할 수 없다.}
::msgcat::mcset kr prefshortip   {ip 주소나 이름을 완성하라}
::msgcat::mcset kr prefshortwa   {경고: 단축키를 편집했습니다. 이를 저장하기를 원하지 않나요?}

::msgcat::mcset kr preffilecache {캐시는 다른 사용자들의 지역적 복사에 사용하여 네트워크 부하를 줄이는데 사용됩니다. 아래 지정된 크기만큼의 캐시만 지원됩니다.}
::msgcat::mcset kr prefcachecmp  {캐시 파일과 원격 파일을 비교하였습니다}
::msgcat::mcset kr prefnatip     {밖에는 아래의 ip 주소로 보이게 됩니다}
::msgcat::mcset kr prefmucconf   {오류복구조처상태로 여럿이 쓰는 대화방이 작동됨}
::msgcat::mcset kr prefrostbgim  {목록에 배경화면으로 사용}
::msgcat::mcset kr preftheme     {테마 집기, 재실행해야 합니다}
::msgcat::mcset kr prefplugctrl  {아무것도 로딩하고 싶지 않으면, 전부 선택해지 할 수 있습니다. 재실행시 부터 적용됩니다.}
::msgcat::mcset kr prefchactret  {대화중에 되돌리기를 항상 활성화 시키기}
::msgcat::mcset kr prefchnormal  {일반 메세지를 대화메세지로 다루기}
::msgcat::mcset kr prefprofname  {사용자 프로파일에 원하는 이름을 적으시오}
::msgcat::mcset kr prefstabui    {탬이 설정된 쓰기 환경 사용하기}
::msgcat::mcset kr prefsusesasl  {SASL 인증 방법 사용하기}
::msgcat::mcset kr prefprivmsg   {사용자 각각은 없거나 몇개의 목록을 관리할 수 있다. 단 활성 목록 또는 기본 목록만 메세지 처리에 영향을 준다. 다른 활성 목록은 단지 해당 세션에만 영향을 준다.\
  아무런 활성 목록이 없다면 기본 목록이 처리된다.}
::msgcat::mcset kr prefprivunav  {연결되지 않은 상태에서 필터 옵션은 접근할 수 없습니다}
::msgcat::mcset kr prefprivnotex {이 서버에 대한 필터 옵션은 접근할 수 없습니다}
::msgcat::mcset kr prefprivobtained {서버로 부터 필터 목록을 받았습니다}
::msgcat::mcset kr prefprivgetlist {필터 목록 "%s"을 받는중}
::msgcat::mcset kr prefprivrules {각 목록은 하나이사의 규칙을 가지고 있는데, 각각의 규칙은 각 이벤트가 처리되는 방식을 정하고 있고, 그러한 처리가 일어나게 한다.\
  차단을 할 그룹을 지정하고 싶다면, 그대의 목록에 있어야만 한다.}
::msgcat::mcset kr prefuserinactive {사용자가 잠시동안 비활성화 됩니다}  
::msgcat::mcset kr preficonsel   {선택한 아이콘세트는 저장후에 적용됩니다}
::msgcat::mcset kr prefwbscroll  {%sx%s 인 기본 크기보다 크게 설정했습니다}
::msgcat::mcset kr prefssbts     {이전, 이후 버튼을 보여주기}
::msgcat::mcset kr prefssresize  {캔버스를 자동으로 이미지 크기에 맞추기}
::msgcat::mcset kr prefavashare {이 아바타를 다른 이들과 나누기}
::msgcat::mcset kr prefproxymsg  {Http proxy 사용은 각 프로파일 설정이 따른다. Http proxy를 사용하면 파일 전송이 되지 않습니다!}
::msgcat::mcset kr prefproxyexc  {배제되는 주소 (* 는 와일드카드)}

::msgcat::mcset kr prefdrivesame {항상 프로그램과 같은 드라이브에 사용자 설정을 저장하기}
::msgcat::mcset kr prefdriwsame  {응용 프로그램과 같은 드라이브에 사용자 설정을 저장한다고 선택했습니다. 이 드라이브가 이동식이 아니라면, 개인 설정이 보여질 수 있습니다.\
  그래도 되겠습니까?}
::msgcat::mcset kr prefdriwdef   {기본 위치에 사용자 설정을 저장하기로 선택했습니다. "%s"에 있는 개인 설정을 다른 데로 옶기거나 지우지 않으면\
  다음 부터 Coccinella를 사용할 때 자동적으로 적용됩니다. 지금 지우길 원하나요?}


# EditShortcuts namespace:
namespace eval ::EditShortcuts:: {
	::msgcat::mcset kr shortip       {ip 주소나 이름을 채우시오}
	::msgcat::mcset kr shortwarn     {경고: 단축키를 편집했습니다. 저장하길 원하지 않나요?}


}


::msgcat::mcset kr jalogin 	{재버 서버의 ip 주소나 이름을 적으시오. 이미 이 서버에 계정을 가지고 있어야 합니다.}
::msgcat::mcset kr janewaccount {재버 서버의 ip 주소나 이름을 적으시오. 사용자 이름과 암호를 집으세요.}
::msgcat::mcset kr janewpass    {새 암호를 설정하기:}
::msgcat::mcset kr jasubwant    {"%s"님은 당신 목록에 등록 신청하였습니다.}
::msgcat::mcset kr jasubopts    {다음의 옵션중에서 고르세요. 별명과 그룹명은 옵션입니다. 이는 당신의 개인적 용도로만 사용됩니다.}
::msgcat::mcset kr jasubgetvcard {vCard 받아오기}
::msgcat::mcset kr jasubsndmsg  {이 이에게 메세지 보내기:}
::msgcat::mcset kr jasuballow   {"%s"님에게 나의 상태 보기 허용하기}
::msgcat::mcset kr jasubadd     {"%s"님을 내 목록에 더하기}
::msgcat::mcset kr jarostadd	{나의 대화상대 명부에 재버 사용자를 등록하기, 언제든지 별명과 모둠은 설정하거나 바꿀수 있다. 외부 인터넷 메신저시스템의 사용자를 더하려면, 해당 시스템에 미리 계정을 가지고 있어야만 한다\
  , 그리고, 게이트웨이나 전송을 위한 재버 서버로 등록할 때 이를 사용하여야 한다.}
::msgcat::mcset kr jarostset	{"%s"님의 별명과 그룹을 당신이 원하는 데로 지정하기. 이후로 적용됩니다.}
::msgcat::mcset kr jarostsub	{이 사용자에게 등록신청하기}
::msgcat::mcset kr jarostunsub	{이 사용자에게 등록해지하기}
::msgcat::mcset kr jasearch	{특정 서비스를 사용하는 사용자 찾기. 채워야 할 새 양식을 원하면 받기 버튼을 누르세요.}
::msgcat::mcset kr jasearchwait	{선택한 것을 받는 중}
::msgcat::mcset kr jaservclosed	{서버 연결이 닫힘.}
::msgcat::mcset kr jarostupdate {목록이 갱신됨}
::msgcat::mcset kr jawaitresp 	{%s에 연결됨. 반응 기다리는 중...}
::msgcat::mcset kr jawaitxml 	{"%s"로 연결됨. XML 스트림 초기화중...}
::msgcat::mcset kr jasendauth	{서버 "%s"가 반응하였습니다. 인증 정보 보내는 중.}
::msgcat::mcset kr jaerrlogin	{%s에 로그인 실패함: %s}
::msgcat::mcset kr jaauthok	{서버 "%s"로의 인증이 성공했습니다. 목록 받는 중...}
::msgcat::mcset kr jagchatmsg	{그룹 대화 서버를 선택하고 방과 당신 자신의 별명을 고르시오}
::msgcat::mcset kr jacreateroom	{희의 서비스에 더해서 방 이름을 고르세요. 그리고, "가져오기"를 누르면, 각 서버가 제공하는 특정 사양 기준에서 원하는 회의실을 만들 수 있다.}
::msgcat::mcset kr jawaitserver	{서버의 반응 기다리는 중...}
::msgcat::mcset kr jaregmsg	{이 서버의 특정 서비스에 대한 등록. 이미 등록하였다면, 이창을 이용하여 당신의 정보를 바꿀 수 있습니다.}
::msgcat::mcset kr jastatavailable {가능함}
::msgcat::mcset kr jastatchat	{대화중: 즉작적인 연결 가능함}
::msgcat::mcset kr jastataway	{자리비움: 온라인, 잠시 자리비움}
::msgcat::mcset kr jastatxa	{멀리나감: 온라인, 당분간 연결 안됨}
::msgcat::mcset kr jastatdnd	{DND: 지금 일에 집중하고 싶어요}
::msgcat::mcset kr jastatinvisible {보이지 않음}
::msgcat::mcset kr javersinfo	{%s에 대한 버전 정보}
::msgcat::mcset kr jabrowseaddserver	{서비스 목록에 추가하고자 하는 서버의 JID 를 적으시요,예를 들면, "jabber.org".}
::msgcat::mcset kr jaupdatemsg	{Coccinella의 버젼에 있습니다.}
::msgcat::mcset kr jaupdatevers	{현재의 버젼: %s}
::msgcat::mcset kr jaupdatepri	{업데이트 버젼: %s}
::msgcat::mcset kr jaupdatenewver {새 버젼: %s}
::msgcat::mcset kr jaupdateremind {더이상 이에 대해 알리지 마세요}
# remove-- ::msgcat::mcset kr jasettopic   {현 그룹 대화방에 대한 주제 설정하기.}
::msgcat::mcset kr jasettopic2  {회의 주제을 설정하세요.}
::msgcat::mcset kr jadirpresmsg {"%s"님에게 지시된 사용자 출석 알리기.}
::msgcat::mcset kr jatlsnegot   {TLS 보안 설정중...}
::msgcat::mcset kr jamucentermsg {별명을 쓰고, 방에 들어가기 위해 엔터를 치세요. 특정 서비스를 젝오하는 방을 검색할 수 있습니다. 회원 전용 방은 암호를 요구합니다.}
::msgcat::mcset kr jainmsgshow  {이창에서 받은 메세지 보여주기}
::msgcat::mcset kr jadisaddserv {그룹 대화방과 다른 서비스를 위한 다른 서버를 찾기. 자동으로 찾아지면 이를 고정적으로 서버에 더할 수 있다. 로그인 서버는 항상 보여진다.}
::msgcat::mcset kr jadisrmall   {자동으로 또는 항시적으로 보여지는 서버 모두를 제거하기.}
::msgcat::mcset kr jauserinnote {이 사용자에 대한 자신의 개인 메모하기}
::msgcat::mcset kr jaregisterex {당신이 등록하길 원하는 재버 서버 이름을 적으시오. 그리고 등록 양식를 얻기 위해 받기 버튼을 누르시오. 양식을 채워 등록하세요.}
::msgcat::mcset kr jaloginjid   {"joey@myjabb.org"처럼 당신의 jid를 적거나 프로파일을 선택하시요. 이 서버에 게정을 이미 가지고 있어야 합니다.}
::msgcat::mcset kr jaregalready {이미 이 서버에 등록되었습니다. 당신의 현재 등록된 설정을 다음과 같습니다.}
::msgcat::mcset kr jaactiveret  {메세지를 보내기위해 Return 체크하던지 아니면 Ctrl/Cmd-Return 을 사용하세요}
::msgcat::mcset kr jainvitegchat {%s 방에 그룹 대화를 위해 사용자를 초대하기}
::msgcat::mcset kr jaxformreq   {(*) 라고 표시할 필요가 있습니다}
::msgcat::mcset kr jagcsyncpres {사용자 출석상황을 대화방과 맞춥니다}
::msgcat::mcset kr jaloginuser  {%s에 로그인 하기 위한 당신의 사용자명과 암호를 적으세요.}
::msgcat::mcset kr jaregnewwith {%s에 새 계정으로 등록하기를 원하나요.}
::msgcat::mcset kr jaregisterexserv {%s 서비스에 등록하기. 자동적으로 등록 정보가 구해지지 않으면, 받기 버튼을 눌러야 합니다.}
::msgcat::mcset kr jaseliconset {각 그룹에서 사용될 아이콘 세트를 고르세요. 각 그룹별로 선택해지 할 수 있습니다.}
::msgcat::mcset kr jachathist   {대화 기록 보이거나 감추기}
::msgcat::mcset kr jawaitdisco  {disco 결과 기다리는 중...}
::msgcat::mcset kr jagclogoutmsg {당신은 로그아웃하였고 방도 나가 있습니다}

::msgcat::mcset kr jagcreqnick  {Please enter your desired nick name for the room %s}

::msgcat::mcset kr {InfoRoomDesc}       {이 대화창은 대화방에 대한 가능한 옵션과 활동을 지정할 수 있습니다. 당신의 강비및 역할이 조정할 수 있는 권한을 결정합니다.\
특정 방의 조정에 따라 몇가지 기능이 제한되기도 합니다.}

# Setup assistant:
::msgcat::mcset kr suintro1 	{설정 지원은 재버 서버에 새롭게 등록하거나 계정을 설정하는데 필요한 것을 채우는 것을 지원합니다.}
::msgcat::mcset kr suintro3 	{언제든지 전 과정으로 가려면, 이전 버튼을 누르면 됩니다. 각 페이지의 지시에 따르고, 다음 버튼을 눌르면 됩니다.}
::msgcat::mcset kr sulang       {언어를 집으세요. 조정한 내용은 이후에 생성되는 창에서 부터 적용됩니다.}
::msgcat::mcset kr suservmsg	{당신의 계정이 있는 재버 서버의 이름을 채우시오. 개버 서버에 이미 계정이 있다면, 서버의 이름을 채우시오.\
  전형적인 재버 서버의 이름은 "jabber.org"와 같습니다.}
::msgcat::mcset kr suusermsg	{사용자명과 암호를 적으세요. 이미 등록되어 있지 않다면 사용자명은 사용하지 않은 것이어야 한다.\
  다른 이가 이미 사용한 사용자명이라면, 다른 이름을 사용하길 권하는 안내를 받게 될 것입니다.}
::msgcat::mcset kr suregmsg	{새 계정이라면, 이 계정으로 지금 등록하길 원하나요? 등록하기 위해서는 네트워크(방화벽을 통과하여) 이미 연결되어 있어야 합니다.}
::msgcat::mcset kr sufinmsg	{잘되었습니다. 또한, 버그문제도 없군요 ;-)}
::msgcat::mcset kr suheadtxt	{Coccinella 설정 지원}
::msgcat::mcset kr supubserv	{공개/대중 재버 서버의 목록 얻기}
::msgcat::mcset kr suservlist	{공개 재버 서버 목록}


# Groupchat:
::msgcat::mcset kr mucErrEnter      {"%s"방에 들어가는데 오류가 생겼습니다.}
::msgcat::mcset kr mucErrCode       {오류 코드는 %s입니다: %s}
::msgcat::mcset kr mucErrEnterTitle {방에 들어가지 못했습니다}
::msgcat::mcset kr mucErrInvite     {%s님에게 하신 %s방으로의 초대가 실패했습니다.}
::msgcat::mcset kr mucErrInviteCode {오류문: %s}
::msgcat::mcset kr mucInviteText    {%s님으로 부터 그룹대화방 %s으로 오시라는 초대를 받았습니다.}
::msgcat::mcset kr mucInviteReason  {원인: %s}
::msgcat::mcset kr mucInvitePass    {들어가기 위해 암호 "%s"가 필요합니다.}
::msgcat::mcset kr mucInviteQuest   {당장 합류하길 원하나요?}
::msgcat::mcset kr mucInvite        {초대}
::msgcat::mcset kr mucDestroy       {"%s"방을 방금 없앴습니다. 방 동료들에게 다른 방 JID와 닫는 이유를 보낼 수도 있습니다.}
::msgcat::mcset kr mucIQError       {"%s"방에서의 과정중에 오류가 발생했습니다.: %s}
::msgcat::mcset kr mucChat2ConfInv  {대화를 회의로 바꾸기}

::msgcat::mcset kr vcardget	{%s님으로 부터 vCard 받기. 서버 반응 기다리기...}
::msgcat::mcset kr vcarderrget	{vCard 받는데 실패했습니다. 이유: %s}
::msgcat::mcset kr vcardrec	{vCard 자료 받음.}



::msgcat::mcset kr autoupdatenot        {업데이르점검을 자동으로 하지 않기}
::msgcat::mcset kr oobmsg               {%s님이 당신의 서버에서 파일을 다운로드하게 둔다. 설명을 할 수도 있습니다.}

# Composing events
::msgcat::mcset kr chatcompreply      {%s님이 응답 작성중}
::msgcat::mcset kr chatcompactive     {%s님은 대화중입니다}
::msgcat::mcset kr chatcompcomposing  {%s님이 응답 작성중}
::msgcat::mcset kr chatcomppaused     {%s님이 무엇을 쓸 지를 생각중}
::msgcat::mcset kr chatcompinactive   {%s님이 잠시동안 대화방을 떠나있습니다}
::msgcat::mcset kr chatcompgone       {%s님이 대화방을 닫았습니다}


# Get file
::msgcat::mcset kr getcontacting   {%s에 연결중. 응답 기다리는 중...}
::msgcat::mcset kr geteoferr       {%s에 연결 실패: 파일끝이라는 메세지 받음.}
::msgcat::mcset kr getconnerr	    {%s에 연결 실패.}
::msgcat::mcset kr getnegotiate    {사용자 프로그램 연결됨: %s; 상호 조정중...}
::msgcat::mcset kr getreaderr      {%s부터 서버 응답을 받는데 실패함.}
::msgcat::mcset kr getunknownprot  {%s에서 서버가 제대로 구성된 프로토콜로 반응하지 않습니다.}
::msgcat::mcset kr getnot200	    {%s에서 서버가 %s라드 코드를 보냈습니다: "%s"}
::msgcat::mcset kr getstarts	    {%s에서 사용자가 "%s"를 허용 했습니다. 전송 시작...}
::msgcat::mcset kr getended	    {%s로 부터의 전송이 완료되지 않고 끊났습니다.}
::msgcat::mcset kr getfinished	    {"%s"를 %s로 부터 받기를 마쳤습니다.}
::msgcat::mcset kr getneterr	    {%s로 부터 받는 중 네트워크 오류가 생겼습니다.}

# Put file
::msgcat::mcset kr putcontacting   {%s에 연결중. 응답 기다리는 중...}
::msgcat::mcset kr puteoferr       {%s에 연결 실패: 파일끝이라는 메세지 받은.}
::msgcat::mcset kr putconnerr	    {%s에 연결 실패.}
::msgcat::mcset kr putnegotiate    {사용자 프로그램 연결됨: %s; 상호 조정중...}
::msgcat::mcset kr putreaderr      {%s부터 서버 응답을 받는데 실패함}
::msgcat::mcset kr putunknownprot  {%s에서 서버가 제대로 구성된 프로토콜로 반응하지 않습니다.}
::msgcat::mcset kr putnot200	    {%s에서 서버가 %s라드 코드를 보냈습니다: "%s"}
::msgcat::mcset kr putstarts	    {%s에서 사용자가 "%s"를 허용 했습니다. 전송 시작...}
::msgcat::mcset kr putended	    {%s로 전송이 완료되지 않고 끊났습니다.}
::msgcat::mcset kr putfinished	    {"%s"를 %s로 부터 보내기를 마쳤습니다.}
::msgcat::mcset kr putneterr	    {%s로 부터 보내는 중 네트워크 오류가 생겼습니다.}

# These are specific for phones (VoIP)
::msgcat::mcset kr phoneMakeCall           {전화걸기}
::msgcat::mcset kr phoneMakeForward        {현재 전화 전달하기...}
::msgcat::mcset kr phoneRing               {따르릉, 따르릉...}
::msgcat::mcset kr phoneRingFrom           {%s로 부터 전화가 울리고 있습니다}
::msgcat::mcset kr phoneFailedCalling      {%s에 전화걸기 실패}
::msgcat::mcset kr phoneDial               {번호입력중}
::msgcat::mcset kr phoneNumber             {번호}
::msgcat::mcset kr phoneDialerCall         {전화걸기...}
::msgcat::mcset kr phoneDialerForward      {전달하기...}

::msgcat::mcset kr AddressBook		{주소록}
::msgcat::mcset kr newAddressbookDlg	{새 주소록}
::msgcat::mcset kr newAddressbook       {새 주소록}
::msgcat::mcset kr abName		{성명}
::msgcat::mcset kr abPhone		{전화번호}
::msgcat::mcset kr modifyAddressbookDlg {주소록 고치기}
::msgcat::mcset kr modifyAddressbook	{주소록 고치기}
::msgcat::mcset kr mNewAB		{새}
::msgcat::mcset kr mModifyAB		{고치기}
::msgcat::mcset kr mRemoveAB		{지우기}

::msgcat::mcset kr outCall              {전화하기}
::msgcat::mcset kr notifyCall           {알림전화}
::msgcat::mcset kr inboundCall          {내부 전화}
::msgcat::mcset kr outboundCall         {외부 전화}
::msgcat::mcset kr callAnswer           {응답}
::msgcat::mcset kr callHungUp           {전화 들기}
::msgcat::mcset kr callInfo             {안내}
::msgcat::mcset kr callVM               {가상머신 부르기?}

# Fore some of these generic names could be used?
::msgcat::mcset kr iaxPhone             {IAX 전화}
::msgcat::mcset kr iaxPhoneAccount      {IAX 계정}
::msgcat::mcset kr iaxPhoneUser         {사용자}
::msgcat::mcset kr iaxPhonePassword     {암호}
::msgcat::mcset kr iaxPhoneHost         {호스트}
::msgcat::mcset kr iaxPhoneCidNum       {Cid 번호}
::msgcat::mcset kr iaxPhoneCidName      {Cid 이름}
::msgcat::mcset kr iaxPhoneInputDev     {입력 장치}
::msgcat::mcset kr iaxPhoneOutputDev    {출력 장치}
::msgcat::mcset kr iaxPhoneAGC          {AGC}
::msgcat::mcset kr iaxPhoneAAGC         {AAGC}
::msgcat::mcset kr iaxPhoneNoise        {잡음}
::msgcat::mcset kr iaxPhoneComfort      {편안함}
::msgcat::mcset kr iaxPhoneCodec        {Codec}

# Messages for Mood PEP
::msgcat::mcset kr mMood        분위기 
::msgcat::mcset kr mAngry       화난
::msgcat::mcset kr mAnxious     불안한
::msgcat::mcset kr mAshamed     부끄러운
::msgcat::mcset kr mBored       지겨운
::msgcat::mcset kr mCurious     궁금한
::msgcat::mcset kr mDepressed   의기소침한
::msgcat::mcset kr mExcited     흥분한
::msgcat::mcset kr mHappy       행복한
::msgcat::mcset kr mInLove      {사랑에 빠진}
::msgcat::mcset kr mInvincible  완강한
::msgcat::mcset kr mJealous     샘나는
::msgcat::mcset kr mNervous     날카로운
::msgcat::mcset kr mSad         슬픈
::msgcat::mcset kr mSleepy      졸리는
::msgcat::mcset kr mStressed    스트레스받은
::msgcat::mcset kr mWorried     걱정하는

::msgcat::mcset kr moodEvent   {분위기 변화}
::msgcat::mcset kr heIs        ..
::msgcat::mcset kr because     왜냐하면
::msgcat::mcset kr angry       화남
::msgcat::mcset kr anxious     불안함
::msgcat::mcset kr ashamed     부끄러움
::msgcat::mcset kr bored       지겨움
::msgcat::mcset kr curious     궁금함
::msgcat::mcset kr depressed   의기소침함
::msgcat::mcset kr excited     흥분함
::msgcat::mcset kr happy       행복함
::msgcat::mcset kr in_love     {사랑에 빠짐}
::msgcat::mcset kr invincible  완강함
::msgcat::mcset kr jealous     샘
::msgcat::mcset kr nervous     신경질남
::msgcat::mcset kr sad         슬픔
::msgcat::mcset kr sleepy      졸림
::msgcat::mcset kr stressed    스트레스받음
::msgcat::mcset kr worried     걱정함

::msgcat::mcset kr moodDlg              {분위기}
::msgcat::mcset kr selectCustomMood     {분위기 고르기}
::msgcat::mcset kr moodMessage          {분위기에 대한 이유}
::msgcat::mcset kr mCustomMood              {일번적 분위기}

# END --------------------------------------------------------------------------


