# Russian language version of the Coccinella message catalog.
#
# Translated by Gescheit(xmmp://gescheit@jabber.ttn.ru)
#
# General type of text, such as "OK", "Cancel", and the like. 
# We use the source string as the message.
# Defined in global namespace and may therefore be used in any namespace.

::msgcat::mcset en Accept
::msgcat::mcset ru Action	{Действие}
::msgcat::mcset ru Active	{Активные}
::msgcat::mcset ru Add		{Добавить}
::msgcat::mcset ru Address	{Адрес}
::msgcat::mcset ru email		{Почта}
::msgcat::mcset ru Advanced	{Настройки}
::msgcat::mcset ru Agents		{Агенты}
::msgcat::mcset ru Allow			{Разрешен}
::msgcat::mcset ru Appearance	{Внешность}
::msgcat::mcset ru Apply			{Применить}
::msgcat::mcset ru Available		{Доступен}
::msgcat::mcset ru Away			{Ушел}
::msgcat::mcset ru Binary		{Бинарный}
::msgcat::mcset ru Birthday		{День рождения}
::msgcat::mcset ru Block			{Блокировка}
::msgcat::mcset ru Blockers		{Блокированные}
::msgcat::mcset ru Blocking		{Блокировка}
::msgcat::mcset ru Browser		{Смотреть}
::msgcat::mcset ru Browse		{Смотреть}
::msgcat::mcset ru Both			{Оба}
::msgcat::mcset en Buffering
::msgcat::mcset ru Cancel		{Отмена}
::msgcat::mcset ru Change		{Изменить}
::msgcat::mcset ru Chat			{Чат}
::msgcat::mcset ru Choose		{Выбрать}
::msgcat::mcset ru City			{Город}
::msgcat::mcset ru Clear			{Отчистить}
::msgcat::mcset ru Client			{Клиент}
::msgcat::mcset ru Close			{Закрыть}
::msgcat::mcset ru Conference	{Конференция}	
::msgcat::mcset ru Connect		{Подключиться}
::msgcat::mcset ru Connection	{Подключение}
::msgcat::mcset ru Contact		{Контакт}
::msgcat::mcset ru Contacts		{Контакты}
::msgcat::mcset ru Country		{Страна}
::msgcat::mcset ru Create		{Создать}
::msgcat::mcset ru Customization	{Настройки}
::msgcat::mcset ru Date			{Дата}
::msgcat::mcset ru Default		{По умолчанию}
::msgcat::mcset ru Delete		{Удалить}
::msgcat::mcset ru Deny			{Запретить}
::msgcat::mcset ru Department	{отдел}
::msgcat::mcset ru Description		{Описание}
::msgcat::mcset en Drawing
::msgcat::mcset en Document
::msgcat::mcset en Done
::msgcat::mcset ru Disco		{Сервисы}
::msgcat::mcset ru Edit		{Редактировать}
::msgcat::mcset ru Enter		{Вход}
::msgcat::mcset ru Error		{Ошибки}
::msgcat::mcset ru Exit		{Выход}
::msgcat::mcset ru File		{Файл...}
::msgcat::mcset ru Finish		{Закончен}
::msgcat::mcset ru Finished	{Закончен}
::msgcat::mcset ru First		{Первый}
::msgcat::mcset ru Filter		{Фильтр}
::msgcat::mcset ru Friends		{Друзья}
::msgcat::mcset ru Forward		{переслать}
::msgcat::mcset ru From			{от}
::msgcat::mcset ru General		{Общее}	
::msgcat::mcset ru Get			{Получить}
::msgcat::mcset en Getting
::msgcat::mcset ru Group		{Группа}
::msgcat::mcset ru Groupchat		{Конференция}
::msgcat::mcset en Handling
::msgcat::mcset ru Height		{Высота}
::msgcat::mcset ru History		{История}
::msgcat::mcset ru Home		{Дом}
::msgcat::mcset en Image
::msgcat::mcset ru Import	{Открыть файл}
::msgcat::mcset ru {>>Import>>}	{импортировать}
::msgcat::mcset ru Inbox		{Входящие}
::msgcat::mcset ru Info		{Инфо}
::msgcat::mcset ru Invite		{Пригласить}
::msgcat::mcset en Last
::msgcat::mcset ru Less		{Меньше}
::msgcat::mcset ru Login		{Логин}
::msgcat::mcset ru Logout		{Отключится}
::msgcat::mcset ru Message		{Сообщение}
::msgcat::mcset ru Middle		{Отчество}
::msgcat::mcset ru Moderators	{Модераторы}
::msgcat::mcset ru More			{Больше}
::msgcat::mcset ru Name			{Имя}
::msgcat::mcset ru Never			{Никогда}
::msgcat::mcset ru New			{Новый}
::msgcat::mcset en Next
::msgcat::mcset en Nick
::msgcat::mcset ru Nickname		{Ник}
::msgcat::mcset en No
::msgcat::mcset en no
::msgcat::mcset en None
::msgcat::mcset ru Notes			{Обо мне}
::msgcat::mcset ru Occupation	{Занятия}
::msgcat::mcset ru Offline		{Не в сети}
::msgcat::mcset ru OK
::msgcat::mcset ru Online		{В сети}
::msgcat::mcset ru Open			{Открыть}
::msgcat::mcset en Options
::msgcat::mcset ru Participants	{Участники}
::msgcat::mcset ru Password		{Пароль} 
::msgcat::mcset en Pause
::msgcat::mcset ru Pick			{Выбрать}
::msgcat::mcset ru Phone		{Телефон}
::msgcat::mcset ru Play			{Проиграть}
::msgcat::mcset ru Plugins		{Плагины}
::msgcat::mcset ru Port			{Порт}
::msgcat::mcset en Preferences
::msgcat::mcset en Previous
::msgcat::mcset ru Print		{Печать}
::msgcat::mcset ru Priority	{Приоритет}
::msgcat::mcset ru Privacy	{Приватность}
::msgcat::mcset ru Profile		{Профиль}
::msgcat::mcset ru Profiles	{Профили}
::msgcat::mcset en Progress
::msgcat::mcset en Quit?
::msgcat::mcset ru Quote	{Цитирование}
::msgcat::mcset ru Reason	{Причина}
::msgcat::mcset en Register
::msgcat::mcset en Remaining
::msgcat::mcset ru Remove	{Удалить}
::msgcat::mcset ru Reply		{Ответить}
::msgcat::mcset ru Resource	{Ресурс}
::msgcat::mcset en Restart
::msgcat::mcset en Room
::msgcat::mcset ru Roster	{Ростер}
::msgcat::mcset ru Save		{Сохранить}
::msgcat::mcset ru Search	{Поиск}
::msgcat::mcset ru Select		{Выбрать}
::msgcat::mcset ru Send		{Послать}
::msgcat::mcset en Server
::msgcat::mcset en Servers
::msgcat::mcset en Service
::msgcat::mcset ru Set			{Установить}
::msgcat::mcset ru Settings		{Настройки}
::msgcat::mcset en Shortcut
::msgcat::mcset en Shortcuts
::msgcat::mcset ru Sounds		{Звуки}
::msgcat::mcset en Specifications
::msgcat::mcset ru Speech		{Речь}
::msgcat::mcset ru State			{Область}	
::msgcat::mcset ru State/Region	{Область/регион}
::msgcat::mcset ru Stop			{Остановить}
::msgcat::mcset ru Standart		{Стандарт}
::msgcat::mcset ru Subject		{Тема}
::msgcat::mcset ru Subscribe		{Регистрации}
::msgcat::mcset en Subscribed
::msgcat::mcset ru Subscription	{Подписка}
::msgcat::mcset ru Subscriptions	{Подписки}
::msgcat::mcset en Text
::msgcat::mcset en Time
::msgcat::mcset en Timeout
::msgcat::mcset ru Title			{Должность}
::msgcat::mcset en To
::msgcat::mcset ru Topic			{Тема}
::msgcat::mcset en Transports
::msgcat::mcset ru Trash			{Удалить}
::msgcat::mcset ru Type			{Тип}
::msgcat::mcset en Unregister
::msgcat::mcset en Unsubscribe
::msgcat::mcset en Unsubscribed
::msgcat::mcset ru Username		{Имя пользователя}
::msgcat::mcset ru Value			{Значение}
::msgcat::mcset ru Volume		{Громкость}
::msgcat::mcset en Visitors
::msgcat::mcset en Warning
::msgcat::mcset en Welcome
::msgcat::mcset ru Whiteboard	{Доска для рисования}
::msgcat::mcset ru Width	{Ширина}
::msgcat::mcset ru Work		{Работа}
::msgcat::mcset en Yes
::msgcat::mcset en yes

# dashes.
::msgcat::mcset en none
::msgcat::mcset en dotted
::msgcat::mcset en dash-dotted
::msgcat::mcset en dashed

# Status messages.
::msgcat::mcset ru available				{Доступен}
::msgcat::mcset ru away					{Ушел}
::msgcat::mcset ru {do not disturb}		{Не беспокоить}
::msgcat::mcset ru {not available}			{Не доступен}
::msgcat::mcset ru {extended away}		{Нет на месте и надолго}
::msgcat::mcset ru invisible				{Невидим}
::msgcat::mcset ru chat					{Свободен для чата}
::msgcat::mcset ru subscribed				{Авторизован}
::msgcat::mcset ru unsubscribed			{Не авторизован}


# MUC menu
::msgcat::mcset ru Voice			{Голос}
::msgcat::mcset ru {Voice...}		{Голос...}
::msgcat::mcset ru Member		{Участник}
::msgcat::mcset ru Moderator		{Модератор}
::msgcat::mcset ru Admin		{Администратор}
::msgcat::mcset ru Owner		{Владелец}
::msgcat::mcset ru {Grant:}		{Предоставляется}
::msgcat::mcset ru {Revoke:}		{Отменять}
::msgcat::mcset ru {Kick Particpant}	{Кик}

# All menu labels; concateneted and prepended with 'm' for the database key.
::msgcat::mcset ru mFile		{Файл}
::msgcat::mcset ru mEdit		{Правка}
::msgcat::mcset ru mPreferences		{Настройки}
::msgcat::mcset ru mJabber		{Жаббер}
::msgcat::mcset ru mItems		{Элементы}
::msgcat::mcset ru mLibrary		{Библиотеки}
::msgcat::mcset ru mInfo		{Инфо}
::msgcat::mcset ru mAddons		{Аддоны}
::msgcat::mcset ru mPlugins		{Плугины}
::msgcat::mcset ru unavailable		{Недоступно}
::msgcat::mcset ru {Advanced...}		{Еще}
::msgcat::mcset ru {Connect using HTTP}	{Подключатся через HTTP}


::msgcat::mcset ru mAboutWhiteboard   {О доске для рисования...}
::msgcat::mcset ru mAboutCoccinella   	{О Coccinella...}
::msgcat::mcset ru mAboutQuickTimeTcl	{О QuickTimeTcl...}
::msgcat::mcset ru mWelcome		{Добро пожаловать}
::msgcat::mcset ru mNew			{Новый}
::msgcat::mcset ru mNewWhiteboard	{Новая доска}
::msgcat::mcset ru mOpenConnection	{&Открыть соединение...}
::msgcat::mcset ru mCloseWindow		{&Закрыть окно}
::msgcat::mcset ru mStartServer		{Запустить сервер}
::msgcat::mcset ru mOpenImage/Movie	{Открыть &Изображение/Видео...}
::msgcat::mcset ru mOpenURLStream	{Открыть URL...}
::msgcat::mcset ru mPutCanvas		{Создать холст}
::msgcat::mcset ru mGetCanvas		{Открыть холст...}
::msgcat::mcset ru mPutFile			{Положить файл...}
::msgcat::mcset ru mStopPut/Get/Open	{Остановить Открыть/Получить/Поставить}
::msgcat::mcset ru mOpenCanvas		{Открыть холст...}
::msgcat::mcset ru mSaveCanvas		{&Сохранить холст...}
::msgcat::mcset ru mSaveAs			{Сохранить как...}
::msgcat::mcset ru mSaveAsItem		{Сохранить как...}
::msgcat::mcset ru mSaveImageAs         {Сохранить изображение как...}
::msgcat::mcset ru mPageSetup		{Настройка печати...}
::msgcat::mcset ru mPrintCanvas		{Напечатать холст...}
::msgcat::mcset ru mQuit			{&Выход}
::msgcat::mcset ru mAll				{&Все}
::msgcat::mcset ru mEraseAll			{Стереть все}
::msgcat::mcset ru mUndo			{Назад}
::msgcat::mcset ru mRedo			{Вперед}
::msgcat::mcset ru mCut				{Вырезать}
::msgcat::mcset ru mCopy			{&Копировать}
::msgcat::mcset ru mPaste			{&Вставить}
::msgcat::mcset ru mInspectItem		{Проверить элемент...}
::msgcat::mcset ru mRaise			{&Поднять}
::msgcat::mcset ru mLower			{&Опустить}
::msgcat::mcset ru mLarger			{Больше}
::msgcat::mcset ru mSmaller			{Меньше}
::msgcat::mcset ru mFlip				{Вращать}
::msgcat::mcset ru mHorizontal		{Горизонтально}
::msgcat::mcset ru mVertical			{Вертикально}
::msgcat::mcset ru mImageLarger		{Увеличеть изображениеr}
::msgcat::mcset ru mImageSmaller		{Уменьшить изображение}
::msgcat::mcset ru mBackgroundColor	{Цвет фона...}
::msgcat::mcset ru mGrid				{Сетка}
::msgcat::mcset ru mThickness		{Толщина}
::msgcat::mcset ru mBrushThickness	{Толщина кисти}
::msgcat::mcset ru mFill				{Заполнить}
::msgcat::mcset ru mFillColor			{Заполнить цветом...}
::msgcat::mcset en mOutlineColor		{Outline Color}
::msgcat::mcset ru mLineSmoothness	{Гладкая лининя}
::msgcat::mcset ru mStraighten   		{Выпрямить}
::msgcat::mcset ru mArcs			{Дуги}
::msgcat::mcset en mPieslice			{Pieslice}
::msgcat::mcset en mChord		{Chord}
::msgcat::mcset en mArc			{Arc}
::msgcat::mcset ru mDash		{Бросок}
::msgcat::mcset ru mShiftConstrain	{Ограничение Shift}
::msgcat::mcset ru mTo90degrees		{На 90 градусов}
::msgcat::mcset ru mTo45degrees		{На 45 градусов}
::msgcat::mcset ru mFont		{Шрифт}
::msgcat::mcset ru mSize		{Размер}
::msgcat::mcset ru mWeight		{Ширина}
::msgcat::mcset ru mNormal		{Нормальный}
::msgcat::mcset ru mBold		{Жирный}
::msgcat::mcset ru mItalic		{Наклонный}
::msgcat::mcset ru mPreferences...	{Настройки...}
::msgcat::mcset ru mNewAccount		{Новый аккаунт...}
::msgcat::mcset ru mLogin		{Логин...}
::msgcat::mcset ru mLogout		{Отключится}
::msgcat::mcset ru mLogoutWith          {Отключится со статусом...}
::msgcat::mcset en mHideMain            {Hide Main}
::msgcat::mcset en mShowMain            {Show Main}
::msgcat::mcset ru mPassword		{Пароль}
::msgcat::mcset en mRoster/Services	{Roster/Services}
::msgcat::mcset ru mMessageInbox	{Входящие}
::msgcat::mcset ru mSearch		{Поиск...}
::msgcat::mcset ru mAddNewUser		{Добавить юзера...}
::msgcat::mcset ru mSendMessage		{Послать сообщение...}
::msgcat::mcset ru mChat		{Чат}
::msgcat::mcset ru mStatus		{Статус}
::msgcat::mcset ru mDirStatus           {Направленный статус}
::msgcat::mcset ru mAvailable		{Доступен}
::msgcat::mcset ru mAway		{Нет на месте}
::msgcat::mcset ru mDoNotDisturb	{Не беспокоить}
::msgcat::mcset ru mNotAvailable	{Не доступен}
::msgcat::mcset ru mExtendedAway        {Нет на месте и надолго}
::msgcat::mcset ru mInvisible           {Невидимый}
::msgcat::mcset ru mAttachMessage	{Присоединить сообщение...}
::msgcat::mcset ru mEnterRoom		{Вход в чат-комнату...}
::msgcat::mcset ru mExitRoom		{Выйти из чат-комнаты}
::msgcat::mcset ru mCreateRoom		{Создать чат-комнату...}
::msgcat::mcset ru mvCard		{визитка...}
::msgcat::mcset ru mRemoveAccount	{Удалить аккаунт}
::msgcat::mcset ru mErrorLog			{Лог ошибок...}
::msgcat::mcset ru mDebug			{Дебаг}
::msgcat::mcset ru mOnServer		{О &Сервере...}
::msgcat::mcset ru mOnClients		{О &Клиенте...}
::msgcat::mcset ru mOnPlugins		{О &Плагинах...}
::msgcat::mcset ru mHelpOn			{подсказка On}
::msgcat::mcset ru mNetworkSetup		{Настройки сети}
::msgcat::mcset ru mServers			{Сервера}
::msgcat::mcset ru mJabberTransport	{Jabber транспорт}
::msgcat::mcset en mSmileyLegend		{Smiley Legend}
::msgcat::mcset ru mSetupAssistant	{Помощник настроек..}
::msgcat::mcset en mImageLarger		{Image Larger}
::msgcat::mcset en mImageSmaller		{Image Smaller}
::msgcat::mcset en mExportImage		{Export Image...}
::msgcat::mcset en mExportMovie		{Export Movie...}
::msgcat::mcset en mSyncPlayback		{Sync Playback}
::msgcat::mcset ru mColor			{Цвет...}
::msgcat::mcset en mAddSpeechBubble	{Add Speech Bubble}
::msgcat::mcset ru mUpdateCheck  	{Проверка обновления}
::msgcat::mcset ru mReloadImage 	 	{Обновить изображение}
::msgcat::mcset ru mCoccinellaHome  	{Coccinella Домашняя...}
::msgcat::mcset ru mComponents 	        {Компоненты...}
::msgcat::mcset ru mBugReport  	        {Сообщить о баге...}
::msgcat::mcset ru mTakeSnapShot        {Скриншот}
::msgcat::mcset en mTimeCode		{Timecode}
::msgcat::mcset ru mUserInfo			{Информация о пользовател...}
::msgcat::mcset ru mEditBookmarks	{Закладки}

# Popups
::msgcat::mcset ru mMessage     	{Сообщение...}
::msgcat::mcset ru mWhiteboard     	{Доской...}
::msgcat::mcset ru mLastLogin/Activity  {Последний раз в сети}
::msgcat::mcset ru mEditUser     	{Изменит юзера...}
::msgcat::mcset ru mRemoveUser     	{Удалить юзера...}
::msgcat::mcset ru mRefreshRoster     	{Обновить ростер}
::msgcat::mcset ru mVersion     	{Версия}
::msgcat::mcset ru mRegister     	{Зарегистрироваться}
::msgcat::mcset en mUnregister     	{Unregister}
::msgcat::mcset ru mRefresh     	{Обновить}
::msgcat::mcset ru mAddServer     	{Добавить сервер...}
::msgcat::mcset ru mLocalTime     	{Локальное время...}
::msgcat::mcset ru mSendFile     	{Послать файл...}
::msgcat::mcset ru mChatHistory     	{Журнал}
::msgcat::mcset ru mLoginTrpt     	{Подключится к транспорту}
::msgcat::mcset ru mLogoutTrpt     	{Отключится от транспорта}
::msgcat::mcset ru mRemoveContact  	{Удалить контакт...}
::msgcat::mcset ru mShow         	{Показать}
::msgcat::mcset ru mOffline         	{Офлайн}
::msgcat::mcset ru mTransports         	{Транспорты}


# Short texts only. Use english text as database key.

::msgcat::mcset ru {Description of service provided by}	{Описание сервисов предоставляемых }
::msgcat::mcset ru {Select Photo}	{Выбрать фото}
::msgcat::mcset ru {Remove Photo}	{Удалить фото}
::msgcat::mcset ru {Show Popup}		{Показывать 
всплывающие окна}
::msgcat::mcset ru {Send Message with subject}			{Послать сообщениес темой}
::msgcat::mcset ru {No registered history for %s}			{Нет истории для %s}
::msgcat::mcset ru {ejabberd}			{сервер - ejabberd}
::msgcat::mcset ru {Send File}			{Послать файл}
::msgcat::mcset ru {New Chat}		{Новый чат}
::msgcat::mcset ru {All Off}		{Отключить всё}
::msgcat::mcset ru {Set a specific action when something happens with "%s", which can be changed 
status, or if you receive a message etc. Pick events using the tabs below.}		{Странно, но не работает}
::msgcat::mcset ru {Sounds Set}			{Установка звуков}
::msgcat::mcset ru {MIDI Player}			{MIDI плеер}
::msgcat::mcset ru {Disco method}			{Disco метод}
::msgcat::mcset ru {This dialog makes available a number of options and actions for a
room. Yiur role and affiliation determines your privilege to act.
Further role restrictions may exist depending on specific room 
configuration.}			{Блин}
::msgcat::mcset ru {Item inspector}		{Инспектор}
::msgcat::mcset ru {Item type}		{Тип}
::msgcat::mcset ru {Coordinates}		{Координаты}
::msgcat::mcset ru {Fill}				{Закраска}
::msgcat::mcset ru {Outline}			{Обводка}
::msgcat::mcset ru {Outlinestipple}		{Обводка пунктиром}
::msgcat::mcset ru {Stipple}			{Пунктир}
::msgcat::mcset ru {Tags}			{Тэг}
::msgcat::mcset ru {Width}			{Ширина}
::msgcat::mcset ru Bookmark			{Закладка}
::msgcat::mcset ru Bookmarks			{Закладки}
::msgcat::mcset ru Size				{Размер}
::msgcat::mcset ru mIgnore			{Игнор}



::msgcat::mcset en {30 days}
::msgcat::mcset en {About Coccinella}
::msgcat::mcset en {About Whiteboard}
::msgcat::mcset en {About QuickTimeTcl}
::msgcat::mcset en {About %s}
::msgcat::mcset en {Active <Return>}
::msgcat::mcset ru {Add New User}		{Добавить нового пользователя}
::msgcat::mcset en {Add permanently}
::msgcat::mcset en {Add Server}
::msgcat::mcset en {Add Shortcut}
::msgcat::mcset ru {Address 1}			{Адрес 1}
::msgcat::mcset ru {Address 2}			{Адрес 1}
::msgcat::mcset ru {Advanced Setup}		{Расширенные настройки}
::msgcat::mcset ru {Advanced Configuration}	{Расширенная конфигурация}
::msgcat::mcset en {Alert sounds}
::msgcat::mcset ru {Play Sound}			{Проигровать звук}
::msgcat::mcset ru {Emoticons}			{Смайлики}
::msgcat::mcset en {As text}
::msgcat::mcset ru {Ask each time}			{Постоянно спрашивать}
::msgcat::mcset ru {Auto Away}			{Авто статус}
::msgcat::mcset en {Auto Connect}
::msgcat::mcset ru {Auto-accept}			{Авто-принять}
::msgcat::mcset ru {Auto-reject}			{Авто-отказ}
::msgcat::mcset ru {Away status}			{Нет на месте}
::msgcat::mcset ru {Basic Info}			{Основная информация}
::msgcat::mcset en {Block JID}
::msgcat::mcset ru {Built in server port}		{Порт встроенного сервера}
::msgcat::mcset ru {Cache folder}			{Директория дл кэша}
::msgcat::mcset ru {Canvas Size}			{Размер холста}
::msgcat::mcset en {Chat History}
::msgcat::mcset en {Chat With}
::msgcat::mcset ru {Clear Disk Cache Now}	{Отчиcтить дискоговый кэш сейчас}
::msgcat::mcset ru {Company Name}		{Компания}
::msgcat::mcset en {Component Info}
::msgcat::mcset ru {Conference server}		{Сервер конференций}
::msgcat::mcset ru {Contact Type}			{Тип подключения}
::msgcat::mcset en {Create Room}
::msgcat::mcset ru {Default group}			{Группа по умолчанию}
::msgcat::mcset en {Default Logout Status}
::msgcat::mcset ru {Default nickname}			{Имя с которым вы войдете в конференцию по умолчанию}
::msgcat::mcset ru {Default status descriptions}	{Основные описания статусов}
::msgcat::mcset ru {Delete Rule}				{Удалить правило}
::msgcat::mcset ru {Disk Cache}				{Размер кеша}
::msgcat::mcset en {Different Passwords}
::msgcat::mcset en {Do Not Disturb}
::msgcat::mcset ru {Edit Fonts}		{Изменить шрифт}
::msgcat::mcset en {Edit Item}
::msgcat::mcset en {Edit Shortcut}
::msgcat::mcset en {Edit Shortcuts}
::msgcat::mcset en {Edit User}
::msgcat::mcset ru {Email address}		{Почтовый адрес}
::msgcat::mcset ru {Email addresses}	{Почтовые адреса}
::msgcat::mcset en {Empty Fields}
::msgcat::mcset en {Enter/Create Room}
::msgcat::mcset en {Enter Room}
::msgcat::mcset ru {Every time}		{Всегда}
::msgcat::mcset ru {Extended Away status}	{Нет на месте и надолго}
::msgcat::mcset ru {Factory Settings}	{Вернуть стандартные настройки}
::msgcat::mcset en {Fatal Error}
::msgcat::mcset ru {File Cache}		{Кэш-файл}
::msgcat::mcset en {File coding}
::msgcat::mcset ru {File Mappings}		{}
::msgcat::mcset en {File suffixes}
::msgcat::mcset en {File Transfer}
::msgcat::mcset en {File Transfer Error}
::msgcat::mcset ru {First name}	{Имя}
::msgcat::mcset ru {Font size}			{Размер шрифта}
::msgcat::mcset ru {Font weight}		{Ширина шрифта}
::msgcat::mcset ru {Format mm/dd/yyyy}	{Формат мм/дд/гггг}
::msgcat::mcset en {Get File}
::msgcat::mcset en {Get File Error}
::msgcat::mcset ru {Get vCard}			{Получить визитку}
::msgcat::mcset en {Getting available rooms...}
::msgcat::mcset en {Groupchat in room}
::msgcat::mcset ru {Groupchat presence change}	{Изменение в конференции}
::msgcat::mcset ru {Groupchat-1.0 (fallback)}		
::msgcat::mcset ru {Handled By}				{Использует}
::msgcat::mcset ru {History length}		{Длинна истории}
::msgcat::mcset en {Host name}
::msgcat::mcset en {HTTP port}
::msgcat::mcset en {Import using}
::msgcat::mcset ru {Import/Remove fonts}	{Добавлени/Удаление шрифтов}
::msgcat::mcset ru {Incoming Message}		{Входящее сообщение}
::msgcat::mcset ru {Incoming Messages}		{Входящие сообщения}
::msgcat::mcset ru {Incoming Presence}		{Входящее присутствие}
::msgcat::mcset en {Inspect Associations}
::msgcat::mcset ru {Invite User}			{Пригласить пользователя}
::msgcat::mcset ru {IP address}			{IP адрес}
::msgcat::mcset ru {Is connected}			{Подключен}
::msgcat::mcset en {Is safe}
::msgcat::mcset en {Is server up}
::msgcat::mcset en {Jabber address}
::msgcat::mcset en {Jabber Client}
::msgcat::mcset ru {Jabber Server}		{Jabber сервер}
::msgcat::mcset en {Jabber server port}
::msgcat::mcset en {Jabber user ID}
::msgcat::mcset ru {Jabber ID}
::msgcat::mcset en {JID to block}
::msgcat::mcset en {Last Activity}
::msgcat::mcset ru {Last name}	{Фамилия}
::msgcat::mcset ru {Personal Info}	{Персональная информация}
::msgcat::mcset en {Launch time}
::msgcat::mcset en {Local Time}
::msgcat::mcset en {Logout With Message}
::msgcat::mcset en {Logged out}
::msgcat::mcset ru {Login as invisible}		{Подключится невидимым}
::msgcat::mcset en {Mailbox Error}
::msgcat::mcset en {MIME type}
::msgcat::mcset en {Multi Connect}
::msgcat::mcset en {My Status}
::msgcat::mcset ru {Name of list}			{Имя списка}
::msgcat::mcset en {Network Error}
::msgcat::mcset ru {Network Setup}		{Настройка сети}
::msgcat::mcset en {New Account}
::msgcat::mcset ru {New chat message}		{Новое сообщение в чате}
::msgcat::mcset ru {New chat thread}		{Новый тред в чате}
::msgcat::mcset en {New Color}
::msgcat::mcset ru {New incoming message}	{Новое входящее сообщение}
::msgcat::mcset en {New Message}
::msgcat::mcset ru {New Nickname}		{Новое имя}
::msgcat::mcset ru {New password}		{Новый пароль}
::msgcat::mcset ru {New Rule}			{Новое правило}
::msgcat::mcset en {New Topic}			{Новая тема}
::msgcat::mcset en {New shortcut}
::msgcat::mcset ru {New User}			{Новый пользователь}
::msgcat::mcset ru {New Version}			{Новая версия}
::msgcat::mcset ru {My vCard}			{Моя визитка}
::msgcat::mcset ru {NAT Address}			{NAT адрес}
::msgcat::mcset ru {Nick name}		{Ник}
::msgcat::mcset en {No Address}
::msgcat::mcset en {No Available}
::msgcat::mcset en {No Inbox}
::msgcat::mcset en {No Printing}
::msgcat::mcset en {Not Available}
::msgcat::mcset en {Not available}
::msgcat::mcset ru {Not Connected}		{Не подключен}
::msgcat::mcset ru {Once per session}		{Раз в сессию}
::msgcat::mcset ru {One hour} 			{Один час}
::msgcat::mcset ru {One day} 			{Один день}
::msgcat::mcset ru {One week} 			{Одна неделя}


::msgcat::mcset ru {Bookmark this room}	{Добавить в закладки эту комнату}
::msgcat::mcset ru {Import Iconset...}		{Импортирование иконок}
::msgcat::mcset ru {New bookmark}		{Новая закладка}
::msgcat::mcset ru {No Restriction}			{Без ограничений}
::msgcat::mcset ru {Not older than}		{Не старее чем}
::msgcat::mcset ru {Pick skin}				{Выбрать скин}
::msgcat::mcset ru {Set windows opacity}	{Установить прозрачность окна}
# Time intervals.
::msgcat::mcset ru {Ten seconds}			{Десять секунд}
::msgcat::mcset ru {One minute}			{Одна минута}
::msgcat::mcset ru {Ten minutes}			{Десять минут}



::msgcat::mcset en {Open Canvas}
::msgcat::mcset en {Open Failed}
::msgcat::mcset en {Open Helpfile}
::msgcat::mcset en {Open Image/Movie}
::msgcat::mcset en {Open Stream}
::msgcat::mcset ru {Outgoing Presence}		{Исходящее отключение}
::msgcat::mcset en {Peer-to-Peer}
::msgcat::mcset en {Personal Information}
::msgcat::mcset ru {Personal URL}		{Частная страница}
::msgcat::mcset en {Pick Directory}
::msgcat::mcset en {Pick File}
::msgcat::mcset ru {Plugin Info}		{Инфо о плагинах}
::msgcat::mcset ru {Plugin Control}		{Контроль плагинов}
::msgcat::mcset ru {Port number}		{Номер порта}
::msgcat::mcset ru {Postal Code}			{Почтовый индекс}
::msgcat::mcset ru {Preferred Protocol}		{Предпочитаемый протокол}
::msgcat::mcset en {Presence Error}
::msgcat::mcset en {Privacy List}
::msgcat::mcset ru {Profile Name}		{Имя профиля}
::msgcat::mcset ru {Proxy Setup}		{Настройка прокси}
::msgcat::mcset en {Put File Error}
::msgcat::mcset en {Put Image/Movie}
::msgcat::mcset en {Reject receive}
::msgcat::mcset en {Request To User}
::msgcat::mcset ru {Retype password}		{Повторите новый пароль}
::msgcat::mcset ru {Revert Panel}			{Вернуть эту настройку}
::msgcat::mcset en {Register New Account}
::msgcat::mcset en {Register Now}
::msgcat::mcset en {Register Service}
::msgcat::mcset en {Remove Item}
::msgcat::mcset ru {Room name}			{Имя комнаты}
::msgcat::mcset en {Room name (optional)}	
::msgcat::mcset en {Roster & Services}
::msgcat::mcset ru {Save As}				{Сохранить как}
::msgcat::mcset ru {Save As GIF}			{Сохранить как GIF}
::msgcat::mcset en {Save Canvas}
::msgcat::mcset ru {Save File}				{Сохранить файл}
::msgcat::mcset ru {Save Message}		{Сохранить сообщение}
::msgcat::mcset ru {Scramble password}		{Смешанный пароль}
::msgcat::mcset ru {Search results}			{Результаты поиска}
::msgcat::mcset ru {Search Service}		{Сервис поиска}
::msgcat::mcset en {Search Specifications}
::msgcat::mcset ru {Select a new nickname}	{Выбирете новое имя}
::msgcat::mcset ru {Select Font}			{Выбирете шрифт}
::msgcat::mcset ru {Послать файл}
::msgcat::mcset en {Send Live}
::msgcat::mcset ru {Server Info}			{Инфо о сервере}
::msgcat::mcset en {Service server}
::msgcat::mcset en {Set Directed Presence}
::msgcat::mcset en {Set New Nickname}
::msgcat::mcset ru {Set New Topic}		{Установить новую тему}
::msgcat::mcset ru {Set Status}			{Установить статус}
::msgcat::mcset ru {Settings Panels}		{Панель настроек}
::msgcat::mcset en {Setup Assistant}
::msgcat::mcset en {Slide Show}
::msgcat::mcset en {Slide Show Folder}
::msgcat::mcset ru {Software Update}		{Апдейт программы}
::msgcat::mcset en {Sounds & Speech}
::msgcat::mcset ru {Start Chat}			{Начать чат}
::msgcat::mcset en {Status message}
::msgcat::mcset en {Status when logging out}
::msgcat::mcset en {Subscription Failed}
::msgcat::mcset en {Subscription Pending}
::msgcat::mcset en {Synthetic speech}
::msgcat::mcset ru {System fonts}		{Системный шрифт}
::msgcat::mcset ru {Take Snapshot}	{Сделать скриншот}
::msgcat::mcset ru {Games}			{Игры}
::msgcat::mcset ru {heart}			{сердечко}
::msgcat::mcset ru {Tel (voice)}		{Телефон}
::msgcat::mcset ru {Tel (fax)}			{Факс}
::msgcat::mcset кг {This IP number}	{Номер IP}
::msgcat::mcset ru {Thread started}	{Тред начат}
::msgcat::mcset ru {To/from JID}		{Для/от JID}
::msgcat::mcset ru {To Jabber ID}		{Для JID}
::msgcat::mcset en {To Send or Not}
::msgcat::mcset ru {Type of File}			{Тип файла}
::msgcat::mcset en {Unknown: Prompt user}
::msgcat::mcset ru {Url of homepage}		{Url домашней страницы}
::msgcat::mcset ru {Use SSL for security}	{Использовать SSL}
::msgcat::mcset ru {User is}				{Пользователь}
::msgcat::mcset ru {User is offline}			{Пользователь отключился}
::msgcat::mcset ru {User is online}			{Пользователь подключился}
::msgcat::mcset ru {User Profiles}			{Профили}
::msgcat::mcset ru {User's status changed}	{Пользователь изменил статус}
::msgcat::mcset ru {Username & Password}	{Имя пользователя и пароль}	
::msgcat::mcset ru {Users avatar}			{Пользовательское изображение}
::msgcat::mcset ru {vCard Info}			{Визитка}
::msgcat::mcset ru {Version Info}			{Версия}
::msgcat::mcset ru {Whiteboard fonts}		{Шрифт доски для рисования}
::msgcat::mcset ru {Writing file}			{Запись файла}
::msgcat::mcset ru {Buddy Pouncing}		{Личные настройки}
::msgcat::mcset ru {Info Room}			{Комната модерирования}

# Splash screen:
::msgcat::mcset ru splashsource 		{Чтение Tcl кодв...}
::msgcat::mcset ru splashload 			{Загрузка Tcl...}
::msgcat::mcset ru splashloadsha1 		{Загрузка sha1...}
::msgcat::mcset ru splashsourcejabb 	{Чтение Jabber кода...}
::msgcat::mcset ru splashhost 			{Поиск имени хоста...}
::msgcat::mcset ru splashinit 			{Инициализация...}
::msgcat::mcset ru splashprefs 		{Настройка и чтение установок...}
::msgcat::mcset ru splashbuildmenu		{Настройка меню...}
::msgcat::mcset ru splashbuild 		{Настройка интерфейса...}
::msgcat::mcset ru splashlook 			{Поиск}


# Messages for tk_messageBox:
::msgcat::mcset ru messfailedhttp	{Ошибка запуска встроенного http сервера: %s}
::msgcat::mcset en messinfoscript	{Due to the 'info script' bug on Mac you need to explicitly pick the 'Whiteboard-%s' folder in the following dialog.}
::msgcat::mcset en messfailedsock	{Couldn't create socket to server. Maybe networking is not functioning or server is down. The error code is: %s}
::msgcat::mcset en messeofconnect	{Something went wrong when opening connection. Got an eof.}	
::msgcat::mcset en messfailconnect		{Something went wrong when opening connection to %s}
::msgcat::mcset ru messtimeout		{Кончилось время ожидания открытия сервера.}
::msgcat::mcset en messnoplugs		{There are no plugins or helper applications identified on this system.}
::msgcat::mcset ru messfailopread	{Невозможно открыть %s для чтения: %s}
::msgcat::mcset ru messfailopwrite	{Невозможно открыть %s для записи: %s}
::msgcat::mcset en messcanerasewarn	{Opening a canvas file erases everything in present canvas!}
::msgcat::mcset en messaskreceive	{We are about to receive the file %s. Do you want to receive it?}
::msgcat::mcset en messfailmimeimp 	{Failed finding importer for the MIME type %s}
::msgcat::mcset en messfailnomime 	{Failed finding MIME type for the file %s}
::msgcat::mcset en messfailsend		{We got an error when trying to send to %s}
::msgcat::mcset en messfactorydefaults	{You are about to remove most of your customization. Do you actually want to proceed?}
::msgcat::mcset ru messremoveprofile	{Вы действительно хотите удалить профиль?}
::msgcat::mcset en messfillserveruser	{You need to fill in at least the server name and user name.}
::msgcat::mcset en messprofinuse	{This profile is already in use. Do you want to replace it?}
::msgcat::mcset en messblockbadjid	{The JID "%s" is not well formed. Do you want to add it anyway?}
::msgcat::mcset en messfieldsmissing	{One or more fields are missing. Try again or cancel.}
::msgcat::mcset ru messrmstandardfonts	{Стандартные шрифт: Times, Helvetica, и Courier не могут быть удалены}
::msgcat::mcset ru messprefschanged	{Некоторые настройки были изменины. Вы хотите выйти без сохранения?}
::msgcat::mcset ru messerrpreffile	{Ошибка открытия файла %s.}
::msgcat::mcset ru messfailserver	{Невозможно открыть сокет для сервера. Возможно вы не подключены.}
::msgcat::mcset en messopenhelpfile	{You are about to open a helpfile in the canvas thereby erasing the present stuff. Do you want this to happen?}
::msgcat::mcset en messprintnoextension	{Is not aware of a tcl extension that helps us here :-(}
::msgcat::mcset ru messdoquit?		{Вы точно хотите выйти?}
::msgcat::mcset en messsuassfillin	{Be sure to fill in all entries before you continue}
::msgcat::mcset en messsuassclose	{Are you sure you want to close the setup assistant? You may start it any time later from the menu.}
::msgcat::mcset ru messprotocolch	{Вы изменили настройки связанные с сетью. Надо перезагрузить приложение. Вы хотите продолжить?}
::msgcat::mcset en messpasswddifferent  {The two passwords do not match. Please try again.}
::msgcat::mcset en messaupdatelatest    {You already have the latest version available (%s)}
::msgcat::mcset ru messprefsrestart     {Одна или несколько настроек изменина, чтобы получить результат перезагрузите программу}

# Messages for tk_messageBox:
::msgcat::mcset en jamesserrsend	{We received an error when sending a message to "%s". The error code is %s, and the error message: %s}
::msgcat::mcset en jamessallowsub	{User %s allowed you to subscribe to its presence.}
::msgcat::mcset en jamessunsub		{User %s has unsubscribed your presence and is removed from your roster.}
::msgcat::mcset en jamessunsubpres	{User %s has unsubscribed your presence.}
::msgcat::mcset en jamessunsubask	{User %s has unsubscribed from your presence. Do you want to remove %s from your roster?}
::msgcat::mcset ru jamessunsubscribed	{Вы удалили авторизацию от %s.}
::msgcat::mcset en jamesserrpres	{We received a presence error. The error code is %s and message: %s}
::msgcat::mcset en jamessautoaccepted	{You have just automatically accepted a subscription request from %s.}
::msgcat::mcset en jamessautoreject	{You have just automatically rejected a subscription request from %s.}
::msgcat::mcset en jamessautosubs	{You have just automatically subscribed to %s presence.}


::msgcat::mcset ru jamessconnbroken	{Подключение было неожиданно прервано.}
::msgcat::mcset en jamessautoawayset 	{Automatic away has been set at %s. Do you want to become available again?}
::msgcat::mcset en jamesserrgetpublic	{Received an error when getting the public data from %s. The error code is %s with error message: %s}
::msgcat::mcset en jamesserrlastactive	{We received an error when quering %s for last activity. The error was: %s}
::msgcat::mcset en jamesserrnotimeinfo	{Client or service %s didn't return a time info.}
::msgcat::mcset en jamesstimeused	{Time since client "%s" was last actively used: }
::msgcat::mcset ru jamesstimeconn	{Пользователь "%s" в сети с:}
::msgcat::mcset en jamesstimeservstart	{Time since server "%s" was started: }
::msgcat::mcset ru jamessuptime		{Рабочее время (сервера), или последнея активность пользователей: }
::msgcat::mcset ru jamesserrtime	{Мы получили ошибку когда запрашивали %s. Ошибка такова: %s}
::msgcat::mcset en jamesslocaltime	{The local time for %s is: %s}
::msgcat::mcset en jamesserrvers	{We received an error when quering %s for its version. The error was: %s}
::msgcat::mcset en jamesserrautoupdate 	{We received an error when quering %s for updated client software. The error was: %s}
::msgcat::mcset en jamesswarberasewb	{Do you want to erase the whiteboard first?}
::msgcat::mcset ru jamesswarnremove	{Удаление пользователя - необратимый процесс. Чтоб вернуть пользователя обратно вам придется его снова добавлять. Вв хотите продолжить?}
::msgcat::mcset en jamessillegalchar	{Illegal character(s) in %s: "%s"!}
::msgcat::mcset en jamessbadjid		{The jid "%s" is not well formed. Do you want to continue anyway?}
::msgcat::mcset en jamessalreadyinrost	{The jid "%s" is already in your roster. Do you want to continue anyway?}
::msgcat::mcset en jamessfailsetnick	{There was a failure when setting the nick name or group of user "%s". The error code is %s with the message: %s}
::msgcat::mcset en jamessnamemissing	{The %s is missing or is too short!}
::msgcat::mcset ru jamessnosocket	{Ошибка связи с Jabber сервером "%s". Возможно не работает сеть или сервер выключен. Сообщение: %s}
::msgcat::mcset en jamesstimeoutserver	{Timeout when waiting for server "%s" to respond.}
::msgcat::mcset en jamessregisterok	{The registration to server "%s" was succesful. Now you just need to Login using the same username and password.}
::msgcat::mcset en jamessremoveaccount	{You are about to remove your account from this server. This process cannot be undone. Do you really want to continue?}
::msgcat::mcset en jamesserrunreg	{We received an error when trying to unregister from "%s". Code %s, and message %s}
::msgcat::mcset en jamessokunreg	{You are now unregistered from "%s"}
::msgcat::mcset en jamesspasswddiff	{The passwords do not agree. Please check once again.}
::msgcat::mcset en jamesspasswderr	{Setting new password failed with the error code %s and message: "%s"}
::msgcat::mcset en jamesspasswdok	{Setting new password was succesful}
::msgcat::mcset en jamessregnoserver	{We require the server to be set.}
::msgcat::mcset en jamesserrregget	{Failed obtaining registration info. Error code %s with message: %s}
::msgcat::mcset en jamesserrregset	{Failed registering with service "%s". Error code %s with message: %s}
::msgcat::mcset en jamessokreg		{Registration with service "%s" was succesful.}
::msgcat::mcset en jamessinvalidjid	{The JID address is not well formed. Please be sure that the entry at the bottom of the whiteboard contains a valid address before you act.\
  It should look something like 'username@jabber.org'.}
::msgcat::mcset en jamessnotconnected	{Can't send when not connected to server}
::msgcat::mcset en jamessaddrmiss	{You need to fill in at least one valid address}
::msgcat::mcset en jamesschatclose	{If you close this chat window you also loose the complete conversation. Do you actually like to close?}
::msgcat::mcset en jamessnogroupchat	{We could not recognize any service that provides groupchat}
::msgcat::mcset en jamessgcnoroomname   {You must provide a roomname.}
::msgcat::mcset en jamessgcnoroomnick   {You must provide a nickname.}
::msgcat::mcset en jamessinroommiss	{We require that all fields are nonempty before entering room}
::msgcat::mcset ru jamesswarnexitroom	{Вы действительно хотите выйти из комнаты "%s" ?}
::msgcat::mcset en jamesserrbrowse	{We got an error when browsing "%s": %s}
::msgcat::mcset en jamessenterroomempty	{We require both the server and room name entries to be filled with valid names.}
::msgcat::mcset en jamesserrconfget	{Failed obtaining info entering room. Error code %s with message: %s}
::msgcat::mcset en jamesserrconfgetcre	{Failed obtaining info creating room. Error code %s with message: %s}
::msgcat::mcset en jamessinroomerasewb 	{Do you want to erase the whiteboard before entering a new room?}
::msgcat::mcset en jamessconffailed	{Failed enter/create room "%s". Error code %s with message: %s}
::msgcat::mcset en jamessconfservempty	{We require the server to be filled with a valid name.}
::msgcat::mcset en jamesserragentget	{We got an error when obtaining agents: %s}
::msgcat::mcset en jamesserrsearch	{Failed obtaining search specification. Error code %s with message: %s}
::msgcat::mcset ru jamessoobok		{Передача файла успешно завершилась}
::msgcat::mcset en jamessoobok2         {File transfer of %s to "%s" went ok}
::msgcat::mcset en jamessoobnourl		{When user "%s" wanted us to fetch a file, we did not receive an url to get it from.}
::msgcat::mcset en jamessoobask		{The user "%s" makes the file at %s available for you. Description: %s. Do you want it?}
::msgcat::mcset en jamessoobbad		{The url we got from "%s" was not wellformed. url: "%s"}
::msgcat::mcset en jamessoonnohttp	{The url we got from "%s" did not use the http protocol, but instead %s which is unsupported.}
::msgcat::mcset ru jamessoobfailopen	{Ошибка открытия файла %s}
::msgcat::mcset en jamessoobgetfail	{Failed getting url "%s": %s}
::msgcat::mcset en jamessoobtimeout	{We got a timeout when getting file over http}

::msgcat::mcset en jamessooberr406      {The user %s rejected to accept the file %s.}
::msgcat::mcset en jamessooberr404      {Got an error when trying to send the file %s to %s. The code was %s, and error message: %s}

::msgcat::mcset en jamessnogchat	{We could not recognize any service that provides groupchat}
::msgcat::mcset en jamesserrinboxopen	{Failed open the inbox file %s when trying to save it.}
::msgcat::mcset en jamesserrinboxread	{Got an error when trying to read the Jabber message box file "%s": %s}
::msgcat::mcset en jamesschatclose	{If you close this chat window you also loose the complete conversation. Do you actually like to close?}
::msgcat::mcset en jamessgchatfields	{We require that all fields are nonempty before entering room.}
::msgcat::mcset en jamessconfmsg	{Select a conference service and a room name. Then push "Get" to obtain the specification for entering the desired room since each room & server\
  may have different requirements.}
::msgcat::mcset en jamesssavemsg	{Do you want to save this message before closing?}
::msgcat::mcset en jamessskipsendq	{The address "%s" is not well formed. Do you want to skip it and send to the rest?}
::msgcat::mcset en jamessillformresend	{The address "%s" is not well formed. Please modify it and resend.}
::msgcat::mcset en jamesslogin409	{The login failed with the error code %s because this username is already in use by another user. If this user is you, try to login instead.}
::msgcat::mcset ru jamessloginerr	{При подключении произошла ошибка %s и сообщение: %s}
::msgcat::mcset en jamessaddforeign	        {Adding a user from a non Jabber IM system requires that you already have an account on this system, and that you have used this account to register\
with the corresponding server transport component %s. Do you wish to do that now?}
::msgcat::mcset en jamessowntrpt	        {This is your own account at %s that acts as a server service that transports messages to that IM system. It is necessary for it to be in your roster.\
You have a subscription for %s: %s.}
::msgcat::mcset ru jamesswbchatlost	        {Полный разговор будет потерен при выходе из доски для рисования. Вы все еще хотите выйти?}
::msgcat::mcset en jamesschatoffline            {This user is not online anymore and the message is therfore not sent.}
::msgcat::mcset en jamessregloginok             {You are now registered and automatically logged on as "%s"}
::msgcat::mcset en jamessregerrinuse            {The registration failed because this username is already in use by another user. If this user is you, try to login instead. Error message: %s}
::msgcat::mcset en jamessregerr                 {The registration failed with error message: %s}
::msgcat::mcset en jamesstrptsubsc              {Your registered account with the %s service will be put in your roster to work as a transport with this service.}
::msgcat::mcset en jamessfailedsubsc            {Failed to make a subscription to %s. The user denied the subscription.}
::msgcat::mcset en jamessstarttls-nofeature     {The server "%s" has no support for TLS.}
::msgcat::mcset en jamessstarttls-failure       {TLS negotiating with server "%s" failed.}
::msgcat::mcset en jamessgcinvite               {You have been invited to the groupchat room %s by %s. Do you want to join?}



::msgcat::mcset ru openquicktime		{Открытие QuickTime потока}
::msgcat::mcset en writeurl			{Write URL or choose from shortcut:}
::msgcat::mcset en openquicktimeurlmsg		{Open a URL which contains a SDP file with extension .mov for a QuickTime realtime live streaming sending. Can be audio (radio) or video (TV).\
Alternatively, use your web browser to find the SDP file for a live transmission, download it on disk and open it is an ordinary movie.}
::msgcat::mcset en printunixcmd                 {Shell print command, edit if desired}
::msgcat::mcset en enterpassword                {Enter the password for your account "%s"}



::msgcat::mcset ru httptrptok                   {Закончено получие файла %s}
::msgcat::mcset en httptrpterror                {File transport error when getting the file %s: %s}
::msgcat::mcset ru httptrpteof                  {Сервер закрыл сокет без ответа.}
::msgcat::mcset en httptrptnon200               {File transport error when getting the file %s: code %s; %s}
::msgcat::mcset en httptrptreset                {File transport of %s was reset}

::msgcat::mcset en uastatpointmac 	{Point tool, click to mark, double click to inspect, press to popup}
::msgcat::mcset ru uastatpoint		{Инструменты для рисования, выбирете для выделения, двойной клик для проверки, правый клик для настроек}
::msgcat::mcset ru uastatmove	{Перемещениеl}
::msgcat::mcset ru uastatline		{Рисование прямых}
::msgcat::mcset ru uastatarrow	{Стрелы}
::msgcat::mcset ru uastatrect		{Рисование прямоугольников}
::msgcat::mcset ru uastatoval		{Рисование овалов}
::msgcat::mcset ru uastattext		{Писание текста}
::msgcat::mcset ru uastatdel		{Нажмите для удаления}
::msgcat::mcset ru uastatpen		{Ручка}
::msgcat::mcset ru uastatbrush	{Кисть}
::msgcat::mcset ru uastatpaint		{Закраска, Shift + клик для прозрачности}
::msgcat::mcset ru uastatpoly		{Многоугольникl, пробел для отменыl}
::msgcat::mcset ru uastatarc		{Дуги, клик для установки центра, пробел для отмены}
::msgcat::mcset ru uastatarc2		{Дуги, кликни и тащи}
::msgcat::mcset ru uastatrot		{Вращать, сначало надо выбрать, что вращать}


# Preferences:
::msgcat::mcset ru prefnetconf  {Настройка сервера и сети}
::msgcat::mcset ru prefnethead  {Можно подключится к любому жаббер серверу или подключатся к другоиу клиенту. Большая часть интерфейса зависит от того что вы выбирите.}
::msgcat::mcset ru prefnetauto  {Если клиент подключен к серверу, подключение к другим клиентам сервер сделает сам.}
::msgcat::mcset ru prefnetjabb  {Jabber серверная система. Управление клиентами осуществляется через меню "Жаббер". Используя XML-основанный протокол.}
::msgcat::mcset ru prefnetmulti {Подключатся автоматически к всем клиентам в этой сети  когда конектися кто-то из них.}
::msgcat::mcset ru prefnetadv   {Клиент обычно запускает два разных сервера, которые всягда учавствуют в peer-to-peer случае, и http сервер.\
Жаббер сервер обычно удаленный, и использует порт 5222. При измении порта нужно перезагрузить прогрмму.}
::msgcat::mcset en prefsounsynwb {Have synthetic speech of text written in the whiteboard}
::msgcat::mcset en prefsounsynno {Have synthetic speech of normal messages}
::msgcat::mcset en prefsounsynch {Have synthetic speech of chat}
::msgcat::mcset en prefsounvoin  {Pick voice for incoming text:}
::msgcat::mcset en prefsounvoou  {Pick voice for text you write:}
::msgcat::mcset ru prefsounpick  {Выбирете предупреждающие звуки для событий ниже:}
::msgcat::mcset en prefshortcut  {Here you add or edit shortcuts that are only applicable to "peer-to-peer" connections, and are not used by the Jabber system.\
If you haven't explicitly picked the "peer-to-peer" option in the "Network Setup" panel, these shortcuts don't apply.}
::msgcat::mcset ru prefprof      {Здесь необходимо вводить параметры для подключения к Jabber серверу.}
::msgcat::mcset en prefpers      {Your personal info is stored in your preferences file, but may also be stored on the Jabber User Directory. Server stored info is searchable by any user.}
::msgcat::mcset ru prefaaset     {Настройки, касающегося вашего статуса:}
::msgcat::mcset ru prefminaw     {Минут до установки статуса "Нет на месте":}
::msgcat::mcset ru prefminea     {Минут до установки статуса "Нет на месте и надолго":}
::msgcat::mcset ru prefsuif      {Если кто-то хочет получить регистрацию  и...}
::msgcat::mcset ru prefsuis      {...уже в моем ростере:}
::msgcat::mcset ru prefsuisnot   {...не в моем ростере:}
::msgcat::mcset ru prefsuauto    {Автоматически авторизовать}
::msgcat::mcset ru prefrorm      {Удалять пользователей если не авторизованы}
::msgcat::mcset ru prefroallow   {Разрешить пользователей без авторизации}
::msgcat::mcset ru prefroclr     {Отчищать ростер при отлогировании}
::msgcat::mcset ru prefrochat    {Чат при двайном щелчке, иначе обычное сообщение}
::msgcat::mcset ru prefrosysicons {Показывать иконку в трее}
::msgcat::mcset ru prefrohideoff {Не показывать отключенных пользователей}
::msgcat::mcset ru prefrohidetrpt {Не показывать транспорт}
::msgcat::mcset ru prefblonly    {Получать сообщения только от тех кто в ростере}
::msgcat::mcset ru prefblbl      {Блокировать JID's (* wildcards possible):}
::msgcat::mcset en prefblmsg     {Write the complete JID for the user you want to block. A JID must be of the form "joewest@jabber.org"}
::msgcat::mcset ru prefcufont    {Выбирете шрифт для окна чата:}
::msgcat::mcset ru prefcushow    {Показывать входящие сообщения в новом окне}
::msgcat::mcset ru prefcusave    {Сохранять входящие}
::msgcat::mcset ru prefcuautologin  {Автоматически подключаться при запуске}
::msgcat::mcset ru prefcu2clk    {Двойной щечек для входящих:}
::msgcat::mcset ru prefcuopen    {Открывать сообщения в новом окне}
::msgcat::mcset ru prefcureply   {Ответить отправителю}
::msgcat::mcset ru prefcudisc    {Предпочитаемый метод сервисов:}
::msgcat::mcset ru prefcubrowse  {Просмотр сервисов если возможно}
::msgcat::mcset ru prefcuagent   {Всегда использовать agents method}
::msgcat::mcset ru prefcuupdate  {Автоматически проверять на новые версии}
::msgcat::mcset ru prefcuremdlgs {Запоминать открытые диалоги между сессиями}
::msgcat::mcset ru preffmhelp    {Помощник для файловых плагинов}
::msgcat::mcset en preffmsave    {Just save to disk in incoming directory}
::msgcat::mcset ru preffontmsg   {Внимание: перед импортирование других шрифтов кроме (Times, Helvetica or Courier), вы должны убедится что они есть у всех остальных клиентов.}
::msgcat::mcset en prefcahow     {How to handle files already received:}
::msgcat::mcset en prefcanev     {Never accept a cached file, always load a new one}
::msgcat::mcset en prefcaalw     {Always accept a cached file, never load a new one} 
::msgcat::mcset en prefcaor      {..or accept cached file if not older than:}
::msgcat::mcset ru prefpriv      {Картины нарисованные вами нельзя будет редактировать другим.}
::msgcat::mcset en prefshortip   {Complete ip number or name}
::msgcat::mcset en prefshortwa   {Warning: you have edited the shortcuts. Don't you want to save them?}

::msgcat::mcset ru preffilecache {Кэш используестя для хранения локальных копий файлов от других пользователей которое понижает 
время для  работа транспорта. Размер кэша устанавливается ниже.}
::msgcat::mcset ru prefcachecmp  {Кэшированные файлы сверяются с удаленными}
::msgcat::mcset ru prefnatip     {Использовать следющий ip адрес для внешней сети}
::msgcat::mcset ru prefmucconf   {Multi-User-Chat c конференциями as fallback}
::msgcat::mcset ru prefrostbgim  {Использовать фоновое изображение (gif) в }
::msgcat::mcset ru preftheme     {Выбирете тему (ниобходима перезагрузка)}
::msgcat::mcset ru prefplugctrl  {Вы можете отменить эти пакеты, если не хотите чтоб они не загружались.}
::msgcat::mcset ru prefchactret  {Всегда использовать <Return> в окне диалога}
::msgcat::mcset ru prefchnormal  {Показывать входящие сообщения как сообщения чата}
::msgcat::mcset ru prefprofname  {Введите желаемое имя профайла}
::msgcat::mcset ru prefstabui    {Использовать закладочный интерфейс}
::msgcat::mcset ru prefsusesasl  {Использовать SASL-авторизационный метод}
::msgcat::mcset ru prefprivmsg   {Каждый пользователь может иметь много фильтров. Только активные или фильтры по умолчанию \
 влияют на сообщения.}
::msgcat::mcset ru prefprivunav  {Опции фильтров недоступны пока вы не подключены}
::msgcat::mcset en prefprivnotex {Filter options unavailable at this server}
::msgcat::mcset ru prefprivobtained {Получать список фильтров с сервера}
::msgcat::mcset ru prefprivgetlist {Получение фильтра "%s"}
::msgcat::mcset ru prefprivrules {Each list contains one or many rules, each rule specify the type of events it acts on, and the action it shall take.\
 Если вы выберете группу для блока то она должна существовать в ростере.}
::msgcat::mcset ru prefuserinactive {Пользователь был долго не активен}  
::msgcat::mcset ru preficonsel   {Выбор набора иконок будет работать после сохранения}
::msgcat::mcset ru prefwbscroll  {Вы можете ввести больше чем стандартный размер %sx%s}
::msgcat::mcset ru prefssbts     {Показывать кнопки назад и вперед}
::msgcat::mcset ru prefssresize  {Менять размеры холста автоматическиa в соответствии размерам изображения}




# EditShortcuts namespace:
namespace eval ::EditShortcuts:: {
	::msgcat::mcset en shortip       {Complete ip number or name}
	::msgcat::mcset en shortwarn     {Warning: you have edited the shortcuts. Don't you want to save them?}


}


::msgcat::mcset en jalogin 	{Write Jabber server ip number or name, or choose from the popup menu. You should already have an account with this server.}
::msgcat::mcset en janewaccount {Write jabber server ip number or name. Pick your username and password.}
::msgcat::mcset ru janewpass    {Установите новый пароль для:}
::msgcat::mcset en jasubwant    {The user "%s" wants to subscibe to your presence.}
::msgcat::mcset en jasubopts    {Choose from the options below. Picking a nick name and group is optional, and for your personal use only.}
::msgcat::mcset ru jasubgetvcard {Получить визтку пользователя}
::msgcat::mcset ru jasubsndmsg  {Послать сообщение этому пользователю:}
::msgcat::mcset en jasuballow   {Allow "%s" to see my presence}
::msgcat::mcset en jasubadd     {Add "%s" to my roster}
::msgcat::mcset ru jarostadd	{Добавить пользователя в список контактов. Имя или группа могут быть изменены в любое время. Чтобы добавить пользователей из других IM систем вы должны уже иметь аккаунт\
  в той системе, и Jabber транспорт или шлюз.}
::msgcat::mcset ru jarostset	{Изменения имени и группы "%s". Они могут быть изменены в любое время.}
::msgcat::mcset ru jarostsub	{Авторизовать пользователя}
::msgcat::mcset ru jarostunsub	{Удалить авторизацию}
::msgcat::mcset ru jasearch	{Поиск пользователей. Нажмите "Получить" если вы хотите отчичтить формы.}
::msgcat::mcset en jasearchwait	{Waiting for Get to be pressed}
::msgcat::mcset ru jaservclosed	{Сервер закрыл подключение.}
::msgcat::mcset ru jarostupdate {Список контактов обновлен}
::msgcat::mcset ru jawaitresp 	{Подключение к %s. Ожидание ответа...}
::msgcat::mcset ru jawaitxml 	{Подключение к "%s". Инициализия XML потока...}
::msgcat::mcset en jasendauth	{Server "%s" responded. Sending authorization information.}
::msgcat::mcset ru jaerrlogin	{Не удалось подключиться к %s : %s}
::msgcat::mcset en jaauthok	{Authorization to server "%s" was succesful. Getting the roster...}
::msgcat::mcset en jagchatmsg	{Pick groupchat server and select a room name and your own nick}
::msgcat::mcset en jacreateroom	{Select a conference service and optionally a room name. Then push "Get" to obtain the specification for creating the desired room since each server may have\
  specific requirements.}
::msgcat::mcset ru jawaitserver	{Ожидание ответа сервера...}
::msgcat::mcset en jaregmsg	{Registration for a specific service with this server. If already registered you may alter your personal info with this dialog.}
::msgcat::mcset ru jastatavailable {Доступно}
::msgcat::mcset ru jastatchat	{Чат: с удовльствием початюсь}
::msgcat::mcset ru jastataway	{Нет на месте: в сети но нет меня на месте}
::msgcat::mcset ru jastatxa	{Extended away: online, but inactive a while}
::msgcat::mcset ru jastatdnd	{DND: не беспокоить!}
::msgcat::mcset ru jastatinvisible {Невидимый}
::msgcat::mcset ru javersinfo	{Информация о версии %s}
::msgcat::mcset en jabrowseaddserver	{Enter the JID of the server you want to add to the list of services, for instance, "jabber.org".}
::msgcat::mcset ru jaupdatemsg	{Доступна новая версия Coccinelle.}
::msgcat::mcset ru jaupdatevers	{Текущая версия: %s}
::msgcat::mcset ru jaupdatepri	{Это обновление %s}
::msgcat::mcset ru jaupdatenewver {Новая версия: %s}
::msgcat::mcset ru jaupdateremind {Не напоминать мне об этом}
::msgcat::mcset ru jasettopic   {Установить новую тему для чат-комнаты.}
::msgcat::mcset en jadirpresmsg {Send directed presence to the user "%s".}
::msgcat::mcset ru jatlsnegot   {Получение TLS security...}
::msgcat::mcset ru jamucentermsg {Введите ваш ник и нажмите "Enter" для захода в комнату. Вы можете просмотреть список доступных комнат.	Для частных комнат может понадобиться пароль.}
::msgcat::mcset ru jainmsgshow  {Показывать входящие сообщения в этом окне}
::msgcat::mcset en jadisaddserv {Discover another server for groupchat rooms and other services. You may add a server permanently which is then automatically discovered. The login server is always discovered.}
::msgcat::mcset en jadisrmall   {Remove all servers that are automatically and permanently discovered.}
::msgcat::mcset ru jauserinnote {Добавьте Ваше описание к этому пользователю}
::msgcat::mcset en jaregisterex {Fill in the jabber servers name you want to register with. Then press the Get button to receive the desired registration info. Fill in that info and register.}
::msgcat::mcset ru jaloginjid   {Введите ваш jid типа "joey@myjabb.org", или выбирете профиль. Вы должны быть зарегистрированы на сервере.}
::msgcat::mcset en jaregalready {You are already registered with this service. These are your current settings of your registration parameters.}
::msgcat::mcset en jaactiveret  {If checked Return sends message else use Ctrl/Cmd-Return}
::msgcat::mcset ru jainvitegchat {Пригласить в %s}
::msgcat::mcset ru jaxformreq   {Поля отмеченые  (*) обязательны для заполнения}


::msgcat::mcset ru jamessnorooms		{Не обнаруженно ниодной комнаты в %s.}
# remove-- ::msgcat::mcset en jasettopic   {Set new topic for this groupchat.}
::msgcat::mcset ru jasettopic2			{Установить тему для этой комнаты.}
::msgcat::mcset ru jagcsyncpres		{Синхронизировать комнатуc с присутствием пользователя}

   
# Setup assistant:
::msgcat::mcset en suintro1 	{This is a setup assistant to help you fill in the necessary things that is needed for a new or an existing account on a Jabber server.}
::msgcat::mcset en suintro2 	{If you are going to run in peer-to-peer mode, you just set this in the Preferences panel, and relaunch the Coccinella.}
::msgcat::mcset en suintro3 	{Any time you may press the Previous button to go back. Follow the instructions on each page, and press the Next button until finished.}
::msgcat::mcset en sulang       {Pick a language catalog. If you change the language catalog this will only affect interface elements created after it has been set.}
::msgcat::mcset en suservmsg	{Fill in the name of the Jabber server you wish to have your account on. If you already have an existing account on a Jabber server, fill in the name of that server.\
  A typical name is "jabber.org".}
::msgcat::mcset en suusermsg	{Fill in your username and password. The username must not exist at the specified server, unless you are already registered.\
  If the username is already in use by another, you will receive a note about this when trying to register.}
::msgcat::mcset en suregmsg	{Do you want to register your account now if it is a new one? You must already be connected to a network (without firewall) to register.}
::msgcat::mcset en sufinmsg	{That's all. If the registration was succesful, you only have to press the Connect button, or select the Jabber/Login menu. Also, be nice to the bug ;-)}
::msgcat::mcset ru suheadtxt	{Помощник настройки Coccinella}



::msgcat::mcset ru vcardget	{Получение визитки пользователя %s. Ожидание ответа сервера...}
::msgcat::mcset ru vcarderrget	{Не удалось получить визтку. Результат: %s}
::msgcat::mcset ru vcardrec	{Визитка получена.}



::msgcat::mcset ru autoupdatenot        {Отключить проверку обновлений}
::msgcat::mcset ru oobmsg               {позволить пользователю %s скачать фалй с вашего встроеннго сервера. Описание по желанию.}
::msgcat::mcset ru chatcompreply        {%s пишет в ответ}

# Get file
::msgcat::mcset ru getcontacting   {Соединение с %s. Ожидание ответа...}
::msgcat::mcset ru geteoferr       {Соединение с %s завершилось неудачей: получен eof.}
::msgcat::mcset ru getconnerr	    {Соединение с %s окнчилось ошибкой.}
::msgcat::mcset ru getnegotiate    {Соединение с сервером %s устананавливается...}
::msgcat::mcset ru getreaderr      {Ошибка чтения ответа сервера %s.}
::msgcat::mcset ru getunknownprot  {Сервер %s ответил в не соответствии протоколу}
::msgcat::mcset ru getnot200	    {От сервера %s получен код %s: "%s"}
::msgcat::mcset ru getstarts	    {Клиент %s принял файл %s. Начинаем передачу...}
::msgcat::mcset ru getended	    {Передача %s внезапно завершилась.}
::msgcat::mcset ru getfinished	    {Завершена передача фалы "%s" из %s.}
::msgcat::mcset ru getneterr	    {Ошибка сети при получении с %s.}

# Put file
::msgcat::mcset ru putcontacting   {Подключаемся к  %s. Ожидание ответа...}
::msgcat::mcset ru puteoferr       {Подключение к %s завершилось неудачей: получен eof.}
::msgcat::mcset ru putconnerr	    {Не удалось подключится к %s .}
::msgcat::mcset ru putnegotiate    {Соединение с сервером %s устананавливается...}
::msgcat::mcset ru putreaderr      {Ошибка чтения ответа сервера %s.}
::msgcat::mcset ru putunknownprot  {Сервер %s ответил в не соответствии протоколу}
::msgcat::mcset ru putnot200	    {От сервера %s получен код %s: "%s"}
::msgcat::mcset ru putstarts	    {Клиент %s принял файл %s. Начинаем передачу...}
::msgcat::mcset ru putended	    {Передача %s преждевременно прервалась.}
::msgcat::mcset ru putfinished	    {Заершена передача файла "%s" к %s.}
::msgcat::mcset ru putneterr	    {Ошибка сети при закачке %s.}

# END --------------------------------------------------------------------------
