
namespace eval ::Totd {   
    ::msgcat::mcset en mTotd...          "Suggerimenti utili..."
    ::msgcat::mcset en "Suggerimenti utili"
    ::msgcat::mcset en "Mostra succerimenti all'avvio"
    
    ::msgcat::mcset en totd-first   "Questo è il primo suggerimento :-) http://coccinella.im"
    ::msgcat::mcset en totd-second  "Questo è il secondo suggerimento"
    ::msgcat::mcset en totd-third   "Questo è il terzo suggerimento"
}


