
#  Base64Icons.tcl ---
#  
#      This file is part of The Coccinella application. It contains
#      Mime (base 64) coded icons for the tool buttons and other icons.
#      
#  Copyright (c) 2002-2003  Mats Bengtsson
#  
#  See the README file for license, bugs etc.
#  
# $Id: Base64Icons.tcl,v 1.5 2004-01-13 14:50:21 matben Exp $
 
### First all the tool buttons, both on and off states. ########################

# Make sure we have the namespace.
namespace eval ::UI:: {}

set ::UI::icons(off20) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEcTDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkTNczB+x8z3+2DoBALBpPBE9QlyQNlbnN09lcRQ/TUXazlFZBW9M1HPqKW0Jz
GYpmlsJdrDrN/vjuO3PcdOzrrzdWbYEde4SGgYg3ijQwfo+QJ3iTlD0RADs=
}]
 
set ::UI::icons(off01) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEdjDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui5aA3JJAnsJ4rpM8GmEInOEIOyOntkRumJ7gEnoAOKvUjRTr63qzW+xwaB3niCvl
82ptXrVqbbPzht+OyfvHWwqHzn1xIXUfflE2MXmJgXqLdIKOMGOTlJWWX5iZmREAOw==
}]
 
set ::UI::icons(off40) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEcTDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8Yk/AF4rgOgHQKEEy44/Pg6QMIhp1w2O0fohrkyznrFUtQjfI620GztehN/yT/v
uYUFythWdwo8Na9Hu3ctGJyjaWFwgFx/gyaFg3SJInyNjo+QO5KTlDkRADs=
}]
 
set ::UI::icons(off41) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfjDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkTNfz/dkl4P8+D2+UqfgIneGnSAEgAMhVLoRBPKMbJYc5cV6xpumGK/FCweFW
h5wwE9DpEPBnPYOUXmv9O8Lr9UdwUmpjc4ElWm+KiilaOllij3GSQpGPjpcii5ucnYqGoKGh
EQA7
}]
 
set ::UI::icons(off30)  [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfTDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui5ZADZBwCiD8DeakHQ8BIPxmo1qPYPwAQZmErelEfjJLqucZkixx1g6WyAS3rl5y
icsZF7XVc0hYTLE3trc9jK+V93JiejKBbX+EODEmfIorjI2LhZAbd5MwTJiZmpuaeZ6foKAR
ADs=
}]
 
set ::UI::icons(off31) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfzDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui7oAggCEB8f1nXc7VQ/3W81Sw6KxhbQRP8FSEhQdJZVLoROblQK+BO6mGnLiSGRO
JnE7j9KbDOLkph47cnoYfVfPwWJdIQl6gYJqX0SGhythi0B9MTqRkoyVkBqOmpucnYmfoKGi
nxEAOw==
}]
 
set ::UI::icons(off10) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEUzDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkTNfz/dn6nverH9AkBPIOgKRyyQR4jiaCdEqtdqBDrLHY03a5Om8YfBOXyTRz
Gh2DVd9weHNOp0cAADs=
}]
 
set ::UI::icons(off11) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEZDDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkTNfz/dkugLc9H4inAhiHuZTx6CEun9BnM0moWq/PaoeoNGq3yZKXsAuTAN8p
0EVGrnXgN3zDnZvM8Ppcn8frYFeBgoNWUYaHhxEAOw==
}]
 
set ::UI::icons(on20) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEc3DISau9A+jNu+9JZoxkaZ5l
CKBsa6hunIqyDNfxjbf6+HmongFAKBqPBOJJqGw1Z6vSEzUdMQmu6otG0kqxpmsWDDV5u2SS
2Jm2cn1tc5z548zfI6S+uMTvwn5/aoGCW1GFgIeIg4qLho4zCZKTlJWWlhEAOw==
}]
 
set ::UI::icons(on01) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1HN+nqKe3XKsT9OkISJvQBSDwloadqamS4oxTKzXrEpI8raUGiWySx84X
dpqOts3htendNtRVUNZWKa9yikBMY4BWQ3ddfSuHiIE8NImOao2RcYWUV5aXeAMJnZ6foKGh
EQA7
}]
 
set ::UI::icons(on40) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEeXDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1recqmbo8k4ZA2BCHQBELQDQYhYTkbxV1Ik1VnNJVZO62rW6WBmaJv9Pl
1RZcrdll1RkdC7/J6d5d1rZudCdxWERNN32AWnmIiXWLUo2OiZF8GZNJCZiZmpucnBEAOw==
}]
 
set ::UI::icons(on41) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEgnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1ree6zfeyX6uEE80AiaRSQyimXEhlEoAANF/GoXSKqF5VQkNUSvV+TcLx
sms9o7MmNdfs4o3YBDcYXu6y6UF8fn5MelhPYh95Nz95jo47cEB1kpNOMZaUiJmHnJqeLSFb
o6SlCREAOw==
}]
 
set ::UI::icons(on30) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEf3DISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1zNm5DCDAmKzX+gERAMJQpDMmlS7iCpBIbKBRposaJGBbUhM10eVpWVyk
15xCV8ts4ZSs/mbbU6f9Lldx1jdhV3t8RU83KoKAiCdnK4Q0joyFk5F4lWAZmJabS1WfoKGi
oxEAOw==
}]
 
set ::UI::icons(on11) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEaHDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1ree6zfey3yxGE/VSQaNuk0TeOK4c6dPiEa7YLOeKUz413K7TBiZEveRw
FW0zN4nAd7w4nr/YdpMwf8LnUXxrcIF6AwmHiImKi4sRADs=
}]
 
set ::UI::icons(on31) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEh3DISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1bQAIAhCt3I3nA+JEOuLP+EIOez+XUKYkMJspW1U2bVWv2Nhsy3W6OFaa
maWMqrPsRMLnLsNXgDlBAz7eTXkIe0s2XTuCfH1+Yip5g2k3U2iQkWsGVpQ6hjpBlpydjJ92
ooUDcqeoqaqrEQA7
}]
 
set ::UI::icons(on10) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEWnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1ree6zfeyH7AlHL5ExiAySVySPs2UiUCtWq8E3JJ5lHJVRWY4OTaWh2dg
urfebb+nDLw7Bw8S+Lx+z+dHAAA7
}]
 
set ::UI::icons(off00) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEZjDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkPAK0DQK4q3+8XuoXCspau6BwROwoeaUmJ0ioEmozYBVwjWZvXSyyxPWOSWVx
LA2S7sIfd1tNo9fb3/sqrzfx9TBWgoOEhU+HiIlBEQA7
}]
 
set ::UI::icons(on21) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1redtd/MqDWE4TMmABiGBZWwhAUNXzAWELmVTnGgFtXW1zeQVO1ZVyz30
aRtUc9XPmdXJDma5X/DdFE7O6X12G0RHdS1EUTSGOoWBjHqPNkiRLxmUinuXZgMJnZ6foKGh
EQA7
}]
 
set ::UI::icons(off21) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEejDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkTAI4XtofTvw/HYjX8RFCgOGs+AMlP8QNoDl6dqKHaUl7XUqPN/DKmxU7zSYy
t4rGZsNtctZaXI9bPfqc2sU7c1N8fSlAgh5uNHeJNXKLaX6OipGHIoWWl5hAgJucnZ0RADs=
}]
 
set ::UI::icons(on00) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEa3DISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1redsrKu8Vep3Erk2xKCK81OaOjtjy3NzGjaELMFmBWS90aEMXJXOyDTz
eMtVr9viM1tmbc1ddaIpr+cn3XovGYFpPoQtIQmKi4yNjo4RADs=
}]
 
set ::UI::icons(off50) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Ojo6Pj4+P//////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEnFDJSau1QJ3Nu/9eBo7kQYhl
yp2aqrIpQbzoKMtx/ckIgpMwGwEB+Nl0HlnGCAqCABmFEnBsPSW+IZSaRHKiCEWxt+1aO2Ax
sXeCdpxfrILMbhdXyHRvP4XONnAHGWF7dUVbfyZeg4VKfYmBG4xZRTOIeGdohj9+kF5fjomV
b59fo29mMYlApS6kma47rbGKGje3uLm6W7y9vr+8EQA7
}]
 
set ::UI::icons(on50) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEn3DISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wTBDzK8r3nZu11g2B8OWCrCHASNsJCYAEU4ZcaRJSaIzqZEUTRQJi46qavojE
kkhmmdHqMVG7VVXh7DkdZ+/iiXocfEB+YGCAYUsbgyddBlGIiTeLOilWh5I4lH2WVoFGGlNm
Z5NMS4yNnV6nSS2jKlNNqj+ydbSyt7QouT8hWL/AwcLDEQA7
}]
 
set ::UI::icons(off51) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfDDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui5YAkMI0cdojPgK6zQ7k+wAJnmGn2Dn2eMJZM0gCrqQbZ+7a4mi30e7hCzZJrS60
WTyOqZmnVI26/sRBc+QSGw2RuU9Zf3tse4NJfEt6N4kxhI4lTJCPOpWWl5iXNZucnZ6fNREA
Ow==
}]
 
set ::UI::icons(on51) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEgnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1nN65CxCEnazH+hFMwZiLqDKyki2mwekK4kRFoO33wja126OqRw13d2Xz
2Mu9mdomsvstjnsN1m2amG9pwGdKKn1vaYEteX91S3crSYA0jY6LNlJzV0KXjIKam52RCaGi
o6SlpREAOw==
}]
 
set ::UI::icons(off60) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEdzDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkHAI47tocQPxAXYnX+5wAtVmPADqNiEWQr6lcjpDGavQz9UCt0mwrLGV2vj1s
yLzSro5rr/sM33Tb4yH8vkE/j2x9czU/cnk0YohJh4p4jVQaQJKTlJU5l5iZmpcRADs=
}]
 
set ::UI::icons(on60) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEfnDISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1reemp5s8AGFITN14hhiLYJQhhS4mTcRStqAuZJIgs+Ko1S63pd12s+Cw
C/tKr5rvcRuuGtLZqnKdacUD3VF8Zl90MnZ+J4A2RGSKP4Rej42FknkZlVORmJYJnZ6foKGh
EQA7
}]
 
set ::UI::icons(off61) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEeTDJSau1IJ3Nu/9eBo7kQYhl
yp2aqrLui8YkHHJAnpd2t+vA2gwHJBhPgFGPmDP6CKDlBpj0QD/SA7WaypqOzu6Qhh2PtuWW
inpdmaefovWt5dZ17Y13ukXmTXR8eFAAf3srYCtzamRpjUqBZIeSImCWl5hHW5ucnBEAOw==
}]
 
set ::UI::icons(on61) [image create photo -data {
R0lGODlhHAAcAOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+P//////////////
/////////yH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAHAAcAAAEe3DISau9A+jNu+9J9o2jYYSa
qa5su6KAK8/wbLP1redm3HM3niH1sQk7hCQhJTtukisAoSmKAllTl/O6q66USt3JK6aRZR7t
Gc3JvtbDVrsl/FmfdPjQs5TmmXJtU344eiZgbm4qdWWFgI1/PpB/k1SSlW8JmpucnZ6eEQA7
}]

### Mac Head icons. ############################################################

set ::UI::icons(machead) [image create photo -data {
    R0lGODlhEAAMAPMAAP//////zv/OnN7e3s6cYwAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAAwAAAQxcJRJ57hYhs2D
    KNlVeEJZEmA4mp+AhhpbuGm2sjR8s69KmhTdb/aBxYAWIa6nqyRhEQA7
}]
set ::UI::icons(macheadaway) [image create photo -data {
    R0lGODlhEAAOAPMAAP//////zv/OnN7e3s7O/86cY2NjzjExYwAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA4AAARHcMgpkb2IUhS6
    F5k2cEJZFqFGloiATtgKumkdmGcWYyYvECYgqAUauQyugqGAGuqOTCWT+GpJ
    mUvUpQLFTlWuQ1T8Uu0soggAOw==
}]
set ::UI::icons(macheadgray) [image create photo -data {
    R0lGODlhEAAMAPMAAP///97e3sbGxoSEhAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAEALAAAAAAQAAwAAAQxMJBJZ7hYgs2B
    INlFeEJZDmA4miYaauYkuCrJ0tnKzmlul5SXjtXzxYLCH+8lqliYEQA7
}]
set ::UI::icons(macheadinv) [image create photo -data {
    R0lGODlhEAAMAPEAAP///97e3gAAAAAAACH5BAEAAAEALAAAAAAQAAwAAAIl
    jI4XywYPn2hLxDipxZI6DmTNdoUeeYkMKikaqK6p+5bxmtBUAQA7
}]
set ::UI::icons(macheadsleep) [image create photo -data {
    R0lGODlhEAAPAPMAAP//////zv/OnN7e3s6cYwAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA8AAAQ+cEhZapk4U03r
    vNzWeZoVnoOlllbgBoIAUkFRxzgxpzcuCzqMreD7BT+wYuxIUy53NicQGiBY
    r9ddSsXFRAAAOw==
}]
set ::UI::icons(macheadtalk) [image create photo -data {
    R0lGODlhEAAOAPMAAP//////zv/OnN7e3s6cYwAAYwAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA4AAAQ/cJhJ57hYhs2D
    MNlleEJZEmA4mp+AhhpruGm2svRQ2CT76pibzLDbiXqVS/FoqimBsaYFaBQ2
    qbbK9AnrGi8RADs=
}]
set ::UI::icons(macheadunav) [image create photo -data {
    R0lGODlhEAANAPMAAP//////zv/Ozv/OnP9jY/8xAN7e3t4AAM6cY70AAK0A
    AIwAAHMAAFJSUlIAAAAAACH5BAEAAAYALAAAAAAQAA0AAARV0Jgjq6R2msc7
    Z9YhPMQSnImgPGC1LooyHIXSPNkGK/Sz4pnHLsZCAC2PwCGmYAyMuUeixlRA
    g4QYg8jJHITNgW+lCBGEzoGY07QwHg61/JN7e+iWCAA7
}]
set ::UI::icons(questmark) [image create photo -data {
    R0lGODlhEAANAPMAAP////9jY97e3q0AAFIAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQAA0AAAQmUIgQxpA4y2qt
    zpzUfeKFeeRAZCoptBvsxutM22eNv/ruxz+ZKwIAOw==
}]
set ::UI::icons(dndim) [image create photo -data {
    R0lGODdhEAALALMAAP//////zv/Ozv/OnM6cnM6cY85jY5xjY5xjMZwxMQAAAAAAAAAAAAAA
    AAAAAAAAACwAAAAAEAALAAAERVDJSasMQoxBevmgJEhEoRiIYipIqoyDQkimGbvxPKv8LcUm
    HUnGGh6IO6FhmJoVUjmelJAqHGOKwaqQ6HZbLcNnZylLIgA7
}]
set ::UI::icons(naim) [image create photo -data {
    R0lGODdhEAALALMAAP///87//5z//5zO/2PO/2Oc/2OczjGczjFjzjFjnABjnAAAAAAAAAAA
    AAAAAAAAACwAAAAAEAALAAAESHDJSasEIAQxOiFFSFzBEozDgUhJK22SsAzJPMy1ec/4vNIx
    lAQ4IQ4KvF5qIVjNDMofVACdHZTXo6lKUHgVhFYLMTBULWhJBAA7
}]

# With whiteboard icon.
set ::UI::icons(macheadwb) [image create photo -data {
    R0lGODlhEAAOAPMAAP//////zv/OnN7e3s6cY29vbwAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA4AAARCcJhJ57hYhs2D
    MNlleEJZEmA4mp+AhhpruEZh3ytLAzxf5CxUzwcsUYaAH6n1QSaLR6RSJ5RK
    KhNnMlTQ+ri38C0CADs=
}]
set ::UI::icons(macheadtalkwb) [image create photo -data {
    R0lGODlhEAAOAPMAAP//////zv/OnN7e3s6cY29vbwAAYwAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA4AAARKcJxJ57hYhs2D
    ONl1eEJZEmA4mp+Ahhp7uEdh3ytLAwbgFzkWytcDAEmyQ694NFWIPGPw4Ksu
    pcjPBNpr6qhXo6Sytf5Ct5shHQEAOw==
}]
set ::UI::icons(macheadawaywb) [image create photo -data {
    R0lGODlhEAAOAPMAAP//////zv/OnN7e3s7O/86cY29vb2NjzjExYwAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA4AAARNcMgpk72J0hS6
    F5k2cEJZFqFGlomATtgKumkdmGcWYyYvECYgqAUytAoHF7KAGiaMrgNz2aRB
    qVQM4CpldhOA8PaImJZR4u1oZzG43xEAOw==
}]
set ::UI::icons(macheadinvwb) [image create photo -data {
    R0lGODlhEAAOAPMAAP////7+/vr6+vb29t7e3nV1dW9vbwAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAQALAAAAAAQAA4AAAQ7kJxJJ7lYgs33
    ydfRdR8okh6oocBhvPA5tkNnyOMR2Lg3jQXcSTe65X7FnmdmkFQmAibIMOM0
    M7BsNgIAOw==
}]
set ::UI::icons(macheadunavwb) [image create photo -data {
    R0lGODlhEAAOAPcAAP//////zv/Ozv/OnP9jY/8xAN7e3t4AAM6cY70AAK0A
    AIwAAHMAAG9vb1JSUlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAYALAAAAAAQAA4AAAiJAA0YOCCwoECC
    BgcagMCwIUMGBg8IgEBgQYCLCQQogACx4MYFChQMOFBAgQMICReCVEASwkYI
    DWI2EAhhZUiOCCAA2DlzYYADIRUwGJBzJ4CeEBKUDKqgKE+aBEIyuMnQ6MwD
    NYUOcLlRgdUDBGoOHbCVodCnDCA8IMv2oVWBaR26fZtSpt2YAQEAOw==
}]
set ::UI::icons(macheadsleepwb) [image create photo -data {
    R0lGODlhEAAPAPMAAP//////zv/OnN7e3s6cY29vbwAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQAA8AAAREcEhpqpk4U03r
    vNzWeZoVnoOlFmwxGkEcCIIBAC6s0zxh46mAgUcb+m45IbEmOAJhy94vGaU5
    qdVrkMDtdqcvVaVViAAAOw==
}]
set ::UI::icons(questmarkwb) [image create photo -data {
    R0lGODlhEAAOAPMAAP////9jY97e3q0AAG9vb1IAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQAA4AAAQ9UIgQxpA4y2qt
    zpzUfeKFeeRQYIRKvPCrYlUB3DhAgGqe75ueDwcUuIbEU4GAvBUlzGaxEkUW
    j1JNbPuKAAA7
}]
set ::UI::icons(macheadgraywb) [image create photo -data {
    R0lGODlhEAAOAPMAAP///97e3sbGxoSEhG9vbwAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAEALAAAAAAQAA4AAAQ/MJRJZ7hYgs2B
    KNlVeEJZDmA4miYaauYkoERtr+w8dgTOoh1AjxSbBIe5T1DoqyyRvx1PUjE+
    Q4Qlh4C1eW0RADs=
}]

### Foreign IM systems icons. ##################################################

set ::UI::icons(aim_away) [image create photo -data {
R0lGODlhEAAQAPUAAP//AP+4SP7LZv31tvvUt/Pz8+vp5eThzODg4N/fg9ra
2tbNu87n/8ujR7y8AKunn6bU9qainJ6enp2ckJmDZpjL/pVtMo2Zo4egsYLD
+YCDTH2fzX2BAXFxcG+QkW1gLGZmZmBLAlAsAEay6zqn8zMzMDIuBjFfKB+W
8B87fRsnGg+Q9g8PDQ0rQAVkmAFnywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAsALAAAAAAQABAAAAan
wIVwoTBIWEiQQTEUFhkbmKVhYWGWwyKElCoJBIlPC4JdGCCoVfcrEKPIRAZp
tXrBPg0N67UiMZ4VgRcRDzAwLS0uKxkGIY6Pjg8sJiUsKyONAJqbIQNfDZYo
mRykHAAhFBYfJqGZm5ohHTAsipejpacEVbWMIa+wBAG7fgq+paYhGg0BHyxw
vr8hFybLKlgfDgPa2hweFyUiLAhCEycfkMkHLCoFQ0EAOw==
}]
 
set ::UI::icons(aim_dnd) [image create photo -data {
R0lGODlhEAAQAPUAAP//AP+4SP7LZv31tvvUt/Pz8+vp5eThzODg4N/fg9ra
2tbNu87n/8ujR7y8AKunn6bU9qainJ6enp2ckJmDZpjL/pVtMo2Zo4egsYLD
+YCDTH2fzX2BAXFxcG+QkW1gLGZmZmBLAlAsAEay6zqn8zMzMDIuBjFfKB+W
8B87fRsnGg+Q9g8PDQ0rQAVkmAFnywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAsALAAAAAAQABAAAAan
wIVwoTBIWEiQQTEUFhkbmKVhYWGWwyKElCoJBIlPC4JdGCCoVfcrEKPIRAZp
tXrBPg0N67UiMZ4VgRcRDzAwLS0uKxkGIY6Pjg8sJiUsKyONAJqbIQNfDZYo
mRykHAAhFBYfJqGZm5ohHTAsipejpacEVbWMIa+wBAG7fgq+paYhGg0BHyxw
vr8hFybLKlgfDgPa2hweFyUiLAhCEycfkMkHLCoFQ0EAOw==
}]
 
set ::UI::icons(aim_offline) [image create photo -data {
R0lGODlhEAAQAPUAAP6pP/vNY/i3UNbNu9aoTNScMr+9tr+bXbi1r7Opo7Cw
r6yrq6h9QaSinaOalJycnJmXkpKSkpJhJZGIgoqQjImJiYhycIWFhICAgHJv
dGxaA2hlZGVZVF1cXFBNS0BAQDszBDEyMiEhIQwPDgsKCAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQABAAAAaY
wIFQaEhEKhXHwjBsDhAY0OEgwjCdwkSIEAgcQgmscNHhekMI8cAQJRBAnSu2
YfGMNg/1oNE5BBgiIh4kF2FNUV2JASB4ThscXQySH4SGWR4MAgISJBsOWAgV
HwSaAm8bCk0GDRmZBAykp6lCDiAMAAIaFyKZBSMVWRuxHsATJJnEQqISEiIT
QxUkg89CEBUUE9RC2RPAA0EAOw==
}]
 
set ::UI::icons(aim_online) [image create photo -data {
R0lGODlhEAAQAPUAAPvPaPqoVfLz8uvp5eDg4Nra2tbNu82gUsrl9p7R9J6e
npm2xJOCOI6fqobG+HtRCm6n3G5ubmdnZ1VVVUur70VLA0MrD0BAQDCC0y5H
Yy2Y6SsYAicqKRscGhgpGBdLjRMpQxEQEA+P8gxaqgkKDwKLuAIaKAFoygFY
egBCUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAYALAAAAAAQABAAAAa0
QIPQUBgoOiSSZFAYCosIiIpxYJAazGExoUlZAOAHKJE1DLiizxc8AYnIRIRG
JDqpHlXSSaRBFB10IiYWFyoqJiAoIg4DAxR0KBxgFSEWFiYiFI1zggxgnwck
fJt0JAcABw8MDxwho44iJSEBqIUkipmNgCAXAbQBViN0jAULIBsHwAy+wX0F
BSoVyQcb0b4PJnB3AAHUKRgmHr4dWYarIRmPGoMVKk1EhioRBQQE9CQdAkNB
ADs=
}]
 
set ::UI::icons(aim_xa) [image create photo -data {
R0lGODlhEAAQAPUAAP//AP+4SP7LZv31tvvUt/Pz8+vp5eThzODg4N/fg9ra
2tbNu87n/8ujR7y8AKunn6bU9qainJ6enp2ckJmDZpjL/pVtMo2Zo4egsYLD
+YCDTH2fzX2BAXFxcG+QkW1gLGZmZmBLAlAsAEay6zqn8zMzMDIuBjFfKB+W
8B87fRsnGg+Q9g8PDQ0rQAVkmAFnywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAsALAAAAAAQABAAAAan
wIVwoTBIWEiQQTEUFhkbmKVhYWGWwyKElCoJBIlPC4JdGCCoVfcrEKPIRAZp
tXrBPg0N67UiMZ4VgRcRDzAwLS0uKxkGIY6Pjg8sJiUsKyONAJqbIQNfDZYo
mRykHAAhFBYfJqGZm5ohHTAsipejpacEVbWMIa+wBAG7fgq+paYhGg0BHyxw
vr8hFybLKlgfDgPa2hweFyUiLAhCEycfkMkHLCoFQ0EAOw==
}]

set ::UI::icons(icq_away) [image create photo -data {
R0lGODlhEAAQAPMAAP////f897S0tG5ubgD8AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAUALAAAAAAQABAAAAQ9sMgZpr2yVswl
kULxURTxCdWYjcEZbJiKvmE3vDhcbHNOWz0f7iL01UDFwHH3ES4zlV7N1Pkx
VZenrtOJAAA7
}]
 
set ::UI::icons(icq_dnd) [image create photo -data {
R0lGODlhEAAQAPMAAP////f89/cAAG4AAAD8AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAUALAAAAAAQABAAAAREsMhJq5WBXJs1
9tjUfWCRFcNApGMVDIIAy+UEB7GAD+4a4zgZx6eLqQi1GdCIpLyKP6ETOaty
ApLU6lgTgVoc12Y8iQAAOw==
}]
 
set ::UI::icons(icq_offline) [image create photo -data {
R0lGODlhEAAQAPMAAP////f89/f8APcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAQALAAAAAAQABAAAAQ0kMhJq5VhXJs1
9tjUfSCRkeZQfmG6nRtqCoJbBWdAp2qsy0BfzwWj4Fi8lQg0ugRusSghAgA7
}]
 
set ::UI::icons(icq_online) [image create photo -data {
R0lGODlhEAAQAPMAAP////f89/f8AAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAQALAAAAAAQABAAAAQ0kMhJq5VhXJs1
9tjUfSCRkeZQfmG6nRtqCoJbBWdAp2qsy0BfzwWj4Fi8lQg0ugRusSghAgA7
}]
 
set ::UI::icons(icq_xa) [image create photo -data {
R0lGODlhEAAQAPMAAP////f89/cAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAQALAAAAAAQABAAAAQ9kMhJq5VhXJs1
9tjUfaBgnihKmEHrvu0ZEC1dzzYb3jat4zzRb0Ys+gTGJFEGa5pWqeizkhEN
QNTsZiuJAAA7
}]
 
set ::UI::icons(msn_away) [image create photo -data {
R0lGODlhEAAQAPMAAP////8AAObe3MDAwICAgIAAAACAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQABAAAARSUMgpjT00VwMM
wdrWdV8ocOhggJrVqWVoqPBqnhZhU0EfVIdgJgAAHAA/E7F4RHqCrKWxGCjM
nhJps/rCLptIK2kXAFdTHrJPjI4JCnCLPLeKAAA7
}]
 
set ::UI::icons(msn_dnd) [image create photo -data {
R0lGODlhEAAQAPMAAP////8AAObe3MDAwICAgIAAAACAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQABAAAARMUMgpjT00VwMM
wdrWdV8ocOhggJrVqWVoqPBqnhZhU0EfVIdgxue7EYmeICsAaDoDhVlSwnQ2
oa/p0Rcl7bZdqQ5EDGdjgoLaws6tIgA7
}]

set ::UI::icons(msn_offline) [image create photo -data {
R0lGODlhEAAQAPMAAP////8AAObe3MDAwICAgIAAAACAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQABAAAARiUEhhqjiYzF2B
OQAwEMdGGR4RhmM5GQN6DGvLoR8t2m88zIMggWSqwA7DoatowWBM0E1gyqwk
RVPACzcEZGmDwCnW9X6pMJgq9MUaR2tAARuQV8iEYLAwDRQORh9OTgWFGBEA
Ow==
}]
 
set ::UI::icons(msn_online) [image create photo -data {
R0lGODlhEAAQAPMAAP///+be3MDAwICAgACAgAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAEALAAAAAAQABAAAARAMMhJapkYV0DG
zRTBcR4oEYKIEh+4raW5pgNrnlXd3myx30BXx/fTqGjFQCXFQbqYKl2msmp2
bCGoNYajeqWBCAA7
}]
 
set ::UI::icons(msn_xa) [image create photo -data {
R0lGODlhEAAQAPMAAP////8AAObe3MDAwICAgIAAAACAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQABAAAARSUMgpjT00VwMM
wdrWdV8ocOhggJrVqWVoqPBqnhZhU0EfVIdgJgAAHAA/E7F4RHqCrKWxGCjM
nhJps/rCLptIK2kXAFdTHrJPjI4JCnCLPLeKAAA7
}]
 
set ::UI::icons(yahoo_away) [image create photo -data {
R0lGODlhEAAQAPMAAP//////AP8AAObe3L+/v39/AH8AAAAA/wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQABAAAARDcMhJq71U6C3w
3B8HSuOgIaaWqULhFme1FUEdwKhM23Vx7YBa8LaiAQ4EwiHomyAQO17PQove
iNSbwVD1WJvel2ccAQA7
}]
 
set ::UI::icons(yahoo_dnd) [image create photo -data {
R0lGODlhEAAQAPMAAP//////AP8AAObe3L+/v39/AH8AAAAA/wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQABAAAARDcMhJq71U6C3w
3B8HSuOgIaaWqULhFme1FUEdwKhM23Vx7YBa8LaiAQ4EwiHomyAQO17PQove
iNSbwVD1WJvel2ccAQA7
}]
 
set ::UI::icons(yahoo_offline) [image create photo -data {
R0lGODlhEAAQAPMAAP////8AAObe3L+/v39/f39/AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAIALAAAAAAQABAAAAREUMhJq7006B3w
3B8HSqOgGaaWqULhFmelFgNQw6hM23xx7bUgwBcqDHeuAVFiMAB5N4tRGFxS
pgSCzVqZbj2SFxdMiQAAOw==
}]
 
set ::UI::icons(yahoo_online) [image create photo -data {
R0lGODlhEAAQAPMAAP//////AP8AAObe3L+/v39/AH8AAAAA/wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQABAAAARDcMhJq71U6C3w
3B8HSuOgIaaWqULhFme1FUEdwKhM23Vx7YBa8LaiAQ4EwiHomyAQO17PQove
iNSbwVD1WJvel2ccAQA7
}]

set ::UI::icons(yahoo_xa) [image create photo -data {
R0lGODlhEAAQAPMAAP//////AP8AAObe3L+/v39/AH8AAAAA/wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAEAAAMALAAAAAAQABAAAARDcMhJq71U6C3w
3B8HSuOgIaaWqULhFme1FUEdwKhM23Vx7YBa8LaiAQ4EwiHomyAQO17PQove
iNSbwVD1WJvel2ccAQA7
}]

# More

# General icon for minimal popup menu button.
set ::UI::icons(popupbt) [image create photo -data {
    R0lGODdhEAAOALMAAP///+/v797e3s7Ozr29va2trZycnJSUlIyMjHl5eXR0
    dHNzc2NjY1JSUkJCQgAAACwAAAAAEAAOAAAEYLDIIqoYg5A5iQhVthkGR4HY
    JhkI0gWgphUkspRn5ey8Yy+S0CDRcxRsjOAlUzwuGkERQcGjGZ6S1IxHWjCS
    hZkEcTC2vEAOieRDNlyrNevMaKQnrIXe+71zkF8MC3ASEQA7
}]
set ::UI::icons(popupbtpush) [image create photo -data {
    R0lGODdhEAAOAMQAAP///9DQ0M7Ozr29va2trZycnI2NjYyMjHZ2dnV1dXR0
    dHNzc29vb2NjY1JSUkJCQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEAAOAAAFbqAgCsTSOGhTjMLgmk0s
    O4s7EGW8HEVxHKYDjnCI8Vy4HnBoWhBsN+WigIsVBoGHdvtQCAm0qwDBfRAS
    TvDUVjYs0g6VjbEluL/WIWELnOKKPD0FdAQKbzc4b4EHBg9vUyRDP5N9kFGC
    UjtULT0hADs=
}]
    
# The mac look-alike triangles.
set ::UI::icons(mactriangleopen) [image create photo -data {
    R0lGODlhCwALAPMAAP///97e3s7O/729vZyc/4yMjGNjzgAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAEALAAAAAALAAsAAAQgMMhJq7316M1P
    OEIoEkchHURKGOUwoWubsYVryZiNVREAOw==
}]
set ::UI::icons(mactriangleclosed) [image create photo -data {
    R0lGODlhCwALAPMAAP///97e3s7O/729vZyc/4yMjGNjzgAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAACH5BAEAAAEALAAAAAALAAsAAAQiMMgjqw2H3nqE
    3h3xWaEICgRhjBi6FgMpvDEpwuCBg3sVAQA7
}]


### Miscellaneous images that has no transparency in them. #####################

set ::UI::icons(barvert) [image create photo -data {
    R0lGODlhCwAyAPcAAP//////////////////////////////////////////////////////
    //////////////////////////////////////e1vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1
    vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1vfe1ve+cre+cre+cre+cre+cre+c
    re+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre+cre9zhO9zhO9z
    hO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9zhO9z
    hOdae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+dae+da
    e+dae+dae+dae+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dKY+dK
    Y+dKY+dKY+dKY+dKY+dKY+dKY94xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUt4x
    Ut4xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUt4xUtYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYA
    IdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIc7Ozs7Ozs7Ozs7Ozs7Ozs7O
    zs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzpycnJycnJyc
    nJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJyc
    nISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISE
    hISEhISEhISEhFJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJS
    UlJSUlJSUlJSUlJSUlJSUlJSUlJSUgAAACwAAAAACwAyAAAIfABVCRxIsKBBgRdYBLHC0Moa
    QNQEVppIsRK1XwMrWsRIkOLFgxsPilQFgGDJgukIphxZ8KRAlwNXCpTJ8qVJgzRp1oQJc6bK
    mjcH9lSVE6jQoD9jGrV5FGVSozxxPgUa1anSpVWn6mSZ9apPrEi9El1KMuzXs1TNjhU7MiAA
    Ow==
}]

set ::UI::icons(barhoriz) [image create photo -data {
    R0lGODdhQQALAOcAAP//////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////
    /////++Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+U
    pe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe+Upe97lO97lO97lO97
    lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97
    lO97lO97lO97lO97lO97lO97lO97lO97lO97lO97lNYAIdYAIdYAIdYAIdYAIdYAIdYAIdYA
    IdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYAIdYA
    IdYAIdYAIdYAIdYAIdYAIdYAIc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O
    zs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O
    zs7Ozs7OzpycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJyc
    nJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnISEhISEhISE
    hISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISE
    hISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhFJSUv//////////////////////
    ////////////////////////////////////////////////////////////////////////
    /////////////////////////////////ywAAAAAQQALAAAIdwABCRxIsKDBgwgTKlzIsKHD
    hw9DIAQgkCIgixgrary4MSPHjx4tHgwBBgzCbwJRAlLJMqXLlS9bwpwpU2VBkiVNQtzJc2TO
    nD2D8gTy86fQow5/KV26dGDIjlBBRn0q9SCoq1ivEqwZsytNr1y/Ih1LtqxZhAEBADs=
}]

set ::UI::icons(imcolor) [image create photo -data {
    R0lGODlhOAA0AOMAAAAAAHBwcHh4eIiIiJCQkKCgoMDAwNDQ0NjY2Pj4+AAAAAAAAAAAAAAA
    AAAAAAAAACH+Dk1hZGUgd2l0aCBHSU1QACwAAAAAOAA0AAAE/jDJSau9OGuQjv9gKI5kWXJm
    qq4jgbJw3L5yHbvdR+x87//AnYigwoFcgKRyyWw2czoA0WSMaq6VA/SA5JWqHhx2rI0yp0Ma
    lzPGls086Wwrbmve0akLbT2y7Rl4On58a3R/gBeCM4VghokYiyE7UnyOdZBZW5MAnZ1ol4iZ
    E5J+n36HoxalhJypqhSsR2mvsBKyVGqYsLhfuqKqWnYAfVa2t5smxGG/x8htLsXMzh120dOo
    zsJj14bZx9tY3aHU4VfjzdrWy97G4OvSj+/Q7KE2JPDYOtSJ6Mkq1fj5qxGQ2kAZBZ0dDANE
    RMJjC9d4OhXioa2ISCYWKsMvAcaJXRRBWIT1EaQPDyNVldQ4YUrKUSs9EWiJ0tzFerqA0OQo
    EOc/LhZc2iTpk8TMCkI7RjwStGaQp1ApxTvS8ADIq1izXp16r+scr2CNqglL1kjUs2jTxtHK
    tq3btwAiAAA7
}]

#-------------------------------------------------------------------------------
