# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Adhoc      1.0 [list source [file join $dir Adhoc.tcl]]
package ifneeded Avatar     1.0 [list source [file join $dir Avatar.tcl]]
package ifneeded AutoAway   1.0 [list source [file join $dir AutoAway.tcl]]
package ifneeded AvatarMB   1.0 [list source [file join $dir AvatarMB.tcl]]
package ifneeded Chat       1.0 [list source [file join $dir Chat.tcl]]
package ifneeded ChatTheme  1.0 [list source [file join $dir ChatTheme.tcl]]
package ifneeded Create     1.0 [list source [file join $dir Create.tcl]]
package ifneeded Disco      1.0 [list source [file join $dir Disco.tcl]]
package ifneeded Emoticons  1.0 [list source [file join $dir Emoticons.tcl]]
package ifneeded Enter      1.0 [list source [file join $dir Enter.tcl]]
package ifneeded FTrans     1.0 [list source [file join $dir FTrans.tcl]]
package ifneeded Gateway    1.0 [list source [file join $dir Gateway.tcl]]
package ifneeded GotMsg     1.0 [list source [file join $dir GotMsg.tcl]]
package ifneeded GroupChat  1.0 [list source [file join $dir GroupChat.tcl]]
package ifneeded History    1.0 [list source [file join $dir History.tcl]]
package ifneeded Icondef    1.0 [list source [file join $dir Icondef.tcl]]
package ifneeded Jabber     1.0 [list source [file join $dir Jabber.tcl]]
package ifneeded JForms     1.0 [list source [file join $dir JForms.tcl]]
package ifneeded JPrefs     1.0 [list source [file join $dir JPrefs.tcl]]
package ifneeded JPubServers 1.0 [list source [file join $dir JPubServers.tcl]]
package ifneeded JUI        1.0 [list source [file join $dir JUI.tcl]]
package ifneeded JUser      1.0 [list source [file join $dir JUser.tcl]]
package ifneeded JWB        1.0 [list source [file join $dir JWB.tcl]]
package ifneeded Login      1.0 [list source [file join $dir Login.tcl]]
package ifneeded MailBox    1.0 [list source [file join $dir MailBox.tcl]]
package ifneeded MegaPresence 1.0 [list source [file join $dir MegaPresence.tcl]]
package ifneeded MUC        1.0 [list source [file join $dir MUC.tcl]]
package ifneeded NewMsg     1.0 [list source [file join $dir NewMsg.tcl]]
package ifneeded Nickname   1.0 [list source [file join $dir Nickname.tcl]]
package ifneeded OOB        1.0 [list source [file join $dir OOB.tcl]]
package ifneeded Privacy    1.0 [list source [file join $dir Privacy.tcl]]
package ifneeded Profiles   1.0 [list source [file join $dir Profiles.tcl]]
package ifneeded Register   1.0 [list source [file join $dir Register.tcl]]
package ifneeded Roster     1.0 [list source [file join $dir Roster.tcl]]
package ifneeded RosterAvatar 1.0 [list source [file join $dir RosterAvatar.tcl]]
package ifneeded RosterPlain 1.0 [list source [file join $dir RosterPlain.tcl]]
package ifneeded RosterTree 1.0 [list source [file join $dir RosterTree.tcl]]
package ifneeded RosterTwo  1.0 [list source [file join $dir RosterTwo.tcl]]
package ifneeded Rosticons  1.0 [list source [file join $dir Rosticons.tcl]]
package ifneeded Search     1.0 [list source [file join $dir Search.tcl]]
package ifneeded Servicons  1.0 [list source [file join $dir Servicons.tcl]]
package ifneeded SetupAss   1.0 [list source [file join $dir SetupAss.tcl]]
package ifneeded Status     1.0 [list source [file join $dir Status.tcl]]
package ifneeded Subscribe  1.0 [list source [file join $dir Subscribe.tcl]]
package ifneeded UserInfo   1.0 [list source [file join $dir UserInfo.tcl]]
package ifneeded VCard      1.0 [list source [file join $dir VCard.tcl]]

