
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset nl Location
    ::msgcat::mcset nl Filter
    ::msgcat::mcset nl Name
    ::msgcat::mcset nl Size
    ::msgcat::mcset nl Date
    ::msgcat::mcset nl Permissions
    ::msgcat::mcset nl Owner
    ::msgcat::mcset nl Group
    ::msgcat::mcset nl Folder
    ::msgcat::mcset nl Sorting
    ::msgcat::mcset nl Reverse
    
    ::msgcat::mcset nl {Short View}
    ::msgcat::mcset nl {Detailed View}
    ::msgcat::mcset nl {Show Hidden Files}
    ::msgcat::mcset nl {Separate Folders}
    ::msgcat::mcset nl {By Name}
    ::msgcat::mcset nl {By Date}
    ::msgcat::mcset nl {By Size}
    ::msgcat::mcset nl {Folders First}
    ::msgcat::mcset nl {New Folder}
    ::msgcat::mcset nl {Create new folder in}
    
    ::msgcat::mcset nl {File "%s" already exists. Do you want to overwrite it?}
    ::msgcat::mcset nl {File "%s" does not exist.}
    ::msgcat::mcset nl {Cannot change to the directory "%s". Permission denied.}
}


