
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset nl Location                 Locatie
    ::msgcat::mcset nl Filter                   Filter
    ::msgcat::mcset nl Name                     Naam
    ::msgcat::mcset nl Size                     Grootte
    ::msgcat::mcset nl Date                     Datum
    ::msgcat::mcset nl Permissions              Toegangsrechten
    ::msgcat::mcset nl Owner                    Eigenaar
    ::msgcat::mcset nl Group                    Groep
    ::msgcat::mcset nl Folder                   Map
    ::msgcat::mcset nl Sorting                  Sortering
    ::msgcat::mcset nl Reverse                  Omgekeerd
    
    ::msgcat::mcset nl {Short View}             {Korte weergave}
    ::msgcat::mcset nl {Detailed View}          {Gedetailleerde weergave}
    ::msgcat::mcset nl {Show Hidden Files}      {Verborgen bestanden weergeven}
    ::msgcat::mcset nl {Separate Folders}       {Afzonderlijke mappen}
    ::msgcat::mcset nl {By Name}                {Op naam}
    ::msgcat::mcset nl {By Date}                {Op datum}
    ::msgcat::mcset nl {By Size}                {Op grootte}
    ::msgcat::mcset nl {Folders First}          {Mappen eerst}
    ::msgcat::mcset nl {New Folder}             {Nieuwe map}
    ::msgcat::mcset nl {Create new folder in}   {Nieuwe map aanmaken in}
    
    ::msgcat::mcset nl {File "%s" already exists. Do you want to overwrite it?}   {Bestand "%s" bestaat al. Wilt u het overschrijven?}
    ::msgcat::mcset nl {File "%s" does not exist.}                                {Bestand "%s" bestaat niet.}
    ::msgcat::mcset nl {Cannot change to the directory "%s". Permission denied.}  {U hebt geen toegangsrechten voor de map "%s".}
}



